<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">

<title>Aula 3: Topografia de Densidade e Grafos — Clustering Hierárquico e HDBSCAN – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-f6f65eecdb8abf3e35b2d2c28dbef9f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#revisão-e-introdução" id="toc-revisão-e-introdução" class="nav-link active" data-scroll-target="#revisão-e-introdução"><span class="header-section-number">1</span> Revisão e Introdução</a>
  <ul class="collapse">
  <li><a href="#revisão-rápida-da-aula-1-à-aula-2-e-a-limitação-que-ficou-pendente" id="toc-revisão-rápida-da-aula-1-à-aula-2-e-a-limitação-que-ficou-pendente" class="nav-link" data-scroll-target="#revisão-rápida-da-aula-1-à-aula-2-e-a-limitação-que-ficou-pendente"><span class="header-section-number">1.1</span> Revisão Rápida: Da Aula 1 à Aula 2, e a Limitação Que Ficou Pendente</a></li>
  <li><a href="#ideia-central" id="toc-ideia-central" class="nav-link" data-scroll-target="#ideia-central"><span class="header-section-number">1.2</span> Ideia Central</a></li>
  <li><a href="#roteiro-da-aula" id="toc-roteiro-da-aula" class="nav-link" data-scroll-target="#roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</a></li>
  <li><a href="#problema-motivador" id="toc-problema-motivador" class="nav-link" data-scroll-target="#problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</a></li>
  <li><a href="#pergunta" id="toc-pergunta" class="nav-link" data-scroll-target="#pergunta"><span class="header-section-number">1.5</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#intuição-vales-e-montanhas" id="toc-intuição-vales-e-montanhas" class="nav-link" data-scroll-target="#intuição-vales-e-montanhas"><span class="header-section-number">2</span> Intuição — Vales e Montanhas</a>
  <ul class="collapse">
  <li><a href="#pergunta-1" id="toc-pergunta-1" class="nav-link" data-scroll-target="#pergunta-1"><span class="header-section-number">2.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#conjuntos-de-nível-de-densidade" id="toc-conjuntos-de-nível-de-densidade" class="nav-link" data-scroll-target="#conjuntos-de-nível-de-densidade"><span class="header-section-number">3</span> Conjuntos de Nível de Densidade</a>
  <ul class="collapse">
  <li><a href="#pergunta-2" id="toc-pergunta-2" class="nav-link" data-scroll-target="#pergunta-2"><span class="header-section-number">3.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#dbscan" id="toc-dbscan" class="nav-link" data-scroll-target="#dbscan"><span class="header-section-number">4</span> DBSCAN</a>
  <ul class="collapse">
  <li><a href="#pergunta-3" id="toc-pergunta-3" class="nav-link" data-scroll-target="#pergunta-3"><span class="header-section-number">4.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#clustering-hierárquico" id="toc-clustering-hierárquico" class="nav-link" data-scroll-target="#clustering-hierárquico"><span class="header-section-number">5</span> Clustering Hierárquico</a>
  <ul class="collapse">
  <li><a href="#verificando-com-um-exemplo-pequeno" id="toc-verificando-com-um-exemplo-pequeno" class="nav-link" data-scroll-target="#verificando-com-um-exemplo-pequeno"><span class="header-section-number">5.1</span> Verificando com um Exemplo Pequeno</a></li>
  <li><a href="#pergunta-4" id="toc-pergunta-4" class="nav-link" data-scroll-target="#pergunta-4"><span class="header-section-number">5.2</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#hdbscan" id="toc-hdbscan" class="nav-link" data-scroll-target="#hdbscan"><span class="header-section-number">6</span> HDBSCAN</a>
  <ul class="collapse">
  <li><a href="#aplicando-ao-breast-cancer-wisconsin-sem-rótulos" id="toc-aplicando-ao-breast-cancer-wisconsin-sem-rótulos" class="nav-link" data-scroll-target="#aplicando-ao-breast-cancer-wisconsin-sem-rótulos"><span class="header-section-number">6.1</span> Aplicando ao Breast Cancer Wisconsin, Sem Rótulos</a></li>
  <li><a href="#pergunta-5" id="toc-pergunta-5" class="nav-link" data-scroll-target="#pergunta-5"><span class="header-section-number">6.2</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#síntese-vantagens-e-limitações-do-hdbscan" id="toc-síntese-vantagens-e-limitações-do-hdbscan" class="nav-link" data-scroll-target="#síntese-vantagens-e-limitações-do-hdbscan"><span class="header-section-number">7</span> Síntese: Vantagens e Limitações do HDBSCAN</a>
  <ul class="collapse">
  <li><a href="#pergunta-6" id="toc-pergunta-6" class="nav-link" data-scroll-target="#pergunta-6"><span class="header-section-number">7.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#fechamento-e-ponte-para-a-aula-4" id="toc-fechamento-e-ponte-para-a-aula-4" class="nav-link" data-scroll-target="#fechamento-e-ponte-para-a-aula-4"><span class="header-section-number">8</span> Fechamento e Ponte para a Aula 4</a>
  <ul class="collapse">
  <li><a href="#pergunta-7" id="toc-pergunta-7" class="nav-link" data-scroll-target="#pergunta-7"><span class="header-section-number">8.1</span> Pergunta</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula 3: Topografia de Densidade e Grafos — Clustering Hierárquico e HDBSCAN</h1>
<p class="subtitle lead">Aprendizado Não Supervisionado</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos M. Raimundo — Instituto de Computação, UNICAMP </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">30 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/unsupervised-learning/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="revisão-e-introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Revisão e Introdução</h1>
<section id="revisão-rápida-da-aula-1-à-aula-2-e-a-limitação-que-ficou-pendente" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="revisão-rápida-da-aula-1-à-aula-2-e-a-limitação-que-ficou-pendente"><span class="header-section-number">1.1</span> Revisão Rápida: Da Aula 1 à Aula 2, e a Limitação Que Ficou Pendente</h2>
<p>A Aula 1 assumiu uma forma paramétrica fixa para a densidade <span class="math inline">\(p(\mathbf{x})\)</span> (uma gaussiana, por exemplo). A Aula 2 abandonou essa forma fixa: a partir do mesmo estimador geral <span class="math inline">\(p(\mathbf{x})=K/(NV)\)</span>, fixar <span class="math inline">\(K\)</span> e deixar <span class="math inline">\(V\)</span> crescer até capturar <span class="math inline">\(K\)</span> vizinhos dá o <span class="math inline">\(k\)</span>-NN (com a distância ao <span class="math inline">\(K\)</span>-ésimo vizinho, <span class="math inline">\(d_K(\mathbf{x})\)</span>, como subproduto); fixar <span class="math inline">\(V\)</span> e contar quantos pontos caem dentro dá a Janela de Parzen, suavizada com kernel gaussiano na KDE. Nenhum dos dois métodos escapou de duas limitações, porém: sem uma forma paramétrica para “resumir” os dados em poucos parâmetros, os dados <strong>são</strong> o modelo (toda consulta nova revisita o conjunto de treino inteiro), e ambos sofrem a <strong>maldição da dimensionalidade</strong> — em dimensão alta, o volume se concentra numa casca fina e as distâncias perdem poder de discriminação, um problema que volta a aparecer no bloco final desta aula, quando os <span class="math inline">\(30\)</span> atributos originais do Breast Cancer Wisconsin (não só os <span class="math inline">\(2\)</span> usados nas figuras) entram em jogo.</p>
<p>O resultado desses métodos, para qualquer conjunto de dados, é uma <strong>paisagem</strong> <span class="math inline">\(p(\mathbf{x})\)</span> com picos (regiões densas) e vales (regiões raras) — essa paisagem, sozinha, já responde “esse valor de <span class="math inline">\(\mathbf{x}\)</span> é comum ou raro?” ponto a ponto. A própria Aula 2 já apontou para onde isso ia: fechou com uma “Ponte para a Aula 3” avisando que <span class="math inline">\(d_K(\mathbf{x})\)</span>, ali uma ferramenta de estimação de densidade, seria reaproveitada como uma <strong>métrica de densidade local</strong> para construir caminhos num grafo — é exatamente esse reaproveitamento que esta aula cumpre.</p>
</section>
<section id="ideia-central" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="ideia-central"><span class="header-section-number">1.2</span> Ideia Central</h2>
<p>Só que “comum ou raro” não é a única pergunta que interessa. Dado um conjunto de pacientes, uma pergunta diferente — e ainda sem resposta — é: <strong>quais pacientes são parecidos o bastante entre si para merecer o mesmo rótulo?</strong> Saber que um ponto está numa região densa não diz, sozinho, com quais outros pontos ele forma um grupo: duas regiões densas separadas por um vale de baixa densidade são dois grupos diferentes, mas dois pontos dentro da mesma região densa e contígua — mesmo geometricamente distantes um do outro — deveriam contar como um único grupo. “Comum ou raro” é uma propriedade de um ponto isolado; “parecido com quem” é uma propriedade de <em>conjuntos</em> de pontos. Essa segunda pergunta é <strong>clustering</strong> — o objeto desta aula: transformar a mesma paisagem de densidade que a Aula 2 já sabe estimar numa partição de grupos, sem que ninguém diga de antemão quantos grupos existem, nem que forma cada um tem.</p>
</section>
<section id="roteiro-da-aula" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</h2>
<p>A pergunta que fecha o Organizador Prévio — transformar uma paisagem de densidade numa partição de grupos — se desdobra em quatro perguntas mais específicas, cada uma resolvida em um bloco desta aula:</p>
<ol type="1">
<li>Densidade sozinha não define grupo — <strong>o que exatamente deveria significar “cluster”</strong>?</li>
<li>Dada essa definição, <strong>como construir um cluster computacionalmente</strong>, sem escolher quantos grupos existem de antemão?</li>
<li>Isso pode ser reduzido a um problema de <strong>grafos</strong> — e, se sim, qual estrutura de grafo captura <em>toda</em> a hierarquia de clusters possível de uma só vez?</li>
<li>Uma vez com essa estrutura, <strong>como decidir quais clusters encontrados são estrutura real dos dados</strong>, e quais são só flutuação amostral?</li>
</ol>
</section>
<section id="problema-motivador" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</h2>
<p>Antes de resolver nada, olhe a paisagem de densidade de frente: a figura abaixo é a mesma ferramenta da Aula 2 — KDE — aplicada a um conjunto de pontos sintético e controlado, em forma de duas luas entrelaçadas, escolhido especificamente porque nenhuma suposição de “bola em torno de um centro” o respeitaria.</p>
<div class="fig-resize" style="width: 65%; margin: 0 auto;">
<div id="48f994d7" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>A paisagem mostra exatamente duas cristas conectadas, cada uma acompanhando o formato de uma lua, separadas por um vale visível de baixa densidade — apesar de as duas luas se entrelaçarem geometricamente (a ponta de uma passa perto do meio da outra). Isso já é informação nova, que a Aula 2 sozinha nunca perguntou: a Aula 2 calculava <span class="math inline">\(p(\mathbf{x})\)</span> para qualquer ponto individual do plano, mas nunca perguntava “quantas cristas separadas existem nessa paisagem, e onde termina uma e começa a outra?” — essa é uma pergunta sobre a <strong>conectividade</strong> do terreno alto, não sobre o valor da densidade em nenhum ponto isolado. Repare também que a resposta óbvia a olho nu (duas cristas) não tem nada a ver com “estar perto de um centro geométrico fixo”: as duas pontas de cada lua estão, em linha reta, tão longe uma da outra quanto de pontos da lua vizinha — o que as une é a crista de densidade alta que as conecta, não a proximidade a um ponto central.</p>
</section>
<section id="pergunta" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="pergunta"><span class="header-section-number">1.5</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>A paisagem de densidade acima parece ter, a olho nu, duas cristas separadas por um vale. Isso já resolve sozinho o problema de encontrar os grupos, ou falta alguma coisa?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se “ter uma paisagem de densidade” é a mesma coisa que “ter uma lista de quais pontos pertencem a qual grupo” — e o que teria que acontecer, algoritmicamente, para ir de um para o outro.</p>
<ul>
<li>□ Basta calcular <span class="math inline">\(p(\mathbf{x})\)</span> em cada ponto do dataset e aplicar um limiar fixo <span class="math inline">\(\lambda\)</span>: os pontos acima do limiar já vêm automaticamente rotulados por grupo, sem nenhum passo adicional.</li>
<li>□ Se toda a paisagem de densidade fosse uma única crista, sem nenhum vale separando regiões, não existiria estrutura de cluster genuína a recuperar — qualquer partição imposta sobre ela seria arbitrária.</li>
<li>□ Já que a Aula 2 responde “esse ponto é comum ou raro?” para cada ponto isolado, basta ordenar os pacientes por densidade estimada e cortar a lista ao meio para obter os dois grupos verdadeiros, em qualquer dataset com exatamente dois grupos.</li>
<li>□ Numa aplicação de detecção de fraude com dois golpes bem distintos, cada um formando sua própria concentração no espaço de atributos, a mesma lógica de “componente conectada de uma região de alta densidade” se aplicaria para separar os dois tipos de fraude entre si, mesmo sem nunca ter visto o rótulo do tipo de golpe.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="intuição-vales-e-montanhas" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Intuição — Vales e Montanhas</h1>
<p>Antes de qualquer formalismo, veja o resultado inteiro primeiro — só vai faltar nomear os passos. Pense na densidade <span class="math inline">\(p(\mathbf{x})\)</span> dos dados como uma <strong>paisagem</strong>: regiões densas são montanhas, regiões raras são vales. A aposta desta aula é que <strong>um cluster é uma montanha inteira</strong> — não importa o formato do contorno da montanha na base, só importa que ela seja um bloco conectado de terreno alto, separado das outras montanhas por um vale (uma região de baixa densidade).</p>
<p>Um algoritmo que respeita essa definição não precisa de centróide nenhum: em vez de “para qual centro fixo eu estou mais perto”, ele pergunta “caminhando sempre por terreno alto, até onde eu consigo chegar sem descer a um vale?”. Cada lua inteira, mesmo curva, é terreno alto conectado de ponta a ponta — não importa que as duas pontas da lua estejam geometricamente longe uma da outra em linha reta, porque a trilha entre elas nunca desce a um vale.</p>
<p>Essa escolha não é só estética. Qualquer regra que particione o espaço atribuindo cada ponto ao centro fixo mais próximo, dentre um pequeno conjunto de protótipos, sempre corta o espaço em regiões <strong>convexas</strong> — a região de cada protótipo é a interseção dos semiespaços “mais perto deste protótipo do que de qualquer outro”, e toda interseção de semiespaços é convexa. Isso significa que nenhuma escolha de protótipos, por mais que se aumente a quantidade deles, recupera uma lua ou um anel como um cluster único: a fronteira entre dois protótipos vizinhos é sempre reta (ou, em mais dimensões, um hiperplano), e uma reta não acompanha uma curva fechada. A definição por conectividade de terreno alto não tem essa restrição de forma nenhuma.</p>
<div class="fig-resize" style="width: 62%; margin: 0 auto;">
<div id="81bcbdb2" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Os dois painéis usam exatamente o algoritmo que esta aula vai construir — HDBSCAN, cujo nome ainda não foi justificado — e acertam por completo: acurácia <span class="math inline">\(100\%\)</span> contra o rótulo verdadeiro (nunca visto pelo algoritmo), tanto nas duas luas quanto nos dois anéis concêntricos — uma forma ainda mais hostil à ideia de “bola em torno de um centro”, já que o anel externo <em>envolve</em> o interno por todos os lados. Nenhum dos dois resultados depende de qualquer suposição sobre a forma do cluster: o algoritmo nunca precisou saber, de antemão, que a forma certa era uma lua ou um anel.</p>
<p>Falta nomear os passos: como, exatamente, “caminhar por terreno alto” se transforma em um algoritmo executável? A resposta atravessa três ideias, uma por bloco: (i) formalizar “montanha” como um conjunto de nível de densidade (Bloco 3); (ii) transformar isso em um grafo, usando uma distância que “sabe” onde é vale e onde é montanha (Bloco 4); (iii) extrair, desse grafo, uma única estrutura que contém toda a hierarquia de clusters possível ao mesmo tempo (Bloco 5).</p>
<section id="pergunta-1" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="pergunta-1"><span class="header-section-number">2.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Duas montanhas separadas por um vale raso (densidade baixa, mas não zero) — “andar por terreno alto” as trata como um cluster só, ou dois?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que muda se o vale for rebaixado ainda mais, até chegar a densidade zero, comparado ao vale raso original.</p>
<ul>
<li>□ Se o vale entre as duas montanhas nunca é totalmente seco (densidade sempre estritamente positiva em todo o caminho), então, para qualquer limiar de altura <span class="math inline">\(\lambda\)</span> suficientemente baixo, existe um caminho de terreno “alto o bastante” ligando as duas montanhas — então, nesse limiar, elas formam um cluster só.</li>
<li>□ A pergunta “cluster só ou dois clusters” tem uma resposta fixa, independente de qual altura <span class="math inline">\(\lambda\)</span> se usa para definir “terreno alto”.</li>
<li>□ Se o vale for rebaixado até ter densidade exatamente zero em algum ponto do caminho, nenhum limiar <span class="math inline">\(\lambda&gt;0\)</span> jamais conecta as duas montanhas por cima desse ponto.</li>
<li>□ Um vale raso entre duas montanhas altas é evidência de que, na verdade, os dados vieram de uma única população, e a divisão em duas montanhas é sempre um artefato de estimação.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="conjuntos-de-nível-de-densidade" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Conjuntos de Nível de Densidade</h1>
<p>Antes do formalismo, veja o esqueleto abstrato da metáfora da paisagem (Bloco 2) num corte transversal simples: um eixo <span class="math inline">\(\mathbf{x}\)</span> (aqui em 1D, só para poder desenhar) e a densidade <span class="math inline">\(p(\mathbf{x})\)</span> no eixo vertical, com duas “montanhas” separadas por um “vale”.</p>
<div class="fig-resize" style="width: 62%; margin: 0 auto;">
<img src="index_files/mediabag/f48b6b7b280587629f88dda8c4a72a23b3a06cef.svg" class="img-fluid">
</div>
<p>Fixando um limiar <span class="math inline">\(\lambda\)</span> (linha vermelha tracejada), o conjunto de nível <span class="math inline">\(L_\lambda=\{\mathbf{x}:p(\mathbf{x})\ge\lambda\}\)</span> é exatamente o trecho do eixo <span class="math inline">\(\mathbf{x}\)</span> em que a curva azul-acinzentada está acima da linha — aqui, <strong>duas componentes conexas disjuntas</strong> (destacadas em azul), uma por montanha, porque o vale entre elas fica abaixo de <span class="math inline">\(\lambda\)</span>. Baixando <span class="math inline">\(\lambda\)</span> até abaixo da altura do vale, as duas componentes se tocariam e passariam a contar como uma componente só — exatamente o mecanismo que a figura seguinte (com densidade estimada de verdade, via KDE, sobre os dados reais de duas luas) verifica numericamente, variando <span class="math inline">\(\lambda\)</span> de fato.</p>
<p>Formalize a metáfora da paisagem. Para um limiar <span class="math inline">\(\lambda \ge 0\)</span>, defina o <strong>conjunto de nível</strong> de densidade</p>
<p><span class="math display">\[L_\lambda = \{\mathbf{x} : p(\mathbf{x}) \ge \lambda\}.\]</span></p>
<p><span class="math inline">\(L_\lambda\)</span> é o “terreno acima da altura <span class="math inline">\(\lambda\)</span>” — o conjunto de todos os pontos do espaço onde a densidade é pelo menos <span class="math inline">\(\lambda\)</span>. A tese central desta aula, anunciada na Abertura, agora tem uma fórmula:</p>
<blockquote class="blockquote">
<p><strong>Um cluster, num nível <span class="math inline">\(\lambda\)</span> fixo, é uma componente conexa de <span class="math inline">\(L_\lambda\)</span>.</strong></p>
</blockquote>
<p>Essa definição já responde ao Bloco 2: uma componente conexa não precisa ser convexa, nem ter contorno regular — só precisa ser um bloco de terreno alto que se pode percorrer inteiro sem descer abaixo de <span class="math inline">\(\lambda\)</span>. Hastie, Tibshirani &amp; Friedman (ESL, 2009, p.&nbsp;507) descrevem essa família de método como um dos três paradigmas fundamentais de clustering, ao lado do combinatório (baseado em protótipos fixos, como o discutido no Bloco 2 — não o foco desta disciplina) e da modelagem por mistura (que a Aula 4 vai cobrir) — tradução livre:</p>
<blockquote class="blockquote">
<p>“Buscadores de moda (‘caçadores de irregularidades’) adotam uma perspectiva não-paramétrica, tentando estimar diretamente as modas distintas da função de densidade de probabilidade. As observações ‘mais próximas’ de cada respectiva moda definem então os clusters individuais.”</p>
</blockquote>
<p><strong>Os três paradigmas, lado a lado, nos mesmos dados.</strong> Para ver a diferença na prática, não só na definição, rode os três sobre as mesmas duas luas:</p>
<div id="1be8224d" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Nos mesmos dados, os dois primeiros paradigmas erram de formas diferentes: o combinatório (KMeans, à esquerda) só sabe traçar fronteiras retas entre protótipos — cada lua fica cortada ao meio, metade indo para o cluster errado. A mistura de duas gaussianas (centro) já é paramétrica o bastante para inclinar a fronteira, mas continua elíptica — ainda erra pontos nas pontas de cada lua. Só o terceiro (direita), sem nenhuma suposição de forma, acompanha exatamente o contorno de cada lua — é essa liberdade de forma que motiva usar conjuntos de nível de densidade nesta aula.</p>
<p><strong>O que acontece variando <span class="math inline">\(\lambda\)</span>.</strong> Para <span class="math inline">\(\lambda\)</span> muito alto, só os picos mais extremos de densidade sobrevivem — poucas regiões, pequenas, bem separadas (cada montanha isolada pelo próprio topo). Conforme <span class="math inline">\(\lambda\)</span> cai, cada região de <span class="math inline">\(L_\lambda\)</span> cresce (o “terreno acima de <span class="math inline">\(\lambda\)</span>” se expande encosta abaixo) e, em algum ponto crítico, duas regiões que eram separadas se tocam e se fundem numa só — exatamente o fenômeno da Pergunta do Bloco 2. Em <span class="math inline">\(\lambda=0\)</span>, <span class="math inline">\(L_0\)</span> é o suporte inteiro da densidade: uma única componente (supondo suporte conexo).</p>
<p>Isso já é, em germe, uma <strong>hierarquia de clusters indexada por <span class="math inline">\(\lambda\)</span></strong>: decrescer <span class="math inline">\(\lambda\)</span> de <span class="math inline">\(\infty\)</span> até <span class="math inline">\(0\)</span> nunca separa componentes que já estavam unidas (só pode fundir, nunca dividir) — a mesma estrutura de árvore, de baixo para cima, que o dendrograma da Aula de hierárquico clássico (Bloco 5) vai produzir. A figura abaixo mostra <span class="math inline">\(L_\lambda\)</span> estimado por KDE nos dados de duas luas, para limiares decrescentes: repare como as duas luas — cada uma uma componente sozinha nos limiares mais altos — permanecem separadas até <span class="math inline">\(\lambda\)</span> ficar baixo o bastante para o “vale” entre elas ser absorvido.</p>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<div id="261be6d8" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-7-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Da esquerda para a direita, <span class="math inline">\(\lambda\)</span> cai de <span class="math inline">\(0{,}20\)</span> para <span class="math inline">\(0{,}04\)</span>: no painel esquerdo, as duas luas ainda são regiões nitidamente separadas de <span class="math inline">\(L_\lambda\)</span> (a área azul); no painel direito, <span class="math inline">\(\lambda\)</span> já é baixo o bastante para que o vale entre as luas seja absorvido em <span class="math inline">\(L_\lambda\)</span> — as duas regiões se tocam e, para esse <span class="math inline">\(\lambda\)</span>, seriam contadas como uma componente conexa só. Nenhum <span class="math inline">\(\lambda\)</span> único é “o certo” — é exatamente esse problema (qual <span class="math inline">\(\lambda\)</span> escolher?) que o Bloco 6 vai resolver, não escolhendo um único <span class="math inline">\(\lambda\)</span>, mas medindo quanto tempo cada cluster “sobrevive” ao longo de toda a faixa de <span class="math inline">\(\lambda\)</span>.</p>
<section id="pergunta-2" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="pergunta-2"><span class="header-section-number">3.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>No limite <span class="math inline">\(\lambda \to \infty\)</span>, quantas componentes conexas tem <span class="math inline">\(L_\lambda\)</span>, em geral?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que sobra de “terreno acima de <span class="math inline">\(\lambda\)</span>” quando <span class="math inline">\(\lambda\)</span> é maior que a densidade máxima de qualquer região dos dados.</p>
<ul>
<li>□ No limite <span class="math inline">\(\lambda\to\infty\)</span>, <span class="math inline">\(L_\lambda\)</span> é, em geral, o conjunto vazio — nenhum ponto do espaço tem densidade infinita, então nenhum ponto sobrevive ao limiar.</li>
<li>□ O número de componentes conexas de <span class="math inline">\(L_\lambda\)</span> é uma função monótona não-crescente de <span class="math inline">\(\lambda\)</span> — nunca aumenta conforme <span class="math inline">\(\lambda\)</span> sobe (pode diminuir ou ficar igual, indo a zero no limite).</li>
<li>□ Existe sempre um <span class="math inline">\(\lambda\)</span> finito tal que <span class="math inline">\(L_\lambda\)</span> tem exatamente uma componente conexa por moda (pico local) da densidade — desde que os picos tenham alturas suficientemente diferentes entre si e o <span class="math inline">\(\lambda\)</span> seja escolhido logo abaixo do menor pico relevante.</li>
<li>□ Se a densidade <span class="math inline">\(p(\mathbf{x})\)</span> é estritamente positiva em todo o espaço <span class="math inline">\(\mathbb{R}^d\)</span> (nunca toca zero, mesmo longe dos dados), então <span class="math inline">\(L_\lambda\)</span> para <span class="math inline">\(\lambda\)</span> pequeno mas positivo pode ainda ter mais de uma componente conexa, dependendo de como <span class="math inline">\(p\)</span> varia.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="dbscan" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> DBSCAN</h1>
<p><strong>Do conjunto de nível a uma regra mais direta.</strong> O Bloco 3 definiu cluster via conjuntos de nível de densidade <span class="math inline">\(L_\lambda\)</span> — mas isso exige estimar <span class="math inline">\(p(\mathbf{x})\)</span> (KDE) e escolher um <span class="math inline">\(\lambda\)</span>. Existe uma via mais direta e clássica para a mesma ideia (“cluster = região densa conectada”), baseada só em <strong>contar vizinhos dentro de um raio</strong>, sem estimar densidade nenhuma: o <strong>DBSCAN</strong> (<em>Density-Based Spatial Clustering of Applications with Noise</em>, Ester, Kriegel, Sander &amp; Xu, 1996).</p>
<p><strong>Os dois parâmetros.</strong> DBSCAN precisa de um raio <span class="math inline">\(\varepsilon\)</span> e uma contagem mínima <code>minPts</code>. Defina a vizinhança <span class="math inline">\(N_\varepsilon(p)=\{q : d(p,q)\le\varepsilon\}\)</span> — que, por convenção (Ester et al., 1996; a mesma que o <code>scikit-learn</code> usa), <strong>conta o próprio <span class="math inline">\(p\)</span></strong> (afinal <span class="math inline">\(d(p,p)=0\le\varepsilon\)</span> sempre). Um ponto <span class="math inline">\(p\)</span> é <strong>núcleo</strong> (<em>core point</em>) se <span class="math inline">\(|N_\varepsilon(p)|\ge\text{minPts}\)</span> — se tem gente suficiente por perto, incluindo ele mesmo.</p>
<p><strong>Conexão direta e cadeia.</strong> Dois núcleos <span class="math inline">\(p,q\)</span> conectam <strong>diretamente</strong> se <span class="math inline">\(d(p,q)\le\varepsilon\)</span>. Um cluster é formado seguindo <strong>cadeias</strong> dessas conexões diretas — o fecho transitivo de “conectar direto”, uma definição <strong>recursiva</strong>, não um teste par a par: <span class="math inline">\(p\)</span> e um ponto distante <span class="math inline">\(z\)</span> podem acabar no mesmo cluster sem que <span class="math inline">\(d(p,z)\le\varepsilon\)</span>, desde que exista uma cadeia de núcleos <span class="math inline">\(p=x_0,x_1,\dots,x_m=z\)</span> com <span class="math inline">\(d(x_i,x_{i-1})\le\varepsilon\)</span> em cada passo. Um ponto não-núcleo que cai a <span class="math inline">\(\le\varepsilon\)</span> de algum núcleo entra no cluster como <strong>borda</strong> (mas não propaga a cadeia adiante); quem sobra — nem núcleo, nem a <span class="math inline">\(\le\varepsilon\)</span> de nenhum núcleo — vira <strong>ruído</strong>.</p>
<p><strong>O algoritmo, por extenso.</strong> Nada aqui exige nenhuma peça sofisticada — dá para descrever o DBSCAN clássico direto da definição, em poucos passos, usando só a matriz de distâncias <span class="math inline">\(D\)</span>:</p>
<ol type="1">
<li>Para cada ponto <span class="math inline">\(p\)</span>, conte quantos pontos (incluindo o próprio <span class="math inline">\(p\)</span>) estão a distância <span class="math inline">\(\le\varepsilon\)</span>; se houver pelo menos <code>minPts</code>, marque <span class="math inline">\(p\)</span> como <strong>núcleo</strong>.</li>
<li>Escolha um núcleo <span class="math inline">\(p\)</span> ainda não visitado e abra um cluster novo; marque <span class="math inline">\(p\)</span> como visitado e ponha <span class="math inline">\(p\)</span> numa fila de busca.</li>
<li>Tire um ponto <span class="math inline">\(q\)</span> da fila e examine todo vizinho <span class="math inline">\(r\)</span> a distância <span class="math inline">\(\le\varepsilon\)</span> de <span class="math inline">\(q\)</span>: coloque <span class="math inline">\(r\)</span> no cluster atual (núcleo ou borda); se <span class="math inline">\(r\)</span> <strong>também for núcleo</strong> e ainda não tiver sido visitado, marque-o como visitado e <strong>acrescente-o à fila</strong> — é essa propagação, só por núcleos, que forma a cadeia (fecho transitivo).</li>
<li>Repita o passo 3 até a fila esvaziar; volte ao passo 2 para o próximo núcleo ainda não visitado, até cobrir todos os núcleos.</li>
<li>Todo ponto que nunca entrou em cluster nenhum (não é núcleo, e não está a <span class="math inline">\(\le\varepsilon\)</span> de nenhum núcleo) fica como <strong>ruído</strong>.</li>
</ol>
<p><strong>Um jeito mais fácil de checar “esses dois estão juntos?”.</strong> Decidir se dois pontos <span class="math inline">\(p,q\)</span> conectam, do jeito que acabamos de ver, exige <strong>duas</strong> verificações separadas: “<span class="math inline">\(p\)</span> é núcleo?”, “<span class="math inline">\(q\)</span> é núcleo?”, e só então “<span class="math inline">\(d(p,q)\le\varepsilon\)</span>?”. Dá para colapsar tudo isso numa <strong>única</strong> comparação de distância — o que também é exatamente o que falta para montar um grafo pesado e usar tudo que já se sabe sobre grafos (Bloco 5). Para isso, é preciso primeiro medir “o quão núcleo” um ponto é, sem fixar <span class="math inline">\(\varepsilon\)</span> ainda.</p>
<p>O Bloco 3 já definiu cluster em termos de <span class="math inline">\(p(\mathbf{x})\)</span> — mas <span class="math inline">\(p\)</span> nunca é conhecido de verdade, só estimado. A Aula 2 já resolveu exatamente esse problema com o estimador <span class="math inline">\(k\)</span>-NN: fixar <span class="math inline">\(K\)</span> vizinhos e medir o raio <span class="math inline">\(d_K(\mathbf{x})\)</span> da bola que os captura dá <span class="math inline">\(p(\mathbf{x})\approx K/(NV)\)</span>, com <span class="math inline">\(V\)</span> o volume dessa bola — e <span class="math inline">\(V\)</span> cresce junto com <span class="math inline">\(d_K(\mathbf{x})\)</span> (raio maior, volume maior). É por isso, e não por coincidência, que <span class="math inline">\(d_K(\mathbf{x})\)</span> é <strong>inversamente relacionado à densidade local</strong>: ele é literalmente o raio que aparece no denominador do estimador. <span class="math inline">\(d_K(\mathbf{x})\)</span> pequeno significa que bastou uma bola pequena (volume pequeno) para juntar <span class="math inline">\(K\)</span> vizinhos — região densa; <span class="math inline">\(d_K(\mathbf{x})\)</span> grande significa que foi preciso um raio grande — região rara. Sem exigir nenhuma forma paramétrica para <span class="math inline">\(p\)</span>, é essa mesma distância, sem nenhuma mudança na fórmula, que hoje recebe um nome novo — <strong>core distance</strong>, ou distância ao núcleo, <span class="math inline">\(\mathrm{core}_K(\mathbf{x}) = d_K(\mathbf{x})\)</span> — e um uso novo: virar peso de aresta num grafo.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Premissas desta derivação
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span> pequeno <span class="math inline">\(\Leftrightarrow\)</span> <span class="math inline">\(\mathbf{x}\)</span> está numa região densa (herdado direto da Aula 2).</li>
<li>A distância bruta <span class="math inline">\(d(a,b)\)</span> entre dois pontos, por si só, <strong>não</strong> diz nada sobre a densidade da vizinhança de nenhum dos dois — dois pontos podem estar geometricamente próximos mesmo que um deles more numa região densa e o outro numa região quase vazia.</li>
<li>Um cluster (Bloco 3) é definido por conectividade <em>dentro de terreno alto</em> — então a “distância” usada para conectar dois pontos no grafo precisa penalizar caminhos que passam por regiões raras, não só medir o comprimento geométrico do caminho.</li>
</ol>
</div>
</div>
<p><strong>Por que a distância bruta não basta.</strong> Imagine dois pacientes <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> com valores de atributos geometricamente próximos — <span class="math inline">\(d(a,b)\)</span> pequeno. Se <span class="math inline">\(a\)</span> mora no meio de uma região densa (muitos pacientes parecidos por perto, <span class="math inline">\(\mathrm{core}_K(a)\)</span> pequeno) e <span class="math inline">\(b\)</span> mora sozinho, longe de qualquer vizinho (região rara, <span class="math inline">\(\mathrm{core}_K(b)\)</span> grande), conectar <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> diretamente pelo valor bruto <span class="math inline">\(d(a,b)\)</span> ignoraria que <span class="math inline">\(b\)</span> está, na prática, isolado — <span class="math inline">\(b\)</span> só “parece” perto de <span class="math inline">\(a\)</span> porque a distância entre os dois é pequena, não porque existe uma trilha densa de pacientes ligando os dois.</p>
<p><strong>A construção, passo a passo.</strong> Defina a <strong>distância de alcançabilidade mútua</strong></p>
<p><span class="math display">\[d_{\mathrm{mreach}}(a,b) = \max\bigl(\mathrm{core}_K(a),\ \mathrm{core}_K(b),\ d(a,b)\bigr).\]</span></p>
<p>Ela “acalma” pontos em regiões raras: se <span class="math inline">\(b\)</span> está isolado (<span class="math inline">\(\mathrm{core}_K(b)\)</span> grande), então <span class="math inline">\(d_{\mathrm{mreach}}(a,b) \ge
\mathrm{core}_K(b)\)</span> para <strong>qualquer</strong> <span class="math inline">\(a\)</span> — <span class="math inline">\(b\)</span> nunca parece mais próximo de ninguém do que sua própria distância ao vale mais próximo permite. Ao mesmo tempo, se <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> moram na mesma região densa (ambos os <em>core distances</em> pequenos e <span class="math inline">\(d(a,b)\)</span> também pequeno), <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> continua pequeno — a distância bruta domina o máximo, e a conexão é barata, exatamente o que se espera de dois pontos dentro da mesma “montanha”.</p>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<img src="index_files/mediabag/3a5b473def99a5e08a39c02e07aae193507dba2e.svg" class="img-fluid">
</div>
<p>O diagrama resume a construção: três quantidades entram, uma sai. Note que <span class="math inline">\(d_{\mathrm{mreach}}\)</span> é sempre <strong>maior ou igual</strong> à distância bruta <span class="math inline">\(d(a,b)\)</span> — a alcançabilidade mútua nunca aproxima pontos, só os afasta quando algum dos dois mora numa região rara. Essa assimetria (só afastar, nunca aproximar) é o mecanismo exato de “acalmar” pontos isolados sem alterar em nada as distâncias dentro de uma região já densa.</p>
<div id="95db20e5" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Núcleo pequeno (K=5) sobre os dois atributos reais que vão sustentar</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># o Bloco 6 -- ilustra a "calma" da alcançabilidade mútua em 5 pacientes</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># escolhidos deliberadamente: 4 numa vizinhança densa, 1 isolado.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>_tree_2d <span class="op">=</span> cKDTree(X_2d)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>_core_2d <span class="op">=</span> core_distance(X_2d, K<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>_isolado <span class="op">=</span> np.argmax(_core_2d)          <span class="co"># paciente com o maior core distance</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>_denso <span class="op">=</span> np.argsort(_core_2d)[:<span class="dv">4</span>]        <span class="co"># 4 pacientes na região mais densa</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>_a, _b <span class="op">=</span> _denso[<span class="dv">0</span>], _isolado</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>_d_raw <span class="op">=</span> np.linalg.norm(X_2d[_a] <span class="op">-</span> X_2d[_b])</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>_d_mreach <span class="op">=</span> <span class="bu">max</span>(_core_2d[_a], _core_2d[_b], _d_raw)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"core(</span><span class="sc">{</span>_a<span class="sc">}</span><span class="ss">)=</span><span class="sc">{</span>_core_2d[_a]<span class="sc">:.3f}</span><span class="ss">  core(</span><span class="sc">{</span>_b<span class="sc">}</span><span class="ss">)=</span><span class="sc">{</span>_core_2d[_b]<span class="sc">:.3f}</span><span class="ss">  "</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"d_bruta=</span><span class="sc">{</span>_d_raw<span class="sc">:.3f}</span><span class="ss">  d_mreach=</span><span class="sc">{</span>_d_mreach<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>core(418)=0.033  core(461)=1.288  d_bruta=5.388  d_mreach=5.388</code></pre>
</div>
</div>
<p>Neste exemplo com os dados reais do Breast Cancer Wisconsin (usando apenas os dois atributos de visualização deste bloco em diante, <code>radius_worst</code> e <code>concave points_worst</code>, padronizados), o paciente mais isolado tem <span class="math inline">\(\mathrm{core}_5\)</span> visivelmente maior que a distância bruta até um paciente da região densa — então <span class="math inline">\(d_{\mathrm{mreach}}\)</span> é dominado pelo <em>core distance</em> do isolado, não pela distância bruta: exatamente o comportamento “acalmante” descrito acima, agora visto num número real, não só na fórmula.</p>
<section id="pergunta-3" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="pergunta-3"><span class="header-section-number">4.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(\mathrm{core}_K(a) = \mathrm{core}_K(b) = 0\)</span> (dois pontos coincidentes com pelo menos <span class="math inline">\(K\)</span> outros pontos na mesma posição exata), o que <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> vale?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia a fórmula — o que o <span class="math inline">\(\max\)</span> faz quando dois dos três termos são zero?</p>
<ul>
<li>□ Se <span class="math inline">\(\mathrm{core}_K(a)=\mathrm{core}_K(b)=0\)</span>, então <span class="math inline">\(d_{\mathrm{mreach}}(a,b) = d(a,b)\)</span> — a distância bruta passa a decidir sozinha, porque os dois termos de núcleo não competem com ela no máximo.</li>
<li>□ <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> sempre vale zero quando pelo menos um dos dois <em>core distances</em> é zero, independente do valor de <span class="math inline">\(d(a,b)\)</span>.</li>
<li>□ Num caso extremo em que <span class="math inline">\(d(a,b)=0\)</span> também (os próprios <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> coincidem exatamente), <span class="math inline">\(d_{\mathrm{mreach}}(a,b)=0\)</span>.</li>
<li>□ Esse caso extremo (core distance zero) é impossível de ocorrer na prática com dados reais, então não precisa ser considerado ao implementar a fórmula.</li>
</ul>
</div>
</div>
<p><strong>A vantagem: uma distância só, em vez de duas verificações.</strong> Com <span class="math inline">\(d_{\mathrm{mreach}}\)</span> definida para todo par, dá para checar se <span class="math inline">\(p\)</span> e <span class="math inline">\(q\)</span> conectam com uma <strong>única</strong> comparação de distância — sem verificar “núcleo?” separadamente para cada um. Escolha um limiar <span class="math inline">\(\varepsilon\)</span>, construa o grafo cujos vértices são os <span class="math inline">\(N\)</span> pontos e cujas arestas ligam <span class="math inline">\(u,v\)</span> sempre que <span class="math inline">\(d_{\mathrm{mreach}}(u,v)\le\varepsilon\)</span>, e tome as <strong>componentes conexas</strong> desse grafo — cada componente é um cluster; pontos sem nenhuma aresta (porque o <span class="math inline">\(\mathrm{core}_K\)</span> deles já é maior que <span class="math inline">\(\varepsilon\)</span>) ficam isolados e viram ruído, sem nenhuma etapa extra.</p>
<p><strong>Por que isso é exatamente o DBSCAN da seção anterior.</strong> Lembrando: DBSCAN define <span class="math inline">\(p\)</span> como núcleo se <span class="math inline">\(|N_\varepsilon(p)|\ge\text{minPts}\)</span> e conecta diretamente dois núcleos <span class="math inline">\(p,q\)</span> se <span class="math inline">\(d(p,q)\le\varepsilon\)</span>.</p>
<p><strong>Atenção a um detalhe de contagem que muda o resultado.</strong> <span class="math inline">\(N_\varepsilon(p)\)</span> conta o próprio <span class="math inline">\(p\)</span> (a distância de <span class="math inline">\(p\)</span> a si mesmo é <span class="math inline">\(0\le\varepsilon\)</span>, sempre) — é a convenção original do DBSCAN (Ester et al., 1996) e a que o <code>scikit-learn</code> usa. Então “pelo menos <code>minPts</code> pontos em <span class="math inline">\(N_\varepsilon(p)\)</span>, contando <span class="math inline">\(p\)</span>” significa “pelo menos <span class="math inline">\(\text{minPts}-1\)</span> <strong>outros</strong> pontos a distância <span class="math inline">\(\le\varepsilon\)</span>” — e <span class="math inline">\(\mathrm{core}_K(p)\)</span>, por definição, é a distância ao <span class="math inline">\(K\)</span>-ésimo vizinho <strong>sem contar <span class="math inline">\(p\)</span></strong>. O <span class="math inline">\(K\)</span> certo, portanto, é <span class="math display">\[K = \text{minPts} - 1,\]</span> não <span class="math inline">\(K=\text{minPts}\)</span> (testei os dois numericamente contra o <code>DBSCAN</code> do <code>scikit-learn</code>: com <span class="math inline">\(K=\text{minPts}-1\)</span> os conjuntos de pontos-núcleo batem exatamente; com <span class="math inline">\(K=\text{minPts}\)</span>, não — sobra sistematicamente um ponto de vizinhança por causa dessa contagem).</p>
<p>Com esse <span class="math inline">\(K\)</span>, “<span class="math inline">\(p\)</span> é núcleo a um limiar <span class="math inline">\(\varepsilon\)</span>” é exatamente “<span class="math inline">\(\mathrm{core}_K(p)\le\varepsilon\)</span>”, a própria definição de core distance. Logo, os dois requisitos do DBSCAN para uma conexão direta — “<span class="math inline">\(p\)</span> núcleo, <span class="math inline">\(q\)</span> núcleo, e <span class="math inline">\(d(p,q)\le\varepsilon\)</span>” — viram <span class="math display">\[
\mathrm{core}_K(p)\le\varepsilon \ \text{e}\ \mathrm{core}_K(q)\le\varepsilon \ \text{e}\ d(p,q)\le\varepsilon
\quad\iff\quad
\max\bigl(\mathrm{core}_K(p),\mathrm{core}_K(q),d(p,q)\bigr)\le\varepsilon
\quad\iff\quad
d_{\mathrm{mreach}}(p,q)\le\varepsilon.
\]</span> O grafo de <span class="math inline">\(d_{\mathrm{mreach}}\)</span> cortado em <span class="math inline">\(\varepsilon\)</span> e o grafo de núcleos do DBSCAN nesses mesmos parâmetros (<span class="math inline">\(\varepsilon,\ \text{minPts}=K+1\)</span>) têm exatamente as mesmas arestas — logo, as mesmas componentes conexas, os mesmos clusters. Essa variante, que só liga núcleo a núcleo (sem a etapa extra de “anexar ponto de borda ao cluster mais próximo” do DBSCAN original), é chamada <strong>DBSCAN*</strong> no artigo do HDBSCAN (Campello, Moulavi &amp; Sander, 2013).</p>
<p><strong>O desafio que sobra: como escolher os parâmetros?</strong> DBSCAN (ou sua versão <span class="math inline">\(d_{\mathrm{mreach}}\)</span>) funciona bem — mas exige fixar <span class="math inline">\(\varepsilon\)</span> e <code>minPts</code>/<span class="math inline">\(K\)</span> <em>a priori</em>, sem nenhum critério óbvio para escolhê-los, e o resultado pode mudar bastante conforme esses valores mudam. Em vez de tentar adivinhar o <span class="math inline">\(\varepsilon\)</span> “certo” de uma vez, existe uma saída mais palpável: construir a hierarquia inteira, variando <span class="math inline">\(\varepsilon\)</span> de <span class="math inline">\(0\)</span> a <span class="math inline">\(\infty\)</span>, e decidir depois onde (e se) cortar. É essa ideia — clustering hierárquico — que resolve o problema de frente.</p>
</section>
</section>
<section id="clustering-hierárquico" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Clustering Hierárquico</h1>
<p><strong>Motivação: sentir o número de clusters sem fixar um único corte.</strong> O Bloco 4 terminou num desafio: DBSCAN (com ou sem <span class="math inline">\(d_{\mathrm{mreach}}\)</span>) exige fixar <span class="math inline">\(\varepsilon\)</span> e <code>minPts</code>/<span class="math inline">\(K\)</span> de antemão, sem critério óbvio para escolhê-los. Clustering hierárquico ataca o problema de outro jeito: em vez de escolher um corte e ver o que sai, constrói a <strong>sequência inteira</strong> de partições aninhadas, de <span class="math inline">\(N\)</span> clusters (um por ponto) até <span class="math inline">\(1\)</span> cluster (todo mundo junto), e só depois — ou nunca, deixando a árvore inteira como resposta — decide onde cortar. É exatamente essa ideia, aplicada à hierarquia de <span class="math inline">\(d_{\mathrm{mreach}}\)</span> em vez da distância bruta, que o Bloco 6 (HDBSCAN) vai usar para extrair clusters sem escolher nenhum <span class="math inline">\(\lambda\)</span> à mão.</p>
<p><strong>Como funciona: aglomerativo, de baixo para cima.</strong> Um algoritmo hierárquico aglomerativo começa com <span class="math inline">\(N\)</span> clusters — um por ponto — e, a cada passo, funde os <strong>dois clusters mais próximos</strong> num só, sempre num nível de dissimilaridade maior que o passo anterior, até sobrar um único cluster com todo mundo dentro. Essa sequência de <span class="math inline">\(N-1\)</span> fusões é a <strong>hierarquia</strong> propriamente dita — o <strong>dendrograma</strong>. O que falta especificar é uma única coisa: o que significa “distância entre dois <em>clusters</em>” (não entre dois pontos) — existem várias regras possíveis para isso, e a Aula usa uma específica.</p>
<p><strong>Ligação simples (single linkage).</strong> Hastie, Tibshirani &amp; Friedman (ESL, 2009, §14.3.12) descrevem a regra desta aula, tradução livre —</p>
<blockquote class="blockquote">
<p>“<em>Ligação simples</em> (SL) toma a dissimilaridade intergrupo como a do par mais próximo (menos dissimilar): <span class="math inline">\(d_{SL}(G,H) = \min_{i\in G,
i'\in H} d_{ii'}\)</span>. Isso também é chamado, com frequência, de técnica do <em>vizinho mais próximo</em>.” (p.&nbsp;523)</p>
</blockquote>
<p>O algoritmo hierárquico aglomerativo por ligação simples começa com <span class="math inline">\(N\)</span> clusters (um por ponto) e, a cada passo, funde os dois clusters cuja menor distância entre um par de membros é a menor de todas — produzindo uma sequência de <span class="math inline">\(N-1\)</span> fusões, cada uma em um nível de dissimilaridade maior que a anterior (ESL, p.&nbsp;520-521, tradução livre): <em>“cada nível da hierarquia representa um agrupamento particular […] a árvore binária […] tem <span class="math inline">\(N-1\)</span> níveis”</em>.</p>
<p><strong>O custo de fazer isso ingenuamente.</strong> Construir essa hierarquia do zero — recalculando, a cada uma das <span class="math inline">\(N-1\)</span> fusões, qual par de clusters está mais próximo — parece exigir refazer o trabalho inteiro para cada <span class="math inline">\(k\)</span> diferente que se queira testar. Existe um atalho: uma única estrutura, com apenas <span class="math inline">\(N-1\)</span> arestas, que já contém a hierarquia inteira de ligação simples de uma vez — a <strong>Árvore Geradora Mínima</strong> (MST).</p>
<p>Com uma matriz de distâncias definida para todo par de pontos (aqui, <span class="math inline">\(d_{\mathrm{mreach}}\)</span>, mas o argumento a seguir vale para qualquer distância), construa o <strong>grafo completo</strong> cujos vértices são os <span class="math inline">\(N\)</span> pontos e cujo peso de aresta <span class="math inline">\((i,j)\)</span> é a distância entre eles. Esse grafo tem <span class="math inline">\(N(N-1)/2\)</span> arestas — muitas delas redundantes, no sentido de que existem vários caminhos possíveis entre o mesmo par de vértices. Uma <strong>árvore geradora</strong> (<em>spanning tree</em>) é um subgrafo que conecta todos os <span class="math inline">\(N\)</span> vértices usando exatamente <span class="math inline">\(N-1\)</span> arestas e nenhum ciclo — o mínimo de arestas que ainda mantém tudo ligado. Entre todas as árvores geradoras possíveis desse grafo (e existem muitas), a que minimiza a soma dos pesos das suas <span class="math inline">\(N-1\)</span> arestas é a <strong>Árvore Geradora Mínima</strong> (<em>Minimum Spanning Tree</em>, MST).</p>
<p><strong>Teorema (equivalência MST–ligação simples; Gower &amp; Ross, 1969).</strong> Seja <span class="math inline">\(G\)</span> o grafo completo de pesos <span class="math inline">\(d(i,j)\)</span> e, para um limiar <span class="math inline">\(\tau\ge0\)</span>, seja <span class="math inline">\(G_\tau\)</span> o subgrafo de <span class="math inline">\(G\)</span> restrito às arestas de peso <span class="math inline">\(\le\tau\)</span>. Seja <span class="math inline">\(T\)</span> a MST de <span class="math inline">\(G\)</span> e <span class="math inline">\(T_\tau\)</span> o subgrafo de <span class="math inline">\(T\)</span> restrito às arestas de peso <span class="math inline">\(\le\tau\)</span>. Então, <strong>para todo <span class="math inline">\(\tau\)</span>, <span class="math inline">\(G_\tau\)</span> e <span class="math inline">\(T_\tau\)</span> têm exatamente as mesmas componentes conexas</strong> — ou seja, os clusters de ligação simples no nível <span class="math inline">\(\tau\)</span> (componentes de <span class="math inline">\(G_\tau\)</span>, por definição) são idênticos às componentes obtidas cortando de <span class="math inline">\(T\)</span> só as arestas de peso <span class="math inline">\(&gt;\tau\)</span>.</p>
<p><em>Prova.</em> Como <span class="math inline">\(T\subseteq G\)</span> (toda aresta da MST é uma aresta de <span class="math inline">\(G\)</span>), <span class="math inline">\(T_\tau\subseteq G_\tau\)</span>: qualquer caminho dentro de <span class="math inline">\(T_\tau\)</span> também é um caminho dentro de <span class="math inline">\(G_\tau\)</span>, logo toda componente de <span class="math inline">\(T_\tau\)</span> está contida numa componente de <span class="math inline">\(G_\tau\)</span>. Falta a direção que não é óbvia: se <span class="math inline">\(p\)</span> e <span class="math inline">\(q\)</span> estão na mesma componente de <span class="math inline">\(G_\tau\)</span> (existe <em>algum</em> caminho entre eles em <span class="math inline">\(G\)</span> usando só arestas <span class="math inline">\(\le\tau\)</span>), eles também precisam estar na mesma componente de <span class="math inline">\(T_\tau\)</span>. Chame de <strong>custo</strong> de um caminho o <strong>maior</strong> peso de aresta ao longo dele — o “elo mais fraco da corrente”. A MST tem a propriedade do <strong>caminho de gargalo mínimo</strong> (resultado clássico de teoria de grafos): o caminho entre <span class="math inline">\(p\)</span> e <span class="math inline">\(q\)</span> <em>dentro da MST</em> — único, já que é uma árvore — tem sempre o menor custo possível entre <strong>todos</strong> os caminhos de <span class="math inline">\(p\)</span> a <span class="math inline">\(q\)</span> em <span class="math inline">\(G\)</span>; nenhuma rota alternativa consegue um elo mais fraco mais barato. Por hipótese existe um caminho em <span class="math inline">\(G\)</span> de custo <span class="math inline">\(\le\tau\)</span> (o que exibe <span class="math inline">\(p,q\)</span> na mesma componente de <span class="math inline">\(G_\tau\)</span>); logo o custo mínimo entre <span class="math inline">\(p\)</span> e <span class="math inline">\(q\)</span> é <span class="math inline">\(\le\tau\)</span>; logo o caminho da MST entre eles também tem custo <span class="math inline">\(\le\tau\)</span> — ou seja, esse caminho inteiro sobrevive em <span class="math inline">\(T_\tau\)</span>, colocando <span class="math inline">\(p\)</span> e <span class="math inline">\(q\)</span> na mesma componente de <span class="math inline">\(T_\tau\)</span>. <span class="math inline">\(\blacksquare\)</span></p>
<p><strong>Consequência prática.</strong> Cortar as <span class="math inline">\(k-1\)</span> arestas mais pesadas da MST é só escolher <span class="math inline">\(\tau\)</span> logo abaixo do peso da <span class="math inline">\((k-1)\)</span>-ésima aresta mais pesada — pelo teorema, isso produz exatamente as <span class="math inline">\(k\)</span> componentes do clustering por ligação simples com <span class="math inline">\(k\)</span> clusters, para qualquer <span class="math inline">\(k\)</span>, sem recalcular nada.</p>
<p><strong>Verificando num exemplo pequeno.</strong> O teorema já garante a igualdade; mesmo assim vale conferir com números antes de seguir em frente, um <em>worked example</em> no espírito da técnica de “exemplo resolvido antes do resultado geral”.</p>
<section id="verificando-com-um-exemplo-pequeno" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="verificando-com-um-exemplo-pequeno"><span class="header-section-number">5.1</span> Verificando com um Exemplo Pequeno</h2>
<div id="9c2f8ab5" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Arestas da MST (i, j, peso), ordem crescente:"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, j, w <span class="kw">in</span> edges_pts:</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  (</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">,</span><span class="sc">{</span>j<span class="sc">}</span><span class="ss">) peso=</span><span class="sc">{</span>w<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, (labels_mst, labels_sl, iguais) <span class="kw">in</span> _resultado_k.items():</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">:  MST-corte = </span><span class="sc">{</span>labels_mst<span class="sc">}</span><span class="ss">   ligação-simples = </span><span class="sc">{</span>labels_sl<span class="sc">}</span><span class="ss">   partições idênticas? </span><span class="sc">{</span>iguais<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Arestas da MST (i, j, peso), ordem crescente:
  (3,5) peso=0.412
  (3,4) peso=0.500
  (0,1) peso=0.583
  (1,2) peso=0.671
  (2,5) peso=6.140
  (5,6) peso=6.223
k=2:  MST-corte = [0 0 0 0 0 0 1]   ligação-simples = [1 1 1 1 1 1 2]   partições idênticas? True
k=3:  MST-corte = [0 0 0 1 1 1 2]   ligação-simples = [2 2 2 1 1 1 3]   partições idênticas? True</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<div id="b65bb555" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-13-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Os 7 pontos formam visualmente três grupos: A (<span class="math inline">\(0,1,2\)</span>, perto da origem), B (<span class="math inline">\(3,4,5\)</span>, perto de <span class="math inline">\((5,5)\)</span>) e o ponto isolado <span class="math inline">\(6\)</span> (<span class="math inline">\((9{,}5,
0{,}2)\)</span>). A MST tem, como esperado, <span class="math inline">\(6\)</span> arestas (<span class="math inline">\(N-1=6\)</span>): quatro arestas curtas dentro de A e B (pesos entre <span class="math inline">\(0{,}41\)</span> e <span class="math inline">\(0{,}67\)</span>) e duas arestas longas ligando os grupos entre si e ao ponto isolado (pesos <span class="math inline">\(6{,}14\)</span> e <span class="math inline">\(6{,}22\)</span>) — exatamente as duas arestas mais pesadas.</p>
<p>Cortando a aresta mais pesada (<span class="math inline">\(k=2\)</span>): sobra <span class="math inline">\(\{0,1,2,3,4,5\}\)</span> de um lado e <span class="math inline">\(\{6\}\)</span> isolado do outro — e o clustering por ligação simples com <span class="math inline">\(k=2\)</span> produz <strong>exatamente a mesma partição</strong> (o código acima confirma: partições idênticas). Cortando também a segunda mais pesada (<span class="math inline">\(k=3\)</span>): sobra <span class="math inline">\(\{0,1,2\}\)</span>, <span class="math inline">\(\{3,4,5\}\)</span> e <span class="math inline">\(\{6\}\)</span> — os três grupos visuais, de novo idênticos à ligação simples. Note que em <span class="math inline">\(k=2\)</span> os grupos A e B se fundem antes de <span class="math inline">\(6\)</span> se juntar a qualquer um deles — porque a menor distância entre A e B (<span class="math inline">\(6{,}14\)</span>) é, por pouco, menor que a menor distância de <span class="math inline">\(6\)</span> a qualquer dos dois grupos (<span class="math inline">\(6{,}22\)</span>); um exemplo de que “vizinho mais próximo” pode produzir fusões que não são as mais “intuitivas” à primeira vista, mas são as matematicamente corretas pela definição de ligação simples.</p>
<p><strong>A vantagem desta construção.</strong> A MST, uma única estrutura com <span class="math inline">\(N-1\)</span> arestas, contém a hierarquia completa: para obter o clustering de ligação simples em <strong>qualquer</strong> número de clusters <span class="math inline">\(k\)</span>, basta ordenar as arestas da MST por peso e cortar as <span class="math inline">\(k-1\)</span> mais pesadas — sem refazer nenhum cálculo de distância. É a compressão exata da paisagem inteira de <span class="math inline">\(\lambda\)</span>s do Bloco 3 numa única árvore.</p>
<p>Um aviso honesto, também do ESL (p.&nbsp;524, tradução livre), sobre a ligação simples especificamente: <em>“Como a ligação simples exige apenas que uma única dissimilaridade seja pequena para que dois grupos sejam considerados próximos, […] ela terá tendência a combinar, em limiares relativamente baixos, observações ligadas por uma série de observações intermediárias próximas. Esse fenômeno, chamado de <em>encadeamento</em> (<em>chaining</em>), é frequentemente considerado um defeito do método.”</em> — uma fileira de pontos, cada um perto do próximo, pode encadear dois grupos que “deveriam” ser distintos. É esse defeito, mais o problema de “que <span class="math inline">\(k\)</span>/<span class="math inline">\(\lambda\)</span> escolher” do Bloco 3, que o Bloco 6 ataca.</p>
</section>
<section id="pergunta-4" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="pergunta-4"><span class="header-section-number">5.2</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se um único ponto de ruído for inserido exatamente no meio do “vale” entre dois clusters genuinamente distintos, o que acontece com a MST e com o clustering por ligação simples resultante?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no “encadeamento” citado do ESL — o que uma única observação intermediária bem posicionada consegue fazer.</p>
<ul>
<li>□ Esse único ponto de ruído pode, por si só, criar uma aresta curta ligando os dois clusters através dele, fazendo a ligação simples fundir os dois clusters num nível de dissimilaridade bem mais baixo do que fundiria sem esse ponto.</li>
<li>□ Um único ponto no meio do vale nunca afeta a MST global, porque a MST é definida pela soma total de pesos, e um único ponto tem peso desprezível relativo ao total.</li>
<li>□ Esse cenário é exatamente o que o ESL chama de <em>chaining</em> (encadeamento) — um defeito citado explicitamente do método de ligação simples.</li>
<li>□ O problema desapareceria completamente ao usar <span class="math inline">\(d_{\mathrm{mreach}}\)</span> em vez da distância bruta, porque a alcançabilidade mútua nunca permite encadeamento em nenhuma circunstância.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="hdbscan" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> HDBSCAN</h1>
<p>O nome já entrega a receita: <strong>H</strong>ierarchical <strong>DBSCAN</strong> — a ideia do Bloco 4 (núcleo, alcançabilidade mútua, grafo por limiar) rodando por <strong>toda</strong> a hierarquia do Bloco 5 de uma vez, em vez de um único <span class="math inline">\(\varepsilon\)</span>. Mas o Bloco 5 deixou dois problemas em aberto: (i) um único <span class="math inline">\(k\)</span> (ou <span class="math inline">\(\lambda\)</span>) fixo não serve para um dataset com clusters de densidades muito diferentes entre si — um <span class="math inline">\(\lambda\)</span> que revela um cluster raro e denso pode já ter apagado outro, mais espalhado; (ii) encadeamento pode ligar, por um fio fino de pontos, dois grupos que “deveriam” ser distintos. O HDBSCAN ataca os dois de uma vez, com uma ideia que não está em nenhum dos livros-texto desta disciplina (Campello, Moulavi &amp; Sander, 2013) — <strong>persistência</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Ponte conceitual
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pense na hierarquia inteira (a MST cortada em toda altura possível, não só um <span class="math inline">\(k\)</span>) como um filme: em cada quadro (cada valor de <span class="math inline">\(d_{\mathrm{mreach}}\)</span> de corte), alguns clusters existem, outros não. Um cluster que aparece por muitos quadros seguidos, sobrevivendo como componente distinta por uma longa faixa de cortes, é mais “real” do que um que aparece e desaparece rapidamente.</p>
</div>
</div>
<p><strong>Vendo o filme nos 7 pontos do Bloco 5.</strong> A figura abaixo é o mesmo dendrograma de ligação simples dos 7 pontos usado ali para verificar a conexão com a MST, agora cortado em três alturas diferentes — três “quadros” do filme:</p>
<div id="5e4768ee" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-14-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Lendo de baixo para cima: no quadro 1 (corte raso, <span class="math inline">\(\lambda\)</span> alto), nenhuma fusão ainda aconteceu — 7 clusters, um por ponto. No quadro 2 (<span class="math inline">\(\lambda\)</span> médio), os pontos de cada grupo visual já se fundiram entre si (grupo A <span class="math inline">\(=\{0,1,2\}\)</span>, grupo B <span class="math inline">\(=\{3,4,5\}\)</span>), mas A e B ainda não se tocaram, e o ponto isolado <span class="math inline">\(6\)</span> segue sozinho — 3 clusters. No quadro 3 (<span class="math inline">\(\lambda\)</span> baixo, corte fundo), A e B já se fundiram num só cluster; só o ponto isolado resiste separado — 2 clusters. O cluster A (e o B) sobrevive como componente distinta do quadro 1 ao quadro 3 inteiro — uma faixa longa —, exatamente o tipo de “sobrevivência prolongada” que os Passos 1-3 a seguir chamam de alta persistência.</p>
<p><strong>Passo 1 — árvore condensada.</strong> Construa a hierarquia completa (o dendrograma de ligação simples equivalente à MST, Bloco 5) e <strong>condense-a</strong>: sempre que um ramo se divide em dois, mas um dos dois lados tem menos que <code>min_cluster_size</code> pontos, trate esse lado como “pontos que se perderam do cluster pai” (não como um novo cluster) em vez de um novo ramo — só ramos com pelo menos <code>min_cluster_size</code> pontos contam como clusters candidatos. Isso já elimina boa parte do encadeamento do Bloco 5: uma cadeia fina de pontos raramente atinge o tamanho mínimo para ser um ramo próprio.</p>
<p><strong>Passo 2 — persistência por excesso de massa.</strong> Para cada ramo (cluster candidato) da árvore condensada, meça por quanto tempo ele “sobrevive” como componente distinta ao longo da faixa de valores de <span class="math inline">\(\lambda\)</span> (equivalentemente, de <span class="math inline">\(1/d_{\mathrm{mreach}}\)</span>) — a soma, para cada ponto do ramo, do intervalo de <span class="math inline">\(\lambda\)</span> em que aquele ponto pertenceu a esse cluster específico antes de ser absorvido por um cluster-pai ou virar ruído. Essa soma é a <strong>persistência</strong> (excesso de massa) do cluster. Clusters de alta persistência sobreviveram como blocos coerentes por uma faixa longa de limiares — evidência de estrutura real, não um artefato de onde exatamente <span class="math inline">\(\lambda\)</span> foi cortado.</p>
<p><strong>Os Passos 1 e 2, num desenho.</strong> A figura a seguir é <strong>esquemática</strong> (números ilustrativos, não computados de um dataset real — o <code>scikit-learn</code> não expõe a árvore condensada, só o resultado final; ver nota mais abaixo) para mostrar a forma que a árvore condensada assume:</p>
<div id="bf1e7ac8" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-15-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Lendo de baixo para cima: a <strong>raiz</strong> (cinza) começa com todos os <span class="math inline">\(20\)</span> pontos em <span class="math inline">\(\lambda=0\)</span> e vai afinando — cada linha fina que sai de lado é um ponto (ou um grupinho pequeno demais para virar ramo próprio, Passo 1) que “vazou” e virou ruído a partir daquele <span class="math inline">\(\lambda\)</span>. Em <span class="math inline">\(\lambda=2{,}0\)</span> a raiz genuinamente <strong>se divide</strong> em dois — ambos os lados, <span class="math inline">\(6\)</span> e <span class="math inline">\(5\)</span> pontos, já batem <code>min_cluster_size</code>, então os dois viram ramos de verdade (não “vazamento”): o ramo A (azul) e o ramo B (laranja) — esse é o momento em que a raiz vira <strong>cluster-pai</strong> dos dois <strong>ramos-filhos</strong>. Dali em diante, A sobrevive por uma faixa de <span class="math inline">\(\lambda\)</span> bem mais longa (<span class="math inline">\(2{,}0\)</span> a <span class="math inline">\(5{,}0\)</span>), perdendo pontos aos poucos, enquanto B se esvazia quase todo de uma vez, logo em <span class="math inline">\(\lambda=2{,}3\)</span>.</p>
<p><strong>A fórmula por trás da área.</strong> Persistência de um ramo <span class="math inline">\(C\)</span>, nascido em <span class="math inline">\(\lambda_{\text{nasc}}(C)\)</span>: para cada ponto <span class="math inline">\(p\)</span> que já pertenceu a <span class="math inline">\(C\)</span>, some <span class="math inline">\(\lambda_p - \lambda_{\text{nasc}}(C)\)</span>, onde <span class="math inline">\(\lambda_p\)</span> é o <span class="math inline">\(\lambda\)</span> em que <span class="math inline">\(p\)</span> <strong>deixou</strong> <span class="math inline">\(C\)</span> especificamente (virou ruído, ou foi para um ramo-filho quando <span class="math inline">\(C\)</span> se dividiu) —</p>
<p><span class="math display">\[\text{persistência}(C) = \sum_{p\,\in\,C} \bigl(\lambda_p - \lambda_{\text{nasc}}(C)\bigr).\]</span></p>
<p>Essa soma é exatamente a área da barra: cada ponto contribui um “retângulo” de altura igual ao tempo (em <span class="math inline">\(\lambda\)</span>) que ficou dentro do ramo antes de sair.</p>
<p><strong>Calculando para o ramo A</strong> (nasce em <span class="math inline">\(\lambda=2{,}0\)</span>): <span class="math inline">\(2\)</span> pontos vazam em <span class="math inline">\(\lambda=3{,}0\)</span>, cada um contribuindo <span class="math inline">\(3{,}0-2{,}0=1{,}0\)</span> (soma parcial <span class="math inline">\(2\times1{,}0=2{,}0\)</span>); mais <span class="math inline">\(2\)</span> vazam em <span class="math inline">\(\lambda=4{,}2\)</span>, cada um contribuindo <span class="math inline">\(2{,}2\)</span> (soma parcial <span class="math inline">\(4{,}4\)</span>); os últimos <span class="math inline">\(2\)</span> vazam em <span class="math inline">\(\lambda=5{,}0\)</span> (fim do ramo), cada um contribuindo <span class="math inline">\(3{,}0\)</span> (soma parcial <span class="math inline">\(6{,}0\)</span>): <span class="math inline">\(\text{persistência(A)}=2{,}0+4{,}4+6{,}0=12{,}4\)</span>.</p>
<p><strong>Ramo B</strong> (nasce em <span class="math inline">\(\lambda=2{,}0\)</span>, todos os <span class="math inline">\(5\)</span> pontos vazam juntos em <span class="math inline">\(\lambda=2{,}3\)</span>): <span class="math inline">\(\text{persistência(B)}=5\times(2{,}3-2{,}0)=5\times
0{,}3=1{,}5\)</span>.</p>
<p>Quase <span class="math inline">\(10\times\)</span> menor — é por isso que o Passo 3 escolheria A como cluster final e descartaria B: a diferença de persistência não é sutil, é a diferença entre “sobreviveu como bloco coerente por uma faixa longa” e “quase não sobreviveu”.</p>
<p><strong>Passo 3 — extração.</strong> Percorrendo a árvore condensada de baixo para cima, escolha, em cada ramificação, o cluster de maior persistência total entre “manter o cluster-pai inteiro” ou “dividir nos dois filhos” — o algoritmo original (Campello, Moulavi &amp; Sander, 2013, descrito também na documentação do scikit-learn, fonte não-livro, sinalizada como tal) resolve essa escolha por programação dinâmica, maximizando a persistência total da partição final. O resultado: uma partição em clusters que <strong>não</strong> precisa vir de um único corte horizontal em <span class="math inline">\(\lambda\)</span> — clusters diferentes podem ser extraídos de alturas diferentes da árvore, cada um no seu próprio “melhor” <span class="math inline">\(\lambda\)</span>.</p>
<div class="fig-resize" style="width: 35%; margin: 0 auto;">
<img src="index_files/mediabag/ef99003b15fa3979af66b4400223aa0c96219908.svg" class="img-fluid">
</div>
<p>O pipeline resume os três passos: da MST (já construída no Bloco 5) para a hierarquia completa (o dendrograma equivalente), dessa para a árvore condensada (Passo 1) e, por fim, a extração por persistência (Passos 2-3). Cada seta é um passo computável, sem nenhum <span class="math inline">\(\lambda\)</span> escolhido à mão — só o parâmetro de escala <code>min_cluster_size</code> (e, tipicamente, <code>min_samples</code>, o análogo de <span class="math inline">\(K\)</span> do <em>core distance</em>).</p>
<section id="aplicando-ao-breast-cancer-wisconsin-sem-rótulos" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="aplicando-ao-breast-cancer-wisconsin-sem-rótulos"><span class="header-section-number">6.1</span> Aplicando ao Breast Cancer Wisconsin, Sem Rótulos</h2>
<p>Hora de aplicar tudo isso ao problema-fio real, ainda sem usar o diagnóstico. Usando os dois atributos reais de visualização já apresentados (<code>radius_worst</code>, padronizado, e <code>concave points_worst</code>, padronizado) e <code>min_cluster_size=15</code>, o HDBSCAN (via <code>sklearn.cluster.HDBSCAN</code>, confirmado disponível na versão 1.8.0 do scikit-learn instalada no kernel desta disciplina — não o pacote <code>hdbscan</code> externo, que não está instalado) encontra a seguinte partição:</p>
<div id="e6dea433" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hdb_bc <span class="op">=</span> HDBSCAN(min_cluster_size<span class="op">=</span><span class="dv">15</span>).fit(X_2d)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>labels_bc <span class="op">=</span> hdb_bc.labels_</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>uniq, counts <span class="op">=</span> np.unique(labels_bc, return_counts<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters encontrados (rótulo: nº de pacientes):"</span>, <span class="bu">dict</span>(<span class="bu">zip</span>(uniq, counts)))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Fração marcada como ruído (-1): </span><span class="sc">{</span>(labels_bc <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>)<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Clusters encontrados (rótulo: nº de pacientes): {np.int64(-1): np.int64(168), np.int64(0): np.int64(54), np.int64(1): np.int64(347)}
Fração marcada como ruído (-1): 0.295</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<div id="295eadc1" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-19-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Só agora, olhando o painel direito, o diagnóstico entra na conversa</strong> — nenhum passo anterior usou a coluna <code>diagnosis</code>. A correspondência:</p>
<div id="19e91716" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.crosstab(labels_bc, diagnosis, margins<span class="op">=</span><span class="va">True</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>col_0    B    M  All
row_0               
-1      42  126  168
0        0   54   54
1      315   32  347
All    357  212  569</code></pre>
</div>
</div>
<p>O HDBSCAN encontrou dois clusters e marcou <span class="math inline">\(168\)</span> dos <span class="math inline">\(569\)</span> pacientes (<span class="math inline">\(\approx 29{,}5\%\)</span>) como ruído. O <strong>Cluster 0</strong> (<span class="math inline">\(54\)</span> pacientes) é <strong>puro</strong>: os <span class="math inline">\(54\)</span> são malignos, zero benignos — uma “montanha” densa e homogênea de tumores malignos, exatamente o tipo de estrutura que a definição do Bloco 3 promete encontrar sem nunca ter visto o rótulo. O <strong>Cluster 1</strong> (<span class="math inline">\(347\)</span> pacientes) é majoritariamente benigno (<span class="math inline">\(315\)</span> benignos, <span class="math inline">\(32\)</span> malignos — <span class="math inline">\(\approx 90{,}8\%\)</span> de pureza benigna), mas com contaminação real. Dos <span class="math inline">\(212\)</span> pacientes malignos no total, a maioria (<span class="math inline">\(126\)</span>, <span class="math inline">\(\approx 59{,}4\%\)</span>) cai no ruído — não em nenhum dos dois clusters — o que é, honestamente, o resultado esperado: tumores malignos variam muito mais em apresentação do que tumores benignos (a doença tem múltiplos subtipos e estágios), então só uma fração forma uma “montanha” densa o bastante para sobreviver como cluster de alta persistência nesses dois atributos; boa parte fica dispersa no “vale” entre o núcleo maligno denso e a grande massa benigna.</p>
<p>Nenhum dos dois clusters é <span class="math inline">\(100\%\)</span> puro nos dois sentidos ao mesmo tempo, e boa parte dos malignos cai em ruído: o HDBSCAN não é um classificador, e não teve acesso ao rótulo. O fato de encontrar <em>qualquer</em> estrutura — um cluster inteiramente maligno, outro majoritariamente benigno — que se alinha tão bem ao diagnóstico real, começando de dois atributos e nenhuma supervisão, é o resultado central deste bloco.</p>
</section>
<section id="pergunta-5" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="pergunta-5"><span class="header-section-number">6.2</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <code>min_cluster_size</code> fosse reduzido de 15 para 2 no exemplo do Breast Cancer Wisconsin, o que aconteceria com a fração de pacientes marcados como ruído, e por quê?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que <code>min_cluster_size</code> está, na prática, impedindo de virar cluster.</p>
<ul>
<li>□ Reduzir <code>min_cluster_size</code> para 2 tende a diminuir a fração de ruído, porque ramos muito pequenos da árvore condensada (antes descartados como “perda” do cluster-pai) passam a contar como clusters válidos por si mesmos.</li>
<li>□ <code>min_cluster_size=2</code> reintroduz, na prática, uma versão do problema de encadeamento (<em>chaining</em>) da ligação simples pura — uma cadeia fina de 2-3 pontos já basta para ser aceita como cluster próprio.</li>
<li>□ O valor de <code>min_cluster_size</code> não afeta a fração de ruído — ele só afeta quantos clusters distintos são extraídos, mantendo o total de pontos “ruidosos” constante.</li>
<li>□ Escolher <code>min_cluster_size</code> continua sendo, mesmo no HDBSCAN, uma decisão de escala imposta pelo usuário — a persistência decide <em>quais</em> ramos sobrevivem, mas não decide, por si só, o tamanho mínimo que conta como ramo.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="síntese-vantagens-e-limitações-do-hdbscan" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Síntese: Vantagens e Limitações do HDBSCAN</h1>
<p>Recapitulando de ponta a ponta: (1) <span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span>, o mesmo <span class="math inline">\(d_K(\mathbf{x})\)</span> da Aula 2, mede densidade local sem forma paramétrica; (2) <span class="math inline">\(d_{\mathrm{mreach}}\)</span> transforma isso numa distância de grafo que “acalma” pontos isolados; (3) a MST desse grafo comprime toda a hierarquia de clustering por ligação simples numa única árvore; (4) condensar essa árvore e medir persistência por excesso de massa extrai os clusters mais estáveis, em alturas possivelmente diferentes, sem exigir um único corte global.</p>
<p><strong>As vantagens</strong>, em relação a uma partição por protótipos fixos (Bloco 2): nenhuma suposição de convexidade (as duas luas, os dois anéis, resolvidos de ponta a ponta); nenhuma escolha obrigatória do <strong>número de clusters</strong> (não confundir com o <span class="math inline">\(K\)</span> do <em>core distance</em>, <code>min_samples</code> — esse continua sendo escolhido, controla escala de densidade, não quantidade de clusters); pontos genuinamente atípicos podem ser marcados como ruído em vez de forçados a pertencer a algum cluster.</p>
<p><strong>As limitações.</strong> Duas, nenhuma anunciada como “gratuita” antes: primeiro, <code>min_cluster_size</code> (e, em geral, <code>min_samples</code>, que desempenha o papel de <span class="math inline">\(K\)</span> no <em>core distance</em>) ainda é uma escolha de escala — o Bloco 6 mostrou, na Pergunta, que reduzir esse parâmetro reintroduz uma versão do encadeamento. Segundo — e este é o fio que conecta diretamente de volta à Aula 2 — o HDBSCAN herda a mesma maldição da dimensionalidade que <span class="math inline">\(d_K(\mathbf{x})\)</span> já sofria como estimador de densidade, porque <span class="math inline">\(\mathrm{core}_K\)</span> é literalmente o mesmo número. Um teste direto, nos <span class="math inline">\(30\)</span> atributos originais (todos padronizados) do Breast Cancer Wisconsin, torna isso concreto:</p>
<div id="c4e6b79c" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mcs <span class="kw">in</span> [<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">30</span>]:</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    hdb_full <span class="op">=</span> HDBSCAN(min_cluster_size<span class="op">=</span>mcs).fit(X_std)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    frac_ruido <span class="op">=</span> (hdb_full.labels_ <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>).mean()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    n_clusters <span class="op">=</span> <span class="bu">len</span>(<span class="bu">set</span>(hdb_full.labels_) <span class="op">-</span> {<span class="op">-</span><span class="dv">1</span>})</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"min_cluster_size=</span><span class="sc">{</span>mcs<span class="sc">:3d}</span><span class="ss">  →  </span><span class="sc">{</span>n_clusters<span class="sc">}</span><span class="ss"> cluster(s), "</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>frac_ruido<span class="sc">:.1%}</span><span class="ss"> dos pacientes como ruído"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>min_cluster_size=  5  →  2 cluster(s), 59.2% dos pacientes como ruído
min_cluster_size= 10  →  0 cluster(s), 100.0% dos pacientes como ruído
min_cluster_size= 15  →  0 cluster(s), 100.0% dos pacientes como ruído
min_cluster_size= 20  →  0 cluster(s), 100.0% dos pacientes como ruído
min_cluster_size= 30  →  0 cluster(s), 100.0% dos pacientes como ruído</code></pre>
</div>
</div>
<p>Nos <span class="math inline">\(30\)</span> atributos originais, padronizados, sem nenhuma redução de dimensionalidade: com <code>min_cluster_size=5</code> (já um valor agressivo, pequeno), <span class="math inline">\(\approx 59{,}2\%\)</span> dos pacientes já viram ruído; a partir de <code>min_cluster_size=10</code>, <strong><span class="math inline">\(100\%\)</span></strong> dos <span class="math inline">\(569\)</span> pacientes são marcados como ruído — nenhum cluster sobrevive. Comparado aos dois atributos do Bloco 6, onde <span class="math inline">\(70{,}5\%\)</span> dos pacientes ficaram em algum cluster, essa é uma queda drástica de estrutura encontrada, só por aumentar de <span class="math inline">\(2\)</span> para <span class="math inline">\(30\)</span> dimensões (mesmos pacientes, mesmos dados). O mecanismo é exatamente o da Aula 2: em alta dimensão, distâncias perdem poder de discriminação, <span class="math inline">\(d_K(\mathbf{x})\)</span> deixa de refletir bem “densidade local” no sentido intuitivo, <span class="math inline">\(d_{\mathrm{mreach}}\)</span> (que depende de <span class="math inline">\(d_K\)</span> e de <span class="math inline">\(d\)</span> bruta) herda o problema, e a árvore condensada não encontra ramo nenhum estável o bastante para sobreviver como cluster — tudo vira “ruído” porque, em alta dimensão, quase tudo parece igualmente distante de quase tudo.</p>
<section id="pergunta-6" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="pergunta-6"><span class="header-section-number">7.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um colega sugere “resolver” a queda de estrutura em 30 dimensões aumentando <code>min_cluster_size</code> até encontrar pelo menos um cluster de novo. Isso resolveria o problema de fundo?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se <code>min_cluster_size</code> grande está atacando a causa (distâncias perdendo poder discriminativo) ou só mudando o limiar de quantos pontos “contam”.</p>
<ul>
<li>□ Aumentar <code>min_cluster_size</code> pode, sim, eventualmente produzir algum cluster de novo — mas isso resolve o sintoma (nenhum cluster aparecia) sem resolver a causa (as distâncias em 30D perderam poder discriminativo).</li>
<li>□ Se um cluster aparecer com <code>min_cluster_size</code> bem alto em 30D, ele é necessariamente tão confiável estatisticamente quanto o cluster puro de <span class="math inline">\(54\)</span> pacientes encontrado com <span class="math inline">\(2\)</span> atributos no Bloco 6.</li>
<li>□ A solução mais direta para a maldição, sugerida já na Aula 2 e reaproveitável aqui, é reduzir a dimensionalidade (ex.: escolher um subconjunto de atributos informativos, ou usar componentes principais) antes de rodar HDBSCAN, não só ajustar <code>min_cluster_size</code>.</li>
<li>□ Esse problema é exclusivo de métodos baseados em densidade como o HDBSCAN — qualquer método de clustering baseado em distância entre pontos escaparia dessa maldição.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="fechamento-e-ponte-para-a-aula-4" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Fechamento e Ponte para a Aula 4</h1>
<p>Retomando as quatro perguntas da Abertura, uma frase cada:</p>
<ol type="1">
<li><strong>O que deveria significar “cluster”?</strong> Uma componente conexa de uma região de alta densidade — não uma bola em torno de um centróide.</li>
<li><strong>Como construir isso sem escolher o número de clusters a priori?</strong> Via <span class="math inline">\(d_{\mathrm{mreach}}\)</span> e a MST, sem nenhum parâmetro de forma — só uma escala local de densidade, o <span class="math inline">\(K\)</span> do <em>core distance</em> (<code>min_samples</code>), que é uma coisa diferente de “número de clusters”: controla o quão local é a estimativa de densidade, não quantos clusters existem.</li>
<li><strong>Que estrutura de grafo captura toda a hierarquia de uma vez?</strong> A MST — cortar suas <span class="math inline">\(k-1\)</span> arestas mais pesadas reproduz ligação simples para qualquer <span class="math inline">\(k\)</span>, verificado no exemplo do Bloco 5.</li>
<li><strong>Como decidir quais clusters são reais?</strong> Persistência por excesso de massa na árvore condensada, não um único <span class="math inline">\(\lambda\)</span> escolhido à mão.</li>
</ol>
<p><strong>O que fica em aberto.</strong> O HDBSCAN entrega uma partição <strong>rígida</strong>: cada paciente pertence a exatamente um cluster, ou é ruído — uma decisão binária, sem meio-termo. Isso é honesto quando os clusters são genuinamente bem separados (como as duas luas), mas força uma escolha artificial quando dois clusters genuinamente se sobrepõem — um paciente na fronteira entre o núcleo maligno denso e a massa benigna do Bloco 6 não é “um pouco maligno, um pouco benigno”: ele é forçado a ruído ou a um dos dois lados.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Ponte para a Aula 4
</div>
</div>
<div class="callout-body-container callout-body">
<p>A Aula 4 introduz <strong>Modelos de Mistura Gaussiana</strong> (<em>Gaussian Mixture Models</em>) e o algoritmo <strong>EM</strong> (<em>Expectation-Maximization</em>) — a mesma pergunta de agrupar pontos, mas relaxando a atribuição rígida para uma atribuição <strong>probabilística</strong>: cada paciente recebe uma probabilidade de pertencer a cada cluster, não um rótulo único. Útil exatamente onde o HDBSCAN força uma escolha: fronteiras genuinamente ambíguas entre populações que se sobrepõem.</p>
</div>
</div>
<p>O ESL (p.&nbsp;507) já havia citado essa rota como um dos três paradigmas — “modelagem por mistura” — ao lado do combinatório (protótipos fixos, Bloco 2) e do “mode seeking” (esta aula inteira). A Aula 4 fecha o trio.</p>
<p><a href="../../../teaching/unsupervised-learning/aula03/exercicios.html" class="see-all exercicios-link" aria-label="Ver exercícios" title="Ver exercícios">Exercícios</a> <a href="../../../teaching/unsupervised-learning/aula03/soluções.html" class="see-all solucoes-link" aria-label="Ver soluções" title="Ver soluções">Soluções</a></p>
<section id="pergunta-7" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="pergunta-7"><span class="header-section-number">8.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um hospital precisa decidir se atribuição rígida (HDBSCAN) ou probabilística (GMM/EM, Aula 4) se ajusta melhor a uma triagem entre dois subtipos de tumor cujos biomarcadores parecem se sobrepor. O que deveria pesar mais nessa escolha?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se a “ambiguidade” observada nos dados é evidência de um vale de densidade genuíno entre os subtipos, ou de uma sobreposição real e contínua entre eles.</p>
<ul>
<li>□ Se os dois subtipos realmente se sobrepõem numa faixa contínua de biomarcadores, sem um vale de densidade genuíno entre eles, uma atribuição probabilística tende a refletir melhor essa ambiguidade do que forçar cada paciente a um rótulo único.</li>
<li>□ Como o HDBSCAN já produz uma força de pertencimento por ponto dentro do cluster ao qual foi atribuído, ele já é, na prática, equivalente a uma atribuição probabilística completa como a do GMM/EM, que distribui probabilidade entre <em>todos</em> os clusters.</li>
<li>□ No limite em que os dois subtipos verdadeiros são separados por um vale de densidade exatamente zero, a atribuição probabilística do GMM/EM converge para probabilidades próximas de <span class="math inline">\(0\)</span> ou <span class="math inline">\(1\)</span> — coincidindo, na prática, com a atribuição rígida do HDBSCAN.</li>
<li>□ Se a escolha entre partição rígida e probabilística fosse só uma questão de conveniência computacional, sem nenhuma relação com a estrutura real dos dados, então HDBSCAN e GMM deveriam sempre produzir partições idênticas quando aplicados ao mesmo dataset.</li>
</ul>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>