<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Marcos Medeiros Raimundo">

<title>Aula 5: Decomposição em Valores Singulares (SVD) e Aproximações de Baixo Posto – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-f6f65eecdb8abf3e35b2d2c28dbef9f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#revisão-e-introdução" id="toc-revisão-e-introdução" class="nav-link active" data-scroll-target="#revisão-e-introdução"><span class="header-section-number">1</span> Revisão e Introdução</a>
  <ul class="collapse">
  <li><a href="#revisão-rápida-onde-a-aula-4-parou" id="toc-revisão-rápida-onde-a-aula-4-parou" class="nav-link" data-scroll-target="#revisão-rápida-onde-a-aula-4-parou"><span class="header-section-number">1.1</span> Revisão Rápida: Onde a Aula 4 Parou</a></li>
  <li><a href="#organizador-prévio-de-xtx-simétrica-para-x-retangular" id="toc-organizador-prévio-de-xtx-simétrica-para-x-retangular" class="nav-link" data-scroll-target="#organizador-prévio-de-xtx-simétrica-para-x-retangular"><span class="header-section-number">1.2</span> Organizador Prévio: De <span class="math inline">\(X^TX\)</span> Simétrica Para <span class="math inline">\(X\)</span> Retangular</a></li>
  <li><a href="#roteiro-da-aula" id="toc-roteiro-da-aula" class="nav-link" data-scroll-target="#roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</a></li>
  <li><a href="#problema-motivador" id="toc-problema-motivador" class="nav-link" data-scroll-target="#problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</a></li>
  </ul></li>
  <li><a href="#intuição-geométrica-da-svd" id="toc-intuição-geométrica-da-svd" class="nav-link" data-scroll-target="#intuição-geométrica-da-svd"><span class="header-section-number">2</span> Intuição Geométrica da SVD</a>
  <ul class="collapse">
  <li><a href="#uma-matriz-qualquer-agindo-sobre-um-círculo" id="toc-uma-matriz-qualquer-agindo-sobre-um-círculo" class="nav-link" data-scroll-target="#uma-matriz-qualquer-agindo-sobre-um-círculo"><span class="header-section-number">2.1</span> Uma Matriz Qualquer Agindo sobre um Círculo</a></li>
  </ul></li>
  <li><a href="#construção-formal-da-svd-a-partir-do-teorema-espectral" id="toc-construção-formal-da-svd-a-partir-do-teorema-espectral" class="nav-link" data-scroll-target="#construção-formal-da-svd-a-partir-do-teorema-espectral"><span class="header-section-number">3</span> Construção Formal da SVD a Partir do Teorema Espectral</a>
  <ul class="collapse">
  <li><a href="#premissas-o-que-já-temos-disponível" id="toc-premissas-o-que-já-temos-disponível" class="nav-link" data-scroll-target="#premissas-o-que-já-temos-disponível"><span class="header-section-number">3.1</span> Premissas: O Que Já Temos Disponível</a></li>
  <li><a href="#passo-1-vetores-singulares-à-direita-a-partir-de-ata" id="toc-passo-1-vetores-singulares-à-direita-a-partir-de-ata" class="nav-link" data-scroll-target="#passo-1-vetores-singulares-à-direita-a-partir-de-ata"><span class="header-section-number">3.2</span> Passo 1: Vetores Singulares à Direita, a Partir de <span class="math inline">\(A^TA\)</span></a></li>
  <li><a href="#passo-2-vetores-singulares-à-esquerda-como-imagem-normalizada" id="toc-passo-2-vetores-singulares-à-esquerda-como-imagem-normalizada" class="nav-link" data-scroll-target="#passo-2-vetores-singulares-à-esquerda-como-imagem-normalizada"><span class="header-section-number">3.3</span> Passo 2: Vetores Singulares à Esquerda, Como Imagem Normalizada</a></li>
  <li><a href="#passo-3-a-equação-de-valor-singular-e-a-montagem-final" id="toc-passo-3-a-equação-de-valor-singular-e-a-montagem-final" class="nav-link" data-scroll-target="#passo-3-a-equação-de-valor-singular-e-a-montagem-final"><span class="header-section-number">3.4</span> Passo 3: A Equação de Valor Singular e a Montagem Final</a></li>
  <li><a href="#exemplo-resolvido-à-mão" id="toc-exemplo-resolvido-à-mão" class="nav-link" data-scroll-target="#exemplo-resolvido-à-mão"><span class="header-section-number">3.5</span> Exemplo Resolvido à Mão</a></li>
  </ul></li>
  <li><a href="#a-svd-do-dataset-fio-x-do-california-housing" id="toc-a-svd-do-dataset-fio-x-do-california-housing" class="nav-link" data-scroll-target="#a-svd-do-dataset-fio-x-do-california-housing"><span class="header-section-number">4</span> A SVD do Dataset-Fio: <span class="math inline">\(X\)</span> do <em>California Housing</em></a>
  <ul class="collapse">
  <li><a href="#voltando-ao-problema-original" id="toc-voltando-ao-problema-original" class="nav-link" data-scroll-target="#voltando-ao-problema-original"><span class="header-section-number">4.1</span> Voltando ao Problema Original</a></li>
  </ul></li>
  <li><a href="#aproximação-de-baixo-posto-e-o-teorema-de-eckart-young-mirsky" id="toc-aproximação-de-baixo-posto-e-o-teorema-de-eckart-young-mirsky" class="nav-link" data-scroll-target="#aproximação-de-baixo-posto-e-o-teorema-de-eckart-young-mirsky"><span class="header-section-number">5</span> Aproximação de Baixo Posto e o Teorema de Eckart-Young-Mirsky</a>
  <ul class="collapse">
  <li><a href="#decompondo-a-em-pedaços-de-posto-1" id="toc-decompondo-a-em-pedaços-de-posto-1" class="nav-link" data-scroll-target="#decompondo-a-em-pedaços-de-posto-1"><span class="header-section-number">5.1</span> Decompondo <span class="math inline">\(A\)</span> em Pedaços de Posto 1</a></li>
  <li><a href="#medindo-o-erro-da-aproximação-norma-espectral" id="toc-medindo-o-erro-da-aproximação-norma-espectral" class="nav-link" data-scroll-target="#medindo-o-erro-da-aproximação-norma-espectral"><span class="header-section-number">5.2</span> Medindo o Erro da Aproximação: Norma Espectral</a></li>
  <li><a href="#o-teorema-de-eckart-young-mirsky" id="toc-o-teorema-de-eckart-young-mirsky" class="nav-link" data-scroll-target="#o-teorema-de-eckart-young-mirsky"><span class="header-section-number">5.3</span> O Teorema de Eckart-Young-Mirsky</a>
  <ul class="collapse">
  <li><a href="#parte-i-o-erro-de-hatak-é-exatamente-sigma_k1" id="toc-parte-i-o-erro-de-hatak-é-exatamente-sigma_k1" class="nav-link" data-scroll-target="#parte-i-o-erro-de-hatak-é-exatamente-sigma_k1"><span class="header-section-number">5.3.1</span> Parte (i): o erro de <span class="math inline">\(\hat{A}^{(k)}\)</span> é exatamente <span class="math inline">\(\sigma_{k+1}\)</span></a></li>
  <li><a href="#parte-ii-nenhuma-matriz-de-posto-k-faz-melhor" id="toc-parte-ii-nenhuma-matriz-de-posto-k-faz-melhor" class="nav-link" data-scroll-target="#parte-ii-nenhuma-matriz-de-posto-k-faz-melhor"><span class="header-section-number">5.3.2</span> Parte (ii): nenhuma matriz de posto <span class="math inline">\(k\)</span> faz melhor</a></li>
  </ul></li>
  <li><a href="#aplicando-a-x-quanto-se-perde-ao-truncar" id="toc-aplicando-a-x-quanto-se-perde-ao-truncar" class="nav-link" data-scroll-target="#aplicando-a-x-quanto-se-perde-ao-truncar"><span class="header-section-number">5.4</span> Aplicando a <span class="math inline">\(X\)</span>: Quanto Se Perde ao Truncar</a></li>
  <li><a href="#retomando-o-problema-motivador-filtragem-colaborativa" id="toc-retomando-o-problema-motivador-filtragem-colaborativa" class="nav-link" data-scroll-target="#retomando-o-problema-motivador-filtragem-colaborativa"><span class="header-section-number">5.5</span> Retomando o Problema Motivador: Filtragem Colaborativa</a></li>
  </ul></li>
  <li><a href="#decomposição-polar" id="toc-decomposição-polar" class="nav-link" data-scroll-target="#decomposição-polar"><span class="header-section-number">6</span> Decomposição Polar</a>
  <ul class="collapse">
  <li><a href="#rearranjando-os-três-fatores-da-svd" id="toc-rearranjando-os-três-fatores-da-svd" class="nav-link" data-scroll-target="#rearranjando-os-três-fatores-da-svd"><span class="header-section-number">6.1</span> Rearranjando os Três Fatores da SVD</a></li>
  <li><a href="#a-generalização-do-módulo-e-da-fase" id="toc-a-generalização-do-módulo-e-da-fase" class="nav-link" data-scroll-target="#a-generalização-do-módulo-e-da-fase"><span class="header-section-number">6.2</span> A Generalização do Módulo e da Fase</a></li>
  </ul></li>
  <li><a href="#fechamento-e-ponte-para-a-aula-6" id="toc-fechamento-e-ponte-para-a-aula-6" class="nav-link" data-scroll-target="#fechamento-e-ponte-para-a-aula-6"><span class="header-section-number">7</span> Fechamento e Ponte para a Aula 6</a>
  <ul class="collapse">
  <li><a href="#retomando-as-perguntas-de-abertura" id="toc-retomando-as-perguntas-de-abertura" class="nav-link" data-scroll-target="#retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</a></li>
  <li><a href="#o-que-fica-em-aberto" id="toc-o-que-fica-em-aberto" class="nav-link" data-scroll-target="#o-que-fica-em-aberto">O Que Fica em Aberto</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula 5: Decomposição em Valores Singulares (SVD) e Aproximações de Baixo Posto</h1>
<p class="subtitle lead">Álgebra Linear e Otimização para Aprendizado de Máquina</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Marcos Medeiros Raimundo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">12 de setembro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/optimization-linear-algebra/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="revisão-e-introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Revisão e Introdução</h1>
<hr>
<section id="revisão-rápida-onde-a-aula-4-parou" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="revisão-rápida-onde-a-aula-4-parou"><span class="header-section-number">1.1</span> Revisão Rápida: Onde a Aula 4 Parou</h2>
<p>A Aula 4 respondeu, para matrizes <strong>quadradas simétricas</strong>, tudo que precisávamos saber sobre autovalores e autovetores — em três resultados que esta aula vai reciclar diretamente, sem alterar uma vírgula. Vale relembrar cada um com algum detalhe (não só o rótulo), porque a construção da SVD (adiante) não faz mais do que aplicá-los de novo, num lugar diferente.</p>
<p><strong>Primeiro: <span class="math inline">\(A^TA\)</span> é sempre simétrica e semidefinida positiva, para qualquer <span class="math inline">\(A\)</span>.</strong> Isso vale mesmo quando <span class="math inline">\(A\)</span> não é quadrada — na verdade, é justamente para matrizes retangulares que esse resultado importa mais, porque <span class="math inline">\(A\)</span> sozinha não tem autovalores (ver “Organizador Prévio” abaixo), mas <span class="math inline">\(A^TA\)</span> sempre existe e sempre tem a estrutura mais bem-comportada que existe em álgebra linear. Vale relembrar por quê, porque é uma conta de duas linhas, não um fato arbitrário: a simetria sai direto da definição de transposta, <span class="math inline">\((A^TA)^T=A^T(A^T)^T=A^TA\)</span>; a semidefinição positiva sai de reconhecer a forma quadrática associada como uma norma ao quadrado — para qualquer <span class="math inline">\(\mathbf{x}\)</span>, <span class="math inline">\(\mathbf{x}^T(A^TA)\mathbf{x}=(A\mathbf{x})^T(A\mathbf{x})=
\|A\mathbf{x}\|^2\ge 0\)</span>, nunca negativo, porque é literalmente o comprimento (ao quadrado) de um vetor.</p>
<p><strong>Segundo: o Teorema Espectral Real.</strong> Para <strong>qualquer</strong> matriz simétrica <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> — não só as semidefinidas positivas do primeiro resultado, qualquer simétrica, com autovalores de qualquer sinal —, existem <span class="math inline">\(n\)</span> autovalores reais (nunca complexos, ao contrário do que pode acontecer numa matriz não-simétrica qualquer) e uma base ortonormal <em>completa</em> de autovetores associada a eles, isto é, <span class="math inline">\(A=Q\Lambda Q^T\)</span> com <span class="math inline">\(Q\)</span> ortogonal (colunas os autovetores) e <span class="math inline">\(\Lambda\)</span> diagonal (autovalores). <strong>A simetria é exatamente a hipótese que faz essa fatoração ter termos ortonormais</strong> — vale a pena marcar isso com precisão, porque não é o caso geral: uma matriz quadrada qualquer, não simétrica, ainda pode ser diagonalizável (<span class="math inline">\(A=P\Lambda P^{-1}\)</span>), mas <span class="math inline">\(P\)</span> em geral <strong>não</strong> é ortogonal (suas colunas não são ortogonais entre si, nem unitárias), e os autovalores podem nem ser reais. É só porque <span class="math inline">\(A^TA\)</span> é <strong>sempre simétrica</strong> (primeiro resultado) que a versão forte do teorema — com <span class="math inline">\(Q\)</span> ortogonal, não só <span class="math inline">\(P\)</span> invertível — se aplica a ela sem exceção, garantindo, de saída, que a decomposição do primeiro resultado sempre é possível — nenhum caso patológico escapa.</p>
<p><strong>Terceiro: o sinal e a razão dos autovalores carregam informação geométrica direta, não só algébrica.</strong> O sinal caracteriza definitude — <span class="math inline">\(A\succ 0\iff\lambda_{\min}(A)&gt;0\)</span> (todos os autovalores estritamente positivos), <span class="math inline">\(A\succeq 0\iff\lambda_{\min}(A)\ge 0\)</span> — e a razão entre o maior e o menor autovalor é o número de condição <strong>exato</strong>, <span class="math inline">\(\text{cond}(A)=\lambda_{\max}(A)/\lambda_{\min}(A)\)</span>, não uma estimativa. Isso fechou, sem perturbar nada, o ciclo que a Aula 3 só tinha <em>medido</em> empiricamente (perturbando os dados e observando o efeito no peso estimado): agora sabemos exatamente, em função dos autovalores, de onde vem a sensibilidade do sistema a pequenas perturbações.</p>
<p>Vale relembrar os números concretos, porque esta aula vai reencontrá-los: para os 4 atributos completos do <em>California Housing</em> (<span class="math inline">\(X\in
\mathbb{R}^{16\,640\times 4}\)</span>), os autovalores de <span class="math inline">\(X^TX\)</span> eram <span class="math inline">\([747{,}25;\ 52\,666{,}03;\ 273\,990{,}28;\ 1{,}753\times10^7]\)</span>, com <span class="math inline">\(\text{cond}(X^TX)\approx 23\,460{,}5\)</span>; para o par quase-colinear <code>AveRooms</code>/<code>AveBedrms</code>, <span class="math inline">\(\text{cond}\approx 419{,}8\)</span>; para o par bem-condicionado <code>MedInc</code>/<code>HouseAge</code>, <span class="math inline">\(\text{cond}\approx 169{,}1\)</span>.</p>
</section>
<section id="organizador-prévio-de-xtx-simétrica-para-x-retangular" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="organizador-prévio-de-xtx-simétrica-para-x-retangular"><span class="header-section-number">1.2</span> Organizador Prévio: De <span class="math inline">\(X^TX\)</span> Simétrica Para <span class="math inline">\(X\)</span> Retangular</h2>
<p>Tudo isso foi construído em cima de <span class="math inline">\(X^TX\)</span> — uma matriz <span class="math inline">\(4\times 4\)</span>, quadrada e simétrica por construção. Mas o objeto de interesse original nunca foi <span class="math inline">\(X^TX\)</span>; é o próprio <span class="math inline">\(X\)</span>, a matriz de design <span class="math inline">\(16\,640\times 4\)</span>, retangular. Vale ser preciso aqui, porque é fácil confundir dois problemas diferentes: <strong>autovalor e autovetor não são “difíceis de garantir” para uma matriz retangular — eles simplesmente não estão definidos.</strong> A equação <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> exige que <span class="math inline">\(A\mathbf{x}\)</span> viva no mesmo espaço que <span class="math inline">\(\mathbf{x}\)</span> (para que a igualdade com <span class="math inline">\(\lambda\mathbf{x}\)</span> faça sentido); se <span class="math inline">\(A\in
\mathbb{R}^{m\times n}\)</span> com <span class="math inline">\(m\ne n\)</span>, então <span class="math inline">\(A\mathbf{x}\in\mathbb{R}^m\)</span> enquanto <span class="math inline">\(\mathbf{x}\in\mathbb{R}^n\)</span> — a equação nem sequer tem tipo correto, muito menos solução. O polinômio característico <span class="math inline">\(\det(A-\lambda I)\)</span> tem o mesmo problema: <span class="math inline">\(A-\lambda I\)</span> exige subtrair <span class="math inline">\(A\)</span> de uma matriz identidade multiplicada por escalar, e isso só é definido quando <span class="math inline">\(A\)</span> é quadrada.</p>
<p>A ideia central desta aula: em vez de insistir em decompor <span class="math inline">\(X\)</span> da mesma forma que decompomos <span class="math inline">\(X^TX\)</span>, vamos <strong>reciclar exatamente o que a Aula 4 já provou</strong> — aplicando-o não a <span class="math inline">\(X\)</span>, mas às duas matrizes quadradas simétricas que <span class="math inline">\(X\)</span> produz naturalmente, <span class="math inline">\(X^TX\in\mathbb{R}^{4\times 4}\)</span> e <span class="math inline">\(XX^T\in\mathbb{R}^{16\,640\times 16\,640}\)</span> — e depois costurar os dois resultados de volta em uma decomposição de <span class="math inline">\(X\)</span> propriamente dita. Essa costura tem nome: <strong>Decomposição em Valores Singulares (SVD)</strong>.</p>
</section>
<section id="roteiro-da-aula" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</h2>
<p>A pergunta que fecha o Organizador Prévio — “como reciclar o Teorema Espectral Real, aplicado a <span class="math inline">\(X^TX\)</span> e <span class="math inline">\(XX^T\)</span>, para decompor o próprio <span class="math inline">\(X\)</span> retangular?” — se desdobra em quatro perguntas mais específicas:</p>
<ol type="1">
<li>O que é a <strong>Decomposição em Valores Singulares (SVD)</strong> e por que ela existe para <strong>qualquer</strong> matriz retangular, sem exceção?</li>
<li>Como <strong>construir</strong> a SVD a partir do que já sabemos sobre <span class="math inline">\(X^TX\)</span> e <span class="math inline">\(XX^T\)</span> — isto é, a partir do próprio Teorema Espectral da Aula 4?</li>
<li>Como usar a SVD para <strong>aproximar</strong> uma matriz por outra de posto menor, e por que essa aproximação é a <strong>melhor possível</strong> (Teorema de Eckart-Young-Mirsky)?</li>
<li>O que é a <strong>Decomposição Polar</strong>, e como ela nasce “de graça” a partir dos mesmos três fatores da SVD?</li>
</ol>
</section>
<section id="problema-motivador" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</h2>
<p>Considere um cenário bem diferente do <em>California Housing</em>, mas que vai se revelar regido pela mesma matemática. Três espectadores — Ali, Beatrix e Chandra — avaliam quatro filmes (Guerra nas Estrelas, Blade Runner, Amélie Poulain, Delicatessen) numa escala de 0 (pior) a 5 (melhor). As notas formam uma matriz <span class="math inline">\(A\in\mathbb{R}^{4\times 3}\)</span>, uma linha por filme, uma coluna por espectador (tradução livre de um exemplo do MathML, §4.5.1):</p>
<div id="29b9ab9f" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="245">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Ali</th>
<th data-quarto-table-cell-role="th">Beatrix</th>
<th data-quarto-table-cell-role="th">Chandra</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Guerra nas Estrelas</th>
<td>5.0</td>
<td>4.0</td>
<td>1.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Blade Runner</th>
<td>5.0</td>
<td>5.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Amélie Poulain</th>
<td>0.0</td>
<td>0.0</td>
<td>5.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Delicatessen</th>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Olhando só para esses <span class="math inline">\(12\)</span> números, seria razoável suspeitar de uma estrutura escondida: talvez Ali e Beatrix compartilhem um “perfil de gosto” (ficção científica), e Chandra tenha um perfil bem diferente (cinema de arte francês) — e talvez os próprios filmes se agrupem em “temas” correspondentes. Pense por um instante, sem fazer nenhuma conta ainda: <strong>existe alguma forma de extrair, direto da matriz de notas, esses “perfis” e “temas” escondidos — sem que ninguém tenha rotulado os filmes por gênero de antemão?</strong></p>
<div class="fig-resize" style="width: 78%; margin: 0 auto;">
<img src="index_files/mediabag/fc6fe4c6fff366099037005148ff8d4810c308af.svg" class="img-fluid">
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>De volta a <span class="math inline">\(X^TX\)</span>: o que muda (e o que não muda) para <span class="math inline">\(X\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense com cuidado sobre o que está definido para uma matriz <span class="math inline">\(m\times n\)</span> com <span class="math inline">\(m\ne n\)</span>, e o que continua definido só porque a matriz é quadrada simétrica.</p>
<ul>
<li>□ Se <span class="math inline">\(X\)</span> fosse quadrada mas <strong>não</strong> simétrica, o Teorema Espectral Real garantiria, mesmo assim, autovalores reais para <span class="math inline">\(X\)</span>.</li>
<li>□ Se todos os espectadores dessem exatamente a mesma nota a todos os filmes (a matriz de notas <span class="math inline">\(A\)</span> tivesse posto <span class="math inline">\(1\)</span>), haveria mais de um “perfil” de espectador (mais de um par não-nulo de vetores singulares) associado a essa matriz.</li>
<li>□ Uma camada totalmente conectada de uma rede neural, com matriz de pesos <span class="math inline">\(W\in\mathbb{R}^{m\times n}\)</span> e <span class="math inline">\(m\ne n\)</span> (mais neurônios de saída do que de entrada, por exemplo), não possui autovalores no sentido usual, mas ainda assim admite uma decomposição em valores singulares.</li>
<li>□ Como o Teorema Espectral (Aula 4) garante que <span class="math inline">\(X^TX\)</span> sempre tem autovalores reais, isso implica que o próprio <span class="math inline">\(X\)</span> também possui autovalores reais, só que de importância secundária.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="intuição-geométrica-da-svd" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Intuição Geométrica da SVD</h1>
<hr>
<section id="uma-matriz-qualquer-agindo-sobre-um-círculo" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="uma-matriz-qualquer-agindo-sobre-um-círculo"><span class="header-section-number">2.1</span> Uma Matriz Qualquer Agindo sobre um Círculo</h2>
<p>Antes de qualquer fórmula, uma imagem concreta — desta vez com uma matriz que <strong>não</strong> é simétrica, de propósito, para deixar claro por que o Bloco 2 da Aula 4 não se aplica aqui: <span class="math display">\[
A = \begin{bmatrix} 1{,}4 &amp; 0{,}6 \\ 0{,}3 &amp; 0{,}9 \end{bmatrix} ,
\qquad A \ne A^T .
\]</span> Pense em <span class="math inline">\(A\)</span> como transformação linear agindo sobre o círculo unitário de <span class="math inline">\(\mathbb{R}^2\)</span>. Como qualquer matriz <span class="math inline">\(2\times 2\)</span> com autovalores reais e distintos, <span class="math inline">\(A\)</span> tem duas direções especiais no sentido da Aula 4 — autovetores que só esticam, nunca giram, sob <span class="math inline">\(A\)</span>. Mas, como <span class="math inline">\(A\)</span> não é simétrica, o Teorema Espectral Real <strong>não garante</strong> que essas direções sejam ortogonais entre si — e de fato não são.</p>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<div id="403b51b8" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>No painel esquerdo, as setas cheias (azul e laranja) são os <strong>vetores singulares à direita</strong>, <span class="math inline">\(\mathbf{v}_1\)</span> e <span class="math inline">\(\mathbf{v}_2\)</span> — colunas da matriz <span class="math inline">\(V\)</span> que o Bloco 3 vai construir; as setas tracejadas cinzas são os <strong>autovetores</strong> de <span class="math inline">\(A\)</span> no sentido da Aula 4. Numericamente, o ângulo entre os autovetores é <span class="math inline">\(\approx 106{,}9°\)</span> (nada perto de <span class="math inline">\(90°\)</span>), enquanto o ângulo entre <span class="math inline">\(\mathbf{v}_1\)</span> e <span class="math inline">\(\mathbf{v}_2\)</span> é exatamente <span class="math inline">\(90°\)</span> — os vetores singulares são, por construção, <strong>sempre</strong> ortogonais entre si, autovetores de uma matriz qualquer, em geral, não são. Esse é precisamente o ponto: autovetor e vetor singular são conceitos relacionados, mas <strong>não são a mesma coisa</strong> — coincidem apenas quando <span class="math inline">\(A\)</span> é simétrica (Bloco 3 mostra exatamente por quê).</p>
<p>O painel direito mostra a imagem do círculo unitário sob <span class="math inline">\(A\)</span>: uma elipse cujos eixos caem sobre <span class="math inline">\(\sigma_1\mathbf{u}_1\)</span> e <span class="math inline">\(\sigma_2\mathbf{u}_2\)</span> — os <strong>valores singulares</strong> (<span class="math inline">\(\sigma_1\approx 1{,}675\)</span>, <span class="math inline">\(\sigma_2\approx 0{,}645\)</span>, sempre não-negativos e ordenados por convenção, <span class="math inline">\(\sigma_1\ge\sigma_2\)</span>) escalando os <strong>vetores singulares à esquerda</strong>, <span class="math inline">\(\mathbf{u}_1,\mathbf{u}_2\)</span> — que também são ortogonais entre si. A intuição geométrica central da SVD: <span class="math inline">\(A\)</span> pega uma base ortonormal do domínio (<span class="math inline">\(\mathbf{v}_1,\mathbf{v}_2\)</span>) e a transforma em outra base ortogonal do codomínio (<span class="math inline">\(\sigma_1\mathbf{u}_1,
\sigma_2\mathbf{u}_2\)</span>) — nada gira “torto” nem no domínio nem no codomínio; só a costura entre os dois lados muda de base.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Autovetor e vetor singular: a mesma seta, dois papéis diferentes?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que muda (e no que não muda) quando <span class="math inline">\(A\)</span> é simétrica — volte, se precisar, ao Teorema Espectral Real da Aula 4.</p>
<ul>
<li>□ Se <span class="math inline">\(A\)</span> for simétrica, os vetores singulares de <span class="math inline">\(A\)</span> e os autovetores de <span class="math inline">\(A\)</span> podem ser escolhidos exatamente iguais (a menos de sinal).</li>
<li>□ Se todos os autovalores de uma matriz <span class="math inline">\(2\times 2\)</span> forem complexos (não-reais), essa matriz ainda assim possui uma SVD real bem definida.</li>
<li>□ Numa camada linear <span class="math inline">\(f(\mathbf{x})=W\mathbf{x}\)</span> de uma rede neural com <span class="math inline">\(W\)</span> quadrada mas não-simétrica, os vetores singulares de <span class="math inline">\(W\)</span> e os autovetores de <span class="math inline">\(W\)</span> apontam, em geral, em direções diferentes.</li>
<li>□ Como os vetores singulares são sempre ortogonais entre si, isso implica que a imagem do círculo unitário sob qualquer matriz <span class="math inline">\(A\)</span> é sempre um círculo (nunca uma elipse “achatada”).</li>
</ul>
</div>
</div>
</section>
</section>
<section id="construção-formal-da-svd-a-partir-do-teorema-espectral" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Construção Formal da SVD a Partir do Teorema Espectral</h1>
<hr>
<section id="premissas-o-que-já-temos-disponível" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="premissas-o-que-já-temos-disponível"><span class="header-section-number">3.1</span> Premissas: O Que Já Temos Disponível</h2>
<p>Antes de construir qualquer coisa, vale deixar claro <strong>o que estamos procurando</strong> — os termos “vetor singular” e “valor singular” vão aparecer o tempo todo daqui pra frente, e é melhor defini-los já:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definição (Valor e Vetor Singular — prévia do Teorema 4.22, adiante)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um <strong>valor singular</strong> de <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span> é um número <span class="math inline">\(\sigma\ge 0\)</span> para o qual existem vetores unitários <span class="math inline">\(\mathbf{v}\in\mathbb{R}^n\)</span> e <span class="math inline">\(\mathbf{u}\in\mathbb{R}^m\)</span> satisfazendo <span class="math display">\[
A\mathbf{v} = \sigma\mathbf{u} .
\]</span> Chamamos <span class="math inline">\(\mathbf{v}\)</span> de <strong>vetor singular à direita</strong> (mora no domínio de <span class="math inline">\(A\)</span>) e <span class="math inline">\(\mathbf{u}\)</span> de <strong>vetor singular à esquerda</strong> (mora no codomínio), associados a esse mesmo <span class="math inline">\(\sigma\)</span>. O Teorema 4.22 (adiante) garante que <span class="math inline">\(A\)</span> sempre tem um conjunto <em>completo</em> desses trios — os <span class="math inline">\(\mathbf{v}_i\)</span> formando uma base ortonormal de <span class="math inline">\(\mathbb{R}^n\)</span>, os <span class="math inline">\(\mathbf{u}_i\)</span> ortonormais em <span class="math inline">\(\mathbb{R}^m\)</span> — e é exatamente esse conjunto completo que vamos construir a seguir.</p>
</div>
</div>
<p>Note a semelhança de forma com a equação de autovalor <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> (Aula 4): lá, o mesmo vetor <span class="math inline">\(\mathbf{x}\)</span> aparece dos dois lados, porque <span class="math inline">\(A\)</span> precisa ser quadrada para isso fazer sentido. Aqui, <span class="math inline">\(\mathbf{v}\)</span> (entrada) e <span class="math inline">\(\mathbf{u}\)</span> (saída) podem ser vetores diferentes, em espaços diferentes — é essa flexibilidade que permite a existência <strong>para qualquer matriz</strong>, retangular ou não, simétrica ou não.</p>
<p><strong>Como provar que esse trio sempre existe?</strong> A construção que segue (tradução livre e reorganização nossa de MathML, §4.5.2, pp.&nbsp;122-125) usa só resultados já disponíveis desde a Aula 4 — nenhuma ferramenta nova de álgebra linear precisa ser importada. Sejam <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span> uma matriz qualquer (não necessariamente quadrada) e <span class="math inline">\(r=\text{posto}(A)\)</span>. As duas premissas:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Premissas (ambas já provadas na Aula 4)
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(A^TA\in\mathbb{R}^{n\times n}\)</span> e <span class="math inline">\(AA^T\in\mathbb{R}^{m\times m}\)</span> são <strong>sempre</strong> simétricas e semidefinidas positivas, para <strong>qualquer</strong> <span class="math inline">\(A\)</span> — mesmo retangular (Aula 4, teorema <span class="math inline">\(A^TA\)</span> simétrica e semidefinida positiva).</li>
<li>Pelo <strong>Teorema Espectral Real</strong> (Aula 4), toda matriz simétrica admite uma base ortonormal completa de autovetores associados a autovalores reais e não-negativos (semidefinitude positiva <span class="math inline">\(\iff\)</span> <span class="math inline">\(\lambda_i\ge 0\)</span> para todo <span class="math inline">\(i\)</span>).</li>
</ol>
</div>
</div>
<p>A ideia para construir o trio <span class="math inline">\((\mathbf{v}_i,\sigma_i,\mathbf{u}_i)\)</span> da Definição acima, em três movimentos:</p>
<ol type="1">
<li><strong>Metade 1 — só com <span class="math inline">\(A^TA\)</span>.</strong> Aplicamos as duas premissas diretamente em <span class="math inline">\(A^TA\)</span> (simétrica, semidefinida positiva) e extraímos uma base ortonormal de autovetores <span class="math inline">\(\mathbf{v}_1,\dots,\mathbf{v}_n\)</span> — os <strong>vetores singulares à direita</strong> — com autovalores <span class="math inline">\(\lambda_i\ge 0\)</span>, dos quais tiramos os <strong>valores singulares</strong> <span class="math inline">\(\sigma_i=\sqrt{\lambda_i}\)</span>. Isso já entrega <span class="math inline">\(V\)</span> e <span class="math inline">\(\Sigma\)</span> inteiros (Passo 1), sem em nenhum momento ter olhado para o que <span class="math inline">\(A\)</span> faz no codomínio.</li>
<li><strong>Metade 2 — a ação de <span class="math inline">\(A\)</span> sobre esses vetores.</strong> Falta <span class="math inline">\(U\)</span>, e <span class="math inline">\(U\)</span> vive no codomínio <span class="math inline">\(\mathbb{R}^m\)</span> — um espaço diferente de onde moram os <span class="math inline">\(\mathbf{v}_i\)</span>. A saída natural é justamente aplicar <span class="math inline">\(A\)</span> a cada <span class="math inline">\(\mathbf{v}_i\)</span> e examinar o resultado: <span class="math inline">\(A\mathbf{v}_i\in\mathbb{R}^m\)</span> é o candidato a (múltiplo de) vetor singular à esquerda (Passo 2).</li>
<li><strong>A ligação entre as duas metades.</strong> <span class="math inline">\(A\mathbf{v}_i\)</span> não é unitário — mas os <span class="math inline">\(\sigma_i\)</span> que já tínhamos calculado na Metade 1 são exatamente o fator que falta para normalizá-lo: <span class="math inline">\(\mathbf{u}_i:=\frac{1}{\sigma_i}A\mathbf{v}_i\)</span>. O mesmo número <span class="math inline">\(\sigma_i\)</span> entra duas vezes — primeiro como raiz de um autovalor de <span class="math inline">\(A^TA\)</span>, depois como o comprimento de <span class="math inline">\(A\mathbf{v}_i\)</span> (o Passo 2 prova que são o mesmo número) — e é esse reaproveitamento que faz <span class="math inline">\(U\)</span>, <span class="math inline">\(\Sigma\)</span> e <span class="math inline">\(V\)</span> se encaixarem numa única decomposição, em vez de serem três peças soltas sem relação entre si.</li>
</ol>
</section>
<section id="passo-1-vetores-singulares-à-direita-a-partir-de-ata" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="passo-1-vetores-singulares-à-direita-a-partir-de-ata"><span class="header-section-number">3.2</span> Passo 1: Vetores Singulares à Direita, a Partir de <span class="math inline">\(A^TA\)</span></h2>
<p>Pela Premissa 1, <span class="math inline">\(A^TA\)</span> é simétrica e semidefinida positiva. Pela Premissa 2 (Teorema Espectral Real), existe uma base ortonormal completa de autovetores <span class="math inline">\(\mathbf{v}_1,\dots,\mathbf{v}_n\in\mathbb{R}^n\)</span> de <span class="math inline">\(A^TA\)</span>, com autovalores reais e não-negativos <span class="math inline">\(\lambda_1\ge\dots\ge\lambda_n\ge 0\)</span>: <span class="math display">\[
A^TA = V\Lambda V^T, \qquad V=[\mathbf{v}_1\ \cdots\ \mathbf{v}_n]
\text{ ortogonal}, \qquad \Lambda=\text{diag}(\lambda_1,\dots,\lambda_n).
\]</span> A ortonormalidade dos <span class="math inline">\(\mathbf{v}_i\)</span> não precisa de uma prova completa aqui — já vem embutida na Premissa 2 (o Teorema Espectral Real, provado na Aula 4). Vale só mostrar as duas partes de forma simples, sem reabrir a prova inteira.</p>
<p><strong>Ortogonalidade.</strong> Para autovalores distintos, <span class="math inline">\(\lambda_i\ne\lambda_j\)</span>, a própria simetria de <span class="math inline">\(A^TA\)</span> já força <span class="math display">\[
(\lambda_i-\lambda_j)\langle\mathbf{v}_i,\mathbf{v}_j\rangle =
\langle A^TA\mathbf{v}_i,\mathbf{v}_j\rangle -
\langle\mathbf{v}_i,A^TA\mathbf{v}_j\rangle = 0
\;\Longrightarrow\;
\langle\mathbf{v}_i,\mathbf{v}_j\rangle = 0.
\]</span></p>
<p><strong>Norma unitária.</strong> Um autovetor é definido só a menos de escala — se <span class="math inline">\(\mathbf{v}\)</span> satisfaz <span class="math inline">\(A^TA\mathbf{v}=\lambda\mathbf{v}\)</span>, qualquer múltiplo <span class="math inline">\(c\mathbf{v}\)</span> também satisfaz. Escolhemos sempre o representante de norma <span class="math inline">\(1\)</span>, <span class="math inline">\(\mathbf{v}_i:=\mathbf{v}/\|\mathbf{v}\|\)</span> — uma normalização, não uma propriedade que precisa ser provada.</p>
<p>Manter as duas propriedades <strong>simultaneamente</strong> (inclusive quando há autovalores repetidos, via Gram-Schmidt dentro do autoespaço) é exatamente o que a Premissa 2 garante — resultado já demonstrado na Aula 4, não repetido aqui.</p>
<p>Como cada <span class="math inline">\(\lambda_i\ge 0\)</span> (semidefinitude positiva), a raiz quadrada <span class="math inline">\(\sqrt{\lambda_i}\)</span> está sempre bem definida em <span class="math inline">\(\mathbb{R}\)</span> — <strong>é aqui que a Premissa 1 entra de forma essencial</strong>: se <span class="math inline">\(A^TA\)</span> não fosse garantidamente semidefinida positiva, não haveria garantia de poder tomar essa raiz sem cair em números complexos. Definimos os <strong>valores singulares</strong> de <span class="math inline">\(A\)</span> como <span class="math display">\[
\sigma_i := \sqrt{\lambda_i} \ge 0, \qquad i=1,\dots,n,
\]</span> e chamamos os <span class="math inline">\(\mathbf{v}_i\)</span> (autovetores de <span class="math inline">\(A^TA\)</span>) de <strong>vetores singulares à direita</strong> de <span class="math inline">\(A\)</span>.</p>
</section>
<section id="passo-2-vetores-singulares-à-esquerda-como-imagem-normalizada" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="passo-2-vetores-singulares-à-esquerda-como-imagem-normalizada"><span class="header-section-number">3.3</span> Passo 2: Vetores Singulares à Esquerda, Como Imagem Normalizada</h2>
<p><strong>Onde queremos chegar.</strong> O Passo 1 só decompôs <span class="math inline">\(A^TA\)</span> — metade da história, e nem sequer envolve <span class="math inline">\(A\)</span> diretamente sobre o codomínio. Falta achar, no espaço de chegada <span class="math inline">\(\mathbb{R}^m\)</span>, um conjunto ortonormal <span class="math inline">\(\mathbf{u}_1,\dots,\mathbf{u}_r\)</span> tal que a ação de <span class="math inline">\(A\)</span> sobre cada <span class="math inline">\(\mathbf{v}_i\)</span> do Passo 1 seja simplesmente “esticar por <span class="math inline">\(\sigma_i\)</span> na direção <span class="math inline">\(\mathbf{u}_i\)</span>”: <span class="math display">\[
A\mathbf{v}_i = \sigma_i\mathbf{u}_i, \qquad i=1,\dots,r .
\]</span> Essa é literalmente a equação que teremos que satisfazer para montar a SVD (ela reaparece na forma matricial no Passo 3) — se acharmos esses <span class="math inline">\(\mathbf{u}_i\)</span> ortonormais, a segunda metade da construção está pronta. Duas perguntas ficam em aberto: (i) que vetor <strong>é</strong> esse <span class="math inline">\(\mathbf{u}_i\)</span>, e (ii) por que o conjunto resultante seria ortonormal?</p>
<p><strong>Candidato: a própria imagem, normalizada.</strong> A equação acima já diz a direção de <span class="math inline">\(\mathbf{u}_i\)</span> — ele precisa ser paralelo a <span class="math inline">\(A\mathbf{v}_i\)</span> (para <span class="math inline">\(\sigma_i&gt;0\)</span>, isto é, <span class="math inline">\(i\le r\)</span>, já que <span class="math inline">\(\text{posto}(A^TA)=\text{posto}(A)=r\)</span>). O candidato natural é normalizar essa imagem pelo próprio comprimento: <span class="math display">\[
\mathbf{u}_i := \frac{1}{\sigma_i}A\mathbf{v}_i \in \mathbb{R}^m .
\]</span> Só falta confirmar que este candidato entrega o que prometemos: ortonormalidade. Duas verificações, e nada além delas.</p>
<p><strong>Verificação (i) — as imagens já são ortogonais entre si.</strong> Como <span class="math inline">\(\mathbf{v}_i\)</span> é autovetor de <span class="math inline">\(A^TA\)</span> com autovalor <span class="math inline">\(\lambda_i\)</span>, <span class="math inline">\(A^TA\mathbf{v}_j=\lambda_j\mathbf{v}_j\)</span>, e para <span class="math inline">\(i\ne j\)</span>, <span class="math display">\[
(A\mathbf{v}_i)^T(A\mathbf{v}_j) = \mathbf{v}_i^T(A^TA)\mathbf{v}_j =
\mathbf{v}_i^T(\lambda_j\mathbf{v}_j) = \lambda_j(\mathbf{v}_i^T
\mathbf{v}_j) = 0 ,
\]</span> onde o último passo usa a ortogonalidade de <span class="math inline">\(\mathbf{v}_i\)</span> e <span class="math inline">\(\mathbf{v}_j\)</span> (<span class="math inline">\(i\ne j\)</span>), já garantida pela base ortonormal do Passo 1. Repare que essa conta usa <span class="math inline">\(A^TA\)</span> — a mesma Premissa 2 do Passo 1 — e não precisa de <span class="math inline">\(\mathbf{u}_i\)</span> nenhum: <strong>as imagens <span class="math inline">\(A\mathbf{v}_i\)</span> já nascem ortogonais</strong>, antes de qualquer normalização.</p>
<p><strong>Verificação (ii) — a norma de cada imagem é exatamente <span class="math inline">\(\sigma_i\)</span>.</strong> <span class="math display">\[
\|A\mathbf{v}_i\|^2=\mathbf{v}_i^T A^TA\mathbf{v}_i=\lambda_i\|
\mathbf{v}_i\|^2=\lambda_i=\sigma_i^2 \quad\Longrightarrow\quad
\|A\mathbf{v}_i\|=\sigma_i .
\]</span></p>
<p><strong>Chegamos.</strong> As imagens <span class="math inline">\(A\mathbf{v}_1,\dots,A\mathbf{v}_r\)</span> são ortogonais entre si (Verificação i) e cada uma tem norma <span class="math inline">\(\sigma_i\)</span> (Verificação ii) — logo dividir cada uma pelo próprio comprimento, exatamente o que <span class="math inline">\(\mathbf{u}_i:=\frac{1}{\sigma_i}A\mathbf{v}_i\)</span> faz, produz um conjunto ortonormal <span class="math inline">\(\mathbf{u}_1,\dots,\mathbf{u}_r\)</span>. E por construção ele já satisfaz a equação-alvo <span class="math inline">\(A\mathbf{v}_i=\sigma_i\mathbf{u}_i\)</span> com que abrimos o passo. Chamamos os <span class="math inline">\(\mathbf{u}_i\)</span> de <strong>vetores singulares à esquerda</strong> de <span class="math inline">\(A\)</span>.</p>
</section>
<section id="passo-3-a-equação-de-valor-singular-e-a-montagem-final" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="passo-3-a-equação-de-valor-singular-e-a-montagem-final"><span class="header-section-number">3.4</span> Passo 3: A Equação de Valor Singular e a Montagem Final</h2>
<p>O Passo 2 confirmou a meta que havíamos proposto: com <span class="math inline">\(\mathbf{u}_i=\dfrac{1}{\sigma_i}A\mathbf{v}_i\)</span>, vale de fato a <strong>equação de valor singular</strong> <span class="math display">\[
A\mathbf{v}_i = \sigma_i\mathbf{u}_i, \qquad i=1,\dots,r .
\]</span> Falta só empacotar isso em forma matricial. Note a semelhança — e a diferença — com a equação de autovalor <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> da Aula 4: aqui os vetores dos dois lados (<span class="math inline">\(\mathbf{v}_i\)</span> no domínio, <span class="math inline">\(\mathbf{u}_i\)</span> no codomínio) <strong>não precisam ser o mesmo vetor</strong>, porque <span class="math inline">\(A\)</span> pode mudar de espaço. Empilhando os <span class="math inline">\(\mathbf{v}_i\)</span> como colunas de <span class="math inline">\(V\)</span> e os <span class="math inline">\(\mathbf{u}_i\)</span> como colunas de <span class="math inline">\(U\)</span> (completando <span class="math inline">\(U\)</span> e <span class="math inline">\(V\)</span> com bases ortonormais arbitrárias dos espaços-nulos de <span class="math inline">\(A^T\)</span> e <span class="math inline">\(A\)</span>, se <span class="math inline">\(r&lt;m\)</span> ou <span class="math inline">\(r&lt;n\)</span> — os <span class="math inline">\(\sigma_i=0\)</span> correspondentes preenchem <span class="math inline">\(\Sigma\)</span> com zeros, sem violar nada), a equação de valor singular vira, em forma matricial, <span class="math display">\[
AV = U\Sigma ,
\]</span> onde <span class="math inline">\(\Sigma\in\mathbb{R}^{m\times n}\)</span> tem <span class="math inline">\(\Sigma_{ii}=\sigma_i\)</span> e <span class="math inline">\(\Sigma_{ij}=0\)</span> para <span class="math inline">\(i\ne j\)</span>. Como <span class="math inline">\(V\)</span> é ortogonal, <span class="math inline">\(V^{-1}=V^T\)</span>; multiplicando ambos os lados à direita por <span class="math inline">\(V^T\)</span>: <span class="math display">\[
A = U\Sigma V^T .
\]</span> Isso completa a construção. Podemos agora enunciar o resultado de forma autocontida:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema (SVD — MathML, tradução nossa, Teo. 4.22, p.&nbsp;119)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span> uma matriz de posto <span class="math inline">\(r\in[0,\min(m,n)]\)</span>. Então existe uma decomposição <span class="math display">\[
A = U\Sigma V^T
\]</span> com <span class="math inline">\(U\in\mathbb{R}^{m\times m}\)</span> ortogonal (colunas <span class="math inline">\(\mathbf{u}_1,\dots,\mathbf{u}_m\)</span>), <span class="math inline">\(V\in\mathbb{R}^{n\times n}\)</span> ortogonal (colunas <span class="math inline">\(\mathbf{v}_1,\dots,\mathbf{v}_n\)</span>), e <span class="math inline">\(\Sigma\in\mathbb{R}^{m\times n}\)</span> com <span class="math inline">\(\Sigma_{ii}=\sigma_i\ge 0\)</span> e <span class="math inline">\(\Sigma_{ij}=0\)</span> para <span class="math inline">\(i\ne j\)</span>. Os <span class="math inline">\(\sigma_i\)</span>, <span class="math inline">\(i=1,\dots,r\)</span>, são os <strong>valores singulares</strong> (por convenção, ordenados <span class="math inline">\(\sigma_1\ge\dots\ge\sigma_r&gt;0\)</span>); <span class="math inline">\(\mathbf{u}_i\)</span> são os <strong>vetores singulares à esquerda</strong>; <span class="math inline">\(\mathbf{v}_i\)</span> são os <strong>vetores singulares à direita</strong>. Essa decomposição existe para <strong>qualquer</strong> <span class="math inline">\(A\in
\mathbb{R}^{m\times n}\)</span>, sem exceção — em particular, sem exigir que <span class="math inline">\(A\)</span> seja quadrada nem simétrica.</p>
</div>
</div>
<p>Vale registrar explicitamente a diferença em relação à decomposição espectral da Aula 4: lá, <span class="math inline">\(A=Q\Lambda Q^{-1}\)</span> usa a <strong>mesma</strong> matriz de base (<span class="math inline">\(Q\)</span>) nos dois lados, porque o domínio e o codomínio de uma transformação <span class="math inline">\(A:\mathbb{R}^n\to\mathbb{R}^n\)</span> são o mesmo espaço. A SVD usa <strong>duas</strong> bases diferentes (<span class="math inline">\(U\)</span> e <span class="math inline">\(V\)</span>) precisamente porque, em geral, domínio (<span class="math inline">\(\mathbb{R}^n\)</span>) e codomínio (<span class="math inline">\(\mathbb{R}^m\)</span>) da transformação representada por <span class="math inline">\(A\)</span> são espaços diferentes — e a SVD é o que resta de “decomposição em direções especiais” quando essa igualdade de espaços é removida.</p>
</section>
<section id="exemplo-resolvido-à-mão" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="exemplo-resolvido-à-mão"><span class="header-section-number">3.5</span> Exemplo Resolvido à Mão</h2>
<p>Vamos aplicar a construção passo a passo à matriz (MathML, Exemplo 4.13, tradução livre) <span class="math display">\[
A = \begin{bmatrix} 1 &amp; 0 &amp; 1 \\ -2 &amp; 1 &amp; 0 \end{bmatrix} \in
\mathbb{R}^{2\times 3} .
\]</span> <strong>Passo 1.</strong> <span class="math inline">\(A^TA=\begin{bmatrix}5&amp;-2&amp;1\\-2&amp;1&amp;0\\1&amp;0&amp;1\end{bmatrix}\)</span> (simétrica e semidefinida positiva, Premissa 1, verificável por substituição direta). Seus autovalores (via o polinômio característico <span class="math inline">\(3\times 3\)</span>, ou diretamente por <code>numpy</code>) são <span class="math inline">\(\lambda=(6,\,1,\,0)\)</span> — só dois não-nulos, consistente com <span class="math inline">\(\text{posto}(A)=2\)</span>. Logo, <span class="math inline">\(\sigma_1=\sqrt{6}\approx 2{,}449\)</span> e <span class="math inline">\(\sigma_2=\sqrt{1}=1\)</span>.</p>
<p><strong>Passo 2.</strong> <span class="math inline">\(\mathbf{u}_1=A\mathbf{v}_1/\sigma_1\)</span> e <span class="math inline">\(\mathbf{u}_2=A\mathbf{v}_2/\sigma_2\)</span>, calculados a partir dos autovetores <span class="math inline">\(\mathbf{v}_1,\mathbf{v}_2\)</span> de <span class="math inline">\(A^TA\)</span>.</p>
<p><strong>Passo 3.</strong> Verificação numérica completa a seguir.</p>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<div id="168e3418" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>A =
 [[ 1.  0.  1.]
 [-2.  1.  0.]]

posto(A) = 2

valores singulares sigma = [2.4495 1.    ]

U (vetores singulares à esquerda, colunas) =
 [[-0.4472  0.8944]
 [ 0.8944  0.4472]]

V (vetores singulares à direita, colunas) =
 [[-0.9129 -0.     -0.4082]
 [ 0.3651  0.4472 -0.8165]
 [-0.1826  0.8944  0.4082]]

reconstrução U @ Sigma @ V^T =
 [[ 1. -0.  1.]
 [-2.  1.  0.]]

reconstrução bate com A?  True</code></pre>
</div>
</div>
</div>
<p>A reconstrução <span class="math inline">\(U\Sigma V^T\)</span> recupera <span class="math inline">\(A\)</span> exatamente (diferença menor que <span class="math inline">\(10^{-10}\)</span>, arredondamento de ponto flutuante), confirmando a construção passo a passo. Repare que a terceira coluna de <span class="math inline">\(V\)</span> (associada a <span class="math inline">\(\sigma_3=0\)</span>) é uma base ortonormal do espaço-nulo de <span class="math inline">\(A\)</span> — outra consequência direta da construção: a SVD não só decompõe <span class="math inline">\(A\)</span>, como também produz de graça uma base ortonormal de <span class="math inline">\(\ker(A)\)</span>, generalizando o que a Aula 2 chamava de núcleo (espaço-solução de <span class="math inline">\(A\mathbf{x}=
\mathbf{0}\)</span>) para o caso retangular.</p>
<p><strong>Aviso de leitura:</strong> por construção, cada vetor singular é único <strong>a menos de sinal</strong> (assim como os autovetores da Aula 4) — trocar <span class="math inline">\((\mathbf{u}_i,\mathbf{v}_i)\)</span> por <span class="math inline">\((-\mathbf{u}_i,-\mathbf{v}_i)\)</span> simultaneamente não muda <span class="math inline">\(\sigma_i\mathbf{u}_i\mathbf{v}_i^T\)</span>. Por isso os sinais que o <code>numpy</code> devolve podem diferir dos de uma referência impressa em livro sem que a decomposição esteja errada — o que importa é o produto <span class="math inline">\(U\Sigma V^T\)</span>, não os sinais individuais.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(A^TA\)</span> tivesse um autovalor negativo, a construção quebraria em qual passo exatamente?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia a Premissa 1 e aponte, com precisão, onde ela é usada.</p>
<ul>
<li>□ A construção quebraria já no Passo 1, porque <span class="math inline">\(\sigma_i:=
\sqrt{\lambda_i}\)</span> deixaria de estar bem definido em <span class="math inline">\(\mathbb{R}\)</span> para um <span class="math inline">\(\lambda_i&lt;0\)</span>.</li>
<li>□ Se <span class="math inline">\(A\)</span> for quadrada e invertível, todos os seus valores singulares são necessariamente iguais aos valores absolutos de seus autovalores.</li>
<li>□ Numa matriz de covariância empírica (Aula 4, Bloco 6) — sempre simétrica semidefinida positiva por construção — a mesma garantia de raiz quadrada real dos autovalores se aplica ao construir os “desvios-padrão principais” via SVD/decomposição espectral.</li>
<li>□ Como <span class="math inline">\(A^TA\)</span> é sempre semidefinida positiva para qualquer <span class="math inline">\(A\)</span> real (Aula 4), isso implica que <span class="math inline">\(A\)</span> em si também tem só autovalores não-negativos, quando <span class="math inline">\(A\)</span> é quadrada.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="a-svd-do-dataset-fio-x-do-california-housing" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> A SVD do Dataset-Fio: <span class="math inline">\(X\)</span> do <em>California Housing</em></h1>
<hr>
<section id="voltando-ao-problema-original" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="voltando-ao-problema-original"><span class="header-section-number">4.1</span> Voltando ao Problema Original</h2>
<p>Chegou a hora de aplicar a construção do Bloco 3 ao objeto que motivou toda a aula: a matriz de design <span class="math inline">\(X\in\mathbb{R}^{16\,640\times 4}\)</span> do <em>California Housing</em> (colunas <code>MedInc</code>, <code>HouseAge</code>, <code>AveRooms</code>, <code>AveBedrms</code>), a mesma usada desde a Aula 1. Como <span class="math inline">\(X\)</span> tem muito mais linhas que colunas (<span class="math inline">\(m=16\,640 \gg n=4\)</span>), calcular a SVD completa (<span class="math inline">\(U\in\mathbb{R}^{16\,640\times 16\,640}\)</span>) seria um desperdício: as últimas <span class="math inline">\(16\,640-4\)</span> colunas de <span class="math inline">\(U\)</span> só completam uma base ortonormal do codomínio sem carregar nenhuma informação nova sobre <span class="math inline">\(X\)</span> (correspondem a <span class="math inline">\(\sigma_i=0\)</span>). Por isso, na prática, usa-se a <strong>SVD reduzida</strong> (MathML, p.&nbsp;128) — <span class="math inline">\(U\in\mathbb{R}^{16\,640\times 4}\)</span>, <span class="math inline">\(\Sigma\in
\mathbb{R}^{4\times 4}\)</span> diagonal, <span class="math inline">\(V\in\mathbb{R}^{4\times 4}\)</span> —, matematicamente equivalente à SVD completa, só descartando as colunas que multiplicariam por zero de qualquer forma.</p>
<div class="fig-resize" style="width: 50%; margin: 0 auto;">
<div id="a9799d4b" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-7-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma(X)      = [4186.9964  523.4408  229.4908   27.3359]
sigma(X)^2    = [1.75309388e+07 2.73990283e+05 5.26660328e+04 7.47253300e+02]
lambda(X^TX)  = [1.75309388e+07 2.73990283e+05 5.26660328e+04 7.47253300e+02]
cond(X)       = sigma_max/sigma_min       = 153.1682
cond(X^TX)    = lambda_max/lambda_min     = 23460.5031
cond(X)^2     = 23460.5031</code></pre>
</div>
</div>
</div>
<p>Os quatro valores singulares de <span class="math inline">\(X\)</span> são <span class="math inline">\(\sigma=[4\,186{,}996;\
523{,}441;\ 229{,}491;\ 27{,}336]\)</span> (ordem decrescente). Elevando ao quadrado: <span class="math inline">\(\sigma^2=[1{,}753\times10^7;\ 273\,990{,}28;\ 52\,666{,}03;\
747{,}25]\)</span> — <strong>exatamente</strong> os autovalores de <span class="math inline">\(X^TX\)</span> que a Aula 4 já tinha calculado, na mesma ordem. Isso não é coincidência nem aproximação numérica: é o Passo 1 da construção do Bloco 3, aplicado diretamente a <span class="math inline">\(A=X\)</span> — <span class="math inline">\(\sigma_i(X)^2=\lambda_i(X^TX)\)</span> por definição. O painel direito da figura confirma isso visualmente: todos os pontos caem exatamente sobre a reta <span class="math inline">\(y=x\)</span> (em escala log-log, para acomodar a diferença de quatro ordens de grandeza entre o maior e o menor autovalor).</p>
<p>Essa identidade fecha, de forma exata, o gancho que a Aula 4 deixou em aberto: o Boyd (Apêndice A.5.2, já citado na Aula 4) define o número de condição de uma matriz retangular qualquer usando <strong>valores singulares</strong>, <span class="math inline">\(\text{cond}(X)=\sigma_{\max}/\sigma_{\min}\)</span>, não autovalores. Calculando: <span class="math inline">\(\text{cond}(X)\approx 4\,186{,}996/27{,}336
\approx 153{,}168\)</span>. Compare com <span class="math inline">\(\text{cond}(X^TX)\approx 23\,460{,}5\)</span>, já calculado na Aula 4 — a razão entre os dois não é arbitrária:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Proposição: <span class="math inline">\(\text{cond}(X^TX)=\text{cond}(X)^2\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para qualquer <span class="math inline">\(X\in\mathbb{R}^{m\times n}\)</span> de posto completo (todos os <span class="math inline">\(\sigma_i&gt;0\)</span>), <span class="math inline">\(\text{cond}(X^TX)=\text{cond}(X)^2\)</span>.</p>
<p><strong>Prova (nossa, direta da definição).</strong> Por <span class="math inline">\(\sigma_i(X)^2=
\lambda_i(X^TX)\)</span> (Passo 1, Bloco 3, aplicado a <span class="math inline">\(A=X\)</span>), o maior e o menor autovalor de <span class="math inline">\(X^TX\)</span> são <span class="math inline">\(\lambda_{\max}=\sigma_{\max}^2\)</span> e <span class="math inline">\(\lambda_{\min}=\sigma_{\min}^2\)</span>. Logo, <span class="math display">\[
\text{cond}(X^TX) = \frac{\lambda_{\max}}{\lambda_{\min}} =
\frac{\sigma_{\max}^2}{\sigma_{\min}^2} = \left(\frac{\sigma_{\max}}
{\sigma_{\min}}\right)^2 = \text{cond}(X)^2 . \qquad\blacksquare
\]</span></p>
</div>
</div>
<p>Numericamente: <span class="math inline">\(153{,}168^2\approx 23\,460{,}5\)</span> — bate exatamente com o valor já calculado na Aula 4 (nenhuma aproximação, a igualdade é exata a menos de arredondamento de ponto flutuante). Essa proposição tem uma consequência prática que vale registrar como aviso, mesmo sem desenvolver agora (a Aula 8 retoma o tema, ao discutir estabilidade de algoritmos iterativos): <strong>resolver as Equações Normais <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> diretamente trabalha, por dentro, com o número de condição elevado ao quadrado</strong> — <span class="math inline">\(23\,460{,}5\)</span>, contra apenas <span class="math inline">\(153{,}168\)</span> se um algoritmo numérico trabalhasse com <span class="math inline">\(X\)</span> diretamente (via SVD, por exemplo, em vez de formar <span class="math inline">\(X^TX\)</span> explicitamente). É por isso que bibliotecas numéricas de produção (como o <code>scipy.linalg.lstsq</code>) evitam formar <span class="math inline">\(X^TX\)</span> explicitamente sempre que possível.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se o menor valor singular de <span class="math inline">\(X\)</span> fosse exatamente zero, o que isso significaria sobre <code>AveRooms</code>/<code>AveBedrms</code>/<code>MedInc</code>/<code>HouseAge</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: relacione posto, dependência linear (Aula 2) e <span class="math inline">\(\sigma_{\min}=0\)</span>.</p>
<ul>
<li>□ <span class="math inline">\(\sigma_{\min}(X)=0\)</span> significaria que as 4 colunas de <span class="math inline">\(X\)</span> são linearmente dependentes, no mesmo sentido de dependência linear definido na Aula 2.</li>
<li>□ Se todos os 4 valores singulares de <span class="math inline">\(X\)</span> fossem exatamente iguais entre si, o número de condição de <span class="math inline">\(X\)</span> seria <span class="math inline">\(1\)</span>, mas isso não diria nada sobre o número de condição de <span class="math inline">\(X^TX\)</span>.</li>
<li>□ Numa matriz de embeddings de palavras (uma linha por palavra, uma coluna por dimensão latente), um valor singular próximo de zero indicaria uma dimensão latente quase redundante com as demais.</li>
<li>□ Como <span class="math inline">\(\sigma_i(X)^2=\lambda_i(X^TX)\)</span> vale para qualquer <span class="math inline">\(X\)</span>, isso implica que basta calcular os autovalores de <span class="math inline">\(X^TX\)</span> (Aula 4, já feito) para nunca mais ser necessário calcular a SVD de <span class="math inline">\(X\)</span> diretamente, em qualquer aplicação.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="aproximação-de-baixo-posto-e-o-teorema-de-eckart-young-mirsky" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Aproximação de Baixo Posto e o Teorema de Eckart-Young-Mirsky</h1>
<hr>
<section id="decompondo-a-em-pedaços-de-posto-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="decompondo-a-em-pedaços-de-posto-1"><span class="header-section-number">5.1</span> Decompondo <span class="math inline">\(A\)</span> em Pedaços de Posto 1</h2>
<p>A SVD <span class="math inline">\(A=U\Sigma V^T\)</span> pode ser reescrita numa forma que deixa mais explícito o que cada valor singular “carrega”. Comece escrevendo o produto matricial <span class="math inline">\(U\Sigma V^T\)</span> em forma de somatório sobre todos os pares de índices <span class="math inline">\((i,j)\)</span>: <span class="math display">\[
A = U\Sigma V^T = \sum_{i,j} \Sigma_{ij}\, \mathbf{u}_i\mathbf{v}_j^T .
\]</span> Como <span class="math inline">\(\Sigma\)</span> é diagonal, <span class="math inline">\(\Sigma_{ij}=0\)</span> sempre que <span class="math inline">\(i\ne j\)</span> — só os termos com <span class="math inline">\(i=j\)</span> sobrevivem à soma: <span class="math display">\[
A = \sum_{i=1}^{\min(m,n)} \Sigma_{ii}\,\mathbf{u}_i\mathbf{v}_i^T =
\sum_{i=1}^{\min(m,n)} \sigma_i\,\mathbf{u}_i\mathbf{v}_i^T .
\]</span> E como <span class="math inline">\(\sigma_i=0\)</span> para <span class="math inline">\(i&gt;r\)</span> (Passo 3, Bloco 3: <span class="math inline">\(\sigma_i&gt;0\)</span> só até <span class="math inline">\(i=r=\text{posto}(A)\)</span>), esses termos não contribuem nada — a soma pode parar em <span class="math inline">\(r\)</span>: <span class="math display">\[
A = \sum_{i=1}^{r} \sigma_i\,\mathbf{u}_i\mathbf{v}_i^T .
\]</span> Essa é a forma que queríamos. Cada termo <span class="math inline">\(\sigma_i\mathbf{u}_i
\mathbf{v}_i^T\)</span> é uma matriz de posto <span class="math inline">\(1\)</span> (produto externo entre um vetor de <span class="math inline">\(U\)</span> e um vetor de <span class="math inline">\(V\)</span>, escalado por <span class="math inline">\(\sigma_i\)</span>) — vale nomeá-lo, já <strong>com o <span class="math inline">\(\sigma_i\)</span> embutido</strong>, porque é literalmente o pedaço de <span class="math inline">\(A\)</span> que aquele valor singular contribui: <span class="math display">\[
A_i := \sigma_i\,\mathbf{u}_i\mathbf{v}_i^T \in \mathbb{R}^{m\times n},
\qquad i=1,\dots,r .
\]</span> Com essa definição, a decomposição em pedaços de posto <span class="math inline">\(1\)</span> (MathML, §4.6, tradução nossa) fica simplesmente <span class="math display">\[
A = \sum_{i=1}^r A_i .
\]</span></p>
<p>Se, em vez de somar todos os <span class="math inline">\(r\)</span> termos, pararmos numa posição intermediária <span class="math inline">\(k&lt;r\)</span>, obtemos a <strong>aproximação de posto-<span class="math inline">\(k\)</span></strong> (MathML, Def. informal, §4.6): <span class="math display">\[
\hat{A}^{(k)} := \sum_{i=1}^k A_i = \sum_{i=1}^k
\sigma_i\mathbf{u}_i\mathbf{v}_i^T , \qquad \text{com }
\text{posto}(\hat{A}^{(k)})=k .
\]</span> Isso é chamado de <strong>SVD truncada</strong> (MathML, p.&nbsp;129). Intuitivamente: como os <span class="math inline">\(\sigma_i\)</span> vêm ordenados de forma decrescente, cada termo adicional contribui cada vez menos para <span class="math inline">\(A\)</span> — descartar os últimos <span class="math inline">\(r-k\)</span> termos descarta as direções que menos importam, na medida exata de <span class="math inline">\(\sigma_i\)</span>.</p>
</section>
<section id="medindo-o-erro-da-aproximação-norma-espectral" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="medindo-o-erro-da-aproximação-norma-espectral"><span class="header-section-number">5.2</span> Medindo o Erro da Aproximação: Norma Espectral</h2>
<p>Para dizer, com precisão, “o quanto <span class="math inline">\(\hat{A}^{(k)}\)</span> erra em relação a <span class="math inline">\(A\)</span>”, precisamos de uma noção de tamanho para matrizes — uma norma matricial, análoga às normas vetoriais da Aula 1. O plano desta seção é em dois tempos: primeiro provamos um fato <strong>geral</strong>, que vale para qualquer matriz <span class="math inline">\(M\)</span> (não só para <span class="math inline">\(A\)</span>); depois, na próxima seção (Eckart-Young-Mirsky), aplicamos esse mesmo fato a uma matriz específica — o <strong>erro</strong> <span class="math inline">\(A-\hat{A}^{(k)}\)</span> — para medir exatamente o tamanho desse erro. Ou seja: o que vem a seguir ainda não fala do erro diretamente, mas é a ferramenta sem a qual não dá para medi-lo depois.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definição (Norma Espectral — MathML, tradução nossa, Def. 4.23, p.&nbsp;131)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span>, a <strong>norma espectral</strong> de <span class="math inline">\(A\)</span> é <span class="math display">\[
\|A\|_2 := \max_{\mathbf{x}\ne\mathbf{0}} \frac{\|A\mathbf{x}\|_2}
{\|\mathbf{x}\|_2} .
\]</span></p>
</div>
</div>
<p>Ou seja: <span class="math inline">\(\|A\|_2\)</span> mede o maior fator de esticamento que <span class="math inline">\(A\)</span> pode impor sobre <strong>qualquer</strong> vetor. Isso tem uma resposta exata em termos da SVD:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema (MathML, tradução nossa, Teo. 4.24, p.&nbsp;131)
</div>
</div>
<div class="callout-body-container callout-body">
<p>A norma espectral de <span class="math inline">\(A\)</span> é seu maior valor singular: <span class="math inline">\(\|A\|_2=
\sigma_1\)</span>. <em>(O MathML deixa a prova como exercício — a demonstração abaixo é nossa, reciclando a base ortonormal de autovetores de <span class="math inline">\(A^TA\)</span> do Passo 1.)</em></p>
</div>
</div>
<p><strong>Prova.</strong> Para <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>, <span class="math inline">\(\|A\mathbf{x}\|_2^2=
\mathbf{x}^T(A^TA)\mathbf{x}\)</span>. Como <span class="math inline">\(\{\mathbf{v}_1,\dots,\mathbf{v}_n\}\)</span> é uma base ortonormal de autovetores de <span class="math inline">\(A^TA\)</span> (Passo 1), escreva <span class="math inline">\(\mathbf{x}\)</span> nessa base, <span class="math inline">\(\mathbf{x}=\sum_{i=1}^n c_i\mathbf{v}_i\)</span> com <span class="math inline">\(c_i=\langle\mathbf{x},\mathbf{v}_i\rangle\)</span>. Ortonormalidade dá <span class="math inline">\(\mathbf{x}^T\mathbf{x}=\sum_i c_i^2\)</span>, e usando <span class="math inline">\(A^TA\mathbf{v}_i=\lambda_i\mathbf{v}_i\)</span>, <span class="math display">\[
\mathbf{x}^T(A^TA)\mathbf{x} = \mathbf{x}^T\Big(\sum_i \lambda_i c_i
\mathbf{v}_i\Big) = \sum_i \lambda_i c_i \langle\mathbf{x},
\mathbf{v}_i\rangle = \sum_i \lambda_i c_i^2 .
\]</span> <strong>Aqui entra o passo de majoração, explícito, sem pular etapa:</strong> como <span class="math inline">\(\lambda_1\ge\lambda_2\ge\dots\ge\lambda_n\ge 0\)</span> (ordenação do Passo 1), todo <span class="math inline">\(\lambda_i\)</span> satisfaz <span class="math inline">\(\lambda_i\le\lambda_1\)</span>; como cada <span class="math inline">\(c_i^2\ge
0\)</span>, multiplicar uma desigualdade entre os <span class="math inline">\(\lambda_i\)</span> por um número não-negativo preserva o sentido dela, termo a termo: <span class="math display">\[
\sum_i \lambda_i c_i^2 \;\le\; \sum_i \lambda_1 c_i^2 = \lambda_1
\sum_i c_i^2 = \lambda_1\,\mathbf{x}^T\mathbf{x} = \sigma_1^2\,
\mathbf{x}^T\mathbf{x} ,
\]</span> onde a desigualdade veio de <strong>trocar cada <span class="math inline">\(\lambda_i\)</span> pelo maior deles, <span class="math inline">\(\lambda_1\)</span></strong> — a majoração não é uma afirmação solta, é essa troca termo a termo, válida porque nenhum coeficiente <span class="math inline">\(c_i^2\)</span> é negativo. Logo <span class="math display">\[
\frac{\|A\mathbf{x}\|_2^2}{\|\mathbf{x}\|_2^2} =
\frac{\sum_i\lambda_i c_i^2}{\sum_i c_i^2} \le \sigma_1^2 \quad
\text{para todo } \mathbf{x}\ne\mathbf{0} .
\]</span> A igualdade ocorre exatamente quando só o coeficiente <span class="math inline">\(c_1\)</span> é não-nulo (todo termo com <span class="math inline">\(\lambda_i&lt;\lambda_1\)</span> e <span class="math inline">\(c_i\ne 0\)</span> tornaria a desigualdade estrita) — em particular em <span class="math inline">\(\mathbf{x}=\mathbf{v}_1\)</span> (<span class="math inline">\(c_1=1\)</span>, demais <span class="math inline">\(c_i=0\)</span>), onde <span class="math inline">\(\|A\mathbf{v}_1\|_2^2/\|\mathbf{v}_1\|_2^2=\lambda_1=\sigma_1^2\)</span>. Tomando a raiz quadrada de ambos os lados (ambos não-negativos), <span class="math inline">\(\|A\mathbf{x}\|_2/\|\mathbf{x}\|_2\le\sigma_1\)</span>, com igualdade atingida em <span class="math inline">\(\mathbf{x}=\mathbf{v}_1\)</span>. Logo <span class="math inline">\(\max_{\mathbf{x}\ne\mathbf{0}}\|A\mathbf{x}\|_2/\|\mathbf{x}\|_2=
\sigma_1\)</span>. <span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="o-teorema-de-eckart-young-mirsky" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="o-teorema-de-eckart-young-mirsky"><span class="header-section-number">5.3</span> O Teorema de Eckart-Young-Mirsky</h2>
<p>Agora podemos enunciar, com precisão, o que significa <span class="math inline">\(\hat{A}^{(k)}\)</span> ser a “melhor” aproximação de posto <span class="math inline">\(k\)</span>:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema (Eckart-Young-Mirsky — MathML, tradução nossa, Teo. 4.25, p.&nbsp;131)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Considere <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span> de posto <span class="math inline">\(r\)</span>, e seja <span class="math inline">\(B\in\mathbb{R}^{m\times n}\)</span> uma matriz qualquer de posto <span class="math inline">\(k\)</span>. Para qualquer <span class="math inline">\(k\le r\)</span>, com <span class="math inline">\(\hat{A}^{(k)}=\sum_{i=1}^k\sigma_i
\mathbf{u}_i\mathbf{v}_i^T\)</span>, vale <span class="math display">\[
\hat{A}^{(k)} = \operatorname*{argmin}_{\text{posto}(B)=k}\|A-B\|_2 ,
\qquad \|A-\hat{A}^{(k)}\|_2 = \sigma_{k+1} .
\]</span></p>
</div>
</div>
<p>Ou seja: <strong>entre todas</strong> as matrizes de posto no máximo <span class="math inline">\(k\)</span> (não só entre as que vêm de truncar a SVD), a aproximação <span class="math inline">\(\hat{A}^{(k)}\)</span> construída pela SVD é a que fica mais próxima de <span class="math inline">\(A\)</span> — e o erro dessa melhor aproximação possível é, exatamente, o primeiro valor singular descartado, <span class="math inline">\(\sigma_{k+1}\)</span>. Isso responde, de forma completa, à pergunta “quanto se perde ao aproximar por um posto menor”: a resposta não depende de qual método de aproximação foi usado, é uma propriedade intrínseca de <span class="math inline">\(A\)</span>.</p>
<p><strong>Prova (tradução e reorganização nossa da prova do MathML, mesma seção).</strong> A afirmação <span class="math inline">\(\hat{A}^{(k)}=\operatorname{argmin}\)</span> tem duas metades <strong>independentes</strong>, e provamos as duas em sequência: (i) <span class="math inline">\(\hat{A}^{(k)}\)</span> de fato atinge erro <span class="math inline">\(\sigma_{k+1}\)</span>; (ii) nenhuma outra matriz de posto <span class="math inline">\(k\)</span> faz melhor que isso. A parte (i) é curta; a parte (ii) é onde mora o argumento de verdade — vale ir com calma.</p>
<section id="parte-i-o-erro-de-hatak-é-exatamente-sigma_k1" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="parte-i-o-erro-de-hatak-é-exatamente-sigma_k1"><span class="header-section-number">5.3.1</span> Parte (i): o erro de <span class="math inline">\(\hat{A}^{(k)}\)</span> é exatamente <span class="math inline">\(\sigma_{k+1}\)</span></h3>
<p><strong>Passo 1 — calcular a diferença.</strong> Por construção (<span class="math inline">\(\hat{A}^{(k)}=\sum_{i=1}^k\sigma_i\mathbf{u}_i\mathbf{v}_i^T\)</span> e <span class="math inline">\(A=\sum_{i=1}^r\sigma_i\mathbf{u}_i\mathbf{v}_i^T\)</span>, Bloco 4), subtraindo termo a termo: <span class="math display">\[
A-\hat{A}^{(k)} = \sum_{i=k+1}^r \sigma_i\mathbf{u}_i\mathbf{v}_i^T .
\]</span></p>
<p><strong>Passo 2 — reconhecer essa diferença como a SVD de uma nova matriz.</strong> Chame <span class="math inline">\(E:=A-\hat{A}^{(k)}\)</span>. A soma acima já tem a forma exata de uma decomposição em valores singulares: os <span class="math inline">\(\mathbf{u}_i\)</span> envolvidos são ortonormais entre si (herdados de <span class="math inline">\(U\)</span>, Passo 2, Bloco 3), os <span class="math inline">\(\mathbf{v}_i\)</span> também (herdados de <span class="math inline">\(V\)</span>, Passo 1, Bloco 3), e os coeficientes vêm em ordem decrescente, <span class="math inline">\(\sigma_{k+1}\ge\sigma_{k+2}\ge\dots\ge\sigma_r&gt;0\)</span>. Ou seja, <span class="math inline">\(E\)</span> tem sua <strong>própria</strong> SVD, e o maior valor singular dessa SVD — o primeiro da lista — é <span class="math inline">\(\sigma_{k+1}\)</span>.</p>
<p><strong>Passo 3 — aplicar o Teorema 4.24.</strong> A seção anterior provou que, para <strong>qualquer</strong> matriz <span class="math inline">\(M\)</span>, <span class="math inline">\(\|M\|_2\)</span> é o maior valor singular de <span class="math inline">\(M\)</span>. Aplicando isso a <span class="math inline">\(M=E=A-\hat{A}^{(k)}\)</span>: <span class="math display">\[
\|A-\hat{A}^{(k)}\|_2 = \|E\|_2 = \sigma_{k+1} .
\]</span> É exatamente aqui que o fato geral da seção anterior faz o trabalho prometido — não o aplicamos a <span class="math inline">\(A\)</span>, aplicamos à matriz <strong>erro</strong>.</p>
</section>
<section id="parte-ii-nenhuma-matriz-de-posto-k-faz-melhor" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="parte-ii-nenhuma-matriz-de-posto-k-faz-melhor"><span class="header-section-number">5.3.2</span> Parte (ii): nenhuma matriz de posto <span class="math inline">\(k\)</span> faz melhor</h3>
<p>A estratégia é por contradição: supor que existe uma matriz melhor e chegar a um absurdo.</p>
<p><strong>Passo 1 — a hipótese de contradição.</strong> Suponha que existisse <span class="math inline">\(B\in\mathbb{R}^{m\times n}\)</span> com <span class="math inline">\(\text{posto}(B)\le k\)</span> e <span class="math inline">\(\|A-B\|_2&lt;\sigma_{k+1}\)</span> — ou seja, estritamente melhor que <span class="math inline">\(\hat{A}^{(k)}\)</span>.</p>
<p><strong>Passo 2 — o núcleo de <span class="math inline">\(B\)</span> é “grande”.</strong> Pelo <strong>Teorema do Núcleo e da Imagem</strong> (resultado padrão de álgebra linear, citado aqui sem prova), <span class="math inline">\(\dim(\ker B)+\text{posto}(B)=n\)</span> para <span class="math inline">\(B:\mathbb{R}^n\to\mathbb{R}^m\)</span>. Como <span class="math inline">\(\text{posto}(B)\le k\)</span>, segue <span class="math inline">\(\dim(\ker B)\ge n-k\)</span>. Chame <span class="math inline">\(Z:=\ker(B)\)</span>.</p>
<p><strong>Passo 3 — em <span class="math inline">\(Z\)</span>, <span class="math inline">\(A\)</span> e <span class="math inline">\(A-B\)</span> agem igual.</strong> Para <span class="math inline">\(\mathbf{x}\in Z\)</span>, por definição <span class="math inline">\(B\mathbf{x}=\mathbf{0}\)</span>, logo <span class="math inline">\(A\mathbf{x}=A\mathbf{x}-B\mathbf{x}=(A-B)\mathbf{x}\)</span>. Usando a definição de norma espectral (<span class="math inline">\(\|(A-B)\mathbf{x}\|_2\le
\|A-B\|_2\|\mathbf{x}\|_2\)</span>) e a hipótese de contradição do Passo 1, <span class="math display">\[
\|A\mathbf{x}\|_2 = \|(A-B)\mathbf{x}\|_2 \le \|A-B\|_2\,
\|\mathbf{x}\|_2 &lt; \sigma_{k+1}\|\mathbf{x}\|_2, \qquad \text{para
todo } \mathbf{x}\in Z .
\]</span></p>
<p><strong>Passo 4 — um subespaço onde <span class="math inline">\(A\)</span> nunca encolhe abaixo de <span class="math inline">\(\sigma_{k+1}\)</span>.</strong> Considere <span class="math inline">\(W:=\text{span}(\mathbf{v}_1,\dots,
\mathbf{v}_{k+1})\)</span>, de dimensão <span class="math inline">\(k+1\)</span>. Afirmamos, e desta vez <strong>provamos</strong> (não só citamos), que <span class="math inline">\(\|A\mathbf{x}\|_2\ge
\sigma_{k+1}\|\mathbf{x}\|_2\)</span> para todo <span class="math inline">\(\mathbf{x}\in W\)</span>. Escreva <span class="math inline">\(\mathbf{x}=\sum_{i=1}^{k+1}c_i\mathbf{v}_i\in W\)</span>. Como <span class="math inline">\(A\mathbf{v}_i=\sigma_i\mathbf{u}_i\)</span> (equação de valor singular, Passo 3) e os <span class="math inline">\(\mathbf{u}_i\)</span> são ortonormais, <span class="math display">\[
A\mathbf{x} = \sum_{i=1}^{k+1}c_i\sigma_i\mathbf{u}_i
\quad\Longrightarrow\quad
\|A\mathbf{x}\|_2^2 = \sum_{i=1}^{k+1}c_i^2\sigma_i^2 .
\]</span> Como <span class="math inline">\(\sigma_1\ge\dots\ge\sigma_{k+1}\)</span> (ordem decrescente), vale <span class="math inline">\(\sigma_i\ge\sigma_{k+1}\)</span> para todo <span class="math inline">\(i\le k+1\)</span>, logo <span class="math display">\[
\|A\mathbf{x}\|_2^2 = \sum_{i=1}^{k+1}c_i^2\sigma_i^2 \ge
\sigma_{k+1}^2\sum_{i=1}^{k+1}c_i^2 = \sigma_{k+1}^2\|\mathbf{x}\|_2^2 ,
\]</span> onde a última igualdade usa que <span class="math inline">\(\mathbf{v}_1,\dots,\mathbf{v}_{k+1}\)</span> são ortonormais (Passo 1, Bloco 3), logo <span class="math inline">\(\|\mathbf{x}\|_2^2=\sum_i c_i^2\)</span>. Tomando raiz quadrada dos dois lados, <span class="math inline">\(\|A\mathbf{x}\|_2\ge\sigma_{k+1}\|\mathbf{x}\|_2\)</span> para todo <span class="math inline">\(\mathbf{x}\in W\)</span>, como prometido.</p>
<p><strong>Passo 5 — <span class="math inline">\(Z\)</span> e <span class="math inline">\(W\)</span> têm que se cruzar.</strong> <span class="math inline">\(\dim(Z)+\dim(W)\ge(n-k)+(k+1)=n+1\)</span>, que é maior que <span class="math inline">\(n=\dim(\mathbb{R}^n)\)</span>. Pela fórmula de dimensão da soma de subespaços, <span class="math inline">\(\dim(Z\cap W)\ge\dim(Z)+\dim(W)-n\ge 1&gt;0\)</span> — a interseção contém algum vetor <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>.</p>
<p><strong>Passo 6 — a contradição.</strong> Esse <span class="math inline">\(\mathbf{x}\)</span> está em <span class="math inline">\(Z\)</span> e em <span class="math inline">\(W\)</span> ao mesmo tempo, então satisfaz as duas desigualdades dos Passos 3 e 4 simultaneamente: <span class="math display">\[
\|A\mathbf{x}\|_2 &lt; \sigma_{k+1}\|\mathbf{x}\|_2 \qquad\text{e}\qquad
\|A\mathbf{x}\|_2 \ge \sigma_{k+1}\|\mathbf{x}\|_2 .
\]</span> Como <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>, <span class="math inline">\(\|\mathbf{x}\|_2&gt;0\)</span>, e as duas desigualdades não podem valer ao mesmo tempo para o mesmo número <span class="math inline">\(\|A\mathbf{x}\|_2\)</span> — um absurdo. Logo a hipótese de contradição do Passo 1 é falsa: nenhum <span class="math inline">\(B\)</span> de posto <span class="math inline">\(\le k\)</span> pode ter <span class="math inline">\(\|A-B\|_2&lt;\sigma_{k+1}\)</span>, e <span class="math inline">\(\hat{A}^{(k)}\)</span> é de fato ótima. <span class="math inline">\(\blacksquare\)</span></p>
</section>
</section>
<section id="aplicando-a-x-quanto-se-perde-ao-truncar" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="aplicando-a-x-quanto-se-perde-ao-truncar"><span class="header-section-number">5.4</span> Aplicando a <span class="math inline">\(X\)</span>: Quanto Se Perde ao Truncar</h2>
<p>Vamos verificar a garantia do Teorema de Eckart-Young-Mirsky numericamente, aplicando a aproximação de posto-<span class="math inline">\(k\)</span> à matriz de design <span class="math inline">\(X\)</span> do <em>California Housing</em> para <span class="math inline">\(k=1,2,3\)</span> (lembrando: <span class="math inline">\(\text{posto}(X)
=4\)</span>, então <span class="math inline">\(k=4\)</span> recupera <span class="math inline">\(X\)</span> exatamente).</p>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<div id="e82147fb" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>  k    ||X - X_k||_2    sigma_{k+1}    erro relativo (Frobenius)
  1       523.440811     523.440811                     13.5401%
  2       229.490812     229.490812                      5.4690%
  3        27.335935      27.335935                      0.6469%</code></pre>
</div>
</div>
</div>
<p>Para <span class="math inline">\(k=1,2,3\)</span>, o erro <span class="math inline">\(\|X-\hat{X}^{(k)}\|_2\)</span> bate, até a sexta casa decimal, com <span class="math inline">\(\sigma_{k+1}\)</span> — confirmação numérica direta do Teorema 4.25. O erro relativo em norma de Frobenius (uma medida “de energia total”, diferente da norma espectral, mas relacionada) cai de <span class="math inline">\(\approx 13{,}5\%\)</span> (<span class="math inline">\(k=1\)</span>) para <span class="math inline">\(\approx 0{,}6\%\)</span> (<span class="math inline">\(k=3\)</span>) — mesmo descartando <span class="math inline">\(3\)</span> de <span class="math inline">\(4\)</span> direções na primeira aproximação, mais de <span class="math inline">\(86\%\)</span> da “energia” de <span class="math inline">\(X\)</span> já está capturada, porque o primeiro valor singular (<span class="math inline">\(\approx 4\,187\)</span>) domina amplamente os demais.</p>
</section>
<section id="retomando-o-problema-motivador-filtragem-colaborativa" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="retomando-o-problema-motivador-filtragem-colaborativa"><span class="header-section-number">5.5</span> Retomando o Problema Motivador: Filtragem Colaborativa</h2>
<p>Voltando à matriz de notas de filmes do Problema Motivador — a aplicação de baixo posto revela exatamente a estrutura que suspeitávamos existir (tradução livre de MathML, Exemplo 4.15, retomando o Exemplo 4.14). A interpretação (MathML, §4.5.1): os vetores singulares à esquerda <span class="math inline">\(\mathbf{u}_i\)</span> podem ser lidos como <strong>“filmes estereotípicos”</strong> (perfis de tema), e os vetores singulares à direita <span class="math inline">\(\mathbf{v}_i\)</span> como <strong>“espectadores estereotípicos”</strong> (perfis de gosto) — sob a suposição de que cada espectador avalia filmes como combinação linear desses perfis, e cada filme pertence a uma combinação linear desses temas.</p>
<div class="fig-resize" style="width: 50%; margin: 0 auto;">
<div id="66afc346" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-9-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>valores singulares: sigma = [9.6438 6.3639 0.7056]
erro espectral k=1: 6.3639 (sigma_2 = 6.3639)
erro espectral k=2: 0.7056 (sigma_3 = 0.7056)</code></pre>
</div>
</div>
</div>
<p>A aproximação de posto <span class="math inline">\(1\)</span> (usando só <span class="math inline">\(\sigma_1\mathbf{u}_1
\mathbf{v}_1^T\)</span>) captura bem as notas de Ali e Beatrix para os filmes de ficção científica (valores <span class="math inline">\(&gt;4\)</span>, próximos do original), mas erra feio nas notas de Chandra para Amélie Poulain e Delicatessen (previstos <span class="math inline">\(\approx 0{,}16\)</span>–<span class="math inline">\(0{,}26\)</span>, contra as notas reais <span class="math inline">\(4\)</span> e <span class="math inline">\(5\)</span>) — o primeiro perfil, sozinho, só “entende” espectadores de ficção científica. A aproximação de posto <span class="math inline">\(2\)</span> (somando o segundo termo, <span class="math inline">\(\sigma_2\mathbf{u}_2\mathbf{v}_2^T\)</span>) já recupera a matriz quase inteira, incluindo o perfil de Chandra. Isso é exatamente o que o Teorema de Eckart-Young-Mirsky quantifica: o erro em norma espectral cai de <span class="math inline">\(\sigma_2\approx 6{,}364\)</span> (posto 1) para <span class="math inline">\(\sigma_3\approx
0{,}706\)</span> (posto 2) — e, como <span class="math inline">\(\text{posto}(A)=3\)</span>, a aproximação de posto <span class="math inline">\(3\)</span> recuperaria <span class="math inline">\(A\)</span> exatamente.</p>
<p>Essa é, em essência, a matemática por trás de <strong>sistemas de recomendação por filtragem colaborativa</strong>: em vez de uma matriz completa de <span class="math inline">\(3\times 4\)</span> notas (aqui, artificialmente pequena e sem valores faltantes), sistemas reais lidam com matrizes de milhões de usuários por milhões de itens, majoritariamente <strong>vazias</strong> (a maioria dos usuários nunca avaliou a maioria dos itens) — mas a mesma ideia de aproximação de baixo posto (adaptada para lidar com entradas faltantes, o que foge do escopo desta aula) é a base de métodos clássicos de <strong>completamento de matrizes</strong> para prever as notas que faltam a partir da estrutura de baixo posto capturada pelos poucos perfis latentes mais importantes.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(A\)</span> tivesse posto <span class="math inline">\(3\)</span> mas só déssemos ao sistema de recomendação os dois primeiros perfis latentes, o que aconteceria com um quarto espectador de um perfil totalmente novo?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que <span class="math inline">\(\hat{A}^{(2)}\)</span> pode e não pode representar, dada sua própria definição.</p>
<ul>
<li>□ Um quarto espectador com um perfil de gosto genuinamente novo (não combinação linear dos dois perfis já capturados) teria suas notas mal previstas por <span class="math inline">\(\hat{A}^{(2)}\)</span>, mesmo que o sistema tivesse dados históricos abundantes desse espectador.</li>
<li>□ Aumentar <span class="math inline">\(k\)</span> de <span class="math inline">\(2\)</span> para <span class="math inline">\(3\)</span> (o posto completo de <span class="math inline">\(A\)</span>) sempre reduz o erro de aproximação em norma espectral, mas nunca pode aumentá-lo.</li>
<li>□ Numa matriz de embeddings de documentos de texto (linhas = documentos, colunas = termos), a mesma lógica de perfis latentes se aplicaria: um documento sobre um assunto totalmente não-representado nos primeiros <span class="math inline">\(k\)</span> tópicos latentes teria sua representação de baixo-posto empobrecida.</li>
<li>□ Como a aproximação de posto-<span class="math inline">\(k\)</span> é a <strong>melhor possível</strong> entre todas as matrizes de posto <span class="math inline">\(k\)</span> (Eckart-Young-Mirsky), isso implica que o erro de aproximação <span class="math inline">\(\sigma_{k+1}\)</span> pode ser reduzido escolhendo um método de aproximação diferente da SVD, para o mesmo <span class="math inline">\(k\)</span>.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="decomposição-polar" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Decomposição Polar</h1>
<hr>
<section id="rearranjando-os-três-fatores-da-svd" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="rearranjando-os-três-fatores-da-svd"><span class="header-section-number">6.1</span> Rearranjando os Três Fatores da SVD</h2>
<p>Nenhuma das três fontes desta disciplina traz uma seção dedicada à Decomposição Polar — o que segue é uma construção <strong>nossa</strong>, a partir do Teorema 4.22 já demonstrado no Bloco 3 (não uma tradução de trecho algum). Diferente da SVD, que existe para matriz retangular qualquer, a Decomposição Polar como construída aqui exige <span class="math inline">\(A\)</span> <strong>quadrada</strong> (<span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span>) — é essa restrição de dimensão que permite multiplicar os dois fatores finais na ordem certa, como o argumento abaixo deixa explícito.</p>
<p>Seja <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> com SVD completa <span class="math inline">\(A=U\Sigma V^T\)</span> (<span class="math inline">\(U,V\in\mathbb{R}^{n\times n}\)</span> ambas ortogonais, <span class="math inline">\(\Sigma\in
\mathbb{R}^{n\times n}\)</span> diagonal com entradas <span class="math inline">\(\ge 0\)</span>). Insira a matriz identidade <span class="math inline">\(I=V^TV\)</span> entre <span class="math inline">\(U\)</span> e <span class="math inline">\(\Sigma\)</span>: <span class="math display">\[
A = U\Sigma V^T = (UV^T)(V\Sigma V^T) =: QS ,
\]</span> definindo <span class="math display">\[
Q := UV^T \in\mathbb{R}^{n\times n}, \qquad
S := V\Sigma V^T \in\mathbb{R}^{n\times n} .
\]</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Proposição (Decomposição Polar — construção nossa a partir do Teorema 4.22)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span>, com <span class="math inline">\(Q:=UV^T\)</span> e <span class="math inline">\(S:=V\Sigma V^T\)</span> definidos a partir da SVD <span class="math inline">\(A=U\Sigma V^T\)</span>: <span class="math inline">\(Q\)</span> é ortogonal, <span class="math inline">\(S\)</span> é simétrica semidefinida positiva, e <span class="math inline">\(A=QS\)</span>.</p>
</div>
</div>
<p><strong>Prova de que <span class="math inline">\(Q\)</span> é ortogonal.</strong> <span class="math inline">\(Q^TQ=(UV^T)^T(UV^T)=VU^TUV^T\)</span>; como <span class="math inline">\(U\)</span> é ortogonal, <span class="math inline">\(U^TU=I\)</span>, logo <span class="math inline">\(Q^TQ=VIV^T=VV^T=I\)</span> (usando, de novo, que <span class="math inline">\(V\)</span> é ortogonal). Como <span class="math inline">\(Q^TQ=I\)</span> com <span class="math inline">\(Q\)</span> quadrada, <span class="math inline">\(Q\)</span> é ortogonal.</p>
<p><strong>Prova de que <span class="math inline">\(S\)</span> é simétrica semidefinida positiva.</strong> <span class="math inline">\(S^T=(V\Sigma
V^T)^T=V\Sigma^TV^T=V\Sigma V^T=S\)</span> (usando que <span class="math inline">\(\Sigma\)</span>, sendo diagonal, satisfaz <span class="math inline">\(\Sigma^T=\Sigma\)</span>) — logo <span class="math inline">\(S\)</span> é simétrica. Para qualquer <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>, definindo <span class="math inline">\(\mathbf{z}:=V^T\mathbf{x}\)</span> (não-nulo, já que <span class="math inline">\(V\)</span> é invertível), <span class="math display">\[
\mathbf{x}^TS\mathbf{x} = \mathbf{x}^TV\Sigma V^T\mathbf{x} =
\mathbf{z}^T\Sigma\mathbf{z} = \sum_{i=1}^n \sigma_i z_i^2 \ge 0 ,
\]</span> já que cada <span class="math inline">\(\sigma_i\ge 0\)</span>. Logo <span class="math inline">\(S\)</span> é semidefinida positiva. <span class="math inline">\(\blacksquare\)</span></p>
<p>Repare que a prova identifica, de graça, os autovalores e autovetores de <span class="math inline">\(S\)</span>: como <span class="math inline">\(S=V\Sigma V^T\)</span> com <span class="math inline">\(V\)</span> ortogonal e <span class="math inline">\(\Sigma\)</span> diagonal, essa <strong>é</strong> a decomposição espectral de <span class="math inline">\(S\)</span> (Aula 4) — os autovalores de <span class="math inline">\(S\)</span> são exatamente os valores singulares de <span class="math inline">\(A\)</span>, e os autovetores de <span class="math inline">\(S\)</span> são exatamente os vetores singulares à direita de <span class="math inline">\(A\)</span>.</p>
</section>
<section id="a-generalização-do-módulo-e-da-fase" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="a-generalização-do-módulo-e-da-fase"><span class="header-section-number">6.2</span> A Generalização do Módulo e da Fase</h2>
<p>A Decomposição Polar leva esse nome por uma analogia direta: assim como todo número complexo <span class="math inline">\(z\ne 0\)</span> se escreve como <span class="math inline">\(z=re^{i\theta}\)</span> — um módulo <span class="math inline">\(r\ge 0\)</span> (quanto “esticar”) vezes uma fase <span class="math inline">\(e^{i\theta}\)</span> (quanto “girar”, sem esticar nem encolher) —, toda matriz quadrada <span class="math inline">\(A\)</span> se escreve como <span class="math inline">\(A=QS\)</span>: uma parte <span class="math inline">\(S\)</span> que só estica/encolhe ao longo de direções ortogonais (nunca gira — <span class="math inline">\(S\)</span> é simétrica, autovetores ortogonais, exatamente o Teorema Espectral da Aula 4), seguida de uma parte <span class="math inline">\(Q\)</span> que só gira/reflete, sem esticar nada (<span class="math inline">\(Q\)</span> ortogonal — preserva norma e ângulo, Aula 1).</p>
<p>Reaproveitando a matriz do Bloco 2, <span class="math inline">\(A=\begin{bmatrix}1{,}4&amp;0{,}6\\
0{,}3&amp;0{,}9\end{bmatrix}\)</span>, o cálculo numérico abaixo mostra os dois fatores explicitamente e a leitura geométrica: primeiro <span class="math inline">\(S\)</span> estica o círculo unitário ao longo de suas próprias direções principais (<span class="math inline">\(\mathbf{v}_1,\mathbf{v}_2\)</span> — as mesmas retas cheias do painel esquerdo do Bloco 2), produzindo uma elipse ainda alinhada com essas direções; depois <span class="math inline">\(Q\)</span> gira essa elipse inteira como corpo rígido, sem distorcer seu formato, até a posição final — que é exatamente a mesma elipse do painel direito do Bloco 2, a imagem de <span class="math inline">\(A\)</span>.</p>
<div class="fig-resize" style="width: 50%; margin: 0 auto;">
<div id="b2478092" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-10-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Q = 
 [[ 0.9916  0.1293]
 [-0.1293  0.9916]]
det(Q) = 1.0 (1 = rotação pura, -1 = reflexão)
S =
 [[1.3494 0.4786]
 [0.4786 0.97  ]]
autovalores de S (= valores singulares de A): [0.645  1.6745]
Q @ S == A? True</code></pre>
</div>
</div>
</div>
<p>Os números confirmam a proposição: <span class="math inline">\(\det(Q)\approx 1\)</span> (rotação pura, sem reflexão) por um ângulo de <span class="math inline">\(\approx 7{,}4°\)</span>; os autovalores de <span class="math inline">\(S\)</span> são <span class="math inline">\([0{,}645;\ 1{,}675]\)</span> — exatamente os valores singulares de <span class="math inline">\(A\)</span> já calculados no Bloco 2 (<span class="math inline">\(\sigma_1\approx 1{,}675\)</span>, <span class="math inline">\(\sigma_2\approx
0{,}645\)</span>); e <span class="math inline">\(QS=A\)</span> até erro de ponto flutuante. O painel do meio mostra <span class="math inline">\(S\)</span> agindo sozinha — uma elipse já com o formato final, mas <strong>ainda alinhada</strong> com <span class="math inline">\(\mathbf{v}_1,\mathbf{v}_2\)</span> (não com os eixos do codomínio); o painel da direita mostra <span class="math inline">\(Q\)</span> girando essa elipse, como um corpo rígido, até a posição final — idêntica à elipse do Bloco 2.</p>
<p><strong>Ponte, sem desenvolver:</strong> a Decomposição Polar reaparece, mais adiante neste curso (Aula 14, Preconditioning Estruturado — Shampoo e Muon), como o objetivo de um algoritmo iterativo (a <strong>iteração de Newton-Schulz</strong>) usado para <em>ortogonalizar</em> matrizes de atualização de pesos de redes neurais em tempo real, sem calcular a SVD completa (cara demais para ser recalculada a cada passo de treino) — extraindo, efetivamente, só o fator <span class="math inline">\(Q\)</span> da Decomposição Polar de cada matriz de atualização.</p>
</section>
</section>
<section id="fechamento-e-ponte-para-a-aula-6" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Fechamento e Ponte para a Aula 6</h1>
<hr>
<section id="retomando-as-perguntas-de-abertura" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</h3>
<ol type="1">
<li><strong>O que é a SVD e por que existe para qualquer matriz retangular?</strong> <span class="math inline">\(A=U\Sigma V^T\)</span>, com <span class="math inline">\(U,V\)</span> ortogonais e <span class="math inline">\(\Sigma\)</span> diagonal com entradas não-negativas; existe sempre porque <span class="math inline">\(A^TA\)</span> é sempre simétrica semidefinida positiva (Aula 4), o que garante autovalores reais não-negativos e, portanto, raízes quadradas reais bem definidas para os valores singulares.</li>
<li><strong>Como construir a SVD a partir do Teorema Espectral?</strong> Os autovetores de <span class="math inline">\(A^TA\)</span> são os vetores singulares à direita (<span class="math inline">\(V\)</span>); suas imagens sob <span class="math inline">\(A\)</span>, normalizadas pelo próprio comprimento (que é a raiz do autovalor correspondente), são os vetores singulares à esquerda (<span class="math inline">\(U\)</span>) — a ortogonalidade de ambos os conjuntos vem diretamente da relação de autovalor de <span class="math inline">\(A^TA\)</span>.</li>
<li><strong>Como aproximar por posto menor de forma ótima?</strong> Truncando a soma <span class="math inline">\(A=\sum\sigma_i\mathbf{u}_i\mathbf{v}_i^T\)</span> nos <span class="math inline">\(k\)</span> primeiros termos; o Teorema de Eckart-Young-Mirsky garante que essa é a melhor aproximação possível entre <strong>todas</strong> as matrizes de posto <span class="math inline">\(k\)</span>, com erro exato <span class="math inline">\(\sigma_{k+1}\)</span>.</li>
<li><strong>O que é a Decomposição Polar?</strong> Rearranjar os três fatores da SVD (<span class="math inline">\(A=U\Sigma V^T=(UV^T)(V\Sigma V^T)=QS\)</span>) separa <span class="math inline">\(A\)</span> (quadrada) em uma parte que só gira/reflete (<span class="math inline">\(Q\)</span>, ortogonal) e uma parte que só estica/encolhe ao longo de direções ortogonais (<span class="math inline">\(S\)</span>, simétrica semidefinida positiva) — a generalização matricial do módulo e da fase de um número complexo.</li>
</ol>
</section>
<section id="o-que-fica-em-aberto" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="o-que-fica-em-aberto">O Que Fica em Aberto</h3>
<p>A SVD decompõe uma matriz <strong>estática</strong> — ela não diz nada sobre como encontrar os parâmetros de um modelo de aprendizado de máquina que minimizam uma função de perda. E, de fato, olhando para trás: a própria derivação das Equações Normais na Aula 3 (<span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span>) já usou implicitamente a ideia de “encontrar o ponto onde a perda para de diminuir” — mas em nenhum momento este curso definiu formalmente o que significa “a perda parar de diminuir” para uma função de várias variáveis. Esse é exatamente o objeto que abre a Parte 2 do curso, “Cálculo da Otimização Diferenciável”: a <strong>derivada em várias variáveis</strong> — o gradiente e o Jacobiano —, tema da Aula 6.</p>
<p><a href="../../../teaching/optimization-linear-algebra/aula05/exercicios.html" class="see-all exercicios-link">Exercícios</a> <a href="../../../teaching/optimization-linear-algebra/aula05/soluções.html" class="see-all solucoes-link">Soluções</a></p>
<div class="fig-resize" style="width: 78%; margin: 0 auto;">
<img src="index_files/mediabag/96126db16b6ec146950b3250c8f59aa7f07070ec.svg" class="img-fluid">
</div>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>