<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Marcos Medeiros Raimundo">

<title>Aula 4: Autovalores, Autovetores e Matrizes Simétricas – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-f6f65eecdb8abf3e35b2d2c28dbef9f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#revisão-e-introdução" id="toc-revisão-e-introdução" class="nav-link active" data-scroll-target="#revisão-e-introdução"><span class="header-section-number">1</span> Revisão e Introdução</a>
  <ul class="collapse">
  <li><a href="#revisão-rápida-onde-a-aula-3-parou" id="toc-revisão-rápida-onde-a-aula-3-parou" class="nav-link" data-scroll-target="#revisão-rápida-onde-a-aula-3-parou"><span class="header-section-number">1.1</span> Revisão Rápida: Onde a Aula 3 Parou</a></li>
  <li><a href="#organizador-prévio-de-perturbar-os-dados-para-olhar-direto-para-dentro-de-xtx" id="toc-organizador-prévio-de-perturbar-os-dados-para-olhar-direto-para-dentro-de-xtx" class="nav-link" data-scroll-target="#organizador-prévio-de-perturbar-os-dados-para-olhar-direto-para-dentro-de-xtx"><span class="header-section-number">1.2</span> Organizador Prévio: De Perturbar os Dados Para Olhar Direto Para Dentro de <span class="math inline">\(X^TX\)</span></a></li>
  <li><a href="#roteiro-da-aula" id="toc-roteiro-da-aula" class="nav-link" data-scroll-target="#roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</a></li>
  <li><a href="#problema-motivador" id="toc-problema-motivador" class="nav-link" data-scroll-target="#problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</a></li>
  </ul></li>
  <li><a href="#intuição-autovetores" id="toc-intuição-autovetores" class="nav-link" data-scroll-target="#intuição-autovetores"><span class="header-section-number">2</span> Intuição – Autovetores</a>
  <ul class="collapse">
  <li><a href="#uma-matriz-agindo-sobre-um-conjunto-de-direções" id="toc-uma-matriz-agindo-sobre-um-conjunto-de-direções" class="nav-link" data-scroll-target="#uma-matriz-agindo-sobre-um-conjunto-de-direções"><span class="header-section-number">2.1</span> Uma Matriz Agindo sobre um Conjunto de Direções</a></li>
  <li><a href="#a-equação-formal" id="toc-a-equação-formal" class="nav-link" data-scroll-target="#a-equação-formal"><span class="header-section-number">2.2</span> A Equação Formal</a></li>
  </ul></li>
  <li><a href="#o-polinômio-característico" id="toc-o-polinômio-característico" class="nav-link" data-scroll-target="#o-polinômio-característico"><span class="header-section-number">3</span> O Polinômio Característico</a>
  <ul class="collapse">
  <li><a href="#premissas-o-que-precisamos-resolver" id="toc-premissas-o-que-precisamos-resolver" class="nav-link" data-scroll-target="#premissas-o-que-precisamos-resolver"><span class="header-section-number">3.1</span> Premissas: O Que Precisamos Resolver</a></li>
  <li><a href="#passo-i-reescrevendo-a-equação-de-autovalor-como-um-sistema-homogêneo" id="toc-passo-i-reescrevendo-a-equação-de-autovalor-como-um-sistema-homogêneo" class="nav-link" data-scroll-target="#passo-i-reescrevendo-a-equação-de-autovalor-como-um-sistema-homogêneo"><span class="header-section-number">3.2</span> Passo (i): Reescrevendo a Equação de Autovalor Como um Sistema Homogêneo</a></li>
  <li><a href="#o-polinômio-característico-1" id="toc-o-polinômio-característico-1" class="nav-link" data-scroll-target="#o-polinômio-característico-1"><span class="header-section-number">3.3</span> O Polinômio Característico</a></li>
  <li><a href="#passo-ii-aplicando-ao-exemplo-do-bloco-2-o-polinômio" id="toc-passo-ii-aplicando-ao-exemplo-do-bloco-2-o-polinômio" class="nav-link" data-scroll-target="#passo-ii-aplicando-ao-exemplo-do-bloco-2-o-polinômio"><span class="header-section-number">3.4</span> Passo (ii): Aplicando ao Exemplo do Bloco 2 — o Polinômio</a></li>
  <li><a href="#passo-iii-de-volta-à-equação-original-achando-os-autovetores" id="toc-passo-iii-de-volta-à-equação-original-achando-os-autovetores" class="nav-link" data-scroll-target="#passo-iii-de-volta-à-equação-original-achando-os-autovetores"><span class="header-section-number">3.5</span> Passo (iii): De Volta à Equação Original — Achando os Autovetores</a></li>
  <li><a href="#verificação-numérica-numpy.linalg.eig" id="toc-verificação-numérica-numpy.linalg.eig" class="nav-link" data-scroll-target="#verificação-numérica-numpy.linalg.eig"><span class="header-section-number">3.6</span> Verificação Numérica: <code>numpy.linalg.eig</code></a></li>
  </ul></li>
  <li><a href="#o-teorema-espectral-real-para-matrizes-simétricas" id="toc-o-teorema-espectral-real-para-matrizes-simétricas" class="nav-link" data-scroll-target="#o-teorema-espectral-real-para-matrizes-simétricas"><span class="header-section-number">4</span> O Teorema Espectral Real para Matrizes Simétricas</a>
  <ul class="collapse">
  <li><a href="#por-que-isso-importa-para-xtx" id="toc-por-que-isso-importa-para-xtx" class="nav-link" data-scroll-target="#por-que-isso-importa-para-xtx"><span class="header-section-number">4.1</span> Por Que Isso Importa Para <span class="math inline">\(X^TX\)</span></a></li>
  <li><a href="#definição-matrizes-definidas-e-semidefinidas-positivas" id="toc-definição-matrizes-definidas-e-semidefinidas-positivas" class="nav-link" data-scroll-target="#definição-matrizes-definidas-e-semidefinidas-positivas"><span class="header-section-number">4.2</span> Definição: Matrizes Definidas e Semidefinidas Positivas</a></li>
  <li><a href="#teorema-ata-é-simétrica-e-semidefinida-positiva" id="toc-teorema-ata-é-simétrica-e-semidefinida-positiva" class="nav-link" data-scroll-target="#teorema-ata-é-simétrica-e-semidefinida-positiva"><span class="header-section-number">4.3</span> Teorema: <span class="math inline">\(A^TA\)</span> é Simétrica e Semidefinida Positiva</a></li>
  <li><a href="#premissas-e-prova-autovetores-de-autovalores-distintos-são-ortogonais" id="toc-premissas-e-prova-autovetores-de-autovalores-distintos-são-ortogonais" class="nav-link" data-scroll-target="#premissas-e-prova-autovetores-de-autovalores-distintos-são-ortogonais"><span class="header-section-number">4.4</span> Premissas e Prova: Autovetores de Autovalores Distintos São Ortogonais</a></li>
  <li><a href="#o-teorema-espectral-real" id="toc-o-teorema-espectral-real" class="nav-link" data-scroll-target="#o-teorema-espectral-real"><span class="header-section-number">4.5</span> O Teorema Espectral Real</a></li>
  <li><a href="#contraste-direto-exemplo-resolvido-de-uma-matriz-simétrica" id="toc-contraste-direto-exemplo-resolvido-de-uma-matriz-simétrica" class="nav-link" data-scroll-target="#contraste-direto-exemplo-resolvido-de-uma-matriz-simétrica"><span class="header-section-number">4.6</span> Contraste Direto: Exemplo Resolvido de uma Matriz Simétrica</a></li>
  <li><a href="#decomposição-espectral-o-caso-geral-e-o-caso-simétrico" id="toc-decomposição-espectral-o-caso-geral-e-o-caso-simétrico" class="nav-link" data-scroll-target="#decomposição-espectral-o-caso-geral-e-o-caso-simétrico"><span class="header-section-number">4.7</span> Decomposição Espectral: o Caso Geral e o Caso Simétrico</a></li>
  </ul></li>
  <li><a href="#definitude-positiva-o-sinal-dos-autovalores" id="toc-definitude-positiva-o-sinal-dos-autovalores" class="nav-link" data-scroll-target="#definitude-positiva-o-sinal-dos-autovalores"><span class="header-section-number">5</span> Definitude Positiva: o Sinal dos Autovalores</a>
  <ul class="collapse">
  <li><a href="#retomando-a-forma-quadrática-da-aula-1" id="toc-retomando-a-forma-quadrática-da-aula-1" class="nav-link" data-scroll-target="#retomando-a-forma-quadrática-da-aula-1"><span class="header-section-number">5.1</span> Retomando a Forma Quadrática da Aula 1</a></li>
  <li><a href="#a-ponte-definitude-via-o-sinal-dos-autovalores" id="toc-a-ponte-definitude-via-o-sinal-dos-autovalores" class="nav-link" data-scroll-target="#a-ponte-definitude-via-o-sinal-dos-autovalores"><span class="header-section-number">5.2</span> A Ponte: Definitude Via o Sinal dos Autovalores</a></li>
  <li><a href="#intuição-geométrica-o-formato-da-tigela" id="toc-intuição-geométrica-o-formato-da-tigela" class="nav-link" data-scroll-target="#intuição-geométrica-o-formato-da-tigela"><span class="header-section-number">5.3</span> Intuição Geométrica: o Formato da Tigela</a></li>
  <li><a href="#o-quociente-de-rayleigh-isolando-lambda_max-e-lambda_min" id="toc-o-quociente-de-rayleigh-isolando-lambda_max-e-lambda_min" class="nav-link" data-scroll-target="#o-quociente-de-rayleigh-isolando-lambda_max-e-lambda_min"><span class="header-section-number">5.4</span> O Quociente de Rayleigh: Isolando <span class="math inline">\(\lambda_{\max}\)</span> e <span class="math inline">\(\lambda_{\min}\)</span></a></li>
  <li><a href="#o-número-de-condição-agora-exato" id="toc-o-número-de-condição-agora-exato" class="nav-link" data-scroll-target="#o-número-de-condição-agora-exato"><span class="header-section-number">5.5</span> O Número de Condição, Agora Exato</a></li>
  <li><a href="#ponte-breve-sem-aprofundar-hessiana-e-convexidade" id="toc-ponte-breve-sem-aprofundar-hessiana-e-convexidade" class="nav-link" data-scroll-target="#ponte-breve-sem-aprofundar-hessiana-e-convexidade"><span class="header-section-number">5.6</span> Ponte Breve (Sem Aprofundar): Hessiana e Convexidade</a></li>
  </ul></li>
  <li><a href="#aplicação-e-verificação-no-dado-real" id="toc-aplicação-e-verificação-no-dado-real" class="nav-link" data-scroll-target="#aplicação-e-verificação-no-dado-real"><span class="header-section-number">6</span> Aplicação e Verificação no Dado Real</a>
  <ul class="collapse">
  <li><a href="#recalculando-o-número-de-condição-da-aula-3-agora-exato" id="toc-recalculando-o-número-de-condição-da-aula-3-agora-exato" class="nav-link" data-scroll-target="#recalculando-o-número-de-condição-da-aula-3-agora-exato"><span class="header-section-number">6.1</span> Recalculando o Número de Condição da Aula 3 — Agora Exato</a></li>
  <li><a href="#uma-segunda-matriz-simétrica-psd-a-covariância-empírica" id="toc-uma-segunda-matriz-simétrica-psd-a-covariância-empírica" class="nav-link" data-scroll-target="#uma-segunda-matriz-simétrica-psd-a-covariância-empírica"><span class="header-section-number">6.2</span> Uma Segunda Matriz Simétrica PSD: a Covariância Empírica</a></li>
  <li><a href="#interpretando-o-autovetor-principal-sobre-os-dados-reais" id="toc-interpretando-o-autovetor-principal-sobre-os-dados-reais" class="nav-link" data-scroll-target="#interpretando-o-autovetor-principal-sobre-os-dados-reais"><span class="header-section-number">6.3</span> Interpretando o Autovetor Principal sobre os Dados Reais</a></li>
  <li><a href="#semente-para-pca-sem-aprofundar-e-um-aviso-honesto-sobre-escala" id="toc-semente-para-pca-sem-aprofundar-e-um-aviso-honesto-sobre-escala" class="nav-link" data-scroll-target="#semente-para-pca-sem-aprofundar-e-um-aviso-honesto-sobre-escala"><span class="header-section-number">6.4</span> Semente Para PCA (Sem Aprofundar) — e um Aviso Honesto sobre Escala</a></li>
  </ul></li>
  <li><a href="#fechamento-e-ponte-para-a-aula-5" id="toc-fechamento-e-ponte-para-a-aula-5" class="nav-link" data-scroll-target="#fechamento-e-ponte-para-a-aula-5"><span class="header-section-number">7</span> Fechamento e Ponte para a Aula 5</a>
  <ul class="collapse">
  <li><a href="#retomando-as-perguntas-de-abertura" id="toc-retomando-as-perguntas-de-abertura" class="nav-link" data-scroll-target="#retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</a></li>
  <li><a href="#o-que-fica-em-aberto" id="toc-o-que-fica-em-aberto" class="nav-link" data-scroll-target="#o-que-fica-em-aberto">O Que Fica em Aberto</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula 4: Autovalores, Autovetores e Matrizes Simétricas</h1>
<p class="subtitle lead">Álgebra Linear e Otimização para Aprendizado de Máquina</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Marcos Medeiros Raimundo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">7 de setembro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/optimization-linear-algebra/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="revisão-e-introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Revisão e Introdução</h1>
<hr>
<section id="revisão-rápida-onde-a-aula-3-parou" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="revisão-rápida-onde-a-aula-3-parou"><span class="header-section-number">1.1</span> Revisão Rápida: Onde a Aula 3 Parou</h2>
<p>A Aula 3 resolveu o problema da regressão sobredeterminada por completo, em três passos. <strong>Primeiro</strong>, formalizou a “sombra” (a projeção ortogonal <span class="math inline">\(\hat{\mathbf{y}}\)</span> de <span class="math inline">\(\mathbf{y}\)</span> sobre <span class="math inline">\(\text{col}(X)\)</span>) como o ponto de menor distância, provando que essa condição é equivalente a uma condição algébrica exata: o resíduo <span class="math inline">\(\mathbf{y}-X\hat{\mathbf{w}}\)</span> ortogonal a todo o espaço-coluna. <strong>Segundo</strong>, transformou essa condição de ortogonalidade nas <strong>Equações Normais</strong>, <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span>, e mostrou que — sob posto completo de <span class="math inline">\(X\)</span> (herdado da Aula 2) — <span class="math inline">\(X^TX\)</span> é invertível e <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> é a única solução. <strong>Terceiro</strong>, no Bloco 6, mostrou que “posto completo” não é garantia de robustez numérica: comparando o par de atributos quase-colinear (<code>AveRooms</code>/<code>AveBedrms</code>, correlação <span class="math inline">\(0{,}865\)</span>) com o par bem-condicionado (<code>MedInc</code>/<code>HouseAge</code>), a mesma perturbação de <span class="math inline">\(1\%\)</span> nos dados produzia uma oscilação de <span class="math inline">\(\approx 29{,}5\%\)</span> no peso do primeiro par contra <span class="math inline">\(\approx 0{,}1\%\)</span> no segundo — quase <span class="math inline">\(300\)</span> vezes mais sensível. Vale relembrar o que essa perturbação faz e o que ela mede: soma-se a <code>MedHouseVal</code> um ruído gaussiano de média zero e desvio-padrão igual a apenas <span class="math inline">\(1\%\)</span> do desvio-padrão da própria variável (uma mudança minúscula, do tamanho de um erro de medição), reajusta-se por mínimos quadrados, e mede-se a <strong>taxa de amplificação</strong> entre essa mudança pequena na entrada e a mudança resultante no peso estimado — quanto maior a amplificação, mais frágil o par de atributos.</p>
<p>Essa fragilidade foi <strong>medida</strong>, não <strong>explicada</strong>. A Aula 3 batizou a quantidade certa para isso — o <strong>número de condição</strong> de <span class="math inline">\(X^TX\)</span> — mas só soube calculá-lo perturbando os dados e observando o efeito (<span class="math inline">\(\text{cond}(X^TX)\approx 23\,460\)</span> para os 4 atributos completos, <span class="math inline">\(\approx 420\)</span> para o par quase-colinear, <span class="math inline">\(\approx 169\)</span> para o par bem-condicionado, todos via <code>np.linalg.cond</code>). A própria aula fechou com essa promessa explícita, que serve de gancho direto para hoje: “o número de condição foi usado aqui de forma empírica (perturbar os dados e medir o efeito) — a Aula 4 dá a ferramenta exata para medi-lo diretamente a partir da estrutura de <span class="math inline">\(X^TX\)</span> (seus <strong>autovalores</strong> e <strong>autovetores</strong>), sem precisar perturbar nada.”</p>
</section>
<section id="organizador-prévio-de-perturbar-os-dados-para-olhar-direto-para-dentro-de-xtx" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="organizador-prévio-de-perturbar-os-dados-para-olhar-direto-para-dentro-de-xtx"><span class="header-section-number">1.2</span> Organizador Prévio: De Perturbar os Dados Para Olhar Direto Para Dentro de <span class="math inline">\(X^TX\)</span></h2>
<p>Perturbar os dados e medir o efeito é um experimento — funciona, mas não explica <em>por que</em> um par de atributos é mais frágil que outro, nem permite prever a fragilidade <strong>antes</strong> de perturbar nada. Olhando com mais cuidado para o que esse experimento faz: ao somar um ruído pequeno a <span class="math inline">\(\mathbf{y}\)</span> e reajustar, o que se está medindo, por fora, é uma <strong>taxa de amplificação</strong> — o quanto uma perturbação pequena na entrada se transforma numa oscilação grande (ou pequena) na saída (<span class="math inline">\(\hat{\mathbf{w}}\)</span>). Essa taxa não é uma propriedade do ruído específico usado no experimento — é uma propriedade fixa da própria matriz <span class="math inline">\(X^TX\)</span>, que existiria mesmo que ninguém nunca tivesse perturbado nada. Esta aula propõe uma mudança de estratégia: em vez de sacudir a matriz <span class="math inline">\(X^TX\)</span> de fora e observar como ela reage, vamos abrir <span class="math inline">\(X^TX\)</span> por dentro e encontrar os números que já determinam essa taxa de amplificação de antemão, de forma exata — os <strong>autovalores</strong>. A ideia central, que vai se repetir em cada bloco: a maioria das direções do espaço, quando atravessa uma transformação linear <span class="math inline">\(A\)</span>, gira e muda de tamanho ao mesmo tempo; mas existem direções especiais que só mudam de tamanho, nunca de direção — e são exatamente essas direções, e os fatores de escala associados a elas, que carregam toda a informação sobre o comportamento numérico de uma matriz, incluindo a taxa de amplificação que o experimento de perturbação só conseguia estimar de fora.</p>
</section>
<section id="roteiro-da-aula" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</h2>
<p>A pergunta que fecha o Organizador Prévio — “que números, dentro de <span class="math inline">\(X^TX\)</span>, já determinam a fragilidade antes de qualquer perturbação?” — se desdobra em quatro perguntas mais específicas, cada uma resolvida em um ou mais blocos desta aula:</p>
<ol type="1">
<li>O que é, geometricamente, um autovalor e um autovetor de uma matriz?</li>
<li>Como calcular autovalores e autovetores à mão, de forma sistemática, via o <strong>polinômio característico</strong>?</li>
<li>Por que toda matriz simétrica — como <span class="math inline">\(X^TX\)</span>, sempre — tem autovalores reais e autovetores ortogonais entre si? Esse é o <strong>Teorema Espectral Real</strong>.</li>
<li>Como o sinal e a razão entre os autovalores definem, respectivamente, a <strong>definitude positiva</strong> de uma matriz e o <strong>número de condição exato</strong> de <span class="math inline">\(X^TX\)</span> — fechando, sem perturbar nada, o ciclo aberto na Aula 3?</li>
</ol>
</section>
<section id="problema-motivador" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</h2>
<p>Volte aos mesmos dois pares de atributos do <em>California Housing Dataset</em> que a Aula 3 comparou no Bloco 6: <code>AveRooms</code>/<code>AveBedrms</code> (quase-colinear, correlação <span class="math inline">\(0{,}865\)</span>) e <code>MedInc</code>/<code>HouseAge</code> (bem-condicionado). A Aula 3 só soube dizer <em>qual</em> par era mais frágil depois de perturbar os dados e observar a oscilação no peso estimado. Pense por um instante, sem fazer nenhuma conta ainda: será que existe alguma propriedade de <span class="math inline">\(X^TX\)</span> — algo que se possa calcular olhando só para a matriz, sem perturbar absolutamente nada nos dados — que já anteciparia qual par vai se comportar mal?</p>
<div class="fig-resize" style="width: 85%; margin: 0 auto;">
<img src="index_files/mediabag/710fa2a90807c35f9cdbefe4eb2a99764f1962a5.svg" class="img-fluid">
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se dois pares de atributos têm a mesma correlação entre si, eles necessariamente têm o mesmo número de condição de <span class="math inline">\(X^TX\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: o número de condição da Aula 3 foi medido via perturbação nos dados; pense se a <em>escala</em> dos atributos (não só a correlação entre eles) poderia influenciar o resultado.</p>
<ul>
<li>□ Dois pares de atributos com a mesma correlação de Pearson entre si necessariamente têm o mesmo número de condição de <span class="math inline">\(X^TX\)</span>, porque correlação e número de condição medem exatamente a mesma coisa.</li>
<li>□ Se um par de atributos fosse exatamente ortogonal (correlação zero, como duas colunas perfeitamente descorrelacionadas), isso por si só não garante que o número de condição de <span class="math inline">\(X^TX\)</span> para esse par seja igual a <span class="math inline">\(1\)</span> — a escala relativa das duas colunas também importa.</li>
<li>□ Num modelo de risco de crédito (dataset German Credit), com dois atributos de histórico de pagamento fortemente correlacionados entre si (ex.: duração do empréstimo e valor total do crédito, que tendem a crescer juntos), o mesmo tipo de fragilidade numérica de <span class="math inline">\(X^TX\)</span> discutido aqui se aplicaria, mesmo fora do contexto de imóveis.</li>
<li>□ Como a Aula 3 mediu a fragilidade só perturbando os dados, isso significa que não existe nenhuma forma de calcular o número de condição de <span class="math inline">\(X^TX\)</span> sem realizar, na prática, uma perturbação real dos dados.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="intuição-autovetores" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Intuição – Autovetores</h1>
<hr>
<section id="uma-matriz-agindo-sobre-um-conjunto-de-direções" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="uma-matriz-agindo-sobre-um-conjunto-de-direções"><span class="header-section-number">2.1</span> Uma Matriz Agindo sobre um Conjunto de Direções</h2>
<p>Antes de qualquer fórmula, uma imagem concreta. Tome a matriz <span class="math display">\[
A = \begin{bmatrix} 4 &amp; 2 \\ 1 &amp; 3 \end{bmatrix}
\]</span> (a mesma matriz do MathML, Exemplo 4.5, reaproveitada no Bloco 3 para o cálculo à mão) e pense nela como uma transformação linear <span class="math inline">\(\mathbf{v}\mapsto A\mathbf{v}\)</span> agindo sobre todo o plano <span class="math inline">\(\mathbb{R}^2\)</span>. Escolha um punhado de vetores unitários apontando em direções diferentes ao redor da origem, e observe o que <span class="math inline">\(A\)</span> faz com cada um deles.</p>
<div class="fig-resize" style="width: 60%; margin: 0 auto;">
<div id="bcf6d030" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>No painel esquerdo, cada seta cinza é um vetor unitário original, e a seta azul correspondente é sua imagem <span class="math inline">\(A\mathbf{v}\)</span>: a maioria delas gira visivelmente — a direção de chegada não é a mesma da direção de partida. Mas as duas retas tracejadas (laranja e vermelha) marcam duas direções específicas em que <strong>isso não acontece</strong>: qualquer vetor sobre essas retas continua, depois de multiplicado por <span class="math inline">\(A\)</span>, sobre a <strong>mesma reta</strong> — só o comprimento muda (nesse caso, sempre esticando, nunca invertendo, porque os dois fatores de escala são positivos). O painel direito mostra a mesma ideia de outro ângulo: o círculo unitário inteiro (pontilhado) vira uma elipse (linha cheia azul) sob a ação de <span class="math inline">\(A\)</span>, e os eixos dessa elipse caem <strong>exatamente</strong> sobre as duas direções especiais — cada eixo esticado por um fator diferente (<span class="math inline">\(\lambda=2\)</span> numa direção, <span class="math inline">\(\lambda=5\)</span> na outra, valores que o Bloco 3 vai calcular à mão, à mão).</p>
<p>Vale nomear informalmente o que o desenho já mostra, antes de qualquer equação: essas duas direções especiais são os <strong>autovetores</strong> de <span class="math inline">\(A\)</span>, e os fatores de escala associados a cada uma são os <strong>autovalores</strong> correspondentes. Repare em um detalhe que vai ficar importante no Bloco 4: as duas retas tracejadas do painel esquerdo <strong>não são perpendiculares uma à outra</strong> — o ângulo entre elas não é de <span class="math inline">\(90°\)</span>. Isso não é um detalhe cosmético; é uma propriedade de <span class="math inline">\(A\)</span> <strong>não ser simétrica</strong> (<span class="math inline">\(A\ne A^T\)</span>, já que a entrada <span class="math inline">\((1,2)=2\)</span> é diferente da entrada <span class="math inline">\((2,1)=1\)</span>), e vai mudar completamente quando a matriz for simétrica — gancho direto para o Bloco 4.</p>
</section>
<section id="a-equação-formal" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="a-equação-formal"><span class="header-section-number">2.2</span> A Equação Formal</h2>
<p>A intuição visual do painel acima tem um nome e uma equação precisos. O MathML define (tradução nossa, §4.2, Definição 4.6, p.&nbsp;105):</p>
<blockquote class="blockquote">
<p>“Seja <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> uma matriz quadrada. Então <span class="math inline">\(\lambda\in\mathbb{R}\)</span> é um <strong>autovalor</strong> de <span class="math inline">\(A\)</span> e <span class="math inline">\(\mathbf{x}\in\mathbb{R}^n\setminus\{\mathbf{0}\}\)</span> é o <strong>autovetor</strong> correspondente de <span class="math inline">\(A\)</span> se <span class="math display">\[A\mathbf{x} = \lambda\mathbf{x}.\]</span> Chamamos essa equação de <strong>equação de autovalor</strong>.”</p>
</blockquote>
<p>Essa é exatamente a propriedade que o desenho já mostrou: multiplicar o autovetor <span class="math inline">\(\mathbf{x}\)</span> por <span class="math inline">\(A\)</span> dá o mesmo resultado que simplesmente esticá-lo por um número <span class="math inline">\(\lambda\)</span> — nenhuma rotação, só escala (com inversão de sentido se <span class="math inline">\(\lambda&lt;0\)</span>, caso que não aparece no exemplo desta figura, mas vai aparecer mais adiante no curso). Vale notar, desde já, uma propriedade que vai evitar uma confusão comum: o autovetor <span class="math inline">\(\mathbf{x}\)</span> associado a um autovalor <strong>não é único</strong>. O MathML observa (tradução nossa, mesma seção): “se <span class="math inline">\(\mathbf{x}\)</span> é um autovetor de <span class="math inline">\(A\)</span> associado ao autovalor <span class="math inline">\(\lambda\)</span>, então, para qualquer <span class="math inline">\(c\in\mathbb{R}
\setminus\{0\}\)</span>, vale que <span class="math inline">\(c\mathbf{x}\)</span> também é um autovetor de <span class="math inline">\(A\)</span> com o mesmo autovalor, já que <span class="math inline">\(A(c\mathbf{x})=cA\mathbf{x}=c\lambda\mathbf{x}
=\lambda(c\mathbf{x})\)</span>. Assim, todos os vetores colineares a <span class="math inline">\(\mathbf{x}\)</span> também são autovetores de <span class="math inline">\(A\)</span>.” Ou seja: o que a figura chama de “direção especial” é literalmente isso — uma <strong>reta</strong> inteira de autovetores (menos a origem), não um vetor específico; qualquer múltiplo escalar não-nulo de um autovetor serve igualmente bem.</p>
<p>Essa não-unicidade é o motivo para tratar um autovetor, antes de mais nada, como uma <strong>direção</strong> — não como “o” vetor com um comprimento fixo. Um vetor propriamente dito carrega duas informações, direção <strong>e</strong> amplitude (o próprio comprimento da seta); num autovetor, a amplitude é arbitrária — qualquer <span class="math inline">\(c\ne 0\)</span> serve igualmente bem, inclusive <span class="math inline">\(c&lt;0\)</span>, que aponta para o lado oposto da mesma reta — só a direção (a reta que passa pela origem) é a informação que de fato pertence a <span class="math inline">\(A\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se um vetor <span class="math inline">\(\mathbf{v}\)</span> fosse mapeado por <span class="math inline">\(A\)</span> exatamente para <span class="math inline">\(-3\mathbf{v}\)</span>, isso significaria que <span class="math inline">\(\mathbf{v}\)</span> não é autovetor de <span class="math inline">\(A\)</span>, já que a direção “inverteu”?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia a equação de autovalor — ela permite <span class="math inline">\(\lambda\)</span> negativo? “Mesma reta, sentido oposto” ainda conta como “não girar”?</p>
<ul>
<li>□ Se <span class="math inline">\(A\mathbf{v}=-3\mathbf{v}\)</span> para algum <span class="math inline">\(\mathbf{v}\ne\mathbf{0}\)</span>, isso significa que <span class="math inline">\(\mathbf{v}\)</span> <strong>não</strong> é autovetor de <span class="math inline">\(A\)</span>, porque a direção do vetor se inverteu.</li>
<li>□ Se todos os vetores do plano fossem autovetores de uma mesma matriz <span class="math inline">\(A\)</span> (não só duas direções especiais, mas qualquer direção), isso forçaria <span class="math inline">\(A\)</span> a ser um múltiplo escalar da identidade, <span class="math inline">\(A=cI\)</span>.</li>
<li>□ Numa camada linear de uma rede neural (sem ativação não-linear), representada pela matriz de pesos <span class="math inline">\(W\)</span>, se um vetor de entrada <span class="math inline">\(\mathbf{v}\)</span> satisfaz <span class="math inline">\(W\mathbf{v}=-3\mathbf{v}\)</span>, a mesma leitura vale: <span class="math inline">\(\mathbf{v}\)</span> é autovetor de <span class="math inline">\(W\)</span> com autovalor negativo, e sua direção continua preservada por <span class="math inline">\(W\)</span>, só com o sentido invertido.</li>
<li>□ Como o autovetor associado a um autovalor não é único (qualquer múltiplo escalar serve), isso implica que o autoespaço associado a um autovalor sempre tem dimensão maior que 1.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="o-polinômio-característico" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> O Polinômio Característico</h1>
<hr>
<section id="premissas-o-que-precisamos-resolver" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="premissas-o-que-precisamos-resolver"><span class="header-section-number">3.1</span> Premissas: O Que Precisamos Resolver</h2>
<p>O Bloco 2 mostrou a existência das direções especiais só visualmente. Para encontrá-las <strong>sem depender de um desenho</strong>, precisamos transformar a equação de autovalor <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> num problema de álgebra resolvível passo a passo. Deixando as premissas explícitas antes de qualquer manipulação:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Premissas
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Temos uma matriz quadrada <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> fixa (no nosso caso, <span class="math inline">\(n=2\)</span>, a matriz do Bloco 2).</li>
<li>Procuramos pares <span class="math inline">\((\lambda,\mathbf{x})\)</span>, com <span class="math inline">\(\mathbf{x}\in\mathbb{R}^n\setminus\{\mathbf{0}\}\)</span>, satisfazendo <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span>.</li>
<li>Não sabemos ainda quantos autovalores existem, nem seus valores — só sabemos, do Bloco 2, que <strong>pelo menos dois</strong> existem nesse exemplo específico (as duas direções desenhadas).</li>
</ol>
</div>
</div>
</section>
<section id="passo-i-reescrevendo-a-equação-de-autovalor-como-um-sistema-homogêneo" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="passo-i-reescrevendo-a-equação-de-autovalor-como-um-sistema-homogêneo"><span class="header-section-number">3.2</span> Passo (i): Reescrevendo a Equação de Autovalor Como um Sistema Homogêneo</h2>
<p>A manipulação decisiva é puramente algébrica: subtrair <span class="math inline">\(\lambda\mathbf{x}\)</span> dos dois lados, <span class="math display">\[
A\mathbf{x} = \lambda\mathbf{x}
\quad\Longleftrightarrow\quad
A\mathbf{x} - \lambda\mathbf{x} = \mathbf{0}
\quad\Longleftrightarrow\quad
(A-\lambda I)\mathbf{x} = \mathbf{0},
\]</span> usando <span class="math inline">\(I\)</span> (a identidade) para poder subtrair uma matriz de outra matriz. Essa última forma é um <strong>sistema linear homogêneo</strong> <span class="math inline">\(B\mathbf{x}=\mathbf{0}\)</span>, com <span class="math inline">\(B=A-\lambda I\)</span> — a mesma estrutura de sistema linear já estudada nas Aulas 2-3, só que agora a incógnita não é só <span class="math inline">\(\mathbf{x}\)</span>: o próprio <span class="math inline">\(\lambda\)</span> também é desconhecido, e está embutido dentro de <span class="math inline">\(B\)</span>.</p>
<p>Um sistema homogêneo <span class="math inline">\(B\mathbf{x}=\mathbf{0}\)</span> <strong>sempre</strong> tem a solução trivial <span class="math inline">\(\mathbf{x}=\mathbf{0}\)</span> — mas a Premissa 2 exige <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>. Isso só é possível quando o sistema tem <strong>mais de uma</strong> solução (a trivial e outras) — e a Aula 2 já ensinou o critério exato para isso: um sistema quadrado homogêneo tem soluções não-triviais se, e somente se, sua matriz de coeficientes <strong>não</strong> tem posto completo, ou seja, é <strong>singular</strong> (não-invertível).</p>
<p>Falta um elo, e ele não é óbvio: por que “singular” equivale a <span class="math inline">\(\det(B)=0\)</span>? Não é uma definição nem uma consequência imediata do que já vimos — é um teorema, na verdade dois, que o MathML enuncia separadamente (tradução nossa, §4.1): “para qualquer matriz quadrada <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> vale que <span class="math inline">\(A\)</span> é invertível se, e somente se, <span class="math inline">\(\det(A)\ne 0\)</span>” (Teorema 4.1, p.&nbsp;100), e “uma matriz quadrada <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> tem <span class="math inline">\(\det(A)\ne 0\)</span> se, e somente se, <span class="math inline">\(\text{rk}(A)=n\)</span>; em outras palavras, <span class="math inline">\(A\)</span> é invertível se, e somente se, tem posto completo” (Teorema 4.3, p.&nbsp;103). Encadeando os dois teoremas com o critério de posto da Aula 2: <span class="math display">\[
B\mathbf{x}=\mathbf{0} \text{ tem solução não-trivial}
\;\overset{\text{Aula 2}}{\iff}\; B \text{ não tem posto completo}
\;\overset{\text{Teo. 4.3}}{\iff}\; B \text{ não é invertível}
\;\overset{\text{Teo. 4.1}}{\iff}\; \det(B) = 0.
\]</span> Com <span class="math inline">\(B=A-\lambda I\)</span>, isso equivale a <span class="math display">\[
\det(A-\lambda I) = 0.
\]</span> Essa equação — não <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> diretamente — é o alvo do resto deste bloco: ela só tem <span class="math inline">\(\lambda\)</span> como incógnita (o <span class="math inline">\(\mathbf{x}\)</span> já foi eliminado), o que a torna resolvível por conta própria.</p>
</section>
<section id="o-polinômio-característico-1" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="o-polinômio-característico-1"><span class="header-section-number">3.3</span> O Polinômio Característico</h2>
<p>O MathML batiza a expressão <span class="math inline">\(\det(A-\lambda I)\)</span> vista como função de <span class="math inline">\(\lambda\)</span> (tradução nossa, §4.1, Definição 4.5, p.&nbsp;104):</p>
<blockquote class="blockquote">
<p>“Para <span class="math inline">\(\lambda\in\mathbb{R}\)</span> e uma matriz quadrada <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span>, <span class="math display">\[
p_A(\lambda) := \det(A-\lambda I) = c_0+c_1\lambda+c_2\lambda^2+\cdots
+c_{n-1}\lambda^{n-1}+(-1)^n\lambda^n,\quad c_0,\dots,c_{n-1}
\in\mathbb{R},
\]</span> é o <strong>polinômio característico</strong> de <span class="math inline">\(A\)</span>.”</p>
</blockquote>
<p>E o MathML conecta essa definição diretamente ao problema que queremos resolver (tradução nossa, §4.2, Teorema 4.8, p.&nbsp;106): “<span class="math inline">\(\lambda\in
\mathbb{R}\)</span> é um autovalor de <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> se, e somente se, <span class="math inline">\(\lambda\)</span> é uma raiz do polinômio característico <span class="math inline">\(p_A(\lambda)\)</span> de <span class="math inline">\(A\)</span>.” Ou seja: <strong>os autovalores de <span class="math inline">\(A\)</span> são exatamente as raízes reais de um único polinômio</strong>, <span class="math inline">\(p_A(\lambda)\)</span> — encontrar todos os autovalores de uma matriz <span class="math inline">\(2\times 2\)</span> vira, literalmente, resolver uma equação do segundo grau.</p>
</section>
<section id="passo-ii-aplicando-ao-exemplo-do-bloco-2-o-polinômio" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="passo-ii-aplicando-ao-exemplo-do-bloco-2-o-polinômio"><span class="header-section-number">3.4</span> Passo (ii): Aplicando ao Exemplo do Bloco 2 — o Polinômio</h2>
<p>Vamos calcular à mão, do zero, usando a mesma matriz do Bloco 2, <span class="math inline">\(A=\begin{bmatrix}4&amp;2\\1&amp;3\end{bmatrix}\)</span> (MathML, Exemplo 4.5, p.&nbsp;107). <span class="math display">\[
A-\lambda I = \begin{bmatrix}4-\lambda &amp; 2\\ 1 &amp; 3-\lambda\end{bmatrix},
\qquad
p_A(\lambda) = \det(A-\lambda I) = (4-\lambda)(3-\lambda) - 2\cdot 1.
\]</span> Expandindo o produto: <span class="math inline">\((4-\lambda)(3-\lambda) = 12-7\lambda+\lambda^2\)</span>, logo <span class="math display">\[
p_A(\lambda) = 12-7\lambda+\lambda^2-2 = \lambda^2-7\lambda+10.
\]</span> O MathML resolve essa mesma equação por fatoração direta (tradução nossa): “fatorizamos o polinômio característico e obtemos <span class="math inline">\(p(\lambda)=(4-\lambda)(3-\lambda)-2\cdot 1=10-7\lambda+\lambda^2=
(2-\lambda)(5-\lambda)\)</span>, dando as raízes <span class="math inline">\(\lambda_1=2\)</span> e <span class="math inline">\(\lambda_2=5\)</span>.” Confirmando por Bhaskara, para não depender só de “ver” a fatoração: raízes de <span class="math inline">\(\lambda^2-7\lambda+10=0\)</span> são <span class="math display">\[
\lambda=\frac{7\pm\sqrt{49-40}}{2}=\frac{7\pm\sqrt{9}}{2}=\frac{7\pm 3}{2},
\]</span> ou seja <span class="math inline">\(\lambda\in\{2,5\}\)</span> — exatamente os dois valores que a elipse do Bloco 2 já tinha marcado nos eixos.</p>
</section>
<section id="passo-iii-de-volta-à-equação-original-achando-os-autovetores" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="passo-iii-de-volta-à-equação-original-achando-os-autovetores"><span class="header-section-number">3.5</span> Passo (iii): De Volta à Equação Original — Achando os Autovetores</h2>
<p>Achar <span class="math inline">\(\lambda\)</span> resolveu metade do problema; falta achar, para cada <span class="math inline">\(\lambda\)</span>, o(s) autovetor(es) associado(s), resolvendo <span class="math inline">\((A-\lambda I)\mathbf{x}=\mathbf{0}\)</span> com o valor de <span class="math inline">\(\lambda\)</span> já conhecido. Para <span class="math inline">\(\lambda_2=5\)</span>: <span class="math display">\[
A - 5I = \begin{bmatrix}-1 &amp; 2\\ 1 &amp; -2\end{bmatrix},
\qquad
(A-5I)\mathbf{x}=\mathbf{0} \;\Longrightarrow\; -x_1+2x_2=0
\;\Longrightarrow\; x_1=2x_2.
\]</span> A equação <span class="math inline">\(x_1=2x_2\)</span> tem uma variável livre: qualquer valor de <span class="math inline">\(x_2\)</span> determina <span class="math inline">\(x_1\)</span>. Parametrizando <span class="math inline">\(x_2=t\)</span> para <span class="math inline">\(t\in\mathbb{R}\)</span> arbitrário, obtemos <span class="math inline">\(x_1=2t\)</span>, ou seja <span class="math display">\[
(x_1,x_2) = (2t,t) = t\cdot(2,1).
\]</span> Esse é, por definição, o conjunto de todos os múltiplos escalares de <span class="math inline">\((2,1)\)</span> — <span class="math inline">\(\text{span}((2,1)) := \{t\cdot(2,1) : t\in\mathbb{R}\}\)</span>. O <strong>autoespaço</strong> <span class="math inline">\(E_5\)</span> é, por definição, o conjunto-solução inteiro de <span class="math inline">\((A-5I)\mathbf{x}=\mathbf{0}\)</span> (uma reta pela origem, incluindo o caso <span class="math inline">\(t=0\)</span>, que dá a solução trivial); os <strong>autovetores</strong> propriamente ditos são os elementos não-nulos desse conjunto (<span class="math inline">\(t\ne 0\)</span>, pela Premissa 2). Logo <span class="math display">\[
E_5=\text{span}((2,1))
\]</span> (MathML: “obtemos o espaço-solução <span class="math inline">\(E_5=\text{span}([2,1])\)</span>”). Para <span class="math inline">\(\lambda_1=2\)</span>: <span class="math display">\[
A-2I = \begin{bmatrix}2 &amp; 2\\ 1 &amp; 1\end{bmatrix},
\qquad
(A-2I)\mathbf{x}=\mathbf{0} \;\Longrightarrow\; x_1+x_2=0
\;\Longrightarrow\; x_1=-x_2,
\]</span> mesmo processo: parametrizando <span class="math inline">\(x_2=t\)</span>, <span class="math inline">\((x_1,x_2)=(-t,t)=t\cdot(-1,1)\)</span>, dando <span class="math inline">\(E_2=\text{span}((-1,1))\)</span>. Como <span class="math inline">\((-1,1)=-1\cdot(1,-1)\)</span>, essa é a mesma reta que <span class="math inline">\(\text{span}((1,-1))\)</span> — trocar o sinal do parâmetro <span class="math inline">\(t\)</span> não muda o conjunto de múltiplos escalares, só relabeia qual <span class="math inline">\(t\)</span> gera qual ponto. Escrevemos <span class="math inline">\(E_2=\text{span}((1,-1))\)</span> por convenção; isso é consistente com o autovetor ser uma <strong>direção</strong>, não um vetor de sinal fixo (Bloco 2, “A Equação Formal”). Note que <span class="math inline">\((2,1)\)</span> e <span class="math inline">\((1,-1)\)</span> são exatamente as duas direções (laranja e vermelha) desenhadas no painel do Bloco 2 — o cálculo algébrico confirma, número por número, o que o desenho já tinha mostrado visualmente.</p>
</section>
<section id="verificação-numérica-numpy.linalg.eig" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="verificação-numérica-numpy.linalg.eig"><span class="header-section-number">3.6</span> Verificação Numérica: <code>numpy.linalg.eig</code></h2>
<p>Fazer essa conta à mão é indispensável para entender <strong>de onde</strong> vêm os autovalores/autovetores, mas na prática — matrizes maiores que <span class="math inline">\(2\times 2\)</span>, ou o caso <span class="math inline">\(X^TX\in\mathbb{R}^{4\times 4}\)</span> do Bloco 6 — o polinômio característico vira inviável de resolver manualmente (polinômios de grau <span class="math inline">\(\ge 5\)</span> nem sempre têm raiz em forma fechada). <code>numpy.linalg.eig</code> resolve o mesmo problema numericamente:</p>
<div id="e01a06a8" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>autovalores, autovetores <span class="op">=</span> np.linalg.eig(A_exemplo)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Autovalores reais (2 e 5); numpy.linalg.eig devolve dtype complexo por</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># padrão para matrizes não-simétricas — parte imaginária é zero aqui.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>autovalores <span class="op">=</span> autovalores.real</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>autovetores <span class="op">=</span> autovetores.real</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores:"</span>, autovalores)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovetores (colunas, normalizados por numpy):"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(autovetores)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Conferindo A x = lambda x diretamente, para cada par</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2</span>):</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    lhs <span class="op">=</span> A_exemplo <span class="op">@</span> autovetores[:, k]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    rhs <span class="op">=</span> autovalores[k] <span class="op">*</span> autovetores[:, k]</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  lambda=</span><span class="sc">{</span>autovalores[k]<span class="sc">:.1f}</span><span class="ss">: ||A x - lambda x|| = </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(lhs <span class="op">-</span> rhs)<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Autovalores: [5. 2.]
Autovetores (colunas, normalizados por numpy):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
  lambda=5.0: ||A x - lambda x|| = 0.00e+00
  lambda=2.0: ||A x - lambda x|| = 3.14e-16</code></pre>
</div>
</div>
<p>Os autovalores batem exatamente com <span class="math inline">\(\{2,5\}\)</span> calculados à mão, e a igualdade <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> é confirmada numericamente até erro de arredondamento. Uma diferença importante de convenção: o <code>numpy</code> sempre devolve os autovetores <strong>normalizados</strong> (norma <span class="math inline">\(1\)</span>) — é só mais uma escolha dentro da reta de infinitos múltiplos escalares válidos (a não-unicidade do Bloco 2), não uma contradição com o <span class="math inline">\((2,1)\)</span>/<span class="math inline">\((1,-1)\)</span> calculado à mão.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se o polinômio característico de uma matriz <span class="math inline">\(3\times 3\)</span> tivesse grau 3 mas só uma raiz real, quantos autovalores reais essa matriz teria?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: o Teorema 4.8 conecta autovalor a <strong>raiz real</strong> do polinômio característico — o que acontece quando algumas raízes não são reais?</p>
<ul>
<li>□ Uma matriz <span class="math inline">\(3\times 3\)</span> cujo polinômio característico (grau 3) tem só uma raiz real teria exatamente <strong>um</strong> autovalor real — as outras duas raízes, sendo complexas, não correspondem a autovalores reais da matriz.</li>
<li>□ Se o polinômio característico de uma matriz <span class="math inline">\(2\times 2\)</span> não tivesse nenhuma raiz real (discriminante negativo em Bhaskara), essa matriz não teria autovalor real algum, mas ainda seria uma transformação linear perfeitamente válida sobre <span class="math inline">\(\mathbb{R}^2\)</span> (ex.: uma rotação pura por um ângulo diferente de <span class="math inline">\(0°\)</span>/<span class="math inline">\(180°\)</span>).</li>
<li>□ Numa cadeia de Markov usada em aprendizado por reforço para descrever as transições de um agente entre dois estados, com uma matriz de transição <span class="math inline">\(2\times 2\)</span>, encontrar os autovalores dessa matriz por polinômio característico é uma aplicação válida da mesma técnica, mesmo a matriz não vindo de geometria.</li>
<li>□ Como o autovetor associado a um autovalor não é único, isso implica que, ao resolver <span class="math inline">\((A-\lambda I)\mathbf{x}=\mathbf{0}\)</span> à mão para achar <span class="math inline">\(E_\lambda\)</span>, sempre existe mais de uma equação linearmente independente restringindo <span class="math inline">\(\mathbf{x}\)</span>.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="o-teorema-espectral-real-para-matrizes-simétricas" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> O Teorema Espectral Real para Matrizes Simétricas</h1>
<hr>
<section id="por-que-isso-importa-para-xtx" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="por-que-isso-importa-para-xtx"><span class="header-section-number">4.1</span> Por Que Isso Importa Para <span class="math inline">\(X^TX\)</span></h2>
<p>Antes de qualquer prova, a razão de este bloco existir: a Aula 3 usou <span class="math inline">\(X^TX\)</span> o tempo todo, e uma propriedade dela nunca foi explorada a fundo — <strong><span class="math inline">\(X^TX\)</span> é sempre simétrica</strong>, para qualquer <span class="math inline">\(X\)</span>, mesmo retangular (<span class="math inline">\((X^TX)^T=X^T(X^T)^T=X^TX\)</span>, pela regra <span class="math inline">\((AB)^T=B^TA^T\)</span> seguida de <span class="math inline">\((X^T)^T=X\)</span> — uma linha de álgebra). O MathML vai além: (tradução nossa, §4.2, Teorema 4.14, p.&nbsp;111) “dada uma matriz <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span>, sempre podemos obter uma matriz simétrica, semidefinida positiva <span class="math inline">\(S\in\mathbb{R}^{n\times n}\)</span> definindo <span class="math inline">\(S:=A^TA\)</span>.” O próprio MathML separa a segunda metade num comentário à parte (Observação, p.&nbsp;111): “se <span class="math inline">\(\text{rk}(A)=n\)</span>, então <span class="math inline">\(S:=A^TA\)</span> é simétrica, definida positiva.” <strong>As duas condições são diferentes, e só uma delas depende do posto:</strong> “semidefinida positiva” vale <strong>sempre</strong>, para qualquer <span class="math inline">\(A\)</span> — mesmo singular, mesmo retangular, sem nenhuma hipótese extra; é <strong>só</strong> “definida positiva” (a versão mais forte, que exclui vetores não-nulos no núcleo de <span class="math inline">\(S\)</span> — definição formal logo a seguir) que exige <span class="math inline">\(\text{rk}(A)=n\)</span>, posto completo. Aplicando a <span class="math inline">\(X^TX\)</span>: <strong><span class="math inline">\(X^TX\)</span> é sempre semidefinida positiva</strong>, tenha <span class="math inline">\(X\)</span> posto completo ou não; ela só é <strong>definida</strong> positiva sob posto completo — a mesma condição que a Aula 3 já usou para garantir invertibilidade. Este bloco prova o que a simetria de <span class="math inline">\(X^TX\)</span> garante sobre seus autovalores e autovetores — a peça que faltava para o Bloco 5 fechar o ciclo da Aula 3.</p>
</section>
<section id="definição-matrizes-definidas-e-semidefinidas-positivas" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="definição-matrizes-definidas-e-semidefinidas-positivas"><span class="header-section-number">4.2</span> Definição: Matrizes Definidas e Semidefinidas Positivas</h2>
<p>Antes de provar que <span class="math inline">\(X^TX\)</span> tem essa propriedade, falta a definição formal — “semidefinida positiva” foi usado acima antes de ser definido, e essa lacuna se fecha agora. O MathML define (tradução nossa, §3.2.3, Definição 3.4, p.&nbsp;74):</p>
<blockquote class="blockquote">
<p>“Uma matriz simétrica <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> que satisfaz […] <span class="math inline">\(\mathbf{x}^TA\mathbf{x}&gt;0\)</span> para todo <span class="math inline">\(\mathbf{x}\in V\setminus
\{\mathbf{0}\}\)</span> é chamada simétrica, definida positiva, ou apenas <strong>positiva definida</strong>. Se vale apenas <span class="math inline">\(\ge\)</span> […], então <span class="math inline">\(A\)</span> é chamada simétrica, <strong>semidefinida positiva</strong>.”</p>
</blockquote>
<p>Duas cláusulas, uma definição, uma hipótese comum: <span class="math inline">\(A\)</span> precisa ser <strong>simétrica</strong> (<span class="math inline">\(A=A^T\)</span>) — sem isso a definição nem se aplica, “definida positiva” e “semidefinida positiva” só classificam matrizes simétricas. Dada essa hipótese, o que separa as duas é só o tipo de desigualdade sobre <span class="math inline">\(\mathbf{x}^TA\mathbf{x}\)</span>: estrita (<span class="math inline">\(&gt;0\)</span>) para “definida”, fraca (<span class="math inline">\(\ge 0\)</span>) para “semidefinida” — e em ambos os casos a desigualdade precisa valer para <strong>todo</strong> <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>, não para um <span class="math inline">\(\mathbf{x}\)</span> escolhido a dedo. Com a definição em mãos, o teorema a seguir mostra por que <span class="math inline">\(X^TX\)</span> sempre satisfaz a versão fraca.</p>
</section>
<section id="teorema-ata-é-simétrica-e-semidefinida-positiva" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="teorema-ata-é-simétrica-e-semidefinida-positiva"><span class="header-section-number">4.3</span> Teorema: <span class="math inline">\(A^TA\)</span> é Simétrica e Semidefinida Positiva</h2>
<p>Isso é exatamente o Teorema 4.14 citado acima — mas citar não é provar, e a prova é curta o bastante para não pular. O MathML só esboça a ideia (tradução nossa, p.&nbsp;111); reconstruímos os dois passos por extenso.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema (MathML 4.14, parte 1 — simetria)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para qualquer <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span>, a matriz <span class="math inline">\(S:=A^TA\in\mathbb{R}^{n\times n}\)</span> é simétrica.</p>
</div>
</div>
<p><em>Prova.</em> Por definição, <span class="math inline">\(S\)</span> é simétrica se <span class="math inline">\(S=S^T\)</span>. Calculamos <span class="math inline">\(S^T\)</span> a partir de <span class="math inline">\(S:=A^TA\)</span>, aplicando a regra <span class="math inline">\((BC)^T=C^TB^T\)</span> com <span class="math inline">\(B=A^T\)</span> e <span class="math inline">\(C=A\)</span>: <span class="math display">\[
S^T = (A^TA)^T = A^T(A^T)^T = A^TA = S,
\]</span> usando <span class="math inline">\((A^T)^T=A\)</span> na penúltima igualdade. Logo <span class="math inline">\(S=S^T\)</span>. <span class="math inline">\(\blacksquare\)</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema (MathML 4.14, parte 2 — semidefinitude positiva)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para qualquer <span class="math inline">\(A\in\mathbb{R}^{m\times n}\)</span>, a matriz <span class="math inline">\(S:=A^TA\)</span> satisfaz <span class="math inline">\(\mathbf{x}^TS\mathbf{x}\ge 0\)</span> para todo <span class="math inline">\(\mathbf{x}\in\mathbb{R}^n\)</span>.</p>
</div>
</div>
<p><em>Prova.</em> Seja <span class="math inline">\(\mathbf{x}\in\mathbb{R}^n\)</span> arbitrário. Substituindo <span class="math inline">\(S=A^TA\)</span> e reagrupando por associatividade do produto de matrizes: <span class="math display">\[
\mathbf{x}^TS\mathbf{x} = \mathbf{x}^T(A^TA)\mathbf{x}
= (\mathbf{x}^TA^T)(A\mathbf{x}).
\]</span> Pela mesma regra <span class="math inline">\((BC)^T=C^TB^T\)</span> (com <span class="math inline">\(B=A\)</span>, <span class="math inline">\(C=\mathbf{x}\)</span>), <span class="math inline">\(\mathbf{x}^TA^T=(A\mathbf{x})^T\)</span>, logo <span class="math display">\[
\mathbf{x}^TS\mathbf{x} = (A\mathbf{x})^T(A\mathbf{x}) = \|A\mathbf{x}\|^2,
\]</span> usando que o produto de um vetor pela sua própria transposta é a soma dos quadrados de suas entradas, ou seja, a norma ao quadrado — sempre <span class="math inline">\(\ge 0\)</span>, qualquer que seja o vetor <span class="math inline">\(A\mathbf{x}\)</span>. Como <span class="math inline">\(\mathbf{x}\)</span> era arbitrário, isso vale para todo <span class="math inline">\(\mathbf{x}\in\mathbb{R}^n\)</span>, que é exatamente a Definição 3.4 de semidefinida positiva. <span class="math inline">\(\blacksquare\)</span></p>
<p>Aplicando os dois teoremas com <span class="math inline">\(A=X\)</span>: <span class="math inline">\(X^TX\)</span> é simétrica e semidefinida positiva, para <strong>qualquer</strong> <span class="math inline">\(X\)</span>, com ou sem posto completo — a prova não usa hipótese nenhuma sobre o posto de <span class="math inline">\(A\)</span> em nenhum dos dois passos. É esse fato, agora demonstrado e não só citado, que o resto deste bloco explora: o que a simetria (e a semidefinitude, quando for estritamente definida) garante sobre os autovalores e autovetores de <span class="math inline">\(X^TX\)</span>.</p>
</section>
<section id="premissas-e-prova-autovetores-de-autovalores-distintos-são-ortogonais" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="premissas-e-prova-autovetores-de-autovalores-distintos-são-ortogonais"><span class="header-section-number">4.4</span> Premissas e Prova: Autovetores de Autovalores Distintos São Ortogonais</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Premissas
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> é <strong>simétrica</strong>, ou seja, <span class="math inline">\(A=A^T\)</span>.</li>
<li><span class="math inline">\(\mathbf{x}_1,\mathbf{x}_2\)</span> são autovetores de <span class="math inline">\(A\)</span> associados a autovalores <strong>distintos</strong>, <span class="math inline">\(\lambda_1\ne\lambda_2\)</span>: <span class="math inline">\(A\mathbf{x}_1=\lambda_1\mathbf{x}_1\)</span>, <span class="math inline">\(A\mathbf{x}_2=\lambda_2\mathbf{x}_2\)</span>.</li>
</ol>
</div>
</div>
<p><strong>Nota de precisão:</strong> a prova a seguir é exposição nossa, não uma citação literal de nenhuma das fontes — o MathML e o Boyd enunciam o Teorema Espectral diretamente, sem detalhar este passo intermediário no nível que este curso quer mostrar. A prova em si é padrão (manipulação de <span class="math inline">\(\mathbf{x}_1^TA\mathbf{x}_2\)</span> dos dois lados), mas construída aqui, não copiada.</p>
<p>Calculamos o escalar <span class="math inline">\(\mathbf{x}_1^TA\mathbf{x}_2\)</span> de duas formas diferentes. <strong>Primeiro</strong>, aplicando <span class="math inline">\(A\)</span> diretamente a <span class="math inline">\(\mathbf{x}_2\)</span> (Premissa 2): <span class="math display">\[
\mathbf{x}_1^TA\mathbf{x}_2 = \mathbf{x}_1^T(\lambda_2\mathbf{x}_2) =
\lambda_2\,(\mathbf{x}_1^T\mathbf{x}_2).
\]</span> <strong>Segundo</strong>, usando que <span class="math inline">\(\mathbf{x}_1^TA\mathbf{x}_2\)</span> é um escalar <span class="math inline">\(1\times 1\)</span> (logo igual à sua própria transposta) e que <span class="math inline">\(A\)</span> é simétrica (Premissa 1): <span class="math display">\[
\mathbf{x}_1^TA\mathbf{x}_2 = (\mathbf{x}_1^TA\mathbf{x}_2)^T =
\mathbf{x}_2^TA^T\mathbf{x}_1 = \mathbf{x}_2^TA\mathbf{x}_1 =
\mathbf{x}_2^T(\lambda_1\mathbf{x}_1) = \lambda_1\,(\mathbf{x}_2^T\mathbf{x}_1).
\]</span> Como <span class="math inline">\(\mathbf{x}_1^T\mathbf{x}_2=\mathbf{x}_2^T\mathbf{x}_1\)</span> (produto interno é simétrico), as duas contas dão o mesmo escalar por dois caminhos, logo <span class="math display">\[
\lambda_2\,(\mathbf{x}_1^T\mathbf{x}_2) = \lambda_1\,(\mathbf{x}_1^T\mathbf{x}_2)
\quad\Longrightarrow\quad
(\lambda_2-\lambda_1)\,(\mathbf{x}_1^T\mathbf{x}_2) = 0.
\]</span> Pela Premissa 2, <span class="math inline">\(\lambda_2-\lambda_1\ne 0\)</span>; logo o único jeito de o produto ser zero é <span class="math inline">\(\mathbf{x}_1^T\mathbf{x}_2=0\)</span> — <strong>autovetores de autovalores distintos de uma matriz simétrica são automaticamente ortogonais</strong>. Note onde a simetria de <span class="math inline">\(A\)</span> entrou: exatamente na troca <span class="math inline">\(A^T\to A\)</span> no segundo cálculo — sem ela, os dois caminhos não coincidiriam, e é por isso que o Bloco 2 encontrou autovetores <strong>não</strong>-ortogonais numa matriz não-simétrica.</p>
</section>
<section id="o-teorema-espectral-real" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="o-teorema-espectral-real"><span class="header-section-number">4.5</span> O Teorema Espectral Real</h2>
<p>A prova acima garante ortogonalidade <strong>entre</strong> autovetores de autovalores distintos, mas o Teorema Espectral Real garante mais: que os autovalores de uma matriz simétrica são sempre <strong>reais</strong> (nunca complexos, ao contrário do que o Bloco 3 mostrou ser possível em geral), e que existe uma base ortonormal <strong>inteira</strong> feita de autovetores — mesmo quando há autovalores repetidos (caso em que a ortogonalidade entre autovetores do <em>mesmo</em> autoespaço não vem de graça da prova acima, e precisa de um processo à parte, Gram-Schmidt, que o MathML ilustra no Exemplo 4.8, sem aprofundar aqui).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema 4.15 — Teorema Espectral Real (MathML, tradução nossa, §4.2, p.&nbsp;111)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Se <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> é simétrica, existe uma base ortonormal do espaço vetorial correspondente <span class="math inline">\(V\)</span> formada por autovetores de <span class="math inline">\(A\)</span>, e cada autovalor é real.</p>
</div>
</div>
<p>O Boyd enuncia a mesma garantia de forma equivalente, já na forma matricial que vamos usar no resto da aula:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema — Forma Matricial Equivalente (Boyd &amp; Vandenberghe, tradução nossa, Apêndice A.5.2, p.&nbsp;646-647)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suponha <span class="math inline">\(A\in\mathcal{S}^n\)</span>, ou seja, <span class="math inline">\(A\)</span> é uma matriz real simétrica <span class="math inline">\(n\times n\)</span>. Então <span class="math inline">\(A\)</span> pode ser fatorada como <span class="math inline">\(A=Q\Lambda Q^T\)</span>, onde <span class="math inline">\(Q\in\mathbb{R}^{n\times n}\)</span> é ortogonal (isto é, <span class="math inline">\(Q^TQ=I\)</span>) e <span class="math inline">\(\Lambda=\text{diag}(\lambda_1,\dots,\lambda_n)\)</span>.</p>
</div>
</div>
<p>“<span class="math inline">\(Q\)</span> ortogonal” significa exatamente <span class="math inline">\(Q^TQ=I\)</span> — as colunas de <span class="math inline">\(Q\)</span> (os autovetores) formam uma base ortonormal, a mesma garantia do teorema anterior, escrita em forma de fatoração matricial: <span class="math inline">\(A=Q\Lambda Q^T\)</span> é a <strong>decomposição espectral</strong> de <span class="math inline">\(A\)</span>. Os dois teoremas acima dizem exatamente a mesma coisa, em duas notações: o MathML fala em “base do espaço vetorial <span class="math inline">\(V\)</span>”, o Boyd fala em “matriz ortogonal <span class="math inline">\(Q\)</span>” cujas colunas são essa base — a ponte entre as duas é literalmente <span class="math inline">\(Q=[\mathbf{x}_1\;\cdots\;\mathbf{x}_n]\)</span>, os autovetores empilhados como colunas.</p>
</section>
<section id="contraste-direto-exemplo-resolvido-de-uma-matriz-simétrica" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="contraste-direto-exemplo-resolvido-de-uma-matriz-simétrica"><span class="header-section-number">4.6</span> Contraste Direto: Exemplo Resolvido de uma Matriz Simétrica</h2>
<p>Para ver a diferença na prática, refazemos o cálculo à mão do Bloco 3, agora com uma matriz <strong>simétrica</strong>, <span class="math display">\[
A_{\text{sim}} = \frac12\begin{bmatrix}5 &amp; -2\\ -2 &amp; 5\end{bmatrix},
\]</span> o mesmo exemplo do MathML (tradução nossa, §4.2, Exemplo 4.11, p. 117-118): “vamos calcular a decomposição em autovalores de <span class="math inline">\(A=\frac12\begin{bmatrix}5&amp;-2\\-2&amp;5\end{bmatrix}\)</span>. […] os autovalores de <span class="math inline">\(A\)</span> são <span class="math inline">\(\lambda_1=7/2\)</span> e <span class="math inline">\(\lambda_2=3/2\)</span> […] <span class="math inline">\(\mathbf{p}_1=\frac{1}{\sqrt2}[1,-1]\)</span>, <span class="math inline">\(\mathbf{p}_2=\frac{1}{\sqrt2}[1,1]\)</span>.” Repare já na diferença mais imediata: <strong><span class="math inline">\(A_{\text{sim}}=A_{\text{sim}}^T\)</span></strong>, diferente da matriz do Bloco 2/3 (<span class="math inline">\(A\ne A^T\)</span> ali). Vamos verificar numericamente — os autovalores, e principalmente o ângulo entre os autovetores, comparado lado a lado com o exemplo não-simétrico:</p>
<div class="fig-resize" style="width: 60%; margin: 0 auto;">
<div id="02149eb1" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>autovalores_sim, autovetores_sim <span class="op">=</span> np.linalg.eigh(A_sim)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores de A_sim:"</span>, autovalores_sim)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovetores de A_sim (colunas):"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(autovetores_sim)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> angulo_entre(u, v):</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    cos_ang <span class="op">=</span> np.clip((u <span class="op">@</span> v) <span class="op">/</span> (np.linalg.norm(u) <span class="op">*</span> np.linalg.norm(v)), <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.degrees(np.arccos(cos_ang))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>ang_sim <span class="op">=</span> angulo_entre(autovetores_sim[:, <span class="dv">0</span>], autovetores_sim[:, <span class="dv">1</span>])</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>ang_nao_sim <span class="op">=</span> angulo_entre(autovetores_ex[:, <span class="dv">0</span>], autovetores_ex[:, <span class="dv">1</span>])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Ângulo entre autovetores de A_sim (simétrica):        </span><span class="sc">{</span>ang_sim<span class="sc">:.2f}</span><span class="ss"> graus"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Ângulo entre autovetores de A_exemplo (não-simétrica): </span><span class="sc">{</span>ang_nao_sim<span class="sc">:.2f}</span><span class="ss"> graus"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">A_sim é simétrica? </span><span class="sc">{</span>np<span class="sc">.</span>allclose(A_sim, A_sim.T)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"A_exemplo é simétrica? </span><span class="sc">{</span>np<span class="sc">.</span>allclose(A_exemplo, A_exemplo.T)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Autovalores de A_sim: [1.5 3.5]
Autovetores de A_sim (colunas):
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Ângulo entre autovetores de A_sim (simétrica):        90.00 graus
Ângulo entre autovetores de A_exemplo (não-simétrica): 108.43 graus

A_sim é simétrica? True
A_exemplo é simétrica? False</code></pre>
</div>
</div>
</div>
<p>Os autovalores <span class="math inline">\(3{,}5\)</span> e <span class="math inline">\(1{,}5\)</span> conferem exatamente com o MathML, e o ângulo entre os autovetores de <span class="math inline">\(A_{\text{sim}}\)</span> dá <span class="math inline">\(90°\)</span> — ortogonais, como a prova deste bloco garantiu. Já o ângulo entre os autovetores de <span class="math inline">\(A_{\text{exemplo}}\)</span> (o exemplo não-simétrico dos Blocos 2-3) fica visivelmente diferente de <span class="math inline">\(90°\)</span>. A distinção não é sutil nem coincidência de arredondamento: é exatamente a diferença entre “matriz simétrica” e “matriz qualquer” que a prova deste bloco isolou. (Chamamos <code>np.linalg.eigh</code>, não <code>np.linalg.eig</code>, porque <code>eigh</code> é a rotina especializada em matrizes simétricas — mais precisa e mais rápida, e devolve autovalores em ordem crescente por convenção; para uma matriz não-simétrica como <span class="math inline">\(A_{\text{exemplo}}\)</span>, <code>eigh</code> não seria aplicável.)</p>
<div class="fig-resize" style="width: 60%; margin: 0 auto;">
<div id="d2de72c3" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>O painel esquerdo repete as duas direções do Bloco 2/3 — visivelmente não perpendiculares. O painel direito mostra as duas direções de <span class="math inline">\(A_{\text{sim}}\)</span>, em ângulo reto exato — a mesma comparação numérica acima, agora visível.</p>
</section>
<section id="decomposição-espectral-o-caso-geral-e-o-caso-simétrico" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="decomposição-espectral-o-caso-geral-e-o-caso-simétrico"><span class="header-section-number">4.7</span> Decomposição Espectral: o Caso Geral e o Caso Simétrico</h2>
<p>Vale encaixar o Teorema Espectral Real dentro de um resultado mais geral. O MathML define a <strong>decomposição em autovalores</strong> para qualquer matriz quadrada cujos autovetores formem uma base:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema 4.20 (MathML, tradução nossa, §4.4, p.&nbsp;116)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma matriz quadrada <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> pode ser fatorada como <span class="math inline">\(A=PDP^{-1}\)</span>, onde <span class="math inline">\(P\in\mathbb{R}^{n\times n}\)</span> e <span class="math inline">\(D\)</span> é uma matriz diagonal cujas entradas são os autovalores de <span class="math inline">\(A\)</span>, se, e somente se, os autovetores de <span class="math inline">\(A\)</span> formam uma base de <span class="math inline">\(\mathbb{R}^n\)</span>.</p>
</div>
</div>
<p>Essa é a forma geral — <span class="math inline">\(P\)</span> é só invertível, não necessariamente ortogonal, e nem toda matriz quadrada admite essa fatoração (uma matriz cujos autovetores não geram todo o espaço, caso que foge do escopo desta aula, não é diagonalizável dessa forma).</p>
<p>O Teorema Espectral Real mostra que matrizes simétricas são sempre um caso particular, sempre bem-comportado, desse resultado geral:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema 4.21 (MathML, tradução nossa, §4.4, p.&nbsp;116)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma matriz simétrica <span class="math inline">\(S\in\mathbb{R}^{n\times n}\)</span> pode sempre ser diagonalizada: existe uma base ortonormal (BON) de autovetores de <span class="math inline">\(\mathbb{R}^n\)</span>, o que faz de <span class="math inline">\(P\)</span> (a matriz cujas colunas são essa base) uma matriz ortogonal, de modo que <span class="math inline">\(D=P^TAP\)</span>.</p>
</div>
</div>
<p>Trocando a notação <span class="math inline">\(P\to Q\)</span> (a convenção do Boyd, que usamos daqui em diante) e isolando <span class="math inline">\(A\)</span>: <span class="math inline">\(D=Q^TAQ \iff A=QDQ^T\)</span> (usando <span class="math inline">\(Q^{-1}=Q^T\)</span>, a própria definição de matriz ortogonal) — a mesma equação <span class="math inline">\(A=Q\Lambda Q^T\)</span> do Boyd. Ou seja: a decomposição espectral não é um resultado à parte da decomposição em autovalores geral, é o caso especial em que a simetria garante diagonalização <strong>sempre</strong>, com uma matriz de mudança de base <strong>ortogonal</strong>, nunca só invertível.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O Teorema 4.21 garante autovetores ortogonais para autovalores distintos. Se um autovalor de uma matriz simétrica aparece repetido, os autovetores associados a ele nunca podem ser escolhidos ortogonais entre si?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no caso mais extremo de repetição — todos os <span class="math inline">\(n\)</span> autovalores de <span class="math inline">\(A\)</span> iguais entre si. Quantos autovetores independentes isso deixa?</p>
<ul>
<li>□ Como a prova deste bloco só cobre autovalores <strong>distintos</strong>, isso significa que autovetores associados ao <strong>mesmo</strong> autovalor (repetido) de uma matriz simétrica nunca podem ser escolhidos ortogonais entre si.</li>
<li>□ Se uma matriz simétrica <span class="math inline">\(A\)</span> tivesse <strong>todos</strong> os autovalores iguais entre si (ex.: <span class="math inline">\(A=3I\)</span>), então <strong>qualquer</strong> vetor não-nulo de <span class="math inline">\(\mathbb{R}^n\)</span> seria autovetor de <span class="math inline">\(A\)</span>, e qualquer base ortonormal de <span class="math inline">\(\mathbb{R}^n\)</span> serviria como conjunto de autovetores ortogonais.</li>
<li>□ Na matriz de covariância dos atributos de um dataset de aprendizado de máquina (ex.: os <span class="math inline">\(30\)</span> atributos do Breast Cancer Wisconsin), se dois autovalores dessa matriz forem exatamente iguais, os dois eixos principais de PCA correspondentes não são unicamente determinados — qualquer rotação dentro do plano gerado por eles também é uma escolha ortogonal válida.</li>
<li>□ Se a demonstração deste bloco cobrisse autovalores repetidos diretamente (não só distintos), a conclusão do Teorema 4.21 mudaria: matrizes simétricas com autovalores repetidos deixariam de ser sempre diagonalizáveis ortogonalmente.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="definitude-positiva-o-sinal-dos-autovalores" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Definitude Positiva: o Sinal dos Autovalores</h1>
<hr>
<section id="retomando-a-forma-quadrática-da-aula-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="retomando-a-forma-quadrática-da-aula-1"><span class="header-section-number">5.1</span> Retomando a Forma Quadrática da Aula 1</h2>
<p>A Aula 1 já usou a forma quadrática <span class="math inline">\(\mathbf{x}^TA\mathbf{x}\)</span> (dentro do produto interno geral) sem nomear a propriedade central deste bloco: o <strong>sinal</strong> dessa expressão, para todo <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>, classifica a matriz simétrica <span class="math inline">\(A\)</span>. O MathML define (tradução nossa, §3.2.3, Definição 3.4, p.&nbsp;74):</p>
<blockquote class="blockquote">
<p>“Uma matriz simétrica <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span> que satisfaz […] <span class="math inline">\(\mathbf{x}^TA\mathbf{x}&gt;0\)</span> para todo <span class="math inline">\(\mathbf{x}\in V\setminus
\{\mathbf{0}\}\)</span> é chamada simétrica, definida positiva, ou apenas <strong>positiva definida</strong>. Se vale apenas <span class="math inline">\(\ge\)</span> […], então <span class="math inline">\(A\)</span> é chamada simétrica, <strong>semidefinida positiva</strong>.”</p>
</blockquote>
<p>E resolve, no próprio texto, dois exemplos que vamos reaproveitar (tradução nossa, mesma seção, Exemplo 3.4): “considere as matrizes <span class="math inline">\(A_1=\begin{bmatrix}9&amp;6\\6&amp;5\end{bmatrix}\)</span>, <span class="math inline">\(A_2=\begin{bmatrix}9&amp;6\\6&amp;3\end{bmatrix}\)</span>. <span class="math inline">\(A_1\)</span> é definida positiva porque é simétrica e <span class="math inline">\(\mathbf{x}^TA_1\mathbf{x}=9x_1^2+12x_1x_2+5x_2^2=(3x_1+2x_2)^2+x_2^2&gt;0\)</span> para todo <span class="math inline">\(\mathbf{x}\in V\setminus\{\mathbf{0}\}\)</span>. Em contraste, <span class="math inline">\(A_2\)</span> é simétrica mas não é definida positiva porque <span class="math inline">\(\mathbf{x}^TA_2\mathbf{x}=9x_1^2+12x_1x_2+3x_2^2=(3x_1+2x_2)^2-x_2^2\)</span> pode ser menor que <span class="math inline">\(0\)</span>, por exemplo, para <span class="math inline">\(\mathbf{x}=[2,-3]^T\)</span>.”</p>
</section>
<section id="a-ponte-definitude-via-o-sinal-dos-autovalores" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="a-ponte-definitude-via-o-sinal-dos-autovalores"><span class="header-section-number">5.2</span> A Ponte: Definitude Via o Sinal dos Autovalores</h2>
<p>Testar o sinal de <span class="math inline">\(\mathbf{x}^TA\mathbf{x}\)</span> para <strong>todo</strong> <span class="math inline">\(\mathbf{x}\)</span> não parece, à primeira vista, uma tarefa finita — são infinitos vetores para checar. O Teorema Espectral Real do Bloco 4 dá exatamente a saída: como <span class="math inline">\(A\)</span> simétrica se escreve <span class="math inline">\(A=Q\Lambda Q^T\)</span>, qualquer <span class="math inline">\(\mathbf{x}\)</span> se decompõe na base ortonormal de <span class="math inline">\(Q\)</span>, e a forma quadrática vira uma soma ponderada pelos autovalores — o sinal de <span class="math inline">\(\mathbf{x}^TA\mathbf{x}\)</span> para <strong>todo</strong> <span class="math inline">\(\mathbf{x}\)</span> passa a depender só do sinal dos <span class="math inline">\(n\)</span> autovalores, não de infinitos vetores. O Boyd enuncia essa equivalência diretamente (tradução nossa, Apêndice A.5.2, p.&nbsp;646-647): “vemos que <span class="math inline">\(A\succ 0\)</span> se, e somente se, todos os seus autovalores são positivos, ou seja, <span class="math inline">\(\lambda_{\min}(A)&gt;0\)</span>.” (A notação <span class="math inline">\(A\succ 0\)</span> é a forma compacta de “<span class="math inline">\(A\)</span> é definida positiva”; <span class="math inline">\(A\succeq 0\)</span>, semidefinida positiva.) Verificando nos mesmos <span class="math inline">\(A_1\)</span>, <span class="math inline">\(A_2\)</span> do MathML:</p>
<div id="3038009f" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>A1 <span class="op">=</span> np.array([[<span class="fl">9.0</span>, <span class="fl">6.0</span>], [<span class="fl">6.0</span>, <span class="fl">5.0</span>]])</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>A2 <span class="op">=</span> np.array([[<span class="fl">9.0</span>, <span class="fl">6.0</span>], [<span class="fl">6.0</span>, <span class="fl">3.0</span>]])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>autoval_A1 <span class="op">=</span> np.linalg.eigh(A1)[<span class="dv">0</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>autoval_A2 <span class="op">=</span> np.linalg.eigh(A2)[<span class="dv">0</span>]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores de A1:"</span>, autoval_A1, <span class="st">"-&gt; definida positiva?"</span>, np.<span class="bu">all</span>(autoval_A1 <span class="op">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores de A2:"</span>, autoval_A2, <span class="st">"-&gt; definida positiva?"</span>, np.<span class="bu">all</span>(autoval_A2 <span class="op">&gt;</span> <span class="dv">0</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Autovalores de A1: [ 0.67544468 13.32455532] -&gt; definida positiva? True
Autovalores de A2: [-0.70820393 12.70820393] -&gt; definida positiva? False</code></pre>
</div>
</div>
<p><span class="math inline">\(A_1\)</span> tem os dois autovalores positivos — definida positiva, confirmando o exemplo resolvido do MathML sem precisar testar infinitos <span class="math inline">\(\mathbf{x}\)</span>. <span class="math inline">\(A_2\)</span> tem um autovalor negativo — a mesma informação que o contraexemplo <span class="math inline">\(\mathbf{x}=(2,-3)\)</span> já tinha revelado, mas agora visível de antemão, olhando só para a matriz.</p>
</section>
<section id="intuição-geométrica-o-formato-da-tigela" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="intuição-geométrica-o-formato-da-tigela"><span class="header-section-number">5.3</span> Intuição Geométrica: o Formato da Tigela</h2>
<p>Vale conectar essa ideia a uma imagem: a forma quadrática <span class="math inline">\(f(\mathbf{x})=\mathbf{x}^TA\mathbf{x}\)</span>, vista como uma função de <span class="math inline">\(\mathbf{x}\in\mathbb{R}^2\)</span>, desenha uma superfície. Quando <span class="math inline">\(A\)</span> é definida positiva, essa superfície tem o formato de uma tigela — um único mínimo na origem, subindo em toda direção. Quando <span class="math inline">\(A\)</span> é indefinida (nem positiva nem negativa definida, o caso de <span class="math inline">\(A_2\)</span>), a superfície tem formato de sela: sobe em algumas direções, desce em outras — exatamente consistente com <span class="math inline">\(\mathbf{x}^TA_2\mathbf{x}\)</span> trocar de sinal.</p>
<div class="fig-resize" style="width: 85%; margin: 0 auto;">
<div id="0071f156" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-8-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>No painel esquerdo (<span class="math inline">\(A_1\)</span>), as curvas de nível são elipses concêntricas crescendo em todas as direções a partir da origem — nenhuma curva de nível zero aparece porque o valor mínimo, zero, só é atingido em <span class="math inline">\(\mathbf{x}=\mathbf{0}\)</span>. No painel direito (<span class="math inline">\(A_2\)</span>), a linha vermelha marca onde <span class="math inline">\(\mathbf{x}^TA_2\mathbf{x}=0\)</span> — e o mapa de cores muda de azul (positivo) para vermelho (negativo) atravessando essa linha, o retrato visual direto de “indefinida”.</p>
</section>
<section id="o-quociente-de-rayleigh-isolando-lambda_max-e-lambda_min" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="o-quociente-de-rayleigh-isolando-lambda_max-e-lambda_min"><span class="header-section-number">5.4</span> O Quociente de Rayleigh: Isolando <span class="math inline">\(\lambda_{\max}\)</span> e <span class="math inline">\(\lambda_{\min}\)</span></h2>
<p>Falta uma última peça para fechar exatamente o número de condição: uma forma de isolar o <strong>maior</strong> e o <strong>menor</strong> autovalor de <span class="math inline">\(A\)</span> diretamente da forma quadrática, sem calcular todos os autovalores primeiro. O Boyd define essa peça — o <strong>quociente de Rayleigh</strong> — e prova a desigualdade que o conecta à forma quadrática (tradução nossa, Apêndice A.5.2, p. 646-647):</p>
<blockquote class="blockquote">
<p>“O maior e o menor autovalor satisfazem <span class="math inline">\(\lambda_{\max}(A)=\sup_{\mathbf{x}\ne 0}
\frac{\mathbf{x}^TA\mathbf{x}}{\mathbf{x}^T\mathbf{x}}\)</span>, <span class="math inline">\(\lambda_{\min}(A)=\inf_{\mathbf{x}\ne 0}
\frac{\mathbf{x}^TA\mathbf{x}}{\mathbf{x}^T\mathbf{x}}\)</span>. Em particular, para qualquer <span class="math inline">\(\mathbf{x}\)</span>, temos <span class="math inline">\(\lambda_{\min}(A)\,\mathbf{x}^T\mathbf{x}\le\mathbf{x}^TA\mathbf{x}
\le\lambda_{\max}(A)\,\mathbf{x}^T\mathbf{x}\)</span>.”</p>
</blockquote>
<p>A prova é uma aplicação direta do Teorema Espectral: decompondo <span class="math inline">\(\mathbf{x}=\sum_i c_i\mathbf{q}_i\)</span> na base ortonormal de autovetores (<span class="math inline">\(\mathbf{q}_i\)</span>, colunas de <span class="math inline">\(Q\)</span>), a forma quadrática vira <span class="math inline">\(\mathbf{x}^TA\mathbf{x}=\sum_i\lambda_ic_i^2\)</span> e a norma <span class="math inline">\(\mathbf{x}^T\mathbf{x}=\sum_ic_i^2\)</span> — o quociente <span class="math inline">\(\frac{\sum_i\lambda_ic_i^2}{\sum_ic_i^2}\)</span> é, literalmente, uma <strong>média ponderada</strong> dos autovalores (pesos <span class="math inline">\(c_i^2\ge 0\)</span>), e toda média ponderada fica entre o menor e o maior valor pesado. É exatamente essa média ponderada que dá nome ao quociente.</p>
</section>
<section id="o-número-de-condição-agora-exato" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="o-número-de-condição-agora-exato"><span class="header-section-number">5.5</span> O Número de Condição, Agora Exato</h2>
<p>Essa é a peça que fecha, com precisão, o ciclo aberto na Aula 3. O Boyd define (tradução nossa, Apêndice A.5.2, p.&nbsp;649): “o número de condição de uma matriz não-singular <span class="math inline">\(A\in\mathbb{R}^{n\times n}\)</span>, denotado <span class="math inline">\(\text{cond}(A)\)</span> ou <span class="math inline">\(\kappa(A)\)</span>, é definido como <span class="math inline">\(\text{cond}(A)=\|A\|_2\|A^{-1}\|_2=\sigma_{\max}(A)/\sigma_{\min}(A)\)</span>” — uma definição em termos de valores singulares <span class="math inline">\(\sigma\)</span>, que se aplica a qualquer matriz (mesmo retangular). Para uma matriz <strong>simétrica</strong> definida positiva (o caso de <span class="math inline">\(X^TX\)</span> sob posto completo), os valores singulares coincidem exatamente com os autovalores (todos positivos), e a definição colapsa para <span class="math display">\[
\text{cond}(A) = \frac{\lambda_{\max}(A)}{\lambda_{\min}(A)}.
\]</span> Essa é a fórmula que faltava desde a Aula 3: o número de condição de <span class="math inline">\(X^TX\)</span> não precisa ser estimado perturbando os dados — é, literalmente, a razão entre o maior e o menor autovalor de <span class="math inline">\(X^TX\)</span>, calculável de uma só vez via <code>numpy.linalg.eigh</code>. O Bloco 6 aplica exatamente essa fórmula aos mesmos números que a Aula 3 só tinha medido empiricamente.</p>
</section>
<section id="ponte-breve-sem-aprofundar-hessiana-e-convexidade" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="ponte-breve-sem-aprofundar-hessiana-e-convexidade"><span class="header-section-number">5.6</span> Ponte Breve (Sem Aprofundar): Hessiana e Convexidade</h2>
<p>Vale uma menção, sem desenvolver agora: a mesma forma quadrática <span class="math inline">\(\mathbf{x}^TA\mathbf{x}\)</span> que classifica <span class="math inline">\(A\)</span> aqui é, literalmente, a segunda derivada (Hessiana) de uma função quadrática — e definitude positiva da Hessiana é exatamente a condição que caracteriza convexidade (um único mínimo, sem sela nem máximo espúrio), tema formal da Aula 7 desta disciplina. A Aula 3 já usou isso de relance, sem nomear: a Hessiana <span class="math inline">\(2X^TX\)</span> da função de mínimos quadrados era sempre semidefinida positiva, o que garantia convexidade e, portanto, que a condição de gradiente-zero das Equações Normais era suficiente para um mínimo global — o mesmo raciocínio deste bloco, aplicado antes de ter o nome.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(\lambda_{\min}(A)\)</span> estivesse muito próximo de zero (mas ainda positivo), o que aconteceria com o número de condição, mesmo <span class="math inline">\(A\)</span> continuando definida positiva?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia a fórmula <span class="math inline">\(\text{cond}(A)=\lambda_{\max}(A)/\lambda_{\min}(A)\)</span> — o que acontece com uma fração quando o denominador tende a zero?</p>
<ul>
<li>□ Se <span class="math inline">\(\lambda_{\min}(A)\)</span> estivesse muito próximo de zero, mas ainda estritamente positivo, o número de condição de <span class="math inline">\(A\)</span> ficaria muito grande, mesmo com <span class="math inline">\(A\)</span> continuando definida positiva (todos os autovalores positivos).</li>
<li>□ Se todos os autovalores de uma matriz simétrica <span class="math inline">\(A\)</span> fossem iguais entre si (<span class="math inline">\(A=cI\)</span>, <span class="math inline">\(c&gt;0\)</span>), o número de condição de <span class="math inline">\(A\)</span> seria necessariamente igual a <span class="math inline">\(1\)</span>, o menor valor possível.</li>
<li>□ Na Hessiana da função de perda usada para treinar uma regressão logística, um número de condição muito alto sinalizaria o mesmo tipo de sensibilidade numérica discutida aqui (ex.: gradiente descendente convergindo muito devagar em certas direções), mesmo fora do contexto de regressão linear.</li>
<li>□ Como o quociente de Rayleigh é uma média ponderada dos autovalores, isso implica que o quociente <span class="math inline">\(\mathbf{x}^TA\mathbf{x}/\mathbf{x}^T
\mathbf{x}\)</span> é sempre igual à média aritmética simples dos autovalores, qualquer que seja <span class="math inline">\(\mathbf{x}\)</span>.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="aplicação-e-verificação-no-dado-real" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Aplicação e Verificação no Dado Real</h1>
<hr>
<section id="recalculando-o-número-de-condição-da-aula-3-agora-exato" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="recalculando-o-número-de-condição-da-aula-3-agora-exato"><span class="header-section-number">6.1</span> Recalculando o Número de Condição da Aula 3 — Agora Exato</h2>
<p>Chegou a hora de fechar o ciclo prometido no início desta aula. Reaproveitando exatamente <span class="math inline">\(X^TX\)</span> da Aula 3 — os mesmos 4 atributos completos e os mesmos dois pares na amostra de 20 bairros — vamos calcular os autovalores exatos via <code>numpy.linalg.eigh</code> (a rotina especializada em matrizes simétricas, já usada no Bloco 4) e confirmar que a razão <span class="math inline">\(\lambda_{\max}/\lambda_{\min}\)</span> reproduz, número por número, os números que a Aula 3 só tinha obtido via <code>np.linalg.cond</code> e perturbação:</p>
<div id="599d5ed2" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>X_completo <span class="op">=</span> _housing[COLS].to_numpy()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>XtX <span class="op">=</span> X_completo.T <span class="op">@</span> X_completo</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>autoval_XtX, autovec_XtX <span class="op">=</span> np.linalg.eigh(XtX)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>cond_completo_exato <span class="op">=</span> autoval_XtX.<span class="bu">max</span>() <span class="op">/</span> autoval_XtX.<span class="bu">min</span>()</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores de X^T X (4 atributos, ordem crescente):"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(autoval_XtX)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">cond(X^T X) via autovalores exatos: </span><span class="sc">{</span>cond_completo_exato<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond(X^T X) via np.linalg.cond (Aula 3): </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(XtX)<span class="sc">:,.1f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Autovalores de X^T X (4 atributos, ordem crescente):
[7.47253320e+02 5.26660328e+04 2.73990283e+05 1.75309388e+07]

cond(X^T X) via autovalores exatos: 23,460.5
cond(X^T X) via np.linalg.cond (Aula 3): 23,460.5</code></pre>
</div>
</div>
<p>Os dois números coincidem até a primeira casa decimal — <span class="math inline">\(\text{cond}(X^TX)\approx 23\,460{,}5\)</span>, exatamente o valor que a Aula 3 tinha medido de forma indireta (<code>np.linalg.cond</code>, que por baixo dos panos já usa os valores singulares — para uma matriz simétrica PSD como <span class="math inline">\(X^TX\)</span>, os mesmos autovalores calculados aqui). A diferença é que agora sabemos <strong>de onde</strong> esse número vem: da razão entre o maior autovalor (<span class="math inline">\(\approx 1{,}75\times 10^7\)</span>) e o menor (<span class="math inline">\(\approx 747\)</span>) de <span class="math inline">\(X^TX\)</span> — uma propriedade da própria matriz, não do resultado de nenhuma perturbação. Repetindo para os dois pares de 20 bairros:</p>
<div id="15ebaf8f" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>_amostra_20 <span class="op">=</span> _housing.sample(n<span class="op">=</span><span class="dv">20</span>, random_state<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>X_quase_dep <span class="op">=</span> _amostra_20[[<span class="st">"AveRooms"</span>, <span class="st">"AveBedrms"</span>]].to_numpy()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>X_bem_cond <span class="op">=</span> _amostra_20[[<span class="st">"MedInc"</span>, <span class="st">"HouseAge"</span>]].to_numpy()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>autoval_qd <span class="op">=</span> np.linalg.eigh(X_quase_dep.T <span class="op">@</span> X_quase_dep)[<span class="dv">0</span>]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>autoval_bc <span class="op">=</span> np.linalg.eigh(X_bem_cond.T <span class="op">@</span> X_bem_cond)[<span class="dv">0</span>]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>cond_qd_exato <span class="op">=</span> autoval_qd.<span class="bu">max</span>() <span class="op">/</span> autoval_qd.<span class="bu">min</span>()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>cond_bc_exato <span class="op">=</span> autoval_bc.<span class="bu">max</span>() <span class="op">/</span> autoval_bc.<span class="bu">min</span>()</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores de X^T X (AveRooms, AveBedrms):"</span>, autoval_qd)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond exato (quase-colinear):    </span><span class="sc">{</span>cond_qd_exato<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovalores de X^T X (MedInc, HouseAge):    "</span>, autoval_bc)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond exato (bem-condicionado):  </span><span class="sc">{</span>cond_bc_exato<span class="sc">:,.1f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Autovalores de X^T X (AveRooms, AveBedrms): [  1.76730921 741.96132008]
cond exato (quase-colinear):    419.8

Autovalores de X^T X (MedInc, HouseAge):     [  139.61748016 23613.01422068]
cond exato (bem-condicionado):  169.1</code></pre>
</div>
</div>
<p>Os três números reproduzem exatamente os valores da Aula 3: <span class="math inline">\(\text{cond}(X^TX)\approx 419{,}8\)</span> para o par quase-colinear e <span class="math inline">\(\approx 169{,}1\)</span> para o par bem-condicionado — mais que o dobro de diferença, agora explicado, não só medido. A resposta à pergunta do Bloco 1 (“existe alguma propriedade de <span class="math inline">\(X^TX\)</span> calculável sem perturbar nada que já anteciparia a fragilidade?”) é, enfim, sim: o menor autovalor de <span class="math inline">\(X^TX\)</span> para o par quase-colinear (<span class="math inline">\(\approx 1{,}77\)</span>) é minúsculo perto do maior (<span class="math inline">\(\approx 742\)</span>) — um sintoma direto de que uma das direções do espaço gerado pelas duas colunas quase não é “vista” pela matriz, exatamente a direção em que <code>AveRooms</code> e <code>AveBedrms</code> praticamente coincidem. Já no par bem-condicionado, os dois autovalores (<span class="math inline">\(\approx 139{,}6\)</span> e <span class="math inline">\(\approx 23\,613{,}0\)</span>) ainda diferem bastante em escala bruta — lembrando que <code>MedInc</code> e <code>HouseAge</code> têm variâncias naturais bem diferentes —, mas a razão entre eles é quase <span class="math inline">\(2{,}5\times\)</span> menor que no par quase-colinear, o suficiente para tornar o sistema consideravelmente mais estável.</p>
</section>
<section id="uma-segunda-matriz-simétrica-psd-a-covariância-empírica" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="uma-segunda-matriz-simétrica-psd-a-covariância-empírica"><span class="header-section-number">6.2</span> Uma Segunda Matriz Simétrica PSD: a Covariância Empírica</h2>
<p><span class="math inline">\(X^TX\)</span> não é a única matriz simétrica semidefinida positiva que aparece naturalmente em dados. Outra, de natureza um pouco diferente — <strong>não</strong> mais colunas brutas, mas colunas <strong>centradas</strong> na própria média — é a <strong>matriz de covariância empírica</strong>. Para as duas colunas <code>AveRooms</code> e <code>AveBedrms</code> (o mesmo par quase-colinear de cima), a covariância mede como elas variam juntas em torno das respectivas médias:</p>
<div id="ce6881ee" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>X_cov_dados <span class="op">=</span> _housing[[<span class="st">"AveRooms"</span>, <span class="st">"AveBedrms"</span>]].to_numpy()</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>cov_empirica <span class="op">=</span> np.cov(X_cov_dados, rowvar<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Matriz de covariância (AveRooms, AveBedrms):"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cov_empirica)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">É simétrica?"</span>, np.allclose(cov_empirica, cov_empirica.T))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>autoval_cov, autovec_cov <span class="op">=</span> np.linalg.eigh(cov_empirica)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Autovalores:"</span>, autoval_cov)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Autovetores (colunas):"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(autovec_cov)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Ortogonalidade (produto interno entre os dois autovetores):"</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>      autovec_cov[:, <span class="dv">0</span>] <span class="op">@</span> autovec_cov[:, <span class="dv">1</span>])</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Matriz de covariância (AveRooms, AveBedrms):
[[7.01551552 1.17219151]
 [1.17219151 0.26163945]]

É simétrica? True

Autovalores: [0.06398052 7.21317445]
Autovetores (colunas):
[[ 0.16627604 -0.98607925]
 [-0.98607925 -0.16627604]]

Ortogonalidade (produto interno entre os dois autovetores): 0.0</code></pre>
</div>
</div>
<p>A matriz é simétrica (por construção — covariância entre <span class="math inline">\(i\)</span> e <span class="math inline">\(j\)</span> é sempre igual à covariância entre <span class="math inline">\(j\)</span> e <span class="math inline">\(i\)</span>) e semidefinida positiva (nenhum autovalor negativo, <span class="math inline">\(\approx 0{,}064\)</span> e <span class="math inline">\(\approx 7{,}213\)</span>), e os dois autovetores são ortogonais entre si até erro de arredondamento — exatamente o Teorema Espectral Real do Bloco 4 se aplicando de novo, desta vez a uma matriz de covariância, não a <span class="math inline">\(X^TX\)</span> bruta. O autovetor principal — o de <strong>maior</strong> autovalor, <span class="math inline">\(\approx (-0{,}986;-0{,}166)\)</span> (ou, de forma equivalente, <span class="math inline">\((0{,}986;0{,}166)\)</span>, já que o sinal de um autovetor não importa, Bloco 2) — aponta na direção de <strong>maior variância</strong> dos dados: geometricamente, é a direção ao longo da qual a nuvem de pontos <code>AveRooms</code>/<code>AveBedrms</code> está mais “esticada”.</p>
</section>
<section id="interpretando-o-autovetor-principal-sobre-os-dados-reais" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="interpretando-o-autovetor-principal-sobre-os-dados-reais"><span class="header-section-number">6.3</span> Interpretando o Autovetor Principal sobre os Dados Reais</h2>
<p>Vale ver essa direção sobreposta ao espalhamento real das duas variáveis, não só como um vetor abstrato:</p>
<div class="fig-resize" style="width: 75%; margin: 0 auto;">
<div id="679cb911" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-12-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>O autovetor principal (vermelho) segue quase exatamente ao longo do eixo <code>AveRooms</code> — coerente com <code>AveRooms</code> ter variância bruta bem maior que <code>AveBedrms</code> (<span class="math inline">\(\approx 7{,}02\)</span> contra <span class="math inline">\(\approx 0{,}26\)</span>, quase <span class="math inline">\(27\times\)</span>) —, mas ligeiramente inclinado na direção de <code>AveBedrms</code> positiva, refletindo a covariância positiva entre as duas (<span class="math inline">\(\approx
1{,}17\)</span>: bairros com mais cômodos por domicílio tendem a ter também mais quartos por domicílio, o que já era esperado). O autovetor secundário (laranja), ortogonal ao principal, captura a variação residual — a parte de <code>AveBedrms</code> que <strong>não</strong> é só “proporcional a <code>AveRooms</code>” —, e seu autovalor muito menor (<span class="math inline">\(\approx 0{,}064\)</span> contra <span class="math inline">\(\approx 7{,}213\)</span>) mostra que essa direção secundária carrega bem pouca informação adicional sobre a nuvem de pontos.</p>
</section>
<section id="semente-para-pca-sem-aprofundar-e-um-aviso-honesto-sobre-escala" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="semente-para-pca-sem-aprofundar-e-um-aviso-honesto-sobre-escala"><span class="header-section-number">6.4</span> Semente Para PCA (Sem Aprofundar) — e um Aviso Honesto sobre Escala</h2>
<p>O que acabamos de fazer — encontrar a direção de maior variância de um conjunto de dados via a autodecomposição da matriz de covariância — é, sem exagero nenhum, o primeiro passo da <strong>Análise de Componentes Principais</strong> (PCA), tema que a disciplina de Aprendizado Não Supervisionado desenvolve por completo; esta aula planta a semente, sem desenvolvê-la. Antes de fechar o bloco, um aviso honesto sobre um detalhe fácil de esconder: essa análise é <strong>sensível à escala</strong>. Se, em vez de só <code>AveRooms</code>/<code>AveBedrms</code>, calculássemos a covariância dos <strong>4</strong> atributos brutos, o resultado seria dominado por <code>HouseAge</code> — o atributo de maior variância numérica bruta, não necessariamente o mais “importante” para qualquer tarefa:</p>
<div id="0a0adf3a" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>X_cov4 <span class="op">=</span> _housing[COLS].to_numpy()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>cov4 <span class="op">=</span> np.cov(X_cov4, rowvar<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variância de cada atributo (diagonal da covariância):"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nome, var <span class="kw">in</span> <span class="bu">zip</span>(COLS, np.diag(cov4)):</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>nome<span class="sc">:10s}</span><span class="ss">: </span><span class="sc">{</span>var<span class="sc">:10.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>autoval_cov4 <span class="op">=</span> np.linalg.eigh(cov4)[<span class="dv">0</span>]</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Autovalores da covariância (4 atributos):"</span>, autoval_cov4)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variância de cada atributo (diagonal da covariância):
  MedInc    :     3.4862
  HouseAge  :   163.7848
  AveRooms  :     7.0155
  AveBedrms :     0.2616

Autovalores da covariância (4 atributos): [3.36605897e-02 2.96906503e+00 7.52330508e+00 1.64022194e+02]</code></pre>
</div>
</div>
<p>A variância de <code>HouseAge</code> (<span class="math inline">\(\approx 163{,}8\)</span>) é mais de <span class="math inline">\(20\times\)</span> maior que a de qualquer outro atributo — e o maior autovalor da covariância completa (<span class="math inline">\(\approx 164{,}0\)</span>) reflete quase só essa escala, não a estrutura de correlação entre os quatro atributos que de fato interessaria numa análise de PCA. É exatamente por isso que aplicar PCA a sério exige <strong>padronizar</strong> os atributos antes (subtrair a média e dividir pelo desvio-padrão de cada coluna) — sem isso, a “direção de maior variância” tende a só apontar para o atributo de maior escala numérica bruta, não para a estrutura real dos dados. Não vamos desenvolver a padronização nem o PCA aqui — só deixamos o aviso, e a ponte, explícitos.</p>
</section>
</section>
<section id="fechamento-e-ponte-para-a-aula-5" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Fechamento e Ponte para a Aula 5</h1>
<hr>
<section id="retomando-as-perguntas-de-abertura" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</h3>
<ol type="1">
<li><strong>O que é, geometricamente, um autovalor e um autovetor?</strong> Um autovetor é uma direção que uma transformação linear <span class="math inline">\(A\)</span> não gira — só estica ou encolhe (e inverte, se o autovalor for negativo); o autovalor é exatamente esse fator de escala.</li>
<li><strong>Como calcular à mão, via o polinômio característico?</strong> A equação <span class="math inline">\(A\mathbf{x}=\lambda\mathbf{x}\)</span> vira o sistema homogêneo <span class="math inline">\((A-\lambda I)\mathbf{x}=\mathbf{0}\)</span>, que só tem solução não-trivial quando <span class="math inline">\(\det(A-\lambda I)=0\)</span> — os autovalores são as raízes reais desse polinômio, os autovetores resolvem o sistema com <span class="math inline">\(\lambda\)</span> já conhecido.</li>
<li><strong>Por que toda matriz simétrica — como <span class="math inline">\(X^TX\)</span> — tem autovalores reais e autovetores ortogonais?</strong> O Teorema Espectral Real garante isso sempre; provamos a ortogonalidade entre autovalores distintos via <span class="math inline">\(\mathbf{x}_1^TA\mathbf{x}_2\)</span> calculado de duas formas, usando a simetria de <span class="math inline">\(A\)</span> exatamente no passo decisivo.</li>
<li><strong>Como sinal e razão dos autovalores definem definitude e o número de condição exato?</strong> <span class="math inline">\(A\succ 0 \iff \lambda_{\min}(A)&gt;0\)</span>; e, para <span class="math inline">\(A\)</span> simétrica definida positiva, <span class="math inline">\(\text{cond}(A)=
\lambda_{\max}(A)/\lambda_{\min}(A)\)</span> — a fórmula que o Bloco 6 usou para reproduzir, exatamente, os números que a Aula 3 só tinha medido por perturbação.</li>
</ol>
</section>
<section id="o-que-fica-em-aberto" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="o-que-fica-em-aberto">O Que Fica em Aberto</h3>
<p>Autovalores e autovetores reais, na forma garantida pelo Teorema Espectral, só existem de forma incondicional para matrizes <strong>quadradas simétricas</strong> — <span class="math inline">\(X^TX\)</span> sempre se encaixa aí, mas <span class="math inline">\(X\)</span> em si, a matriz de design retangular (<span class="math inline">\(N\ne d\)</span> linhas e colunas), não. A pergunta que fica aberta: o que fazer quando se quer decompor a própria <span class="math inline">\(X\)</span>, não <span class="math inline">\(X^TX\)</span>? A resposta é a <strong>Decomposição em Valores Singulares</strong> (SVD), tema da Aula 5 — e o Boyd já deixou uma pista, sem desenvolver: a própria definição de número de condição usada neste bloco (<span class="math inline">\(\sigma_{\max}/
\sigma_{\min}\)</span>) foi escrita em termos de <strong>valores singulares</strong>, não de autovalores — a generalização exata que a Aula 5 vai construir.</p>
<p><a href="../../../teaching/optimization-linear-algebra/aula04/exercicios.html" class="see-all exercicios-link">Exercícios</a> <a href="../../../teaching/optimization-linear-algebra/aula04/soluções.html" class="see-all solucoes-link">Soluções</a></p>
<div class="fig-resize" style="width: 65%; margin: 0 auto;">
<img src="index_files/mediabag/8e38202dd1a5c47dff875f8202bab1c23bd493af.svg" class="img-fluid">
</div>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>