<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">

<title>Revisão Integrada — O Fio Probabilístico das Aulas 1–4 – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-f6f65eecdb8abf3e35b2d2c28dbef9f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#abertura-amarrando-os-quatro-fios" id="toc-abertura-amarrando-os-quatro-fios" class="nav-link active" data-scroll-target="#abertura-amarrando-os-quatro-fios"><span class="header-section-number">1</span> Abertura — Amarrando os Quatro Fios</a></li>
  <li><a href="#bloco-1-distribuição-e-decisão-revisão-da-aula-1" id="toc-bloco-1-distribuição-e-decisão-revisão-da-aula-1" class="nav-link" data-scroll-target="#bloco-1-distribuição-e-decisão-revisão-da-aula-1"><span class="header-section-number">2</span> Bloco 1 — Distribuição e Decisão (revisão da Aula 1)</a></li>
  <li><a href="#bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" id="toc-bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" class="nav-link" data-scroll-target="#bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2"><span class="header-section-number">3</span> Bloco 2 — Independência e Teoria da Decisão (revisão da Aula 2)</a></li>
  <li><a href="#bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" id="toc-bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" class="nav-link" data-scroll-target="#bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3"><span class="header-section-number">4</span> Bloco 3 — Partição Gulosa e Verossimilhança Categórica (revisão da Aula 3)</a></li>
  <li><a href="#bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" id="toc-bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" class="nav-link" data-scroll-target="#bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4"><span class="header-section-number">5</span> Bloco 4 — Estimando o Risco que Nunca Observamos (revisão da Aula 4)</a></li>
  <li><a href="#bloco-5-síntese-as-quatro-peças-uma-estrutura" id="toc-bloco-5-síntese-as-quatro-peças-uma-estrutura" class="nav-link" data-scroll-target="#bloco-5-síntese-as-quatro-peças-uma-estrutura"><span class="header-section-number">6</span> Bloco 5 — Síntese: As Quatro Peças, Uma Estrutura</a></li>
  <li><a href="#fechamento" id="toc-fechamento" class="nav-link" data-scroll-target="#fechamento"><span class="header-section-number">7</span> Fechamento</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Revisão Integrada — O Fio Probabilístico das Aulas 1–4</h1>
<p class="subtitle lead">Revisão 1 — Distribuição, Verossimilhança e Risco: o que as Quatro Primeiras Aulas Tinham em Comum</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos M. Raimundo — Instituto de Computação, UNICAMP </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">31 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/supervised-learning/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="abertura-amarrando-os-quatro-fios" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abertura — Amarrando os Quatro Fios</h1>
<p>A Aula 4 terminou anunciando que a próxima aula construiria o primeiro modelo paramétrico do curso — regressão linear, ajustada por máxima verossimilhança sob ruído gaussiano. Essa aula ainda vai acontecer (agora como Aula 5). Antes dela, vale parar um momento, porque as quatro aulas que já demos — Beta e limiar de decisão, Naive Bayes e teoria da decisão, árvores CART, validação cruzada e Bootstrap — parecem, na superfície, quatro assuntos técnicos distintos, cada um com seu próprio algoritmo e seu próprio jargão. Não são. Por trás da fachada, as quatro usam a mesma estrutura de três peças, anunciada já no primeiro slide do curso: uma <strong>distribuição</strong> assumida sobre os dados, uma <strong>verossimilhança</strong> usada para ajustá-la aos dados observados, e uma <strong>decisão</strong> fundamentada num risco — esperado, quando é calculável exatamente, ou estimado, quando não é.</p>
<p>Esta aula não introduz nada matematicamente novo. É uma revisão organizada em torno de um único fio condutor experimental — o dataset real <em>Pima Indians Diabetes</em> — que vai atravessar, em sequência, as quatro lentes já vistas.</p>
<p><strong>O roteiro de hoje, em cinco perguntas:</strong></p>
<ol type="1">
<li>O que exatamente as quatro aulas tinham em comum, por trás da fachada de “algoritmos diferentes”?</li>
<li>Como a mesma pergunta — “qual é o formato dos dados?” — aparece disfarçada em Beta, Naive Bayes e árvore de decisão?</li>
<li>Por que “maximizar verossimilhança” e “minimizar impureza/erro” são, estruturalmente, a mesma operação?</li>
<li>Por que nunca observamos o risco de verdade — só conseguimos estimá-lo — e o que a Aula 4 fez sobre isso?</li>
<li>Que peça ainda falta para completar o quadro, e é isso que a Aula 5 resolve?</li>
</ol>
<p><strong>O problema motivador.</strong> <em>Pima Indians Diabetes</em> é um dataset real de 768 pacientes, com oito atributos clínicos (glicose, pressão, IMC, idade etc.) e um alvo binário — diabético ou não. Nenhuma das Aulas 1–4 usou exatamente este dataset (a Aula 1 usou Beta sintética; as Aulas 2 e 4 usaram <em>Breast Cancer Wisconsin</em>; a Aula 3 usou <em>California Housing</em>). É precisamente por isso que ele serve bem hoje: vamos usar o <strong>mesmo</strong> par de atributos (Glicose e IMC) nas quatro lentes, uma de cada vez, para deixar visível o que muda entre elas — e, mais importante, o que <strong>não</strong> muda.</p>
<div id="8e400357" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>N após limpeza: 752  (diabéticos: 264, não-diabéticos: 488, prevalência: 35.1%)</code></pre>
</div>
</div>
<p>Depois de remover os códigos de valor ausente (<code>Glucose==0</code>, <code>BMI==0</code> — nenhum paciente vivo tem glicose ou IMC zero, então zero aqui significa “não medido”, não “medido e igual a zero”), restam 752 pacientes: 264 diabéticos e 488 não-diabéticos, prevalência de 35,1%. Guarde esse número — ele vai reaparecer no Bloco 1 como a priori real deste problema, contrastando com a priori sintética de 95%/5% que a Aula 1 usou para deixar o efeito bem exagerado e visível.</p>
</section>
<section id="bloco-1-distribuição-e-decisão-revisão-da-aula-1" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Bloco 1 — Distribuição e Decisão (revisão da Aula 1)</h1>
<p>A Aula 1 nunca mencionou “diabetes”: trabalhou com duas populações sintéticas em uma única variável <span class="math inline">\(x \in [0,1]\)</span>, geradas por <span class="math inline">\(\text{Beta}(2,5)\)</span> (classe A) e <span class="math inline">\(\text{Beta}(6,3)\)</span> (classe B), numa proporção deliberadamente extrema de <span class="math inline">\(\pi_A=0{,}95\)</span> contra <span class="math inline">\(\pi_B=0{,}05\)</span>. A turma respondeu, intuitivamente, que o corte ótimo entre as duas classes deveria ficar <strong>no cruzamento das curvas condicionais</strong> <span class="math inline">\(p(x\mid\mathcal{C}_A)\)</span> e <span class="math inline">\(p(x\mid\mathcal{C}_B)\)</span> — e essa resposta se revelou errada: o corte que minimiza o erro total é o cruzamento das <strong>conjuntas</strong> <span class="math inline">\(p(x\mid\mathcal{C}_k)\,\pi_k\)</span>, que pondera cada densidade pela frequência real da sua classe. A mesma lição reapareceu, no caso discreto, na triagem médica de DLFC: com sensibilidade <span class="math inline">\(90\%\)</span>, falso positivo <span class="math inline">\(3\%\)</span> e prevalência de apenas <span class="math inline">\(1\%\)</span>, um teste positivo ainda deixa a probabilidade de doença em apenas <span class="math inline">\(23\%\)</span> — a priori baixa, não a verossimilhança alta, é quem decide.</p>
<p>Hoje, a mesma máquina — ajuste de Beta por classe, comparação de cruzamentos — roda sobre um dado real: a coluna <strong>Glicose</strong> do Pima Indians Diabetes, separada por diabético/não-diabético.</p>
<div id="4c3f6f28" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Beta ajustada | não-diabético: a=3.49, b=4.50   |   diabético: a=3.18, b=1.78
priori real: pi(não-diabético)=0.649, pi(diabético)=0.351</code></pre>
</div>
</div>
<p>O ajuste (via <code>scipy.stats.beta.fit</code>, o mesmo estimador de máxima verossimilhança usado na Aula 1 — sem forma fechada simples, porque as estatísticas suficientes da Beta são <span class="math inline">\(\sum\ln x_n\)</span> e <span class="math inline">\(\sum\ln(1-x_n)\)</span>, não a média aritmética) dá <span class="math inline">\(\text{Beta}(3{,}49,\,4{,}50)\)</span> para não-diabéticos e <span class="math inline">\(\text{Beta}(3{,}18,\,1{,}78)\)</span> para diabéticos: a curva dos diabéticos é visivelmente deslocada para glicoses mais altas, exatamente como o exame clínico sugere.</p>
<p>A priori real aqui é <span class="math inline">\(\pi(\text{não-diabético}) \approx 0{,}649\)</span> e <span class="math inline">\(\pi(\text{diabético}) \approx 0{,}351\)</span> — assimétrica, mas <strong>muito</strong> menos extrema do que os <span class="math inline">\(0{,}95/0{,}05\)</span> sintéticos da Aula 1. Isso já é uma primeira lição sobre a diferença entre laboratório e mundo real: a Aula 1 escolheu uma assimetria extrema de propósito, para que o efeito do deslocamento do corte fosse visualmente óbvio; o mundo real raramente é tão gentil.</p>
<div id="0aaff8f4" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t_cond = 134.2 mg/dL -&gt; 81 alarmes falsos + 116 escapes = 197 erros
t_conj = 148.3 mg/dL -&gt; 37 alarmes falsos + 157 escapes = 194 erros</code></pre>
</div>
</div>
<p>O cruzamento das condicionais cai em <span class="math inline">\(134{,}2\)</span> mg/dL, produzindo <span class="math inline">\(81\)</span> alarmes falsos e <span class="math inline">\(116\)</span> escapes (<span class="math inline">\(197\)</span> erros no total). Pesando cada curva pela priori real, o cruzamento das conjuntas se desloca para <span class="math inline">\(148{,}3\)</span> mg/dL — mais alarmes falsos evitados às custas de mais escapes, mas o total cai para <span class="math inline">\(194\)</span> erros. O princípio geométrico é <em>idêntico</em> ao da Aula 1 (<span class="math inline">\(x \in \mathcal{R}_A \iff p(x,\mathcal{C}_A) &gt; p(x,\mathcal{C}_B)\)</span>, PRML eqs. 1.78–1.79): decidir pela conjunta maior é decidir pela posteriori maior, porque a evidência <span class="math inline">\(p(x)\)</span> não depende de <span class="math inline">\(k\)</span>. A diferença é de <strong>magnitude</strong>, não de mecanismo: com prioris <span class="math inline">\(65\%/35\%\)</span>, o deslocamento do corte e o ganho em erros totais são modestos (<span class="math inline">\(197 \to 194\)</span>), bem mais discretos do que a virada dramática que a razão <span class="math inline">\(19\)</span> para <span class="math inline">\(1\)</span> da Aula 1 produzia. Isso não é uma falha do princípio — é exatamente o que se espera quando a assimetria de classes é ela mesma mais moderada.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se a prevalência de diabetes nesta população fosse exatamente <span class="math inline">\(50\%\)</span>, o que aconteceria com a distância entre o cruzamento das condicionais e o cruzamento das conjuntas?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no papel exato que <span class="math inline">\(\pi_k\)</span> desempenha na equação <span class="math inline">\(p(x,\mathcal{C}_k) = p(x\mid\mathcal{C}_k)\,\pi_k\)</span> quando <span class="math inline">\(\pi_A=\pi_B\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Prioris, Cruzamentos e o Caso Real
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a prevalência real fosse exatamente <span class="math inline">\(50\%/50\%\)</span>, o cruzamento das condicionais e o cruzamento das conjuntas coincidiriam exatamente, e a distinção entre os dois deixaria de ter qualquer efeito prático.</li>
<li>□ Como a razão de prioris hoje (<span class="math inline">\(65/35 \approx 1{,}86\)</span>) é muito menor que a da Aula 1 (<span class="math inline">\(95/5 = 19\)</span>), o deslocamento do corte hoje é necessariamente menor em termos absolutos de mg/dL, mas o argumento matemático que o produz é o mesmo.</li>
<li>□ Num exame de triagem para uma doença ainda mais rara que a prevalência de <span class="math inline">\(1\%\)</span> usada no exemplo da DLFC — digamos, <span class="math inline">\(0{,}01\%\)</span> — o efeito “sensibilidade alta não implica probabilidade pós-teste alta” ficaria ainda mais pronunciado, não menos.</li>
<li>□ Já que o corte pela conjunta reduziu o número total de erros (<span class="math inline">\(197 \to 194\)</span>), ele necessariamente reduziu tanto o número de alarmes falsos quanto o número de escapes, individualmente.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Bloco 2 — Independência e Teoria da Decisão (revisão da Aula 2)</h1>
<p>A Aula 2 generalizou o Bloco 1 de duas formas ao mesmo tempo: de uma variável para <span class="math inline">\(d\)</span> variáveis, e de um limiar simples para uma teoria da decisão completa (perda <span class="math inline">\(L(k,a)\)</span>, risco posterior <span class="math inline">\(\rho(a\mid x) = \sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span>, risco de Bayes <span class="math inline">\(R^\star\)</span>). A ponte entre as duas foi o Naive Bayes: assumir independência condicional entre atributos dado a classe, <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k) = \prod_i p(x_i\mid\mathcal{C}_k)\)</span>, para não precisar estimar uma densidade conjunta em <span class="math inline">\(d\)</span> dimensões com poucos dados. No <em>Breast Cancer Wisconsin</em>, essa suposição teve um preço mensurável: os atributos <code>smoothness_mean</code> e <code>concavity_mean</code> tinham correlação intra-classe de <span class="math inline">\(0{,}64\)</span> nos tumores malignos e <span class="math inline">\(0{,}22\)</span> nos benignos, e ignorar essa correlação (covariância diagonal, Naive Bayes) custou cerca de <span class="math inline">\(2\)</span> pontos percentuais de acurácia (<span class="math inline">\(85\%\)</span> contra <span class="math inline">\(87\%\)</span> da Gaussiana de covariância plena).</p>
<p>Hoje, acrescentamos <strong>IMC</strong> à Glicose do Pima e repetimos exatamente essa comparação.</p>
<div id="8c028364" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>correlação Glicose x IMC | não-diabético: 0.123   |   diabético: 0.057
acurácia cov. plena: 0.7646   |   acurácia Naive Bayes (diagonal): 0.7646</code></pre>
</div>
</div>
<p>A correlação intra-classe entre Glicose e IMC é <span class="math inline">\(0{,}123\)</span> nos não-diabéticos e <span class="math inline">\(0{,}057\)</span> nos diabéticos — bem mais baixa do que os <span class="math inline">\(0{,}64/0{,}22\)</span> do <em>Breast Cancer Wisconsin</em>. E o resultado bate com a expectativa: as acurácias de covariância plena e diagonal são <strong>idênticas até a quarta casa decimal</strong> (<span class="math inline">\(76{,}46\%\)</span>), porque com correlação tão baixa, as elipses de covariância plena já são quase circulares — a covariância diagonal não está descartando quase nenhuma informação real. Este é o ponto que a Aula 2 já havia adiantado, citando Domingos &amp; Pazzani (1997) via PRML §8.2.2: “classifica bem, estima mal”. Aqui completamos a lição: o preço da suposição de independência <strong>não é uma constante do método</strong> — é uma função de quanto os atributos realmente covariam dentro de cada classe. No <em>Breast Cancer Wisconsin</em> o preço foi de <span class="math inline">\(2\)</span> pontos; aqui, foi de zero.</p>
<p>Vale também lembrar a peça que a Aula 2 empilhou por cima do Naive Bayes: a teoria da decisão geral. Numa triagem de diabetes, o custo de um <strong>escape</strong> (diabético não identificado, que não recebe tratamento) tipicamente excede o custo de um <strong>alarme falso</strong> (paciente saudável encaminhado para um exame extra). O limiar de decisão ótimo sob essa assimetria de custos não é o de <span class="math inline">\(0{,}5\)</span> de probabilidade posterior — desloca-se para favorecer detectar mais diabéticos às custas de mais alarmes falsos, exatamente pela mesma lógica de <span class="math inline">\(\rho(a\mid x) = \sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span> que a Aula 2 formalizou.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se Glicose e IMC fossem perfeitamente correlacionados dentro de cada classe (<span class="math inline">\(\rho=1\)</span>), a Gaussiana de covariância plena e o Naive Bayes ainda coincidiriam?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que a covariância diagonal literalmente descarta, e no que sobra quando ela descarta tudo que existe para descartar.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Naive Bayes: Quando a Independência Custa Caro
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se Glicose e IMC fossem perfeitamente correlacionados (<span class="math inline">\(\rho=1\)</span>) dentro de cada classe, a Gaussiana diagonal (Naive Bayes) descartaria uma informação real e relevante, ao contrário do caso desta aula onde <span class="math inline">\(\rho\approx0\)</span>.</li>
<li>□ Num problema com <span class="math inline">\(100\)</span> atributos em que apenas dois são fortemente correlacionados entre si e os outros <span class="math inline">\(98\)</span> são praticamente independentes uns dos outros, o Naive Bayes pagaria um preço de acurácia comparável ao preço pago quando todos os <span class="math inline">\(100\)</span> atributos são fortemente correlacionados entre si.</li>
<li>□ Num sistema de recomendação que assume, para simplificar, que o interesse de um usuário por “filmes de ação” e por “filmes com efeitos especiais” são condicionalmente independentes dado o gênero preferido do usuário, o mesmo tipo de preço de correlação ignorada se aplica, mesmo fora do domínio médico desta aula.</li>
<li>□ Como a suposição de independência do Naive Bayes é sempre uma simplificação da realidade, conclui-se que ela sempre reduz a acurácia do classificador em relação a um modelo de covariância plena, ainda que por uma margem pequena.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Bloco 3 — Partição Gulosa e Verossimilhança Categórica (revisão da Aula 3)</h1>
<p>A Aula 3 abandonou a suposição de família paramétrica: em vez de assumir Beta ou Gaussiana, a árvore de decisão deixa o próprio dado escolher a forma da partição, greedy, um split por vez. A tese central daquela aula foi mostrar que “reduzir impureza” (entropia ou Gini) <strong>é</strong>, matematicamente, maximizar verossimilhança — para uma folha de classificação, a categórica <span class="math inline">\(\hat p_{\tau k} = n_{\tau k}/N_\tau\)</span> que maximiza a log-verossimilhança é exatamente a que minimiza a entropia daquela folha, porque <span class="math inline">\(\ell_\tau(\hat p_\tau) = -N_\tau H(\hat p_\tau)\)</span>. A árvore construída sobre o <em>California Housing</em> (regressão, <code>MedInc</code>/<code>HouseAge</code>, cinco folhas) tornou esse processo concreto, split por split.</p>
<p>Hoje, crescemos uma árvore pequena — mas de <strong>classificação</strong>, não de regressão, o que deixa a conexão entropia/Gini/MLE ainda mais direta — sobre Glicose e IMC no Pima.</p>
<div id="822f5580" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>|--- Glicose &lt;= 123.50
|   |--- class: 0
|--- Glicose &gt;  123.50
|   |--- Glicose &lt;= 154.50
|   |   |--- IMC &lt;= 41.65
|   |   |   |--- class: 0
|   |   |--- IMC &gt;  41.65
|   |   |   |--- class: 1
|   |--- Glicose &gt;  154.50
|   |   |--- class: 1

N treino=526, N teste=226
acurácia treino=0.7738, acurácia teste=0.7522</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<img src="index_files/mediabag/6b9e937510f5ee6caaa77d22158ee70cc9981f01.svg" class="img-fluid">
</div>
<p>A árvore, limitada a <span class="math inline">\(4\)</span> folhas para caber num quadro didático, chega a <span class="math inline">\(77{,}4\%\)</span> de acurácia de treino e <span class="math inline">\(75{,}2\%\)</span> de teste — guarde os dois números, eles voltam no Bloco 4. As folhas contam uma história clinicamente sensata: quem tem Glicose <span class="math inline">\(\le 123{,}5\)</span> mg/dL raramente é diabético (<span class="math inline">\(\hat p=17{,}2\%\)</span>, folha A, <span class="math inline">\(n=302\)</span>); quem tem Glicose <span class="math inline">\(&gt;154{,}5\)</span> quase sempre é (<span class="math inline">\(\hat p=78{,}5\%\)</span>, folha D); a faixa intermediária (<span class="math inline">\(123{,}5\)</span> a <span class="math inline">\(154{,}5\)</span>) se divide pelo IMC — abaixo de <span class="math inline">\(41{,}65\)</span> ainda majoritariamente não-diabético (<span class="math inline">\(\hat p=39{,}7\%\)</span>, folha B), acima disso fortemente diabético (<span class="math inline">\(\hat p=93{,}3\%\)</span>, folha C, mas só <span class="math inline">\(n=15\)</span> pacientes — um lembrete de que folhas pequenas merecem menos confiança).</p>
<div id="1bd50bfc" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-8-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Raiz: H=0.648 nats, Gini=0.456, erro bruto=0.352
Após split: H=0.551 nats (IG=0.097), Gini=0.369 (ganho=0.087), erro bruto=0.272</code></pre>
</div>
</div>
<p>O primeiro split (<code>Glicose ≤ 123,5</code>) reduz a entropia de <span class="math inline">\(0{,}648\)</span> para <span class="math inline">\(0{,}551\)</span> nats — um ganho de informação <span class="math inline">\(IG=0{,}097\)</span> nats, exatamente <span class="math inline">\(I(S;\mathcal{C})\)</span> na notação da Aula 3, onde <span class="math inline">\(S\)</span> é o lado do split. O Gini cai de <span class="math inline">\(0{,}456\)</span> para <span class="math inline">\(0{,}369\)</span> (ganho de <span class="math inline">\(0{,}087\)</span>), e o erro bruto (se cada folha previsse sua classe majoritária) cai de <span class="math inline">\(35{,}2\%\)</span> para <span class="math inline">\(27{,}2\%\)</span>. As três medidas concordam em direção — o split ajuda — porque, ao contrário do contraexemplo deliberado que a Aula 3 construiu (dois splits com erro bruto empatado em <span class="math inline">\(0{,}25\)</span> mas <span class="math inline">\(IG\)</span> bem diferente: <span class="math inline">\(0{,}216\)</span> contra <span class="math inline">\(0{,}131\)</span> nats), este split real não empata as três métricas por acidente de construção.</p>
<p>E vale reencontrar aqui o contraste geométrico com o Bloco 2: a fronteira desta árvore é <strong>axis-aligned</strong> — cada split corta perpendicular a um eixo (Glicose ou IMC), nunca na diagonal. As elipses de covariância do Bloco 2, por outro lado, podem se inclinar livremente. Nenhuma das duas fronteiras é “melhor” em abstrato — cada uma paga um preço estrutural diferente, exatamente a limitação que a Aula 3 nomeou explicitamente ao fechar aquele bloco.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um médico usa a regra manual “Glicose acima de 140 mg/dL <span class="math inline">\(\Rightarrow\)</span> suspeita de diabetes” — isso é, estruturalmente, uma árvore de decisão? Se for, por que a árvore do algoritmo é “melhor” (ou não é)?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que faz algo ser uma árvore de decisão — é o algoritmo de ajuste, ou a forma da regra final?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Árvore, Impureza e a Regra do Médico
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ A regra manual do médico (“Glicose <span class="math inline">\(&gt;140 \Rightarrow\)</span> suspeita”) é estruturalmente uma árvore de decisão degenerada, com uma única folha de decisão e nenhum critério de impureza envolvido na sua escolha.</li>
<li>□ Se um split greedy reduzisse a impureza de uma folha, mas o split seguinte (dentro da mesma sub-árvore) só fosse vantajoso se combinado com um terceiro split ainda não considerado, o algoritmo guloso da Aula 3 identificaria essa combinação de qualquer forma, porque avalia globalmente todos os splits futuros antes de escolher o atual.</li>
<li>□ Num sistema de recomendação de crédito que decide “aprovar automaticamente” só quando o escore de crédito supera um limiar único, a mesma lógica de “regra de um único corte” do médico se aplica, com a mesma limitação de não capturar interações entre atributos.</li>
<li>□ Como o algoritmo guloso da árvore encontrou um split com <span class="math inline">\(IG\)</span> positivo na raiz, conclui-se que esse split individual é necessariamente parte da árvore de profundidade ilimitada (sem limite de folhas) que minimizaria globalmente a impureza total.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bloco 4 — Estimando o Risco que Nunca Observamos (revisão da Aula 4)</h1>
<p>A Aula 4 mudou de assunto: em vez de um modelo, o objeto de estudo passou a ser o <em>procedimento</em> de medir o desempenho de um modelo. A tese central foi que o erro de treino <span class="math inline">\(\hat R(\theta)\)</span> é uma estimativa <strong>enviesada para baixo</strong> do risco esperado <span class="math inline">\(R(\theta) = \mathbb{E}_{(X,Y)\sim P}[\mathcal{L}(Y,f_\theta(X))]\)</span> — no <em>Breast Cancer Wisconsin</em>, a acurácia de treino chegou a <span class="math inline">\(100\%\)</span> a partir da profundidade <span class="math inline">\(6\)</span>, enquanto a de teste tinha seu pico em <span class="math inline">\(92{,}98\%\)</span> na profundidade <span class="math inline">\(5\)</span>. A validação cruzada de <span class="math inline">\(5\)</span> ou <span class="math inline">\(10\)</span> folds foi apresentada como uma simulação de amostragem repetida de <span class="math inline">\(P(X,Y)\)</span> (ESL §7.10) — e, honestamente, o experimento daquela aula mostrou LOOCV (sem viés teórico, mas caro) produzindo uma estimativa <em>menor</em> (<span class="math inline">\(89{,}4\%\)</span>) do que <span class="math inline">\(5\)</span>-fold e <span class="math inline">\(10\)</span>-fold repetidos (<span class="math inline">\(\sim92\)</span>–<span class="math inline">\(93\%\)</span>), um resultado específico daquela amostra, não uma garantia geral. A CV escolheu, por custo-complexidade, uma árvore de <span class="math inline">\(4\)</span> folhas empatando com a de <span class="math inline">\(19\)</span> folhas em <span class="math inline">\(91{,}8\%\)</span> de teste; a regra de <span class="math inline">\(1\)</span> desvio-padrão levou a uma árvore de só <span class="math inline">\(2\)</span> folhas, com um custo real de <span class="math inline">\(1{,}7\)</span> ponto percentual (<span class="math inline">\(90{,}1\%\)</span>). O Bootstrap, por fim, respondeu uma pergunta <em>diferente</em> da CV: não “qual é o risco esperado do procedimento”, mas “quão incerta é uma estatística já calculada” — com intervalos de confiança de <span class="math inline">\([87{,}7\%,95{,}9\%]\)</span> (reamostrando o teste) e <span class="math inline">\([88{,}9\%,93{,}6\%]\)</span> (reamostrando e reajustando o treino).</p>
<p>Hoje, aplicamos exatamente esse arsenal — CV e Bootstrap — para avaliar honestamente a árvore de <span class="math inline">\(4\)</span> folhas do Bloco 3.</p>
<div id="7235c272" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-9-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CV 5-fold: [0.755 0.714 0.695 0.695 0.705]  média=0.7128  dp=0.0221
split único (teste): 0.7522
Bootstrap (reamostra teste): média=0.7522  IC95=[0.6903,0.8097]
Bootstrap (reamostra+reajusta treino): média=0.7433  IC95=[0.6924,0.7788]</code></pre>
</div>
</div>
<p>A <span class="math inline">\(5\)</span>-fold CV no conjunto de treino dá uma média de <span class="math inline">\(71{,}3\%\)</span> com desvio-padrão de <span class="math inline">\(2{,}2\%\)</span> — no formato “média<span class="math inline">\(\pm\)</span>desvio” que a Aula 4 insistiu ser obrigatório, <span class="math inline">\(71{,}3\%\pm2{,}2\%\)</span>. A acurácia do nosso único split de teste, <span class="math inline">\(75{,}2\%\)</span>, cai perto do <strong>topo</strong> da faixa revelada pelos cinco folds (que vão de <span class="math inline">\(69{,}5\%\)</span> a <span class="math inline">\(75{,}5\%\)</span>) — não porque a CV esteja “errada”, mas porque um único split é, como a Aula 4 insistiu, um único sorteio de uma distribuição, e o sorteio de hoje calhou de ser um dos mais favoráveis dessa distribuição. É exatamente o motivo de reportar CV com desvio-padrão, não um único número: o número isolado do split de teste, sem esse contexto, sugeriria um desempenho mais otimista do que a média honesta.</p>
<p>O Bootstrap reafirma a distinção conceitual da Aula 4: reamostrar as previsões do teste (mantendo o modelo fixo) mede a <strong>incerteza de medição</strong> daquele número específico (<span class="math inline">\(75{,}2\%\)</span>, IC<span class="math inline">\(_{95\%}=[69{,}0\%,81{,}0\%]\)</span>); reamostrar e reajustar o treino mede a <strong>instabilidade do procedimento</strong> de ajuste em si (<span class="math inline">\(74{,}3\%\)</span>, IC<span class="math inline">\(_{95\%}=[69{,}2\%,77{,}9\%]\)</span>) — duas perguntas relacionadas, mas não idênticas, exatamente como a Aula 4 separou.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>A média de CV (<span class="math inline">\(71{,}3\%\)</span>) ficou abaixo da acurácia do nosso split único de teste (<span class="math inline">\(75{,}2\%\)</span>). Isso significa que o split de teste foi “escolhido a dedo” ou está errado de algum jeito?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense na CV como cinco sorteios de uma distribuição, e o split de teste como um sexto sorteio independente da mesma distribuição.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>CV, Split Único e o que “Discrepância” Significa
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a acurácia do split único estivesse dentro da faixa observada nos cinco folds de CV, isso por si só já seria evidência de que o split de teste não foi selecionado de forma tendenciosa.</li>
<li>□ No limite em que o conjunto de teste tivesse infinitos pontos, a acurácia medida nele convergiria para o risco esperado verdadeiro <span class="math inline">\(R(\theta)\)</span>, e a distância entre essa acurácia e a média de CV desapareceria.</li>
<li>□ Numa pesquisa eleitoral por amostragem, duas pesquisas com metodologias igualmente corretas podem legitimamente divergir por alguns pontos percentuais só por acaso de amostragem — a mesma lógica estatística que explica a diferença entre CV e o split único desta aula.</li>
<li>□ Como a CV usa <span class="math inline">\(5\)</span> vezes mais “medições” do que um único split de teste, a média de CV é sempre mais próxima do risco esperado verdadeiro do que qualquer split único poderia ser, em qualquer amostra particular.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-5-síntese-as-quatro-peças-uma-estrutura" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Bloco 5 — Síntese: As Quatro Peças, Uma Estrutura</h1>
<p>Chegou a hora de desenhar o mapa completo. Nas quatro aulas, a mesma sequência de três perguntas se repete, só que respondida por máquinas diferentes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Distribuição assumida</strong></th>
<th><strong>Verossimilhança usada para ajustar</strong></th>
<th><strong>Decisão / risco</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Aula 1</strong></td>
<td>Beta<span class="math inline">\((x\mid a,b)\)</span> por classe</td>
<td><span class="math inline">\(\sum\ln x_n,\ \sum\ln(1-x_n)\)</span> (sem forma fechada; <code>scipy.stats.beta.fit</code>)</td>
<td>corte no cruzamento das <strong>conjuntas</strong> <span class="math inline">\(p(x,\mathcal{C}_k)\)</span></td>
</tr>
<tr class="even">
<td><strong>Aula 2</strong></td>
<td>Gaussiana com <span class="math inline">\(\Sigma\)</span> diagonal (Naive Bayes) ou plena</td>
<td>fatoração <span class="math inline">\(\prod_i p(x_i\mid\mathcal{C}_k)\)</span> assumida</td>
<td>risco posterior <span class="math inline">\(\rho(a\mid x)=\sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span></td>
</tr>
<tr class="odd">
<td><strong>Aula 3</strong></td>
<td>categórica <span class="math inline">\(\hat p_{\tau k}\)</span> por folha</td>
<td>MLE categórica <span class="math inline">\(=-N_\tau H(\hat p_\tau)\)</span></td>
<td>partição greedy por ganho de informação (IG)</td>
</tr>
<tr class="even">
<td><strong>Aula 4</strong></td>
<td>amostra i.i.d. de <span class="math inline">\(P(X,Y)\)</span> (suposição sobre o <em>processo gerador</em>, não sobre <span class="math inline">\(x\)</span>)</td>
<td><span class="math inline">\(\hat R(\theta)\)</span> recalculado em cada fold/réplica</td>
<td><span class="math inline">\(R(\theta)\)</span>: nunca observado, só estimado (CV, Bootstrap)</td>
</tr>
</tbody>
</table>
<p>A coluna do meio é o ponto que mais se disfarça: em toda aula, algum objeto foi <strong>maximizado</strong> — uma log-verossimilhança, ainda que às vezes escrita como “minimizar entropia” ou “minimizar soma de quadrados”. Na Aula 3, a equivalência foi provada explicitamente (<span class="math inline">\(-N_\tau H(\hat p_\tau)\)</span>); nas Aulas 1 e 2, é a definição padrão de MLE; na Aula 4, o objeto que se maximiza (ajustar <span class="math inline">\(\theta\)</span> ao treino) é justamente o que se torna <strong>enganoso</strong> como medida de risco — a mesma operação de ajuste que funciona bem na coluna do meio se torna a fonte do viés otimista que a coluna da direita precisa corrigir.</p>
<p>Vale registrar, com a mesma honestidade que a Aula 4 pediu para os resultados numéricos, um cuidado de <strong>notação</strong>: o símbolo <span class="math inline">\(k\)</span> significa índice de classe (<span class="math inline">\(\mathcal{C}_k\)</span>) nas Aulas 1–3, mas número de <em>folds</em> na Aula 4 — dois usos completamente distintos do mesmo símbolo. E o custo/penalidade de complexidade aparece como multiplicador de custo assimétrico na Aula 2 (<span class="math inline">\(L(k,a)\)</span>, <span class="math inline">\(c_I/c_{II}\)</span>) e como penalidade de custo-complexidade (<span class="math inline">\(\lambda\)</span>, ou <code>ccp_alpha</code>) nas Aulas 3–4 — parentes conceituais (ambos trocam “ajuste” por “algum outro objetivo”), mas não a mesma quantidade. Não é um erro do curso: é a colisão natural de um alfabeto finito de símbolos sendo reciclado ao longo de quatro aulas — mas vale a pena nomear explicitamente, porque confundir os dois usos de <span class="math inline">\(k\)</span> é exatamente o tipo de erro que “decorar a fórmula sem entender a mecânica” produz.</p>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<img src="index_files/mediabag/07790b7831a9048d80a9ba60e7bbc3950efb1186.svg" class="img-fluid">
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>A Aula 5 vai construir regressão linear com sua própria distribuição, verossimilhança e decisão. Isso significa que regressão linear “é a mesma coisa” que uma árvore de decisão, só escrita com notação diferente?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense na diferença entre “usar os mesmos ingredientes” e “fazer o mesmo prato”.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Mesma Estrutura, Técnicas Diferentes
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se dois algoritmos compartilham a mesma estrutura de três peças (distribuição, verossimilhança, decisão), isso implica que eles vão sempre produzir a mesma fronteira de decisão sobre o mesmo dado.</li>
<li>□ No limite em que a distribuição assumida por um modelo está completamente errada (por exemplo, assumir Beta quando os dados são multimodais e não têm nada a ver com Beta), a etapa de verossimilhança ainda maximiza alguma coisa, mas o resultado da etapa de decisão pode ser sistematicamente ruim, mesmo com a maximização executada “corretamente”.</li>
<li>□ Um estudante que aprende primeiro a estrutura de três peças desta aula, antes de ver o algoritmo específico de regressão linear na Aula 5, deveria ser capaz de prever que existirá algo desempenhando o papel de “distribuição assumida” ali também — mesmo sem ainda saber qual é.</li>
<li>□ Como as quatro aulas revisadas hoje compartilham a mesma estrutura de três peças, conclui-se que a escolha de qual distribuição assumir (Beta, Gaussiana, categórica, i.i.d. de <span class="math inline">\(P(X,Y)\)</span>) é um detalhe secundário que pouco afeta o resultado final de cada técnica.</li>
</ul>
</div>
</div>
</section>
<section id="fechamento" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Fechamento</h1>
<p>Voltando ao roteiro de abertura, com uma frase cada:</p>
<ol type="1">
<li><strong>O que as quatro aulas tinham em comum:</strong> a mesma estrutura de três peças — uma distribuição assumida, uma verossimilhança maximizada para ajustá-la, e uma decisão fundamentada em risco.</li>
<li><strong>Como “qual é o formato dos dados?” se disfarça:</strong> como parâmetros de uma Beta, como uma fatoração de independência condicional, e como a proporção categórica dentro de uma folha — três respostas diferentes à mesma pergunta.</li>
<li><strong>Por que maximizar verossimilhança <span class="math inline">\(=\)</span> minimizar impureza/erro:</strong> porque, para uma categórica, a log-verossimilhança é literalmente <span class="math inline">\(-N_\tau H(\hat p_\tau)\)</span> — não uma analogia, uma identidade algébrica.</li>
<li><strong>Por que nunca observamos o risco de verdade:</strong> porque <span class="math inline">\(R(\theta)\)</span> é uma esperança sobre a distribuição populacional desconhecida <span class="math inline">\(P(X,Y)\)</span>; a Aula 4 respondeu simulando repetidamente essa amostragem via CV, e quantificando a incerteza remanescente via Bootstrap.</li>
<li><strong>Que peça falta:</strong> todas as quatro verossimilhanças de hoje foram sobre densidades, fatorações ou frequências categóricas — nenhuma foi sobre um alvo contínuo ligado linearmente aos atributos. Essa é exatamente a peça que a Aula 5 (Regressão Linear e Máxima Verossimilhança) adiciona: mínimos quadrados como MLE sob um modelo de ruído gaussiano — o mesmo princípio de sempre, agora aplicado a um modelo paramétrico contínuo em vez de uma densidade, uma árvore, ou um esquema de reamostragem.</li>
</ol>
<p><a href="../../../teaching/supervised-learning/revisao1/exercicios.html" class="see-all exercicios-link" aria-label="Ver exercícios" title="Ver exercícios">Exercícios</a> <a href="../../../teaching/supervised-learning/revisao1/soluções.html" class="see-all solucoes-link" aria-label="Ver soluções" title="Ver soluções">Soluções</a></p>


</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>