{
  "hash": "c6531316b5ca65f03636dca82fabd4cc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Aula 4: Autovalores, Autovetores e Matrizes Simétricas\"\nsubtitle: \"Álgebra Linear e Otimização para Aprendizado de Máquina\"\nauthor: \"Prof. Marcos Medeiros Raimundo\"\ndate: \"2026-09-07\"\nlang: pt-BR\nformat:\n  html:\n    include-after-body: ../../lesson-toc-accordion.html\n    output-file: notas.html\n    theme: [flatly, ../../../custom.scss, ../../lesson-theme.scss]\n    code-fold: false\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    fig-width: 8\n    fig-height: 4.5\n  revealjs:\n    transition: slide\n    width: 1280\n    height: 800\n    margin: 0.02\n    fig-responsive: true\n    fig-format: \"svg\"\n    footer: \"UNICAMP — Instituto de Computação\"\n    chalkboard:\n      boardmarker-width: 3\n      chalk-width: 3\n    include-in-header: ../../bootstrap-icons-header.html\n    include-after-body: ../../logos-footer.html\n    title-slide-attributes:\n      data-background-image: \"../../UNICAMP.png, ../../IC.png\"\n      data-background-size: \"140px, 140px\"\n      data-background-position: \"5% 8%, 95% 8%\"\n    theme: [simple, ../../lesson-theme.scss]\n    output-file: slides.html\n    slide-number: true\n    smaller: true\n    scrollable: true\n    fig-width: 8\n    fig-height: 4.5\njupyter: homepage\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n[Slides](slides.html){.see-all aria-label=\"Ver slides\" title=\"Ver slides\"}\n[Lista de aulas](../index.qmd){.see-all .lesson-list-link aria-label=\"Lista de aulas\" title=\"Lista de aulas\"}\n:::\n\n\n\n# Revisão e Introdução\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Revisão Rápida: Onde a Aula 3 Parou\n\nA Aula 3 resolveu o problema da regressão sobredeterminada por completo,\nem três passos. **Primeiro**, formalizou a \"sombra\" (a projeção\nortogonal $\\hat{\\mathbf{y}}$ de $\\mathbf{y}$ sobre $\\text{col}(X)$) como\no ponto de menor distância, provando que essa condição é equivalente a\numa condição algébrica exata: o resíduo $\\mathbf{y}-X\\hat{\\mathbf{w}}$\nortogonal a todo o espaço-coluna. **Segundo**, transformou essa condição\nde ortogonalidade nas **Equações Normais**,\n$X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$, e mostrou que — sob posto completo\nde $X$ (herdado da Aula 2) — $X^TX$ é invertível e\n$\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ é a única solução. **Terceiro**,\nno Bloco 6, mostrou que \"posto completo\" não é garantia de robustez\nnumérica: comparando o par de atributos quase-colinear\n(`AveRooms`/`AveBedrms`, correlação $0{,}865$) com o par bem-condicionado\n(`MedInc`/`HouseAge`), a mesma perturbação de $1\\%$ nos dados produzia\numa oscilação de $\\approx 29{,}5\\%$ no peso do primeiro par contra\n$\\approx 0{,}1\\%$ no segundo — quase $300$ vezes mais sensível. Vale\nrelembrar o que essa perturbação faz e o que ela mede: soma-se a\n`MedHouseVal` um ruído gaussiano de média zero e desvio-padrão igual a\napenas $1\\%$ do desvio-padrão da própria variável (uma mudança\nminúscula, do tamanho de um erro de medição), reajusta-se por mínimos\nquadrados, e mede-se a **taxa de amplificação** entre essa mudança\npequena na entrada e a mudança resultante no peso estimado — quanto\nmaior a amplificação, mais frágil o par de atributos.\n\nEssa fragilidade foi **medida**, não **explicada**. A Aula 3 batizou a\nquantidade certa para isso — o **número de condição** de $X^TX$ — mas só\nsoube calculá-lo perturbando os dados e observando o efeito\n($\\text{cond}(X^TX)\\approx 23\\,460$ para os 4 atributos completos,\n$\\approx 420$ para o par quase-colinear, $\\approx 169$ para o par\nbem-condicionado, todos via `np.linalg.cond`). A própria aula fechou com\nessa promessa explícita, que serve de gancho direto para hoje: \"o número\nde condição foi usado aqui de forma empírica (perturbar os dados e medir\no efeito) — a Aula 4 dá a ferramenta exata para medi-lo diretamente a\npartir da estrutura de $X^TX$ (seus **autovalores** e **autovetores**),\nsem precisar perturbar nada.\"\n\n## Organizador Prévio: De Perturbar os Dados Para Olhar Direto Para Dentro de $X^TX$\n\nPerturbar os dados e medir o efeito é um experimento — funciona, mas não\nexplica *por que* um par de atributos é mais frágil que outro, nem\npermite prever a fragilidade **antes** de perturbar nada. Olhando com\nmais cuidado para o que esse experimento faz: ao somar um ruído pequeno\na $\\mathbf{y}$ e reajustar, o que se está medindo, por fora, é uma **taxa\nde amplificação** — o quanto uma perturbação pequena na entrada se\ntransforma numa oscilação grande (ou pequena) na saída ($\\hat{\\mathbf{w}}$).\nEssa taxa não é uma propriedade do ruído específico usado no experimento\n— é uma propriedade fixa da própria matriz $X^TX$, que existiria mesmo\nque ninguém nunca tivesse perturbado nada. Esta aula propõe uma mudança\nde estratégia: em vez de sacudir a matriz $X^TX$ de fora e observar como\nela reage, vamos abrir $X^TX$ por dentro e encontrar os números que já\ndeterminam essa taxa de amplificação de antemão, de forma exata — os\n**autovalores**. A ideia central, que vai se repetir em cada bloco: a\nmaioria das direções do espaço, quando atravessa uma transformação\nlinear $A$, gira e muda de tamanho ao mesmo tempo; mas existem direções\nespeciais que só mudam de tamanho, nunca de direção — e são exatamente\nessas direções, e os fatores de escala associados a elas, que carregam\ntoda a informação sobre o comportamento numérico de uma matriz, incluindo\na taxa de amplificação que o experimento de perturbação só conseguia\nestimar de fora.\n\n## Roteiro da Aula\n\nA pergunta que fecha o Organizador Prévio — \"que números, dentro de\n$X^TX$, já determinam a fragilidade antes de qualquer perturbação?\" — se\ndesdobra em quatro perguntas mais específicas, cada uma resolvida em um\nou mais blocos desta aula:\n\n1. O que é, geometricamente, um autovalor e um autovetor de uma matriz?\n2. Como calcular autovalores e autovetores à mão, de forma sistemática,\n   via o **polinômio característico**?\n3. Por que toda matriz simétrica — como $X^TX$, sempre — tem autovalores\n   reais e autovetores ortogonais entre si? Esse é o **Teorema Espectral\n   Real**.\n4. Como o sinal e a razão entre os autovalores definem, respectivamente,\n   a **definitude positiva** de uma matriz e o **número de condição\n   exato** de $X^TX$ — fechando, sem perturbar nada, o ciclo aberto na\n   Aula 3?\n\n## Problema Motivador\n\nVolte aos mesmos dois pares de atributos do *California Housing\nDataset* que a Aula 3 comparou no Bloco 6: `AveRooms`/`AveBedrms`\n(quase-colinear, correlação $0{,}865$) e `MedInc`/`HouseAge`\n(bem-condicionado). A Aula 3 só soube dizer *qual* par era mais frágil\ndepois de perturbar os dados e observar a oscilação no peso estimado.\nPense por um instante, sem fazer nenhuma conta ainda: será que existe\nalguma propriedade de $X^TX$ — algo que se possa calcular olhando só\npara a matriz, sem perturbar absolutamente nada nos dados — que já\nanteciparia qual par vai se comportar mal?\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Revisão Rápida\n\n::: {.fragment}\nAula 3: projeção $\\hat{\\mathbf{y}}$ (a \"sombra\") $\\equiv$ resíduo\nortogonal a $\\text{col}(X)$ $\\Rightarrow$ **Equações Normais**\n$X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$ $\\Rightarrow$, sob posto completo,\n$\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$.\n:::\n\n::: {.fragment}\nBloco 6 da Aula 3: `AveRooms`/`AveBedrms` (quase-colinear) oscila\n$\\approx 29{,}5\\%$ sob perturbação de $1\\%$; `MedInc`/`HouseAge`\n(bem-condicionado) oscila só $\\approx 0{,}1\\%$ — quase $300\\times$ mais\nsensível.\n:::\n\n::: {.fragment}\n**O que essa perturbação faz:** soma-se a `MedHouseVal` um ruído\ngaussiano de desvio-padrão igual a $1\\%$ do desvio-padrão da própria\nvariável, reajusta-se por mínimos quadrados. **O que ela mede:** a taxa\nde amplificação entre uma mudança pequena na entrada e a oscilação\nresultante no peso estimado.\n:::\n\n::: {.fragment}\nEssa fragilidade foi **medida** (perturbar e observar), não\n**explicada**. $\\text{cond}(X^TX)\\approx 23\\,460$ (completo), $\\approx\n420$ (quase-colinear), $\\approx 169$ (bem-condicionado) — via\n`np.linalg.cond`, sem saber ainda de onde vêm esses números.\n:::\n\n## O que a perturbação revela sobre $X^TX$\n\n::: {.fragment}\nO experimento de perturbação mede, por fora, uma **taxa de\namplificação**: entrada perturbada pouco $\\to$ saída ($\\hat{\\mathbf{w}}$)\noscila muito ou pouco. Essa taxa não depende do ruído usado — é uma\npropriedade fixa da matriz $X^TX$.\n:::\n\n::: {.fragment}\nEm vez de sacudir $X^TX$ de fora, abrir a matriz por dentro: os\n**autovalores** já determinam essa taxa de amplificação de forma exata,\nsem perturbar nada.\n:::\n\n::: {.fragment}\nIdeia central: a maioria das direções gira **e** muda de tamanho sob uma\ntransformação $A$; direções especiais só mudam de tamanho, **nunca** de\ndireção.\n:::\n\n## Roteiro da Aula\n\n::: {.fragment}\n**1.** O que é, geometricamente, um autovalor e um autovetor?\n:::\n\n::: {.fragment}\n**2.** Como calcular à mão, via o **polinômio característico**?\n:::\n\n::: {.fragment}\n**3.** Por que toda matriz simétrica ($X^TX$, sempre) tem autovalores\nreais e autovetores ortogonais — o **Teorema Espectral Real**?\n:::\n\n::: {.fragment}\n**4.** Como sinal e razão dos autovalores definem **definitude\npositiva** e o **número de condição exato** — fechando o ciclo da Aula 3?\n:::\n\n## Problema Motivador\n\n::: {.fragment}\nMesmos dois pares da Aula 3: `AveRooms`/`AveBedrms` (quase-colinear,\n$r=0{,}865$) vs. `MedInc`/`HouseAge` (bem-condicionado). A Aula 3 só\nsoube qual era mais frágil **depois** de perturbar.\n:::\n\n::: {.fragment}\nExiste alguma propriedade de $X^TX$ — calculável **sem perturbar nada**\n— que já antecipe qual par vai se comportar mal?\n:::\n:::\n\n::: {.fig-resize style=\"width: 85%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{shapes.geometric, arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[\n  node distance=0.7cm and 0.9cm,\n  block/.style={rectangle, draw=icblue, fill=icblue!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=2.7cm, minimum height=1.1cm},\n  concl/.style={rectangle, draw=icred, fill=icred!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=2.7cm, minimum height=1.1cm}\n]\n  \\node (A) [block] {$X^TX$\\\\(sempre simétrica)};\n  \\node (B) [block, right=of A] {autovalores $\\lambda$,\\\\autovetores $\\mathbf{x}$};\n  \\node (C) [block, right=of B] {polinômio\\\\característico};\n  \\node (D) [block, right=of C] {Teorema\\\\Espectral Real};\n  \\node (E) [concl, right=of D] {sinal/razão de $\\lambda$:\\\\definitude,\\\\número de condição};\n\n  \\draw [-Stealth, thick, color=gray!70] (A) -- (B);\n  \\draw [-Stealth, thick, color=gray!70] (B) -- (C);\n  \\draw [-Stealth, thick, color=gray!70] (C) -- (D);\n  \\draw [-Stealth, thick, color=gray!70] (D) -- (E);\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se dois pares de atributos têm a mesma correlação entre si, eles necessariamente têm o mesmo número de condição de $X^TX$?\n\nDica: o número de condição da Aula 3 foi medido via perturbação nos\ndados; pense se a *escala* dos atributos (não só a correlação entre\neles) poderia influenciar o resultado.\n\n- □ Dois pares de atributos com a mesma correlação de Pearson entre si\n  necessariamente têm o mesmo número de condição de $X^TX$, porque\n  correlação e número de condição medem exatamente a mesma coisa.\n- □ Se um par de atributos fosse exatamente ortogonal (correlação zero,\n  como duas colunas perfeitamente descorrelacionadas), isso por si só\n  não garante que o número de condição de $X^TX$ para esse par seja\n  igual a $1$ — a escala relativa das duas colunas também importa.\n- □ Num problema de engenharia estrutural, com duas variáveis de projeto\n  fortemente correlacionadas (ex.: espessura de duas vigas adjacentes que\n  quase sempre variam juntas), o mesmo tipo de fragilidade numérica de\n  $X^TX$ discutido aqui se aplicaria, mesmo fora do contexto de imóveis.\n- □ Como a Aula 3 mediu a fragilidade só perturbando os dados, isso\n  significa que não existe nenhuma forma de calcular o número de\n  condição de $X^TX$ sem realizar, na prática, uma perturbação real dos\n  dados.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Mesma correlação implica mesmo número de condição de $X^TX$?\n\nDica: pense se a *escala* dos atributos (não só a correlação) poderia\ninfluenciar o número de condição.\n\n- □ Mesma correlação de Pearson $\\Rightarrow$ mesmo número de condição\n  de $X^TX$ — as duas quantidades medem a mesma coisa.\n- □ Correlação zero (ortogonalidade) não garante, por si só, número de\n  condição igual a $1$ — a escala relativa das colunas também importa.\n- □ Vigas adjacentes com espessuras fortemente correlacionadas\n  (engenharia estrutural): mesmo tipo de fragilidade numérica se aplica.\n- □ Como a Aula 3 só perturbou os dados para medir, não existe forma de\n  calcular o número de condição sem perturbação real.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Correlação e número de condição — Resposta\n\n- ✗ Correlação mede alinhamento angular entre colunas; número de\n  condição de $X^TX$ mistura esse alinhamento **com** a escala/variância\n  de cada coluna — duas quantidades relacionadas, não idênticas.\n- ✔ Ortogonalidade (correlação $0$) só garante $X^TX$ diagonal; se as\n  variâncias das duas colunas forem muito diferentes, o número de\n  condição ainda pode ser grande.\n- ✔ Mesma mecânica (colunas quase-redundantes $\\Rightarrow$ $X^TX$\n  mal-condicionada), outro domínio de engenharia.\n- ✗ É exatamente o que esta aula resolve: calcular o número de condição\n  **direto da estrutura** de $X^TX$ (autovalores), sem perturbar nada.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** não — correlação e escala são, em geral,\nindependentes, e o número de condição de $X^TX$ depende dos dois. O\nBloco 6 vai calcular os autovalores exatos e confirmar isso nos mesmos\ndois pares.\n:::\n:::\n\n# Intuição -- Autovetores\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Uma Matriz Agindo sobre um Conjunto de Direções\n\nAntes de qualquer fórmula, uma imagem concreta. Tome a matriz\n$$\nA = \\begin{bmatrix} 4 & 2 \\\\ 1 & 3 \\end{bmatrix}\n$$\n(a mesma matriz do MathML, Exemplo 4.5, reaproveitada no Bloco 3 para o\ncálculo à mão) e pense nela como uma transformação linear\n$\\mathbf{v}\\mapsto A\\mathbf{v}$ agindo sobre todo o plano\n$\\mathbb{R}^2$. Escolha um punhado de vetores unitários apontando em\ndireções diferentes ao redor da origem, e observe o que $A$ faz com cada\num deles.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Uma Matriz Agindo sobre um Conjunto de Direções\n\n::: {.fragment}\n**Antes de qualquer fórmula, uma imagem concreta.** Matriz\n$A=\\begin{bmatrix}4&2\\\\1&3\\end{bmatrix}$ (MathML, Exemplo 4.5,\nreaproveitada no Bloco 3) como transformação linear\n$\\mathbf{v}\\mapsto A\\mathbf{v}$ agindo sobre todo o plano $\\mathbb{R}^2$.\n:::\n\n::: {.fragment}\nEscolha um punhado de vetores unitários apontando em direções diferentes\nao redor da origem, e observe o que $A$ faz com cada um deles.\n:::\n\n## O Que os Dois Painéis Mostram\n:::\n\n::: {.fig-resize style=\"width: 60%; margin: 0 auto;\"}\n\n::: {#b3652c3c .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-3-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nNo painel esquerdo, cada seta cinza é um vetor unitário original, e a\nseta azul correspondente é sua imagem $A\\mathbf{v}$: a maioria delas gira\nvisivelmente — a direção de chegada não é a mesma da direção de partida.\nMas as duas retas tracejadas (laranja e vermelha) marcam duas direções\nespecíficas em que **isso não acontece**: qualquer vetor sobre essas\nretas continua, depois de multiplicado por $A$, sobre a **mesma reta** —\nsó o comprimento muda (nesse caso, sempre esticando, nunca invertendo,\nporque os dois fatores de escala são positivos). O painel direito mostra\na mesma ideia de outro ângulo: o círculo unitário inteiro (pontilhado)\nvira uma elipse (linha cheia azul) sob a ação de $A$, e os eixos dessa\nelipse caem **exatamente** sobre as duas direções especiais — cada eixo\nesticado por um fator diferente ($\\lambda=2$ numa direção, $\\lambda=5$ na\noutra, valores que o Bloco 3 vai calcular à mão, à mão).\n\nVale nomear informalmente o que o desenho já mostra, antes de qualquer\nequação: essas duas direções especiais são os **autovetores** de $A$, e\nos fatores de escala associados a cada uma são os **autovalores**\ncorrespondentes. Repare em um detalhe que vai ficar importante no Bloco\n4: as duas retas tracejadas do painel esquerdo **não são perpendiculares\numa à outra** — o ângulo entre elas não é de $90°$. Isso não é um\ndetalhe cosmético; é uma propriedade de $A$ **não ser simétrica**\n($A\\ne A^T$, já que a entrada $(1,2)=2$ é diferente da entrada\n$(2,1)=1$), e vai mudar completamente quando a matriz for simétrica —\ngancho direto para o Bloco 4.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n::: {.fragment}\nEsquerda: seta cinza = vetor original; seta azul = imagem $A\\mathbf{v}$.\nA maioria **gira**. Duas retas tracejadas (laranja/vermelha): sobre elas,\n$A\\mathbf{v}$ fica na **mesma reta** — só o comprimento muda (aqui,\nsempre esticando, nunca invertendo o sentido, porque os dois fatores de\nescala são positivos — isso muda quando um autovalor é negativo,\nPergunta a seguir).\n:::\n\n::: {.fragment}\nDireita: círculo unitário (pontilhado) $\\to$ elipse (azul) sob $A$. Os\neixos da elipse caem **exatamente** sobre as duas direções especiais —\ncada eixo esticado por um fator diferente ($\\lambda=2$ e $\\lambda=5$,\ncalculados à mão no Bloco 3).\n:::\n\n## Nomeando a Intuição\n\n::: {.fragment}\nDireções especiais = **autovetores** de $A$; fatores de escala\nassociados = **autovalores** correspondentes. É isso que o desenho já\nmostrava — só faltava o nome.\n:::\n\n::: {.fragment}\n**Observação plantada:** meça o ângulo entre as duas retas tracejadas —\nnão são perpendiculares ($90°$). Repare: **simetria é propriedade da\nmatriz** ($A=A^T$ ou não); **ortogonalidade é propriedade dos\nautovetores** (perpendiculares entre si, ou não) — são duas coisas\ndiferentes, ligadas por um teorema, não sinônimos.\n:::\n\n::: {.fragment}\nAqui, $A=\\begin{bmatrix}4&2\\\\1&3\\end{bmatrix}$ **não é simétrica**\n($A\\ne A^T$: a entrada $(1,2)=2$ é diferente da entrada $(2,1)=1$) — e os\nautovetores, de fato, não são ortogonais. Bloco 4 prova que essa ligação\nnão é coincidência: **se a matriz for simétrica, os autovetores são\nsempre ortogonais entre si**, garantido. É o gancho direto para lá.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## A Equação Formal\n\nA intuição visual do painel acima tem um nome e uma equação precisos. O\nMathML define (tradução nossa, §4.2, Definição 4.6, p. 105):\n\n> \"Seja $A\\in\\mathbb{R}^{n\\times n}$ uma matriz quadrada. Então\n> $\\lambda\\in\\mathbb{R}$ é um **autovalor** de $A$ e\n> $\\mathbf{x}\\in\\mathbb{R}^n\\setminus\\{\\mathbf{0}\\}$ é o **autovetor**\n> correspondente de $A$ se\n> $$A\\mathbf{x} = \\lambda\\mathbf{x}.$$\n> Chamamos essa equação de **equação de autovalor**.\"\n\nEssa é exatamente a propriedade que o desenho já mostrou: multiplicar o\nautovetor $\\mathbf{x}$ por $A$ dá o mesmo resultado que simplesmente\nesticá-lo por um número $\\lambda$ — nenhuma rotação, só escala (com\ninversão de sentido se $\\lambda<0$, caso que não aparece no exemplo\ndesta figura, mas vai aparecer mais adiante no curso). Vale notar, desde\njá, uma propriedade que vai evitar uma confusão comum: o autovetor\n$\\mathbf{x}$ associado a um autovalor **não é único**. O MathML observa\n(tradução nossa, mesma seção): \"se $\\mathbf{x}$ é um autovetor de $A$\nassociado ao autovalor $\\lambda$, então, para qualquer $c\\in\\mathbb{R}\n\\setminus\\{0\\}$, vale que $c\\mathbf{x}$ também é um autovetor de $A$ com\no mesmo autovalor, já que $A(c\\mathbf{x})=cA\\mathbf{x}=c\\lambda\\mathbf{x}\n=\\lambda(c\\mathbf{x})$. Assim, todos os vetores colineares a\n$\\mathbf{x}$ também são autovetores de $A$.\" Ou seja: o que a figura\nchama de \"direção especial\" é literalmente isso — uma **reta** inteira\nde autovetores (menos a origem), não um vetor específico; qualquer\nmúltiplo escalar não-nulo de um autovetor serve igualmente bem.\n\nEssa não-unicidade é o motivo para tratar um autovetor, antes de mais\nnada, como uma **direção** — não como \"o\" vetor com um comprimento\nfixo. Um vetor propriamente dito carrega duas informações, direção **e**\namplitude (o próprio comprimento da seta); num autovetor, a amplitude é\narbitrária — qualquer $c\\ne 0$ serve igualmente bem, inclusive $c<0$,\nque aponta para o lado oposto da mesma reta — só a direção (a reta que\npassa pela origem) é a informação que de fato pertence a $A$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## A Equação Formal\n\n::: {.fragment}\n**Definição 4.6 (MathML, tradução nossa):** $\\lambda\\in\\mathbb{R}$ é\n**autovalor** de $A\\in\\mathbb{R}^{n\\times n}$ e\n$\\mathbf{x}\\in\\mathbb{R}^n\\setminus\\{\\mathbf{0}\\}$ é o **autovetor**\ncorrespondente se\n$$A\\mathbf{x} = \\lambda\\mathbf{x}$$\n(a **equação de autovalor**) — exatamente \"esticar sem girar\" do desenho\nacima: nenhuma rotação, só escala.\n:::\n\n::: {.fragment}\n**Caso que não aparece no desenho, mas conta:** se $\\lambda<0$, a escala\ninverte o sentido do vetor ($\\mathbf{x}$ e $A\\mathbf{x}$ apontam para\nlados opostos da mesma reta) — ainda \"sem girar\" no sentido da equação\n(a reta é a mesma), só que com sentido trocado. No exemplo desta figura\nos dois autovalores são positivos ($\\lambda=2,5$), por isso nenhuma seta\nse inverte.\n:::\n\n::: {.fragment}\n**Não-unicidade (MathML):** se $\\mathbf{x}$ é autovetor de autovalor\n$\\lambda$, qualquer $c\\mathbf{x}$ ($c\\ne 0$) também é, com o **mesmo**\nautovalor — não é só uma afirmação, sai direto da equação:\n$$A(c\\mathbf{x}) = cA\\mathbf{x} = c\\lambda\\mathbf{x} = \\lambda(c\\mathbf{x}).$$\n:::\n\n::: {.fragment}\nLogo, \"direção especial\" é uma **reta** inteira de autovetores, não um\nvetor específico. Por isso um autovetor é melhor pensado como uma\n**direção**, não como \"o\" vetor: um vetor de verdade carrega direção\n**e** amplitude, mas aqui a amplitude é arbitrária — só a direção\npertence a $A$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se um vetor $\\mathbf{v}$ fosse mapeado por $A$ exatamente para $-3\\mathbf{v}$, isso significaria que $\\mathbf{v}$ não é autovetor de $A$, já que a direção \"inverteu\"?\n\nDica: releia a equação de autovalor — ela permite $\\lambda$ negativo?\n\"Mesma reta, sentido oposto\" ainda conta como \"não girar\"?\n\n- □ Se $A\\mathbf{v}=-3\\mathbf{v}$ para algum $\\mathbf{v}\\ne\\mathbf{0}$,\n  isso significa que $\\mathbf{v}$ **não** é autovetor de $A$, porque a\n  direção do vetor se inverteu.\n- □ Se todos os vetores do plano fossem autovetores de uma mesma matriz\n  $A$ (não só duas direções especiais, mas qualquer direção), isso\n  forçaria $A$ a ser um múltiplo escalar da identidade, $A=cI$.\n- □ Num sistema de molas lineares acopladas, os \"modos normais de\n  vibração\" (frequências e formatos de oscilação que se mantêm\n  proporcionais ao longo do tempo, sem misturar) correspondem, na\n  matriz que descreve o sistema, exatamente a autovetores dessa matriz.\n- □ Como o autovetor associado a um autovalor não é único (qualquer\n  múltiplo escalar serve), isso implica que o autoespaço associado a um\n  autovalor sempre tem dimensão maior que 1.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## $A\\mathbf{v}=-3\\mathbf{v}$ significa que $\\mathbf{v}$ não é autovetor, já que a direção inverteu?\n\nDica: a equação de autovalor permite $\\lambda$ negativo? \"Mesma reta,\nsentido oposto\" ainda conta como \"não girar\"?\n\n- □ $A\\mathbf{v}=-3\\mathbf{v}$ ($\\mathbf{v}\\ne\\mathbf{0}$) significa que\n  $\\mathbf{v}$ **não** é autovetor, pela inversão de direção.\n- □ Se **todo** vetor do plano fosse autovetor de $A$, isso forçaria\n  $A=cI$ (múltiplo escalar da identidade).\n- □ Modos normais de vibração de molas acopladas correspondem a\n  autovetores da matriz que descreve o sistema.\n- □ Autovetor não-único (múltiplo escalar) $\\Rightarrow$ autoespaço\n  sempre tem dimensão $>1$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Sinal do autovalor e o que \"não girar\" realmente exige — Resposta\n\n- ✗ $\\lambda=-3$ é um autovalor válido (é real); \"mesma reta, sentido\n  oposto\" continua sendo \"não girar\" no sentido da equação — a direção\n  (a reta) é preservada, só o sentido e o comprimento mudam.\n- ✔ Se toda direção é preservada, em particular os vetores canônicos\n  $\\mathbf{e}_1,\\mathbf{e}_2$ são autovetores, o que força $A$ diagonal;\n  e se toda direção compartilha o mesmo comportamento de escala, a única\n  matriz consistente é $A=cI$.\n- ✔ Exatamente a interpretação física padrão de autovalores/autovetores\n  em sistemas físicos lineares — mesma matemática, outro domínio.\n- ✗ Não-unicidade do autovetor (múltiplos escalares) não implica\n  dimensão $>1$ do autoespaço — é o contrário do que Bloco 3 vai mostrar\n  para $A_{\\text{exemplo}}$: cada autoespaço aqui tem dimensão $1$ (uma\n  reta), mesmo contendo infinitos vetores (a reta menos a origem).\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** não — o sinal de $\\lambda$ decide se a direção\né preservada com o mesmo sentido ($\\lambda>0$) ou invertida\n($\\lambda<0$), mas em ambos os casos $\\mathbf{v}$ continua autovetor. O\nque de fato desqualificaria $\\mathbf{v}$ seria $A\\mathbf{v}$ apontar para\numa direção **diferente** da reta de $\\mathbf{v}$.\n:::\n:::\n\n# O Polinômio Característico\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Premissas: O Que Precisamos Resolver\n\nO Bloco 2 mostrou a existência das direções especiais só visualmente.\nPara encontrá-las **sem depender de um desenho**, precisamos transformar\na equação de autovalor $A\\mathbf{x}=\\lambda\\mathbf{x}$ num problema de\nálgebra resolvível passo a passo. Deixando as premissas explícitas antes\nde qualquer manipulação:\n\n::: {.callout-note}\n## Premissas\n\n1. Temos uma matriz quadrada $A\\in\\mathbb{R}^{n\\times n}$ fixa (no nosso\n   caso, $n=2$, a matriz do Bloco 2).\n2. Procuramos pares $(\\lambda,\\mathbf{x})$, com\n   $\\mathbf{x}\\in\\mathbb{R}^n\\setminus\\{\\mathbf{0}\\}$, satisfazendo\n   $A\\mathbf{x}=\\lambda\\mathbf{x}$.\n3. Não sabemos ainda quantos autovalores existem, nem seus valores — só\n   sabemos, do Bloco 2, que **pelo menos dois** existem nesse exemplo\n   específico (as duas direções desenhadas).\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Premissas: O Que Precisamos Resolver\n\n::: {.callout-note icon=false}\n**Premissas**\n\n1. Matriz quadrada $A\\in\\mathbb{R}^{n\\times n}$ fixa ($n=2$ no exemplo).\n2. Procuramos $(\\lambda,\\mathbf{x})$, $\\mathbf{x}\\ne\\mathbf{0}$, com\n   $A\\mathbf{x}=\\lambda\\mathbf{x}$.\n3. Não sabemos quantos existem — só que **pelo menos dois** existem\n   neste exemplo (Bloco 2).\n:::\n\n::: {.fragment}\nObjetivo: transformar $A\\mathbf{x}=\\lambda\\mathbf{x}$ num problema de\nálgebra resolvível passo a passo, sem depender de desenho.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo (i): Reescrevendo a Equação de Autovalor Como um Sistema Homogêneo\n\nA manipulação decisiva é puramente algébrica: subtrair\n$\\lambda\\mathbf{x}$ dos dois lados,\n$$\nA\\mathbf{x} = \\lambda\\mathbf{x}\n\\quad\\Longleftrightarrow\\quad\nA\\mathbf{x} - \\lambda\\mathbf{x} = \\mathbf{0}\n\\quad\\Longleftrightarrow\\quad\n(A-\\lambda I)\\mathbf{x} = \\mathbf{0},\n$$\nusando $I$ (a identidade) para poder subtrair uma matriz de outra\nmatriz. Essa última forma é um **sistema linear homogêneo**\n$B\\mathbf{x}=\\mathbf{0}$, com $B=A-\\lambda I$ — a mesma estrutura de\nsistema linear já estudada nas Aulas 2-3, só que agora a incógnita não é\nsó $\\mathbf{x}$: o próprio $\\lambda$ também é desconhecido, e está\nembutido dentro de $B$.\n\nUm sistema homogêneo $B\\mathbf{x}=\\mathbf{0}$ **sempre** tem a solução\ntrivial $\\mathbf{x}=\\mathbf{0}$ — mas a Premissa 2 exige\n$\\mathbf{x}\\ne\\mathbf{0}$. Isso só é possível quando o sistema tem\n**mais de uma** solução (a trivial e outras) — e a Aula 2 já ensinou o\ncritério exato para isso: um sistema quadrado homogêneo tem soluções\nnão-triviais se, e somente se, sua matriz de coeficientes **não** tem\nposto completo, ou seja, é **singular** (não-invertível).\n\nFalta um elo, e ele não é óbvio: por que \"singular\" equivale a\n$\\det(B)=0$? Não é uma definição nem uma consequência imediata do que\njá vimos — é um teorema, na verdade dois, que o MathML enuncia\nseparadamente (tradução nossa, §4.1): \"para qualquer matriz quadrada\n$A\\in\\mathbb{R}^{n\\times n}$ vale que $A$ é invertível se, e somente\nse, $\\det(A)\\ne 0$\" (Teorema 4.1, p.&nbsp;100), e \"uma matriz quadrada\n$A\\in\\mathbb{R}^{n\\times n}$ tem $\\det(A)\\ne 0$ se, e somente se,\n$\\text{rk}(A)=n$; em outras palavras, $A$ é invertível se, e somente\nse, tem posto completo\" (Teorema 4.3, p.&nbsp;103). Encadeando os dois\nteoremas com o critério de posto da Aula 2:\n$$\nB\\mathbf{x}=\\mathbf{0} \\text{ tem solução não-trivial}\n\\;\\overset{\\text{Aula 2}}{\\iff}\\; B \\text{ não tem posto completo}\n\\;\\overset{\\text{Teo. 4.3}}{\\iff}\\; B \\text{ não é invertível}\n\\;\\overset{\\text{Teo. 4.1}}{\\iff}\\; \\det(B) = 0.\n$$\nCom $B=A-\\lambda I$, isso equivale a\n$$\n\\det(A-\\lambda I) = 0.\n$$\nEssa equação — não $A\\mathbf{x}=\\lambda\\mathbf{x}$ diretamente — é o\nalvo do resto deste bloco: ela só tem $\\lambda$ como incógnita (o\n$\\mathbf{x}$ já foi eliminado), o que a torna resolvível por conta\nprópria.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo (i): Reescrevendo Como um Sistema Homogêneo\n\n::: {.fragment}\n$$A\\mathbf{x} = \\lambda\\mathbf{x} \\iff (A-\\lambda I)\\mathbf{x} = \\mathbf{0}$$\nSistema linear homogêneo $B\\mathbf{x}=\\mathbf{0}$, $B=A-\\lambda I$ — mas\n$\\lambda$ também é incógnita, embutida em $B$.\n:::\n\n::: {.fragment}\nPremissa 2 exige $\\mathbf{x}\\ne\\mathbf{0}$ (não iremos usar solução trivial $\\mathbf{x}=\\mathbf{0}$).\n:::\n\n::: {.fragment}\nCom isso temos que $B\\mathbf{x}=\\mathbf{0}$ tem solução não-trivial $\\iff$ $B$ é singular (não-invertível). Então precisamos de $\\det(B)=0$ para que haja autovetor não-trivial.\n:::\n\n::: {.fragment}\nEssa equação só tem $\\lambda$ como incógnita ($\\mathbf{x}$ já\neliminado) — resolvível por conta própria.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## O Polinômio Característico\n\nO MathML batiza a expressão $\\det(A-\\lambda I)$ vista como função de\n$\\lambda$ (tradução nossa, §4.1, Definição 4.5, p. 104):\n\n> \"Para $\\lambda\\in\\mathbb{R}$ e uma matriz quadrada\n> $A\\in\\mathbb{R}^{n\\times n}$,\n> $$\n> p_A(\\lambda) := \\det(A-\\lambda I) = c_0+c_1\\lambda+c_2\\lambda^2+\\cdots\n> +c_{n-1}\\lambda^{n-1}+(-1)^n\\lambda^n,\\quad c_0,\\dots,c_{n-1}\n> \\in\\mathbb{R},\n> $$\n> é o **polinômio característico** de $A$.\"\n\nE o MathML conecta essa definição diretamente ao problema que queremos\nresolver (tradução nossa, §4.2, Teorema 4.8, p. 106): \"$\\lambda\\in\n\\mathbb{R}$ é um autovalor de $A\\in\\mathbb{R}^{n\\times n}$ se, e somente\nse, $\\lambda$ é uma raiz do polinômio característico $p_A(\\lambda)$ de\n$A$.\" Ou seja: **os autovalores de $A$ são exatamente as raízes reais de\num único polinômio**, $p_A(\\lambda)$ — encontrar todos os autovalores\nde uma matriz $2\\times 2$ vira, literalmente, resolver uma equação do\nsegundo grau.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\n**Definição 4.5 - O Polinômio Característico (MathML):**\n$$p_A(\\lambda) := \\det(A-\\lambda I) = c_0+c_1\\lambda+\\cdots+(-1)^n\\lambda^n$$\né o **polinômio característico** de $A$.\n:::\n\n::: {.fragment}\n**Teorema 4.8 (MathML, tradução nossa):** $\\lambda\\in\\mathbb{R}$ é\nautovalor de $A$ $\\iff$ $\\lambda$ é raiz de $p_A(\\lambda)$.\n:::\n\n::: {.fragment}\nAutovalores de $A$ = raízes reais de **um único** polinômio — para\n$2\\times 2$, literalmente resolver uma equação do 2º grau.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo (ii): Aplicando ao Exemplo do Bloco 2 — o Polinômio\n\nVamos calcular à mão, do zero, usando a mesma matriz do Bloco 2,\n$A=\\begin{bmatrix}4&2\\\\1&3\\end{bmatrix}$ (MathML, Exemplo 4.5, p. 107).\n$$\nA-\\lambda I = \\begin{bmatrix}4-\\lambda & 2\\\\ 1 & 3-\\lambda\\end{bmatrix},\n\\qquad\np_A(\\lambda) = \\det(A-\\lambda I) = (4-\\lambda)(3-\\lambda) - 2\\cdot 1.\n$$\nExpandindo o produto: $(4-\\lambda)(3-\\lambda) = 12-7\\lambda+\\lambda^2$,\nlogo\n$$\np_A(\\lambda) = 12-7\\lambda+\\lambda^2-2 = \\lambda^2-7\\lambda+10.\n$$\nO MathML resolve essa mesma equação por fatoração direta (tradução\nnossa): \"fatorizamos o polinômio característico e obtemos\n$p(\\lambda)=(4-\\lambda)(3-\\lambda)-2\\cdot 1=10-7\\lambda+\\lambda^2=\n(2-\\lambda)(5-\\lambda)$, dando as raízes $\\lambda_1=2$ e $\\lambda_2=5$.\"\nConfirmando por Bhaskara, para não depender só de \"ver\" a fatoração:\nraízes de $\\lambda^2-7\\lambda+10=0$ são\n$$\n\\lambda=\\frac{7\\pm\\sqrt{49-40}}{2}=\\frac{7\\pm\\sqrt{9}}{2}=\\frac{7\\pm 3}{2},\n$$\nou seja $\\lambda\\in\\{2,5\\}$ — exatamente os dois valores que a elipse do\nBloco 2 já tinha marcado nos eixos.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo (ii): O Polinômio do Exemplo\n\n::: {.fragment}\n$A=\\begin{bmatrix}4&2\\\\1&3\\end{bmatrix}$ (Bloco 2, MathML Ex. 4.5):\n$$A-\\lambda I = \\begin{bmatrix}4-\\lambda & 2\\\\ 1 & 3-\\lambda\\end{bmatrix}$$\n$$p_A(\\lambda) = (4-\\lambda)(3-\\lambda)-2\\cdot 1 = \\lambda^2-7\\lambda+10$$\n:::\n\n::: {.fragment}\n**MathML (tradução nossa):** fatorando,\n$p(\\lambda)=(2-\\lambda)(5-\\lambda)$ $\\Rightarrow$ raízes\n$\\lambda_1=2$, $\\lambda_2=5$.\n:::\n\n::: {.fragment}\nConfirmando por Bhaskara:\n$$\n\\lambda=\\frac{7\\pm\\sqrt{49-40}}{2}=\\frac{7\\pm\\sqrt{9}}{2}=\\frac{7\\pm 3}{2}\n$$\n$\\lambda\\in\\{2,5\\}$ — exatamente os eixos da elipse do Bloco 2.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo (iii): De Volta à Equação Original — Achando os Autovetores\n\nAchar $\\lambda$ resolveu metade do problema; falta achar, para cada\n$\\lambda$, o(s) autovetor(es) associado(s), resolvendo\n$(A-\\lambda I)\\mathbf{x}=\\mathbf{0}$ com o valor de $\\lambda$ já\nconhecido. Para $\\lambda_2=5$:\n$$\nA - 5I = \\begin{bmatrix}-1 & 2\\\\ 1 & -2\\end{bmatrix},\n\\qquad\n(A-5I)\\mathbf{x}=\\mathbf{0} \\;\\Longrightarrow\\; -x_1+2x_2=0\n\\;\\Longrightarrow\\; x_1=2x_2.\n$$\nA equação $x_1=2x_2$ tem uma variável livre: qualquer valor de $x_2$\ndetermina $x_1$. Parametrizando $x_2=t$ para $t\\in\\mathbb{R}$\narbitrário, obtemos $x_1=2t$, ou seja\n$$\n(x_1,x_2) = (2t,t) = t\\cdot(2,1).\n$$\nEsse é, por definição, o conjunto de todos os múltiplos escalares de\n$(2,1)$ — $\\text{span}((2,1)) := \\{t\\cdot(2,1) : t\\in\\mathbb{R}\\}$. O\n**autoespaço** $E_5$ é, por definição, o conjunto-solução inteiro de\n$(A-5I)\\mathbf{x}=\\mathbf{0}$ (uma reta pela origem, incluindo o caso\n$t=0$, que dá a solução trivial); os **autovetores** propriamente ditos\nsão os elementos não-nulos desse conjunto ($t\\ne 0$, pela Premissa 2).\nLogo\n$$\nE_5=\\text{span}((2,1))\n$$\n(MathML: \"obtemos o espaço-solução $E_5=\\text{span}([2,1])$\"). Para\n$\\lambda_1=2$:\n$$\nA-2I = \\begin{bmatrix}2 & 2\\\\ 1 & 1\\end{bmatrix},\n\\qquad\n(A-2I)\\mathbf{x}=\\mathbf{0} \\;\\Longrightarrow\\; x_1+x_2=0\n\\;\\Longrightarrow\\; x_1=-x_2,\n$$\nmesmo processo: parametrizando $x_2=t$, $(x_1,x_2)=(-t,t)=t\\cdot(-1,1)$,\ndando $E_2=\\text{span}((-1,1))$. Como $(-1,1)=-1\\cdot(1,-1)$, essa é a\nmesma reta que $\\text{span}((1,-1))$ — trocar o sinal do parâmetro\n$t$ não muda o conjunto de múltiplos escalares, só relabeia qual $t$\ngera qual ponto. Escrevemos $E_2=\\text{span}((1,-1))$ por convenção;\nisso é consistente com o autovetor ser uma **direção**, não um vetor de\nsinal fixo (Bloco 2, \"A Equação Formal\"). Note que $(2,1)$ e\n$(1,-1)$ são exatamente as duas direções (laranja e vermelha)\ndesenhadas no painel do Bloco 2 — o cálculo algébrico confirma, número\npor número, o que o desenho já tinha mostrado visualmente.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo (iii): Achando os Autovetores\n\n::: {.fragment}\nPara $\\lambda_2=5$: $A-5I=\\begin{bmatrix}-1&2\\\\1&-2\\end{bmatrix}$\n$\\Rightarrow$ $-x_1+2x_2=0 \\Rightarrow x_1=2x_2$.\n:::\n\n::: {.fragment}\nVariável livre $x_2=t$ $\\Rightarrow$\n$(x_1,x_2)=(2t,t)=t\\cdot(2,1)$ — por definição, o conjunto de todos\nos múltiplos escalares de $(2,1)$:\n$$E_5=\\text{span}((2,1)) := \\{t\\cdot(2,1) : t\\in\\mathbb{R}\\}$$\n(MathML).\n:::\n\n::: {.fragment}\nPara $\\lambda_1=2$: $A-2I=\\begin{bmatrix}2&2\\\\1&1\\end{bmatrix}$\n$\\Rightarrow$ $x_1+x_2=0 \\Rightarrow x_1=-x_2$. \n:::\n\n::: {.fragment}\nParametrizando\n$x_2=t$: $(x_1,x_2)=t\\cdot(-1,1)$, mesma reta que $\\text{span}((1,-1))$\n(sinal do parâmetro só relabeia os pontos) $\\Rightarrow$\n$E_2=\\text{span}((1,-1))$.\n:::\n\n::: {.fragment}\n$(2,1)$ e $(1,-1)$: **exatamente** as duas direções (laranja/vermelha)\ndo Bloco 2 — o cálculo confirma, número por número, o desenho.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Verificação Numérica: `numpy.linalg.eig`\n\nFazer essa conta à mão é indispensável para entender **de onde** vêm os\nautovalores/autovetores, mas na prática — matrizes maiores que\n$2\\times 2$, ou o caso $X^TX\\in\\mathbb{R}^{4\\times 4}$ do Bloco 6 — o\npolinômio característico vira inviável de resolver manualmente\n(polinômios de grau $\\ge 5$ nem sempre têm raiz em forma fechada).\n`numpy.linalg.eig` resolve o mesmo problema numericamente:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Verificação Numérica\n\n::: {.fragment}\nÀ mão é indispensável para entender a origem; mas para matrizes maiores\n(ex.: $X^TX\\in\\mathbb{R}^{4\\times 4}$ do Bloco 6), o polinômio\ncaracterístico vira inviável (grau $\\ge 5$ nem sempre tem raiz fechada).\n`numpy.linalg.eig` resolve numericamente:\n:::\n:::\n\n::: {#b15c6407 .cell execution_count=3}\n``` {.python .cell-code}\nautovalores, autovetores = np.linalg.eig(A_exemplo)\n# Autovalores reais (2 e 5); numpy.linalg.eig devolve dtype complexo por\n# padrão para matrizes não-simétricas — parte imaginária é zero aqui.\nautovalores = autovalores.real\nautovetores = autovetores.real\nprint(\"Autovalores:\", autovalores)\nprint(\"Autovetores (colunas, normalizados por numpy):\")\nprint(autovetores)\n\n# Conferindo A x = lambda x diretamente, para cada par\nfor k in range(2):\n    lhs = A_exemplo @ autovetores[:, k]\n    rhs = autovalores[k] * autovetores[:, k]\n    print(f\"  lambda={autovalores[k]:.1f}: ||A x - lambda x|| = {np.linalg.norm(lhs - rhs):.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAutovalores: [5. 2.]\nAutovetores (colunas, normalizados por numpy):\n[[ 0.89442719 -0.70710678]\n [ 0.4472136   0.70710678]]\n  lambda=5.0: ||A x - lambda x|| = 0.00e+00\n  lambda=2.0: ||A x - lambda x|| = 3.14e-16\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nOs autovalores batem exatamente com $\\{2,5\\}$ calculados à mão, e a\nigualdade $A\\mathbf{x}=\\lambda\\mathbf{x}$ é confirmada numericamente até\nerro de arredondamento. Uma diferença importante de convenção: o\n`numpy` sempre devolve os autovetores **normalizados** (norma $1$) — é\nsó mais uma escolha dentro da reta de infinitos múltiplos escalares\nválidos (a não-unicidade do Bloco 2), não uma contradição com o\n$(2,1)$/$(1,-1)$ calculado à mão.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que a Verificação Confirma\n\n::: {.fragment}\nAutovalores batem exatamente com $\\{2,5\\}$; $A\\mathbf{x}=\\lambda\\mathbf{x}$\nconfirmado até erro de arredondamento.\n:::\n\n::: {.fragment}\n`numpy` sempre normaliza autovetores (norma $1$) — só mais uma escolha\ndentro da reta de múltiplos escalares válidos, não contradição com\n$(2,1)$/$(1,-1)$ calculado à mão.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se o polinômio característico de uma matriz $3\\times 3$ tivesse grau 3 mas só uma raiz real, quantos autovalores reais essa matriz teria?\n\nDica: o Teorema 4.8 conecta autovalor a **raiz real** do polinômio\ncaracterístico — o que acontece quando algumas raízes não são reais?\n\n- □ Uma matriz $3\\times 3$ cujo polinômio característico (grau 3) tem só\n  uma raiz real teria exatamente **um** autovalor real — as outras duas\n  raízes, sendo complexas, não correspondem a autovalores reais da\n  matriz.\n- □ Se o polinômio característico de uma matriz $2\\times 2$ não tivesse\n  nenhuma raiz real (discriminante negativo em Bhaskara), essa matriz\n  não teria autovalor real algum, mas ainda seria uma transformação\n  linear perfeitamente válida sobre $\\mathbb{R}^2$ (ex.: uma rotação\n  pura por um ângulo diferente de $0°$/$180°$).\n- □ Num modelo de crescimento populacional descrito por uma matriz de\n  transição $2\\times 2$, encontrar os autovalores dessa matriz por\n  polinômio característico é uma aplicação válida da mesma técnica, mesmo\n  a matriz não vindo de geometria.\n- □ Como o autovetor associado a um autovalor não é único, isso implica\n  que, ao resolver $(A-\\lambda I)\\mathbf{x}=\\mathbf{0}$ à mão para achar\n  $E_\\lambda$, sempre existe mais de uma equação linearmente\n  independente restringindo $\\mathbf{x}$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Polinômio de grau 3 com só uma raiz real: quantos autovalores reais?\n\nDica: autovalor = raiz **real** do polinômio característico (Teorema\n4.8) — raízes complexas contam?\n\n- □ Grau 3, só uma raiz real: exatamente **um** autovalor real — as\n  outras duas (complexas) não correspondem a autovalor real.\n- □ Se o polinômio característico $2\\times 2$ não tivesse raiz real\n  (discriminante negativo), a matriz não teria autovalor real, mas ainda\n  seria transformação linear válida (ex.: rotação pura).\n- □ Modelo de crescimento populacional ($2\\times 2$): achar autovalores\n  por polinômio característico é aplicação válida, fora da geometria.\n- □ Autovetor não-único $\\Rightarrow$ ao resolver\n  $(A-\\lambda I)\\mathbf{x}=\\mathbf{0}$, sempre há mais de uma equação\n  linearmente independente restringindo $\\mathbf{x}$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Raízes reais vs. complexas, e o autoespaço — Resposta\n\n- ✔ Exatamente a leitura correta do Teorema 4.8: só raízes reais do\n  polinômio característico contam como autovalor (real) da matriz.\n- ✔ Rotação pura por ângulo $\\ne 0°,180°$ não tem direção que só\n  estique/encolha (toda direção gira) — consistente com polinômio\n  característico sem raiz real.\n- ✔ Mesma técnica algébrica, aplicada fora de contexto geométrico.\n- ✗ É o oposto do exemplo desta aula: $A-\\lambda I$ deu **uma** equação\n  independente por autovalor ($x_1=2x_2$ e $x_1=-x_2$), não várias — o\n  autoespaço de $A_{\\text{exemplo}}$ tem dimensão $1$ em cada caso,\n  apesar da não-unicidade do autovetor dentro dessa reta.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** só raízes reais do polinômio característico\ncontam. Uma matriz $n\\times n$ real pode ter menos de $n$ autovalores\nreais — o caso extremo é a rotação pura, sem nenhum.\n:::\n:::\n\n# O Teorema Espectral Real para Matrizes Simétricas\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Por Que Isso Importa Para $X^TX$\n\nAntes de qualquer prova, a razão de este bloco existir: a Aula 3 usou\n$X^TX$ o tempo todo, e uma propriedade dela nunca foi explorada a fundo\n— **$X^TX$ é sempre simétrica**, para qualquer $X$, mesmo retangular\n($(X^TX)^T=X^T(X^T)^T=X^TX$, pela regra $(AB)^T=B^TA^T$ seguida de\n$(X^T)^T=X$ — uma linha de álgebra). O MathML vai além:\n(tradução nossa, §4.2, Teorema 4.14, p. 111) \"dada uma matriz\n$A\\in\\mathbb{R}^{m\\times n}$, sempre podemos obter uma matriz simétrica,\nsemidefinida positiva $S\\in\\mathbb{R}^{n\\times n}$ definindo\n$S:=A^TA$.\" O próprio MathML separa a segunda metade num comentário à\nparte (Observação, p. 111): \"se $\\text{rk}(A)=n$, então $S:=A^TA$ é\nsimétrica, definida positiva.\" **As duas condições são diferentes, e só\numa delas depende do posto:** \"semidefinida positiva\" vale **sempre**,\npara qualquer $A$ — mesmo singular, mesmo retangular, sem nenhuma\nhipótese extra; é **só** \"definida positiva\" (a versão mais forte, que\nexclui vetores não-nulos no núcleo de $S$ — definição formal logo a\nseguir) que exige $\\text{rk}(A)=n$, posto completo. Aplicando a\n$X^TX$: **$X^TX$ é\nsempre semidefinida positiva**, tenha $X$ posto completo ou não; ela só\né **definida** positiva sob posto completo — a mesma condição que a\nAula 3 já usou para garantir invertibilidade. Este bloco prova o que a\nsimetria de $X^TX$ garante sobre seus autovalores e autovetores — a\npeça que faltava para o Bloco 5 fechar o ciclo da Aula 3.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Por Que Isso Importa Para $X^TX$\n\n::: {.fragment}\n$X^TX$ é **sempre simétrica**, para qualquer $X$ (mesmo retangular):\n$(X^TX)^T = X^T(X^T)^T = X^TX$ — uma linha de álgebra (regra\n$(AB)^T=B^TA^T$, depois $(X^T)^T=X$).\n:::\n\n::: {.fragment}\n**Teorema 4.14 (MathML, tradução nossa):** para qualquer\n$A\\in\\mathbb{R}^{m\\times n}$, $S:=A^TA$ é sempre simétrica,\nsemidefinida positiva; se $\\text{rk}(A)=n$, $S$ é definida positiva.\n:::\n\n::: {.fragment}\n**Só uma das duas condições depende do posto:** \"semidefinida\npositiva\" vale **sempre**, mesmo $A$ singular ou retangular; **só**\n\"definida positiva\" exige $\\text{rk}(A)=n$ (definição formal a seguir).\nLogo $X^TX$ é sempre semidefinida positiva — e só é definida positiva\nsob posto completo.\n:::\n\n::: {.fragment}\nEste bloco prova o que a simetria de $X^TX$ garante sobre seus\nautovalores/autovetores — peça que falta para o Bloco 5 fechar o ciclo\nda Aula 3.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Definição: Matrizes Definidas e Semidefinidas Positivas\n\nAntes de provar que $X^TX$ tem essa propriedade, falta a definição\nformal — \"semidefinida positiva\" foi usado acima antes de ser\ndefinido, e essa lacuna se fecha agora. O MathML define (tradução\nnossa, §3.2.3, Definição 3.4, p. 74):\n\n> \"Uma matriz simétrica $A\\in\\mathbb{R}^{n\\times n}$ que satisfaz [...]\n> $\\mathbf{x}^TA\\mathbf{x}>0$ para todo $\\mathbf{x}\\in V\\setminus\n> \\{\\mathbf{0}\\}$ é chamada simétrica, definida positiva, ou apenas\n> **positiva definida**. Se vale apenas $\\ge$ [...], então $A$ é chamada\n> simétrica, **semidefinida positiva**.\"\n\nDuas cláusulas, uma definição, uma hipótese comum: $A$ precisa ser\n**simétrica** ($A=A^T$) — sem isso a definição nem se aplica, \"definida\npositiva\" e \"semidefinida positiva\" só classificam matrizes simétricas.\nDada essa hipótese, o que separa as duas é só o tipo de desigualdade\nsobre $\\mathbf{x}^TA\\mathbf{x}$: estrita ($>0$) para \"definida\",\nfraca ($\\ge 0$) para \"semidefinida\" — e em ambos os casos a desigualdade\nprecisa valer para **todo** $\\mathbf{x}\\ne\\mathbf{0}$, não para um\n$\\mathbf{x}$ escolhido a dedo. Com a definição em mãos, o teorema a\nseguir mostra por que $X^TX$ sempre satisfaz a versão fraca.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Definição: Matrizes Definidas e Semidefinidas Positivas\n\n::: {.fragment}\n**Definição 3.4 (MathML, tradução nossa):** $A$ **simétrica**\n($A=A^T$) é **definida positiva** se $\\mathbf{x}^TA\\mathbf{x}>0$ para\ntodo $\\mathbf{x}\\ne\\mathbf{0}$; é **semidefinida positiva** se vale\napenas $\\mathbf{x}^TA\\mathbf{x}\\ge 0$ para todo $\\mathbf{x}\\ne\\mathbf{0}$.\n:::\n\n::: {.fragment}\nSimetria é **hipótese**, não conclusão — sem $A=A^T$ a definição nem se\naplica. \"Definida\" vs. \"semidefinida\": desigualdade estrita ($>0$)\nvs. fraca ($\\ge 0$), testada para **todo** $\\mathbf{x}\\ne\\mathbf{0}$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Teorema: $A^TA$ é Simétrica e Semidefinida Positiva\n\nIsso é exatamente o Teorema 4.14 citado acima — mas citar não é provar,\ne a prova é curta o bastante para não pular. O MathML só esboça a ideia\n(tradução nossa, p. 111); reconstruímos os dois passos por extenso.\n\n::: {.callout-note icon=false}\n## Teorema (MathML 4.14, parte 1 — simetria)\n\nPara qualquer $A\\in\\mathbb{R}^{m\\times n}$, a matriz\n$S:=A^TA\\in\\mathbb{R}^{n\\times n}$ é simétrica.\n:::\n\n*Prova.* Por definição, $S$ é simétrica se $S=S^T$. Calculamos $S^T$ a\npartir de $S:=A^TA$, aplicando a regra $(BC)^T=C^TB^T$ com $B=A^T$ e\n$C=A$:\n$$\nS^T = (A^TA)^T = A^T(A^T)^T = A^TA = S,\n$$\nusando $(A^T)^T=A$ na penúltima igualdade. Logo $S=S^T$. $\\blacksquare$\n\n::: {.callout-note icon=false}\n## Teorema (MathML 4.14, parte 2 — semidefinitude positiva)\n\nPara qualquer $A\\in\\mathbb{R}^{m\\times n}$, a matriz $S:=A^TA$ satisfaz\n$\\mathbf{x}^TS\\mathbf{x}\\ge 0$ para todo $\\mathbf{x}\\in\\mathbb{R}^n$.\n:::\n\n*Prova.* Seja $\\mathbf{x}\\in\\mathbb{R}^n$ arbitrário. Substituindo\n$S=A^TA$ e reagrupando por associatividade do produto de matrizes:\n$$\n\\mathbf{x}^TS\\mathbf{x} = \\mathbf{x}^T(A^TA)\\mathbf{x}\n= (\\mathbf{x}^TA^T)(A\\mathbf{x}).\n$$\nPela mesma regra $(BC)^T=C^TB^T$ (com $B=A$, $C=\\mathbf{x}$),\n$\\mathbf{x}^TA^T=(A\\mathbf{x})^T$, logo\n$$\n\\mathbf{x}^TS\\mathbf{x} = (A\\mathbf{x})^T(A\\mathbf{x}) = \\|A\\mathbf{x}\\|^2,\n$$\nusando que o produto de um vetor pela sua própria transposta é a soma\ndos quadrados de suas entradas, ou seja, a norma ao quadrado — sempre\n$\\ge 0$, qualquer que seja o vetor $A\\mathbf{x}$. Como $\\mathbf{x}$ era\narbitrário, isso vale para todo $\\mathbf{x}\\in\\mathbb{R}^n$, que é\nexatamente a Definição 3.4 de semidefinida positiva. $\\blacksquare$\n\nAplicando os dois teoremas com $A=X$: $X^TX$ é simétrica e semidefinida\npositiva, para **qualquer** $X$, com ou sem posto completo — a prova\nnão usa hipótese nenhuma sobre o posto de $A$ em nenhum dos dois\npassos. É esse fato, agora demonstrado e não só citado, que o resto\ndeste bloco explora: o que a simetria (e a semidefinitude, quando for\nestritamente definida) garante sobre os autovalores e autovetores de\n$X^TX$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Teorema: $A^TA$ é Simétrica e Semidefinida Positiva\n\n::: {.callout-note icon=false}\n**Teorema (MathML 4.14):** para qualquer $A\\in\\mathbb{R}^{m\\times n}$,\n$S:=A^TA$ é simétrica e satisfaz $\\mathbf{x}^TS\\mathbf{x}\\ge 0$ para\ntodo $\\mathbf{x}\\in\\mathbb{R}^n$.\n:::\n\n::: {.fragment}\n**Prova (simetria).** $S:=A^TA \\Rightarrow$\n$$S^T=(A^TA)^T=A^T(A^T)^T=A^TA=S$$\n(regra $(BC)^T=C^TB^T$, depois $(A^T)^T=A$). $\\blacksquare$\n:::\n\n::: {.fragment}\n**Prova (semidefinitude positiva).** Para todo $\\mathbf{x}\\in\\mathbb{R}^n$:\n$$\\mathbf{x}^TS\\mathbf{x} = \\mathbf{x}^T(A^TA)\\mathbf{x} = (\\mathbf{x}^TA^T)(A\\mathbf{x}) = (A\\mathbf{x})^T(A\\mathbf{x}) = \\|A\\mathbf{x}\\|^2 \\ge 0$$\nusando $\\mathbf{x}^TA^T=(A\\mathbf{x})^T$ (mesma regra de transposta).\n$\\blacksquare$\n:::\n\n::: {.fragment}\nCom $A=X$: prova completa (não só citação) de por que $X^TX$ é sempre\nsimétrica e semidefinida positiva — com ou sem posto completo, nenhuma\ndas duas provas usa essa hipótese.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Premissas e Prova: Autovetores de Autovalores Distintos São Ortogonais\n\n::: {.callout-note}\n## Premissas\n\n1. $A\\in\\mathbb{R}^{n\\times n}$ é **simétrica**, ou seja, $A=A^T$.\n2. $\\mathbf{x}_1,\\mathbf{x}_2$ são autovetores de $A$ associados a\n   autovalores **distintos**, $\\lambda_1\\ne\\lambda_2$:\n   $A\\mathbf{x}_1=\\lambda_1\\mathbf{x}_1$,\n   $A\\mathbf{x}_2=\\lambda_2\\mathbf{x}_2$.\n:::\n\n**Nota de precisão:** a prova a seguir é exposição nossa, não uma\ncitação literal de nenhuma das fontes — o MathML e o Boyd enunciam o\nTeorema Espectral diretamente, sem detalhar este passo intermediário no\nnível que este curso quer mostrar. A prova em si é padrão (manipulação\nde $\\mathbf{x}_1^TA\\mathbf{x}_2$ dos dois lados), mas construída aqui,\nnão copiada.\n\nCalculamos o escalar $\\mathbf{x}_1^TA\\mathbf{x}_2$ de duas formas\ndiferentes. **Primeiro**, aplicando $A$ diretamente a $\\mathbf{x}_2$\n(Premissa 2):\n$$\n\\mathbf{x}_1^TA\\mathbf{x}_2 = \\mathbf{x}_1^T(\\lambda_2\\mathbf{x}_2) =\n\\lambda_2\\,(\\mathbf{x}_1^T\\mathbf{x}_2).\n$$\n**Segundo**, usando que $\\mathbf{x}_1^TA\\mathbf{x}_2$ é um escalar\n$1\\times 1$ (logo igual à sua própria transposta) e que $A$ é simétrica\n(Premissa 1):\n$$\n\\mathbf{x}_1^TA\\mathbf{x}_2 = (\\mathbf{x}_1^TA\\mathbf{x}_2)^T =\n\\mathbf{x}_2^TA^T\\mathbf{x}_1 = \\mathbf{x}_2^TA\\mathbf{x}_1 =\n\\mathbf{x}_2^T(\\lambda_1\\mathbf{x}_1) = \\lambda_1\\,(\\mathbf{x}_2^T\\mathbf{x}_1).\n$$\nComo $\\mathbf{x}_1^T\\mathbf{x}_2=\\mathbf{x}_2^T\\mathbf{x}_1$ (produto\ninterno é simétrico), as duas contas dão o mesmo escalar por dois\ncaminhos, logo\n$$\n\\lambda_2\\,(\\mathbf{x}_1^T\\mathbf{x}_2) = \\lambda_1\\,(\\mathbf{x}_1^T\\mathbf{x}_2)\n\\quad\\Longrightarrow\\quad\n(\\lambda_2-\\lambda_1)\\,(\\mathbf{x}_1^T\\mathbf{x}_2) = 0.\n$$\nPela Premissa 2, $\\lambda_2-\\lambda_1\\ne 0$; logo o único jeito de o\nproduto ser zero é $\\mathbf{x}_1^T\\mathbf{x}_2=0$ — **autovetores de\nautovalores distintos de uma matriz simétrica são automaticamente\nortogonais**. Note onde a simetria de $A$ entrou: exatamente na troca\n$A^T\\to A$ no segundo cálculo — sem ela, os dois caminhos não\ncoincidiriam, e é por isso que o Bloco 2 encontrou autovetores\n**não**-ortogonais numa matriz não-simétrica.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Premissas e Prova: Ortogonalidade\n\n::: {.callout-note icon=false}\n## Premissas\n\n1. $A\\in\\mathbb{R}^{n\\times n}$ **simétrica** ($A=A^T$).\n2. $\\mathbf{x}_1,\\mathbf{x}_2$ autovetores de autovalores **distintos**\n   $\\lambda_1\\ne\\lambda_2$.\n:::\n\n::: {.fragment}\n**Prova.** Calculamos o escalar $\\mathbf{x}_1^TA\\mathbf{x}_2$ de duas\nformas diferentes.\n:::\n\n::: {.fragment}\n**Primeiro**, aplicando $A$ diretamente a $\\mathbf{x}_2$ (Premissa 2):\n$$\\mathbf{x}_1^TA\\mathbf{x}_2 = \\mathbf{x}_1^T(\\lambda_2\\mathbf{x}_2) =\n\\lambda_2\\,(\\mathbf{x}_1^T\\mathbf{x}_2)$$\n:::\n\n::: {.fragment}\n**Segundo**, usando que é um escalar $1\\times 1$ (igual à própria\ntransposta) e que $A$ é simétrica (Premissa 1):\n$$\\mathbf{x}_1^TA\\mathbf{x}_2 = (\\mathbf{x}_1^TA\\mathbf{x}_2)^T =\n\\mathbf{x}_2^TA^T\\mathbf{x}_1 = \\mathbf{x}_2^TA\\mathbf{x}_1 =\n\\lambda_1\\,(\\mathbf{x}_2^T\\mathbf{x}_1)$$\n:::\n\n::: {.fragment}\nComo $\\mathbf{x}_1^T\\mathbf{x}_2=\\mathbf{x}_2^T\\mathbf{x}_1$ (produto\ninterno é simétrico), os dois caminhos calculam o mesmo escalar por\nrotas diferentes, logo\n$$\\lambda_2\\,(\\mathbf{x}_1^T\\mathbf{x}_2) = \\lambda_1\\,(\\mathbf{x}_1^T\\mathbf{x}_2)\n\\;\\Longrightarrow\\; (\\lambda_2-\\lambda_1)\\,(\\mathbf{x}_1^T\\mathbf{x}_2) = 0.$$\n:::\n\n::: {.fragment}\nPela Premissa 2, $\\lambda_2-\\lambda_1\\ne 0$; o único jeito de o produto\nser zero é $\\mathbf{x}_1^T\\mathbf{x}_2=0$ — **autovetores de autovalores\ndistintos de uma matriz simétrica são automaticamente ortogonais**.\n$\\blacksquare$\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## O Teorema Espectral Real\n\nA prova acima garante ortogonalidade **entre** autovetores de\nautovalores distintos, mas o Teorema Espectral Real garante mais: que os\nautovalores de uma matriz simétrica são sempre **reais** (nunca\ncomplexos, ao contrário do que o Bloco 3 mostrou ser possível em\ngeral), e que existe uma base ortonormal **inteira** feita de\nautovetores — mesmo quando há autovalores repetidos (caso em que a\nortogonalidade entre autovetores do *mesmo* autoespaço não vem de graça\nda prova acima, e precisa de um processo à parte, Gram-Schmidt, que o\nMathML ilustra no Exemplo 4.8, sem aprofundar aqui).\n\n::: {.callout-note icon=false}\n## Teorema 4.15 — Teorema Espectral Real (MathML, tradução nossa, §4.2, p. 111)\n\nSe $A\\in\\mathbb{R}^{n\\times n}$ é simétrica, existe uma base ortonormal\ndo espaço vetorial correspondente $V$ formada por autovetores de $A$, e\ncada autovalor é real.\n:::\n\nO Boyd enuncia a mesma garantia de forma equivalente, já na forma\nmatricial que vamos usar no resto da aula:\n\n::: {.callout-note icon=false}\n## Teorema — Forma Matricial Equivalente (Boyd & Vandenberghe, tradução nossa, Apêndice A.5.2, p. 646-647)\n\nSuponha $A\\in\\mathcal{S}^n$, ou seja, $A$ é uma matriz real simétrica\n$n\\times n$. Então $A$ pode ser fatorada como $A=Q\\Lambda Q^T$, onde\n$Q\\in\\mathbb{R}^{n\\times n}$ é ortogonal (isto é, $Q^TQ=I$) e\n$\\Lambda=\\text{diag}(\\lambda_1,\\dots,\\lambda_n)$.\n:::\n\n\"$Q$ ortogonal\" significa exatamente $Q^TQ=I$ — as colunas de $Q$ (os\nautovetores) formam uma base ortonormal, a mesma garantia do teorema\nanterior, escrita em forma de fatoração matricial: $A=Q\\Lambda Q^T$ é a\n**decomposição espectral** de $A$. Os dois teoremas acima dizem\nexatamente a mesma coisa, em duas notações: o MathML fala em \"base do\nespaço vetorial $V$\", o Boyd fala em \"matriz ortogonal $Q$\" cujas\ncolunas são essa base — a ponte entre as duas é literalmente\n$Q=[\\mathbf{x}_1\\;\\cdots\\;\\mathbf{x}_n]$, os autovetores empilhados\ncomo colunas.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Teorema Espectral Real\n\n::: {.fragment}\nGarante mais que a prova de ortogonalidade: autovalores de matriz\nsimétrica são sempre **reais**, e existe uma base ortonormal **inteira**\nde autovetores (mesmo com autovalores repetidos — Gram-Schmidt, MathML\nExemplo 4.8, não aprofundado aqui).\n:::\n\n::: {.callout-note icon=false}\n**Teorema 4.15 (MathML, tradução nossa):** $A$ simétrica $\\Rightarrow$\nexiste base ortonormal de $V$ de autovetores de $A$, cada autovalor\nreal.\n:::\n\n::: {.callout-note icon=false}\n**Teorema (Boyd, Apêndice A.5.2, tradução nossa):** $A\\in\\mathcal{S}^n$\nsimétrica $\\Rightarrow$ $A=Q\\Lambda Q^T$, $Q$ ortogonal ($Q^TQ=I$),\n$\\Lambda=\\text{diag}(\\lambda_1,\\dots,\\lambda_n)$ — a **decomposição\nespectral** de $A$.\n:::\n\n::: {.fragment}\nOs dois dizem a mesma coisa: MathML fala em \"base de $V$\", Boyd em\n\"colunas de $Q$\" — a ponte é $Q=[\\mathbf{x}_1\\;\\cdots\\;\\mathbf{x}_n]$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Contraste Direto: Exemplo Resolvido de uma Matriz Simétrica\n\nPara ver a diferença na prática, refazemos o cálculo à mão do Bloco 3,\nagora com uma matriz **simétrica**,\n$$\nA_{\\text{sim}} = \\frac12\\begin{bmatrix}5 & -2\\\\ -2 & 5\\end{bmatrix},\n$$\no mesmo exemplo do MathML (tradução nossa, §4.2, Exemplo 4.11, p.\n117-118): \"vamos calcular a decomposição em autovalores de\n$A=\\frac12\\begin{bmatrix}5&-2\\\\-2&5\\end{bmatrix}$. [...] os autovalores\nde $A$ são $\\lambda_1=7/2$ e $\\lambda_2=3/2$ [...]\n$\\mathbf{p}_1=\\frac{1}{\\sqrt2}[1,-1]$,\n$\\mathbf{p}_2=\\frac{1}{\\sqrt2}[1,1]$.\" Repare já na diferença mais\nimediata: **$A_{\\text{sim}}=A_{\\text{sim}}^T$**, diferente da matriz do\nBloco 2/3 ($A\\ne A^T$ ali). Vamos verificar numericamente — os\nautovalores, e principalmente o ângulo entre os autovetores, comparado\nlado a lado com o exemplo não-simétrico:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Contraste Direto: Matriz Simétrica\n\n::: {.fragment}\n$A_{\\text{sim}}=\\frac12\\begin{bmatrix}5&-2\\\\-2&5\\end{bmatrix}$ (MathML,\nExemplo 4.11) — diferente do Bloco 2/3, $A_{\\text{sim}}=A_{\\text{sim}}^T$.\n:::\n\n::: {.fragment}\n**MathML (tradução nossa):** $\\lambda_1=7/2$, $\\lambda_2=3/2$,\n$\\mathbf{p}_1=\\frac{1}{\\sqrt2}(1,-1)$, $\\mathbf{p}_2=\\frac{1}{\\sqrt2}(1,1)$.\n:::\n:::\n\n::: {.fig-resize style=\"width: 60%; margin: 0 auto;\"}\n\n::: {#d3fa7d10 .cell execution_count=4}\n``` {.python .cell-code}\nautovalores_sim, autovetores_sim = np.linalg.eigh(A_sim)\nprint(\"Autovalores de A_sim:\", autovalores_sim)\nprint(\"Autovetores de A_sim (colunas):\")\nprint(autovetores_sim)\n\ndef angulo_entre(u, v):\n    cos_ang = np.clip((u @ v) / (np.linalg.norm(u) * np.linalg.norm(v)), -1, 1)\n    return np.degrees(np.arccos(cos_ang))\n\nang_sim = angulo_entre(autovetores_sim[:, 0], autovetores_sim[:, 1])\nang_nao_sim = angulo_entre(autovetores_ex[:, 0], autovetores_ex[:, 1])\nprint(f\"\\nÂngulo entre autovetores de A_sim (simétrica):        {ang_sim:.2f} graus\")\nprint(f\"Ângulo entre autovetores de A_exemplo (não-simétrica): {ang_nao_sim:.2f} graus\")\nprint(f\"\\nA_sim é simétrica? {np.allclose(A_sim, A_sim.T)}\")\nprint(f\"A_exemplo é simétrica? {np.allclose(A_exemplo, A_exemplo.T)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAutovalores de A_sim: [1.5 3.5]\nAutovetores de A_sim (colunas):\n[[-0.70710678 -0.70710678]\n [-0.70710678  0.70710678]]\n\nÂngulo entre autovetores de A_sim (simétrica):        90.00 graus\nÂngulo entre autovetores de A_exemplo (não-simétrica): 108.43 graus\n\nA_sim é simétrica? True\nA_exemplo é simétrica? False\n```\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nOs autovalores $3{,}5$ e $1{,}5$ conferem exatamente com o MathML, e o\nângulo entre os autovetores de $A_{\\text{sim}}$ dá $90°$ — ortogonais,\ncomo a prova deste bloco garantiu. Já o ângulo entre os autovetores de\n$A_{\\text{exemplo}}$ (o exemplo não-simétrico dos Blocos 2-3) fica\nvisivelmente diferente de $90°$. A distinção não é sutil nem\ncoincidência de arredondamento: é exatamente a diferença entre \"matriz\nsimétrica\" e \"matriz qualquer\" que a prova deste bloco isolou.\n(Chamamos `np.linalg.eigh`, não `np.linalg.eig`, porque `eigh` é a\nrotina especializada em matrizes simétricas — mais precisa e mais\nrápida, e devolve autovalores em ordem crescente por convenção; para uma\nmatriz não-simétrica como $A_{\\text{exemplo}}$, `eigh` não seria\naplicável.)\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Números Confirmam\n\n::: {.fragment}\nAutovalores $3{,}5$ e $1{,}5$: conferem com o MathML. Ângulo entre\nautovetores de $A_{\\text{sim}}$: $90°$ — ortogonais, como a prova\ngarantiu.\n:::\n\n::: {.fragment}\nÂngulo entre autovetores de $A_{\\text{exemplo}}$ (não-simétrica, Blocos\n2-3): visivelmente diferente de $90°$. Não é coincidência de\narredondamento — é a diferença exata entre \"simétrica\" e \"qualquer\".\n:::\n\n::: {.fragment}\n`np.linalg.eigh` (não `eig`): rotina especializada em matrizes\nsimétricas — mais precisa/rápida, ordena autovalores crescente; não\naplicável a $A_{\\text{exemplo}}$ (não-simétrica).\n:::\n:::\n\n::: {.fig-resize style=\"width: 60%; margin: 0 auto;\"}\n\n::: {#390b0811 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-6-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nO painel esquerdo repete as duas direções do Bloco 2/3 — visivelmente\nnão perpendiculares. O painel direito mostra as duas direções de\n$A_{\\text{sim}}$, em ângulo reto exato — a mesma comparação numérica\nacima, agora visível.\n\n## Decomposição Espectral: o Caso Geral e o Caso Simétrico\n\nVale encaixar o Teorema Espectral Real dentro de um resultado mais\ngeral. O MathML define a **decomposição em autovalores** para qualquer\nmatriz quadrada cujos autovetores formem uma base:\n\n::: {.callout-note icon=false}\n## Teorema 4.20 (MathML, tradução nossa, §4.4, p. 116)\n\nUma matriz quadrada $A\\in\\mathbb{R}^{n\\times n}$ pode ser fatorada como\n$A=PDP^{-1}$, onde $P\\in\\mathbb{R}^{n\\times n}$ e $D$ é uma matriz\ndiagonal cujas entradas são os autovalores de $A$, se, e somente se, os\nautovetores de $A$ formam uma base de $\\mathbb{R}^n$.\n:::\n\nEssa é a forma geral — $P$ é só invertível, não necessariamente\nortogonal, e nem toda matriz quadrada admite essa fatoração (uma matriz\ncujos autovetores não geram todo o espaço, caso que foge do escopo\ndesta aula, não é diagonalizável dessa forma).\n\nO Teorema Espectral Real mostra que matrizes simétricas são sempre um\ncaso particular, sempre bem-comportado, desse resultado geral:\n\n::: {.callout-note icon=false}\n## Teorema 4.21 (MathML, tradução nossa, §4.4, p. 116)\n\nUma matriz simétrica $S\\in\\mathbb{R}^{n\\times n}$ pode sempre ser\ndiagonalizada: existe uma base ortonormal (BON) de autovetores de\n$\\mathbb{R}^n$, o que faz de $P$ (a matriz cujas colunas são essa base)\numa matriz ortogonal, de modo que $D=P^TAP$.\n:::\n\nTrocando a notação $P\\to Q$ (a convenção do Boyd, que usamos daqui em\ndiante) e isolando $A$:\n$D=Q^TAQ \\iff A=QDQ^T$ (usando $Q^{-1}=Q^T$, a própria definição de\nmatriz ortogonal) — a mesma equação $A=Q\\Lambda Q^T$ do Boyd. Ou seja: a\ndecomposição espectral não é um resultado à parte da decomposição em\nautovalores geral, é o caso especial em que a simetria garante\ndiagonalização **sempre**, com uma matriz de mudança de base\n**ortogonal**, nunca só invertível.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Decomposição Espectral: Caso Geral e Caso Simétrico\n\n::: {.callout-note icon=false}\n**Teorema 4.20 (MathML, tradução nossa):** $A\\in\\mathbb{R}^{n\\times n}$\n$=PDP^{-1}$ ($D$ diagonal de autovalores) $\\iff$ autovetores de $A$\nformam base de $\\mathbb{R}^n$ — $P$ só invertível, **não**\nnecessariamente ortogonal.\n:::\n\n::: {.callout-note icon=false}\n**Teorema 4.21 (MathML, tradução nossa):** $S$ simétrica $\\Rightarrow$\nsempre diagonalizável, com BON de autovetores de $\\mathbb{R}^n$; logo\n$P$ (colunas = essa base) é **ortogonal**, $D=P^TAP$.\n:::\n\n::: {.fragment}\nTrocando $P\\to Q$ (convenção Boyd) e isolando: $A=QDQ^T$ — mesma\nequação do Boyd, $\\Lambda=D$. Decomposição espectral = caso especial\n**sempre** diagonalizável, com mudança de base **ortogonal**.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Duas matrizes simétricas comutam ($AB=BA$)? Se sim, o que isso implica sobre seus autovetores?\n\nDica: pense no caso mais simples — duas matrizes simétricas que já são\ndiagonais na mesma base. Elas comutam?\n\n- □ Duas matrizes simétricas quaisquer $A,B\\in\\mathbb{R}^{n\\times n}$\n  sempre comutam, ou seja, $AB=BA$ vale para qualquer par de matrizes\n  simétricas, independentemente de seus autovalores/autovetores.\n- □ Se uma matriz simétrica $A$ tivesse **todos** os autovalores iguais\n  entre si (ex.: $A=3I$), então **qualquer** vetor não-nulo de\n  $\\mathbb{R}^n$ seria autovetor de $A$, não só duas direções especiais.\n- □ Numa rede de sensores cuja matriz de covariância é, por construção,\n  sempre simétrica e semidefinida positiva, o Teorema Espectral Real\n  garante autovalores reais e autovetores ortogonais entre si, mesmo\n  sem nenhuma relação com o problema de regressão desta disciplina.\n- □ Como a prova deste bloco só cobre autovalores **distintos**, isso\n  significa que autovetores associados ao **mesmo** autovalor (repetido)\n  de uma matriz simétrica nunca podem ser escolhidos ortogonais entre\n  si.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Duas matrizes simétricas sempre comutam ($AB=BA$)?\n\nDica: pense no caso mais simples — duas matrizes já diagonais na mesma\nbase. Elas comutam?\n\n- □ Duas matrizes simétricas quaisquer sempre comutam ($AB=BA$),\n  independentemente de autovalores/autovetores.\n- □ Se $A$ simétrica tivesse **todos** os autovalores iguais (ex.:\n  $A=3I$), **qualquer** vetor não-nulo seria autovetor de $A$.\n- □ Matriz de covariância (sempre simétrica, PSD): Teorema Espectral\n  garante autovalores reais, autovetores ortogonais — mesmo fora de\n  regressão.\n- □ Prova só cobre autovalores distintos $\\Rightarrow$ autovetores do\n  **mesmo** autovalor repetido nunca podem ser escolhidos ortogonais.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Comutatividade, autovalores repetidos e generalidade do teorema — Resposta\n\n- ✗ Falso em geral: duas matrizes simétricas comutam **apenas** quando\n  compartilham a mesma base de autovetores (são simultaneamente\n  diagonalizáveis) — não é uma propriedade automática de \"ser simétrica\".\n- ✔ $A=3I$: $A\\mathbf{v}=3\\mathbf{v}$ para todo $\\mathbf{v}$ — o\n  autoespaço único ocupa o espaço inteiro, consistente com autovalor\n  repetido $n$ vezes.\n- ✔ Aplicação direta e correta do Teorema Espectral Real a qualquer\n  matriz simétrica PSD, de qualquer origem.\n- ✗ É o oposto: autovetores do mesmo autoespaço **podem sempre** ser\n  escolhidos ortogonais entre si via Gram-Schmidt (MathML Exemplo 4.8) —\n  a prova deste bloco só não é necessária nesse caso porque a\n  ortogonalidade não vem \"de graça\", precisa ser imposta.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** não, em geral — comutar exige compartilhar a\nbase de autovetores, uma condição extra além de \"ambas simétricas\".\n:::\n:::\n\n# Definitude Positiva: o Sinal dos Autovalores\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Retomando a Forma Quadrática da Aula 1\n\nA Aula 1 já usou a forma quadrática $\\mathbf{x}^TA\\mathbf{x}$ (dentro do\nproduto interno geral) sem nomear a propriedade central deste bloco: o\n**sinal** dessa expressão, para todo $\\mathbf{x}\\ne\\mathbf{0}$, classifica\na matriz simétrica $A$. O MathML define (tradução nossa, §3.2.3,\nDefinição 3.4, p. 74):\n\n> \"Uma matriz simétrica $A\\in\\mathbb{R}^{n\\times n}$ que satisfaz [...]\n> $\\mathbf{x}^TA\\mathbf{x}>0$ para todo $\\mathbf{x}\\in V\\setminus\n> \\{\\mathbf{0}\\}$ é chamada simétrica, definida positiva, ou apenas\n> **positiva definida**. Se vale apenas $\\ge$ [...], então $A$ é chamada\n> simétrica, **semidefinida positiva**.\"\n\nE resolve, no próprio texto, dois exemplos que vamos reaproveitar\n(tradução nossa, mesma seção, Exemplo 3.4): \"considere as matrizes\n$A_1=\\begin{bmatrix}9&6\\\\6&5\\end{bmatrix}$,\n$A_2=\\begin{bmatrix}9&6\\\\6&3\\end{bmatrix}$. $A_1$ é definida positiva\nporque é simétrica e\n$\\mathbf{x}^TA_1\\mathbf{x}=9x_1^2+12x_1x_2+5x_2^2=(3x_1+2x_2)^2+x_2^2>0$\npara todo $\\mathbf{x}\\in V\\setminus\\{\\mathbf{0}\\}$. Em contraste, $A_2$\né simétrica mas não é definida positiva porque\n$\\mathbf{x}^TA_2\\mathbf{x}=9x_1^2+12x_1x_2+3x_2^2=(3x_1+2x_2)^2-x_2^2$\npode ser menor que $0$, por exemplo, para $\\mathbf{x}=[2,-3]^T$.\"\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Retomando a Forma Quadrática da Aula 1\n\n::: {.fragment}\n**Definição 3.4 (MathML, tradução nossa):** $A$ simétrica é **definida\npositiva** se $\\mathbf{x}^TA\\mathbf{x}>0$ para todo\n$\\mathbf{x}\\ne\\mathbf{0}$; **semidefinida positiva** se vale só $\\ge 0$.\n:::\n\n::: {.fragment}\n**Exemplo 3.4 (MathML, tradução nossa):**\n$A_1=\\begin{bmatrix}9&6\\\\6&5\\end{bmatrix}$: $\\mathbf{x}^TA_1\\mathbf{x} =\n(3x_1+2x_2)^2+x_2^2>0$ sempre — definida positiva.\n:::\n\n::: {.fragment}\n$A_2=\\begin{bmatrix}9&6\\\\6&3\\end{bmatrix}$: $\\mathbf{x}^TA_2\\mathbf{x} =\n(3x_1+2x_2)^2-x_2^2$, negativo p.ex. em $\\mathbf{x}=(2,-3)$ — **não**\ndefinida positiva.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## A Ponte: Definitude Via o Sinal dos Autovalores\n\nTestar o sinal de $\\mathbf{x}^TA\\mathbf{x}$ para **todo** $\\mathbf{x}$\nnão parece, à primeira vista, uma tarefa finita — são infinitos vetores\npara checar. O Teorema Espectral Real do Bloco 4 dá exatamente a saída:\ncomo $A$ simétrica se escreve $A=Q\\Lambda Q^T$, qualquer $\\mathbf{x}$ se\ndecompõe na base ortonormal de $Q$, e a forma quadrática vira uma soma\nponderada pelos autovalores — o sinal de $\\mathbf{x}^TA\\mathbf{x}$ para\n**todo** $\\mathbf{x}$ passa a depender só do sinal dos $n$ autovalores,\nnão de infinitos vetores. O Boyd enuncia essa equivalência diretamente\n(tradução nossa, Apêndice A.5.2, p. 646-647): \"vemos que $A\\succ 0$ se,\ne somente se, todos os seus autovalores são positivos, ou seja,\n$\\lambda_{\\min}(A)>0$.\" (A notação $A\\succ 0$ é a forma compacta de \"$A$\né definida positiva\"; $A\\succeq 0$, semidefinida positiva.) Verificando\nnos mesmos $A_1$, $A_2$ do MathML:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## A Ponte: Definitude Via o Sinal dos Autovalores\n\n::: {.fragment}\nTestar $\\mathbf{x}^TA\\mathbf{x}>0$ para **todo** $\\mathbf{x}$ parece\ninfinito. Teorema Espectral ($A=Q\\Lambda Q^T$): decompor $\\mathbf{x}$ na\nbase de $Q$ vira a forma quadrática numa soma ponderada pelos\nautovalores.\n:::\n\n::: {.fragment}\n**Boyd, Apêndice A.5.2 (tradução nossa):** $A\\succ 0 \\iff$ todos os\nautovalores positivos, $\\lambda_{\\min}(A)>0$.\n:::\n\n::: {.fragment}\nVerificando em $A_1$/$A_2$ do MathML:\n:::\n:::\n\n::: {#8f180d67 .cell execution_count=6}\n``` {.python .cell-code}\nA1 = np.array([[9.0, 6.0], [6.0, 5.0]])\nA2 = np.array([[9.0, 6.0], [6.0, 3.0]])\n\nautoval_A1 = np.linalg.eigh(A1)[0]\nautoval_A2 = np.linalg.eigh(A2)[0]\nprint(\"Autovalores de A1:\", autoval_A1, \"-> definida positiva?\", np.all(autoval_A1 > 0))\nprint(\"Autovalores de A2:\", autoval_A2, \"-> definida positiva?\", np.all(autoval_A2 > 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAutovalores de A1: [ 0.67544468 13.32455532] -> definida positiva? True\nAutovalores de A2: [-0.70820393 12.70820393] -> definida positiva? False\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n$A_1$ tem os dois autovalores positivos — definida positiva, confirmando\no exemplo resolvido do MathML sem precisar testar infinitos\n$\\mathbf{x}$. $A_2$ tem um autovalor negativo — a mesma informação que o\ncontraexemplo $\\mathbf{x}=(2,-3)$ já tinha revelado, mas agora visível\nde antemão, olhando só para a matriz.\n\n## Intuição Geométrica: o Formato da Tigela\n\nVale conectar essa ideia a uma imagem: a forma quadrática\n$f(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}$, vista como uma função de\n$\\mathbf{x}\\in\\mathbb{R}^2$, desenha uma superfície. Quando $A$ é\ndefinida positiva, essa superfície tem o formato de uma tigela — um\núnico mínimo na origem, subindo em toda direção. Quando $A$ é indefinida\n(nem positiva nem negativa definida, o caso de $A_2$), a superfície tem\nformato de sela: sobe em algumas direções, desce em outras — exatamente\nconsistente com $\\mathbf{x}^TA_2\\mathbf{x}$ trocar de sinal.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Autovalores Confirmam\n\n::: {.fragment}\n$A_1$: os dois autovalores positivos — definida positiva, sem testar\ninfinitos $\\mathbf{x}$.\n:::\n\n::: {.fragment}\n$A_2$: um autovalor negativo — mesma informação do contraexemplo\n$\\mathbf{x}=(2,-3)$, visível de antemão.\n:::\n\n## Intuição Geométrica: o Formato da Tigela\n\n::: {.fragment}\n$f(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}$ como superfície: $A$ definida\npositiva $\\Rightarrow$ formato de **tigela** (mínimo único na origem,\nsobe em toda direção).\n:::\n\n::: {.fragment}\n$A$ indefinida (caso $A_2$): formato de **sela** — sobe em algumas\ndireções, desce em outras, consistente com o sinal trocando.\n:::\n:::\n\n::: {.fig-resize style=\"width: 85%; margin: 0 auto;\"}\n\n::: {#08cd8246 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-8-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nNo painel esquerdo ($A_1$), as curvas de nível são elipses concêntricas\ncrescendo em todas as direções a partir da origem — nenhuma curva de\nnível zero aparece porque o valor mínimo, zero, só é atingido em\n$\\mathbf{x}=\\mathbf{0}$. No painel direito ($A_2$), a linha vermelha\nmarca onde $\\mathbf{x}^TA_2\\mathbf{x}=0$ — e o mapa de cores muda de azul\n(positivo) para vermelho (negativo) atravessando essa linha, o retrato\nvisual direto de \"indefinida\".\n\n## O Quociente de Rayleigh: Isolando $\\lambda_{\\max}$ e $\\lambda_{\\min}$\n\nFalta uma última peça para fechar exatamente o número de condição: uma\nforma de isolar o **maior** e o **menor** autovalor de $A$ diretamente da\nforma quadrática, sem calcular todos os autovalores primeiro. O Boyd\ndefine essa peça — o **quociente de Rayleigh** — e prova a desigualdade\nque o conecta à forma quadrática (tradução nossa, Apêndice A.5.2, p.\n646-647):\n\n> \"O maior e o menor autovalor satisfazem\n> $\\lambda_{\\max}(A)=\\sup_{\\mathbf{x}\\ne 0}\n> \\frac{\\mathbf{x}^TA\\mathbf{x}}{\\mathbf{x}^T\\mathbf{x}}$,\n> $\\lambda_{\\min}(A)=\\inf_{\\mathbf{x}\\ne 0}\n> \\frac{\\mathbf{x}^TA\\mathbf{x}}{\\mathbf{x}^T\\mathbf{x}}$. Em particular,\n> para qualquer $\\mathbf{x}$, temos\n> $\\lambda_{\\min}(A)\\,\\mathbf{x}^T\\mathbf{x}\\le\\mathbf{x}^TA\\mathbf{x}\n> \\le\\lambda_{\\max}(A)\\,\\mathbf{x}^T\\mathbf{x}$.\"\n\nA prova é uma aplicação direta do Teorema Espectral: decompondo\n$\\mathbf{x}=\\sum_i c_i\\mathbf{q}_i$ na base ortonormal de autovetores\n($\\mathbf{q}_i$, colunas de $Q$), a forma quadrática vira\n$\\mathbf{x}^TA\\mathbf{x}=\\sum_i\\lambda_ic_i^2$ e a norma\n$\\mathbf{x}^T\\mathbf{x}=\\sum_ic_i^2$ — o quociente\n$\\frac{\\sum_i\\lambda_ic_i^2}{\\sum_ic_i^2}$ é, literalmente, uma **média\nponderada** dos autovalores (pesos $c_i^2\\ge 0$), e toda média ponderada\nfica entre o menor e o maior valor pesado. É exatamente essa média\nponderada que dá nome ao quociente.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Quociente de Rayleigh\n\n::: {.fragment}\nFalta isolar $\\lambda_{\\max}$/$\\lambda_{\\min}$ direto da forma\nquadrática, sem calcular todos os autovalores.\n:::\n\n::: {.fragment}\n**Boyd, Apêndice A.5.2 (tradução nossa):**\n$$\\lambda_{\\min}(A)\\,\\mathbf{x}^T\\mathbf{x} \\leq \\mathbf{x}^TA\\mathbf{x}\n\\leq \\lambda_{\\max}(A)\\,\\mathbf{x}^T\\mathbf{x}$$\nvia $\\lambda_{\\max}=\\sup_{\\mathbf{x}\\ne 0}\n\\frac{\\mathbf{x}^TA\\mathbf{x}}{\\mathbf{x}^T\\mathbf{x}}$,\n$\\lambda_{\\min}=\\inf_{\\mathbf{x}\\ne 0}\n\\frac{\\mathbf{x}^TA\\mathbf{x}}{\\mathbf{x}^T\\mathbf{x}}$.\n:::\n\n::: {.fragment}\nProva: $\\mathbf{x}=\\sum_ic_i\\mathbf{q}_i$ (base de autovetores)\n$\\Rightarrow$ $\\mathbf{x}^TA\\mathbf{x}=\\sum_i\\lambda_ic_i^2$,\n$\\mathbf{x}^T\\mathbf{x}=\\sum_ic_i^2$. Quociente = **média ponderada**\ndos autovalores (pesos $c_i^2\\ge 0$) — sempre entre o menor e o maior.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## O Número de Condição, Agora Exato\n\nEssa é a peça que fecha, com precisão, o ciclo aberto na Aula 3. O Boyd\ndefine (tradução nossa, Apêndice A.5.2, p. 649): \"o número de condição\nde uma matriz não-singular $A\\in\\mathbb{R}^{n\\times n}$, denotado\n$\\text{cond}(A)$ ou $\\kappa(A)$, é definido como\n$\\text{cond}(A)=\\|A\\|_2\\|A^{-1}\\|_2=\\sigma_{\\max}(A)/\\sigma_{\\min}(A)$\" —\numa definição em termos de valores singulares $\\sigma$, que se aplica a\nqualquer matriz (mesmo retangular). Para uma matriz **simétrica**\ndefinida positiva (o caso de $X^TX$ sob posto completo), os valores\nsingulares coincidem exatamente com os autovalores (todos positivos), e\na definição colapsa para\n$$\n\\text{cond}(A) = \\frac{\\lambda_{\\max}(A)}{\\lambda_{\\min}(A)}.\n$$\nEssa é a fórmula que faltava desde a Aula 3: o número de condição de\n$X^TX$ não precisa ser estimado perturbando os dados — é, literalmente,\na razão entre o maior e o menor autovalor de $X^TX$, calculável de uma\nsó vez via `numpy.linalg.eigh`. O Bloco 6 aplica exatamente essa fórmula\naos mesmos números que a Aula 3 só tinha medido empiricamente.\n\n## Ponte Breve (Sem Aprofundar): Hessiana e Convexidade\n\nVale uma menção, sem desenvolver agora: a mesma forma quadrática\n$\\mathbf{x}^TA\\mathbf{x}$ que classifica $A$ aqui é, literalmente, a\nsegunda derivada (Hessiana) de uma função quadrática — e definitude\npositiva da Hessiana é exatamente a condição que caracteriza convexidade\n(um único mínimo, sem sela nem máximo espúrio), tema formal da Aula 7\ndesta disciplina. A Aula 3 já usou isso de relance, sem nomear: a\nHessiana $2X^TX$ da função de mínimos quadrados era sempre semidefinida\npositiva, o que garantia convexidade e, portanto, que a condição de\ngradiente-zero das Equações Normais era suficiente para um mínimo\nglobal — o mesmo raciocínio deste bloco, aplicado antes de ter o nome.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Número de Condição, Agora Exato\n\n::: {.fragment}\n**Boyd, Apêndice A.5.2 (tradução nossa):**\n$\\text{cond}(A)=\\|A\\|_2\\|A^{-1}\\|_2=\\sigma_{\\max}(A)/\\sigma_{\\min}(A)$\n(valores singulares, qualquer matriz).\n:::\n\n::: {.fragment}\nPara $A$ simétrica definida positiva ($X^TX$ sob posto completo):\nvalores singulares = autovalores $\\Rightarrow$\n$$\\text{cond}(A) = \\frac{\\lambda_{\\max}(A)}{\\lambda_{\\min}(A)}$$\n:::\n\n::: {.fragment}\nA peça que faltava desde a Aula 3: número de condição = razão entre\nautovalores de $X^TX$, sem perturbar nada. Bloco 6 aplica isso aos\nmesmos números da Aula 3.\n:::\n\n## Ponte Breve: Hessiana e Convexidade\n\n::: {.fragment}\n$\\mathbf{x}^TA\\mathbf{x}$ = segunda derivada (Hessiana) de função\nquadrática; definitude positiva da Hessiana $\\equiv$ convexidade (Aula\n7).\n:::\n\n::: {.fragment}\nAula 3 já usou isso sem nomear: Hessiana $2X^TX$ sempre PSD\n$\\Rightarrow$ convexidade $\\Rightarrow$ gradiente-zero era suficiente\npara mínimo global.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se $\\lambda_{\\min}(A)$ estivesse muito próximo de zero (mas ainda positivo), o que aconteceria com o número de condição, mesmo $A$ continuando definida positiva?\n\nDica: releia a fórmula $\\text{cond}(A)=\\lambda_{\\max}(A)/\\lambda_{\\min}(A)$\n— o que acontece com uma fração quando o denominador tende a zero?\n\n- □ Se $\\lambda_{\\min}(A)$ estivesse muito próximo de zero, mas ainda\n  estritamente positivo, o número de condição de $A$ ficaria muito\n  grande, mesmo com $A$ continuando definida positiva (todos os\n  autovalores positivos).\n- □ Se todos os autovalores de uma matriz simétrica $A$ fossem iguais\n  entre si ($A=cI$, $c>0$), o número de condição de $A$ seria\n  necessariamente igual a $1$, o menor valor possível.\n- □ Num sistema de controle descrito por uma matriz de ganho simétrica\n  positiva definida, um número de condição muito alto sinalizaria o\n  mesmo tipo de sensibilidade numérica discutida aqui, mesmo fora do\n  contexto de regressão.\n- □ Como o quociente de Rayleigh é uma média ponderada dos autovalores,\n  isso implica que o quociente $\\mathbf{x}^TA\\mathbf{x}/\\mathbf{x}^T\n  \\mathbf{x}$ é sempre igual à média aritmética simples dos autovalores,\n  qualquer que seja $\\mathbf{x}$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## $\\lambda_{\\min}(A)$ perto de zero (mas positivo): o que acontece com o número de condição?\n\nDica: $\\text{cond}(A)=\\lambda_{\\max}/\\lambda_{\\min}$ — o que acontece com\numa fração quando o denominador tende a zero?\n\n- □ $\\lambda_{\\min}(A)$ próximo de zero (positivo): número de condição\n  fica muito **grande**, mesmo $A$ continuando definida positiva.\n- □ Se todos os autovalores de $A$ simétrica fossem iguais ($A=cI$,\n  $c>0$): número de condição necessariamente $=1$ (o menor possível).\n- □ Sistema de controle com ganho simétrico PD: número de condição alto\n  sinaliza a mesma sensibilidade numérica, fora do contexto de regressão.\n- □ Quociente de Rayleigh sendo média ponderada implica que\n  $\\mathbf{x}^TA\\mathbf{x}/\\mathbf{x}^T\\mathbf{x}$ é sempre igual à\n  média **aritmética simples** dos autovalores, para qualquer\n  $\\mathbf{x}$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Autovalor próximo de zero, matriz escalar e a média do quociente — Resposta\n\n- ✔ Denominador $\\to 0^+$ com numerador fixo positivo $\\Rightarrow$\n  razão $\\to\\infty$ — exatamente o mecanismo de mal-condicionamento, sem\n  violar definitude positiva (ainda $\\lambda_{\\min}>0$, só pequeno).\n- ✔ $A=cI$: único autovalor $c$ (repetido $n$ vezes) $\\Rightarrow$\n  $\\lambda_{\\max}=\\lambda_{\\min}=c$ $\\Rightarrow$ $\\text{cond}(A)=1$ —\n  o melhor condicionamento possível.\n- ✔ Aplicação correta e direta do conceito fora do domínio de regressão.\n- ✗ É uma média **ponderada** pelos pesos $c_i^2$ (as componentes de\n  $\\mathbf{x}$ na base de autovetores) — só coincide com a média\n  aritmética simples se todos os pesos forem iguais, o que não vale para\n  $\\mathbf{x}$ arbitrário.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** número de condição muito grande, sinal exato de\nfragilidade numérica mesmo com $A$ tecnicamente definida positiva e\ninvertível — é precisamente o que a Aula 3 observou empiricamente no par\nquase-colinear, e que o Bloco 6 confirma agora via autovalores.\n:::\n:::\n\n# Aplicação e Verificação no Dado Real\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Recalculando o Número de Condição da Aula 3 — Agora Exato\n\nChegou a hora de fechar o ciclo prometido no início desta aula.\nReaproveitando exatamente $X^TX$ da Aula 3 — os mesmos 4 atributos\ncompletos e os mesmos dois pares na amostra de 20 bairros — vamos\ncalcular os autovalores exatos via `numpy.linalg.eigh` (a rotina\nespecializada em matrizes simétricas, já usada no Bloco 4) e confirmar\nque a razão $\\lambda_{\\max}/\\lambda_{\\min}$ reproduz, número por número,\nos números que a Aula 3 só tinha obtido via `np.linalg.cond` e\nperturbação:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Recalculando o Número de Condição da Aula 3 — Agora Exato\n\n::: {.fragment}\nReaproveitando $X^TX$ da Aula 3 (4 atributos completos + os mesmos dois\npares na amostra de 20 bairros): autovalores exatos via\n`numpy.linalg.eigh`, confirmando se $\\lambda_{\\max}/\\lambda_{\\min}$\nreproduz os números da Aula 3:\n:::\n:::\n\n::: {#d6c06dd9 .cell execution_count=8}\n``` {.python .cell-code}\nX_completo = _housing[COLS].to_numpy()\nXtX = X_completo.T @ X_completo\n\nautoval_XtX, autovec_XtX = np.linalg.eigh(XtX)\ncond_completo_exato = autoval_XtX.max() / autoval_XtX.min()\n\nprint(\"Autovalores de X^T X (4 atributos, ordem crescente):\")\nprint(autoval_XtX)\nprint(f\"\\ncond(X^T X) via autovalores exatos: {cond_completo_exato:,.1f}\")\nprint(f\"cond(X^T X) via np.linalg.cond (Aula 3): {np.linalg.cond(XtX):,.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAutovalores de X^T X (4 atributos, ordem crescente):\n[7.47253320e+02 5.26660328e+04 2.73990283e+05 1.75309388e+07]\n\ncond(X^T X) via autovalores exatos: 23,460.5\ncond(X^T X) via np.linalg.cond (Aula 3): 23,460.5\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nOs dois números coincidem até a primeira casa decimal —\n$\\text{cond}(X^TX)\\approx 23\\,460{,}5$, exatamente o valor que a Aula 3\ntinha medido de forma indireta (`np.linalg.cond`, que por baixo dos\npanos já usa os valores singulares — para uma matriz simétrica PSD como\n$X^TX$, os mesmos autovalores calculados aqui). A diferença é que agora\nsabemos **de onde** esse número vem: da razão entre o maior autovalor\n($\\approx 1{,}75\\times 10^7$) e o menor ($\\approx 747$) de $X^TX$ — uma\npropriedade da própria matriz, não do resultado de nenhuma perturbação.\nRepetindo para os dois pares de 20 bairros:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Autovalores Confirmam\n\n::: {.fragment}\n$\\text{cond}(X^TX)\\approx 23\\,460{,}5$ via autovalores — coincide com o\nvalor da Aula 3 (`np.linalg.cond`), até a primeira casa decimal.\n:::\n\n::: {.fragment}\nAgora sabemos **de onde** vem: razão entre maior autovalor\n($\\approx1{,}75\\times10^7$) e menor ($\\approx747$) — propriedade da\nprópria matriz, sem perturbação nenhuma.\n:::\n\n## Repetindo Para os Dois Pares de 20 Bairros\n\n::: {.fragment}\nMesma amostra, mesmos dois pares da Aula 3:\n:::\n:::\n\n::: {#3370cd53 .cell execution_count=9}\n``` {.python .cell-code}\n_amostra_20 = _housing.sample(n=20, random_state=7)\nX_quase_dep = _amostra_20[[\"AveRooms\", \"AveBedrms\"]].to_numpy()\nX_bem_cond = _amostra_20[[\"MedInc\", \"HouseAge\"]].to_numpy()\n\nautoval_qd = np.linalg.eigh(X_quase_dep.T @ X_quase_dep)[0]\nautoval_bc = np.linalg.eigh(X_bem_cond.T @ X_bem_cond)[0]\n\ncond_qd_exato = autoval_qd.max() / autoval_qd.min()\ncond_bc_exato = autoval_bc.max() / autoval_bc.min()\n\nprint(\"Autovalores de X^T X (AveRooms, AveBedrms):\", autoval_qd)\nprint(f\"cond exato (quase-colinear):    {cond_qd_exato:,.1f}\")\nprint()\nprint(\"Autovalores de X^T X (MedInc, HouseAge):    \", autoval_bc)\nprint(f\"cond exato (bem-condicionado):  {cond_bc_exato:,.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAutovalores de X^T X (AveRooms, AveBedrms): [  1.76730921 741.96132008]\ncond exato (quase-colinear):    419.8\n\nAutovalores de X^T X (MedInc, HouseAge):     [  139.61748016 23613.01422068]\ncond exato (bem-condicionado):  169.1\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nOs três números reproduzem exatamente os valores da Aula 3:\n$\\text{cond}(X^TX)\\approx 419{,}8$ para o par quase-colinear e\n$\\approx 169{,}1$ para o par bem-condicionado — mais que o dobro de\ndiferença, agora explicado, não só medido. A resposta à pergunta do\nBloco 1 (\"existe alguma propriedade de $X^TX$ calculável sem perturbar\nnada que já anteciparia a fragilidade?\") é, enfim, sim: o menor\nautovalor de $X^TX$ para o par quase-colinear ($\\approx 1{,}77$) é\nminúsculo perto do maior ($\\approx 742$) — um sintoma direto de que uma\ndas direções do espaço gerado pelas duas colunas quase não é \"vista\"\npela matriz, exatamente a direção em que `AveRooms` e `AveBedrms`\npraticamente coincidem. Já no par bem-condicionado, os dois autovalores\n($\\approx 139{,}6$ e $\\approx 23\\,613{,}0$) ainda diferem bastante em\nescala bruta — lembrando que `MedInc` e `HouseAge` têm variâncias\nnaturais bem diferentes —, mas a razão entre eles é quase $2{,}5\\times$\nmenor que no par quase-colinear, o suficiente para tornar o sistema\nconsideravelmente mais estável.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Os Números Reproduzem Exatamente a Aula 3\n\n::: {.fragment}\n$\\text{cond}(X^TX)\\approx 419{,}8$ (quase-colinear) e $\\approx 169{,}1$\n(bem-condicionado) — idênticos aos da Aula 3, agora **explicados**, não\nsó medidos.\n:::\n\n::: {.fragment}\nResposta ao Bloco 1: sim, existe. Menor autovalor do par quase-colinear\n($\\approx1{,}77$) é minúsculo perto do maior ($\\approx742$) — sintoma de\numa direção quase \"invisível\" para a matriz (onde `AveRooms` $\\approx$\n`AveBedrms`).\n:::\n\n::: {.fragment}\nPar bem-condicionado: autovalores ($\\approx139{,}6$, $\\approx23\\,613{,}0$)\nainda diferem em escala bruta (variâncias naturais diferentes de\n`MedInc`/`HouseAge`), mas a **razão** é bem menor — mais estável.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Uma Segunda Matriz Simétrica PSD: a Covariância Empírica\n\n$X^TX$ não é a única matriz simétrica semidefinida positiva que aparece\nnaturalmente em dados. Outra, de natureza um pouco diferente — **não**\nmais colunas brutas, mas colunas **centradas** na própria média — é a\n**matriz de covariância empírica**. Para as duas colunas `AveRooms` e\n`AveBedrms` (o mesmo par quase-colinear de cima), a covariância mede\ncomo elas variam juntas em torno das respectivas médias:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Uma Segunda Matriz Simétrica PSD: Covariância Empírica\n\n::: {.fragment}\n$X^TX$ não é a única matriz PSD natural em dados. A **matriz de\ncovariância empírica** — colunas **centradas**, não brutas — é outra:\n:::\n:::\n\n::: {#2e90586b .cell execution_count=10}\n``` {.python .cell-code}\nX_cov_dados = _housing[[\"AveRooms\", \"AveBedrms\"]].to_numpy()\ncov_empirica = np.cov(X_cov_dados, rowvar=False)\n\nprint(\"Matriz de covariância (AveRooms, AveBedrms):\")\nprint(cov_empirica)\nprint(\"\\nÉ simétrica?\", np.allclose(cov_empirica, cov_empirica.T))\n\nautoval_cov, autovec_cov = np.linalg.eigh(cov_empirica)\nprint(\"\\nAutovalores:\", autoval_cov)\nprint(\"Autovetores (colunas):\")\nprint(autovec_cov)\nprint(\"\\nOrtogonalidade (produto interno entre os dois autovetores):\",\n      autovec_cov[:, 0] @ autovec_cov[:, 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMatriz de covariância (AveRooms, AveBedrms):\n[[7.01551552 1.17219151]\n [1.17219151 0.26163945]]\n\nÉ simétrica? True\n\nAutovalores: [0.06398052 7.21317445]\nAutovetores (colunas):\n[[ 0.16627604 -0.98607925]\n [-0.98607925 -0.16627604]]\n\nOrtogonalidade (produto interno entre os dois autovetores): 0.0\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nA matriz é simétrica (por construção — covariância entre $i$ e $j$ é\nsempre igual à covariância entre $j$ e $i$) e semidefinida positiva\n(nenhum autovalor negativo, $\\approx 0{,}064$ e $\\approx 7{,}213$), e os\ndois autovetores são ortogonais entre si até erro de arredondamento —\nexatamente o Teorema Espectral Real do Bloco 4 se aplicando de novo,\ndesta vez a uma matriz de covariância, não a $X^TX$ bruta. O autovetor\nprincipal — o de **maior** autovalor, $\\approx (-0{,}986;-0{,}166)$ (ou,\nde forma equivalente, $(0{,}986;0{,}166)$, já que o sinal de um\nautovetor não importa, Bloco 2) — aponta na direção de **maior\nvariância** dos dados: geometricamente, é a direção ao longo da qual a\nnuvem de pontos `AveRooms`/`AveBedrms` está mais \"esticada\".\n\n## Interpretando o Autovetor Principal sobre os Dados Reais\n\nVale ver essa direção sobreposta ao espalhamento real das duas\nvariáveis, não só como um vetor abstrato:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Autovalores/Autovetores Confirmam\n\n::: {.fragment}\nSimétrica (por construção) e semidefinida positiva (autovalores\n$\\approx0{,}064$ e $\\approx7{,}213$, nenhum negativo). Autovetores\nortogonais até arredondamento — Teorema Espectral de novo, agora em\ncovariância.\n:::\n\n::: {.fragment}\nAutovetor principal (maior autovalor) $\\approx(0{,}986;0{,}166)$: aponta\nna direção de **maior variância** dos dados — onde a nuvem está mais\n\"esticada\".\n:::\n\n## Interpretando sobre os Dados Reais\n\n::: {.fragment}\nSobrepondo essa direção ao espalhamento real de\n`AveRooms`/`AveBedrms`:\n:::\n:::\n\n::: {.fig-resize style=\"width: 75%; margin: 0 auto;\"}\n\n::: {#293b9db8 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-12-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nO autovetor principal (vermelho) segue quase exatamente ao longo do\neixo `AveRooms` — coerente com `AveRooms` ter variância bruta bem maior\nque `AveBedrms` ($\\approx 7{,}02$ contra $\\approx 0{,}26$, quase\n$27\\times$) —, mas ligeiramente inclinado na direção de `AveBedrms`\npositiva, refletindo a covariância positiva entre as duas ($\\approx\n1{,}17$: bairros com mais cômodos por domicílio tendem a ter também mais\nquartos por domicílio, o que já era esperado). O autovetor secundário\n(laranja), ortogonal ao principal, captura a variação residual — a\nparte de `AveBedrms` que **não** é só \"proporcional a `AveRooms`\" —, e\nseu autovalor muito menor ($\\approx 0{,}064$ contra $\\approx 7{,}213$)\nmostra que essa direção secundária carrega bem pouca informação\nadicional sobre a nuvem de pontos.\n\n## Semente Para PCA (Sem Aprofundar) — e um Aviso Honesto sobre Escala\n\nO que acabamos de fazer — encontrar a direção de maior variância de um\nconjunto de dados via a autodecomposição da matriz de covariância — é,\nsem exagero nenhum, o primeiro passo da **Análise de Componentes\nPrincipais** (PCA), tema que a disciplina de Aprendizado Não\nSupervisionado desenvolve por completo; esta aula planta a semente, sem\ndesenvolvê-la. Antes de fechar o bloco, um aviso honesto sobre um\ndetalhe fácil de esconder: essa análise é **sensível à escala**. Se, em\nvez de só `AveRooms`/`AveBedrms`, calculássemos a covariância dos **4**\natributos brutos, o resultado seria dominado por `HouseAge` — o\natributo de maior variância numérica bruta, não necessariamente o mais\n\"importante\" para qualquer tarefa:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Autovetores Mostram\n\n::: {.fragment}\nPrincipal (vermelho) quase ao longo de `AveRooms` (variância\n$\\approx7{,}02$ vs. $\\approx0{,}26$ de `AveBedrms`, quase $27\\times$),\nlevemente inclinado — covariância positiva $\\approx1{,}17$.\n:::\n\n::: {.fragment}\nSecundário (laranja), ortogonal: variação residual de `AveBedrms` **não\nexplicada** por `AveRooms`; autovalor bem menor ($\\approx0{,}064$ vs.\n$\\approx7{,}213$) — pouca informação adicional.\n:::\n\n## Semente Para PCA — e um Aviso sobre Escala\n\n::: {.fragment}\nDireção de maior variância via autodecomposição da covariância =\nprimeiro passo de **PCA** (Aprendizado Não Supervisionado) — semente,\nnão desenvolvida aqui.\n:::\n\n::: {.fragment}\n**Aviso honesto:** sensível à escala. Covariância dos 4 atributos brutos\nseria dominada por `HouseAge` (maior variância numérica bruta), não\nnecessariamente o mais \"importante\":\n:::\n:::\n\n::: {#19ede7fb .cell execution_count=12}\n``` {.python .cell-code}\nX_cov4 = _housing[COLS].to_numpy()\ncov4 = np.cov(X_cov4, rowvar=False)\n\nprint(\"Variância de cada atributo (diagonal da covariância):\")\nfor nome, var in zip(COLS, np.diag(cov4)):\n    print(f\"  {nome:10s}: {var:10.4f}\")\n\nautoval_cov4 = np.linalg.eigh(cov4)[0]\nprint(\"\\nAutovalores da covariância (4 atributos):\", autoval_cov4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nVariância de cada atributo (diagonal da covariância):\n  MedInc    :     3.4862\n  HouseAge  :   163.7848\n  AveRooms  :     7.0155\n  AveBedrms :     0.2616\n\nAutovalores da covariância (4 atributos): [3.36605897e-02 2.96906503e+00 7.52330508e+00 1.64022194e+02]\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nA variância de `HouseAge` ($\\approx 163{,}8$) é mais de $20\\times$ maior\nque a de qualquer outro atributo — e o maior autovalor da covariância\ncompleta ($\\approx 164{,}0$) reflete quase só essa escala, não a\nestrutura de correlação entre os quatro atributos que de fato\ninteressaria numa análise de PCA. É exatamente por isso que aplicar PCA\na sério exige **padronizar** os atributos antes (subtrair a média e\ndividir pelo desvio-padrão de cada coluna) — sem isso, a \"direção de\nmaior variância\" tende a só apontar para o atributo de maior escala\nnumérica bruta, não para a estrutura real dos dados. Não vamos\ndesenvolver a padronização nem o PCA aqui — só deixamos o aviso, e a\nponte, explícitos.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Aviso Confirmado nos Números\n\n::: {.fragment}\nVariância de `HouseAge` ($\\approx163{,}8$) é $>20\\times$ maior que\nqualquer outro atributo. Maior autovalor da covariância completa\n($\\approx164{,}0$) reflete quase só essa escala — não a estrutura de\ncorrelação entre os 4 atributos.\n:::\n\n::: {.fragment}\nPCA a sério exige **padronizar** antes (média $0$, desvio-padrão $1$) —\nsem isso, \"maior variância\" só aponta para a maior escala numérica\nbruta. Não desenvolvido aqui — só o aviso e a ponte.\n:::\n:::\n\n# Fechamento e Ponte para a Aula 5\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n### Retomando as perguntas de abertura {.unnumbered}\n\n1. **O que é, geometricamente, um autovalor e um autovetor?** Um\n   autovetor é uma direção que uma transformação linear $A$ não gira —\n   só estica ou encolhe (e inverte, se o autovalor for negativo); o\n   autovalor é exatamente esse fator de escala.\n2. **Como calcular à mão, via o polinômio característico?** A equação\n   $A\\mathbf{x}=\\lambda\\mathbf{x}$ vira o sistema homogêneo\n   $(A-\\lambda I)\\mathbf{x}=\\mathbf{0}$, que só tem solução não-trivial\n   quando $\\det(A-\\lambda I)=0$ — os autovalores são as raízes reais\n   desse polinômio, os autovetores resolvem o sistema com $\\lambda$ já\n   conhecido.\n3. **Por que toda matriz simétrica — como $X^TX$ — tem autovalores\n   reais e autovetores ortogonais?** O Teorema Espectral Real garante\n   isso sempre; provamos a ortogonalidade entre autovalores distintos\n   via $\\mathbf{x}_1^TA\\mathbf{x}_2$ calculado de duas formas, usando a\n   simetria de $A$ exatamente no passo decisivo.\n4. **Como sinal e razão dos autovalores definem definitude e o número\n   de condição exato?** $A\\succ 0 \\iff \\lambda_{\\min}(A)>0$; e, para\n   $A$ simétrica definida positiva, $\\text{cond}(A)=\n   \\lambda_{\\max}(A)/\\lambda_{\\min}(A)$ — a fórmula que o Bloco 6 usou\n   para reproduzir, exatamente, os números que a Aula 3 só tinha medido\n   por perturbação.\n\n### O Que Fica em Aberto {.unnumbered}\n\nAutovalores e autovetores reais, na forma garantida pelo Teorema\nEspectral, só existem de forma incondicional para matrizes **quadradas\nsimétricas** — $X^TX$ sempre se encaixa aí, mas $X$ em si, a matriz de\ndesign retangular ($N\\ne d$ linhas e colunas), não. A pergunta que fica\naberta: o que fazer quando se quer decompor a própria $X$, não $X^TX$?\nA resposta é a **Decomposição em Valores Singulares** (SVD), tema da\nAula 5 — e o Boyd já deixou uma pista, sem desenvolver: a própria\ndefinição de número de condição usada neste bloco ($\\sigma_{\\max}/\n\\sigma_{\\min}$) foi escrita em termos de **valores singulares**, não de\nautovalores — a generalização exata que a Aula 5 vai construir.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Retomando as Perguntas de Abertura\n\n::: {.fragment}\n**1.** Autovetor = direção que $A$ não gira, só estica/encolhe\n(inverte se $\\lambda<0$); autovalor = o fator de escala.\n:::\n\n::: {.fragment}\n**2.** $A\\mathbf{x}=\\lambda\\mathbf{x}\\Rightarrow(A-\\lambda I)\\mathbf{x}=\n\\mathbf{0}$, solução não-trivial $\\iff\\det(A-\\lambda I)=0$ — autovalores\n= raízes reais; autovetores resolvem o sistema com $\\lambda$ conhecido.\n:::\n\n::: {.fragment}\n**3.** Teorema Espectral Real: matriz simétrica $\\Rightarrow$\nautovalores reais, autovetores ortogonais — provado via\n$\\mathbf{x}_1^TA\\mathbf{x}_2$ de duas formas, usando a simetria no passo\ndecisivo.\n:::\n\n::: {.fragment}\n**4.** $A\\succ 0\\iff\\lambda_{\\min}(A)>0$; para simétrica PD,\n$\\text{cond}(A)=\\lambda_{\\max}/\\lambda_{\\min}$ — reproduziu, exato, os\nnúmeros empíricos da Aula 3.\n:::\n\n## Ponte para a Aula 5\n\n::: {.fragment}\nTeorema Espectral só garante autovalores/autovetores reais\nincondicionalmente para matrizes **quadradas simétricas**. $X^TX$\nsempre se encaixa; $X$ em si (retangular, $N\\ne d$), não.\n:::\n\n::: {.fragment}\nO que fazer para decompor $X$ diretamente? **Decomposição em Valores\nSingulares (SVD)**, Aula 5.\n:::\n\n::: {.fragment}\nPista já deixada pelo Boyd: o número de condição foi definido em termos\nde **valores singulares** ($\\sigma_{\\max}/\\sigma_{\\min}$), não\nautovalores — a generalização exata que a Aula 5 constrói.\n:::\n:::\n\n::: {.fig-resize style=\"width: 65%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{shapes.geometric, arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[\n  block/.style={rectangle, draw=icblue, fill=icblue!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.0cm, minimum height=1.1cm},\n  decision/.style={diamond, draw=icorange, fill=icorange!10, align=center,\n                    font=\\small, inner sep=1pt, text width=2.6cm, aspect=2.0},\n  concl/.style={rectangle, draw=icred, fill=icred!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.4cm, minimum height=1.1cm}\n]\n  \\node (A) [block] at (0,0) {matriz quadrada?};\n  \\node (Q) [decision] at (5.0,0) {$A$ simétrica?};\n  \\node (S) [concl] at (10.9,2.3) {Teorema Espectral:\\\\$A=Q\\Lambda Q^T$\\\\autovalores reais,\\\\autovetores ortogonais};\n  \\node (N) [concl] at (10.9,-2.3) {sem garantia geral\\\\(pode ter autovalor\\\\complexo, Bloco 3)};\n  \\node (SVD) [concl] at (0,-3.5) {não é quadrada:\\\\Teorema Espectral\\\\não se aplica\\\\direto $\\to$ SVD\\\\(Aula 5)};\n\n  \\draw [-Stealth, thick, color=gray!70] (A) -- (Q);\n  \\draw [-Stealth, thick, color=gray!70] (Q) -- (S);\n  \\draw [-Stealth, thick, color=gray!70] (Q) -- (N);\n  \\draw [-Stealth, thick, color=gray!70] (A) -- (SVD);\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n# Exercícios\n\n## Questões discursivas\n\n1. Explique, com suas próprias palavras, por que a condição\n   $\\det(A-\\lambda I)=0$ (e não a equação de autovalor\n   $A\\mathbf{x}=\\lambda\\mathbf{x}$ diretamente) é o alvo certo para\n   encontrar os autovalores de uma matriz. Que propriedade de sistemas\n   lineares homogêneos, já estudada na Aula 2, torna essa equivalência\n   possível?\n\n2. A prova de ortogonalidade do Bloco 4 (autovetores de autovalores\n   distintos de uma matriz simétrica são ortogonais) usa a simetria de\n   $A$ em exatamente um passo da manipulação algébrica. Reproduza a\n   prova e aponte esse passo com precisão — o que aconteceria à\n   conclusão se $A$ não fosse simétrica?\n\n3. Compare os dois papéis que $X^TX$ desempenha nesta disciplina: como\n   a matriz das Equações Normais (Aula 3) e como o objeto central desta\n   aula (autovalores/autovetores, definitude, número de condição).\n   Explique por que a simetria de $X^TX$ — garantida para **qualquer**\n   $X$, mesmo retangular — é a peça que conecta os dois papéis.\n\n## Questões de Verdadeiro/Falso\n\n::: {.callout-note icon=false}\n## Autovalores e autovetores: a equação básica\n\n- □ Se $\\mathbf{x}$ é autovetor de $A$ associado ao autovalor\n  $\\lambda=0$, então $\\mathbf{x}$ pertence ao núcleo (espaço-nulo) de\n  $A$, no mesmo sentido definido na Aula 2 para sistemas homogêneos.\n- □ Uma matriz de rotação pura em $\\mathbb{R}^2$ por um ângulo de $90°$\n  não tem nenhum autovetor real, porque nenhuma direção não-nula do\n  plano é mapeada sobre si mesma (nem esticada, nem invertida) por essa\n  rotação.\n- □ Num sistema dinâmico discreto $\\mathbf{x}_{k+1}=A\\mathbf{x}_k$, se\n  $\\mathbf{x}_0$ for exatamente um autovetor de $A$ com autovalor\n  $\\lambda$, então toda a trajetória futura $\\mathbf{x}_1,\\mathbf{x}_2,\n  \\dots$ permanece sobre a mesma reta que $\\mathbf{x}_0$, só variando em\n  magnitude por potências de $\\lambda$.\n- □ Como o autovetor associado a um autovalor não é único, a equação de\n  autovalor $A\\mathbf{x}=\\lambda\\mathbf{x}$ admite, para qualquer $A$ e\n  qualquer $\\lambda$ real, pelo menos um autovetor não-nulo que a\n  satisfaça.\n:::\n\n::: {.callout-note icon=false}\n## O polinômio característico\n\n- □ Se o polinômio característico de uma matriz $A\\in\\mathbb{R}^{2\n  \\times 2}$ tiver uma raiz **dupla** (discriminante zero em Bhaskara),\n  isso garante automaticamente que $A$ tem apenas um autovetor\n  linearmente independente associado a essa raiz.\n- □ Multiplicar uma matriz $A$ inteira por um escalar $c\\ne 0$ (obtendo\n  $cA$) preserva exatamente os mesmos autovetores de $A$, mas multiplica\n  cada autovalor por $c$.\n- □ Num modelo de epidemiologia descrito por uma matriz de transição de\n  estados $3\\times 3$, encontrar os autovalores dessa matriz via seu\n  polinômio característico (grau 3) é uma aplicação legítima da mesma\n  técnica usada nesta aula para matrizes $2\\times 2$.\n- □ Como $\\det(A-\\lambda I)=0$ é a condição para autovalor, isso implica\n  que $\\det(A)=0$ é condição necessária para que $A$ tenha algum\n  autovalor real.\n:::\n\n::: {.callout-note icon=false}\n## Não-unicidade e autoespaços\n\n- □ Se dois autovetores distintos, $\\mathbf{x}_1$ e $\\mathbf{x}_2$, de\n  uma mesma matriz $A$ (não necessariamente simétrica) estiverem\n  associados ao **mesmo** autovalor $\\lambda$, então qualquer combinação\n  linear não-nula $c_1\\mathbf{x}_1+c_2\\mathbf{x}_2$ também é autovetor de\n  $A$ com esse mesmo autovalor $\\lambda$.\n- □ Se uma matriz $A\\in\\mathbb{R}^{2\\times 2}$ tivesse dois autovalores\n  distintos, mas um deles com autoespaço de dimensão $2$, isso seria\n  matematicamente possível para essa matriz.\n- □ Num problema de classificação de imagens em que cada \"direção\" do\n  espaço de atributos representasse uma característica visual, um\n  autoespaço de dimensão maior que $1$ significaria, na prática, que\n  existe mais de uma direção de atributos igualmente \"especial\" (mesmo\n  fator de escala) para a transformação em questão.\n- □ Como o vetor nulo nunca é considerado autovetor por definição, isso\n  implica que um autoespaço $E_\\lambda$ nunca contém o vetor\n  $\\mathbf{0}$.\n:::\n\n::: {.callout-note icon=false}\n## Teorema Espectral Real\n\n- □ Se duas matrizes simétricas $A$ e $B$ compartilhassem exatamente a\n  mesma base ortonormal de autovetores (mesmo $Q$ na decomposição\n  espectral, com $\\Lambda$ possivelmente diferentes), então $A$ e $B$\n  comutariam, ou seja, $AB=BA$.\n- □ O Teorema Espectral Real garante que toda matriz simétrica\n  $A\\in\\mathbb{R}^{n\\times n}$ tem exatamente $n$ autovalores **distintos**\n  entre si.\n- □ Numa rede elétrica descrita por uma matriz de admitância simétrica,\n  o Teorema Espectral Real garante autovalores reais e autovetores\n  ortogonais, ainda que o contexto físico não tenha nenhuma relação com\n  regressão ou projeção.\n- □ Se uma matriz $A$ tivesse autovalores reais, mas seus autovetores\n  associados a autovalores distintos não fossem ortogonais entre si,\n  isso seria suficiente para concluir que $A$ não é simétrica.\n:::\n\n::: {.callout-note icon=false}\n## Definitude positiva\n\n- □ Se uma matriz simétrica $A\\in\\mathbb{R}^{n\\times n}$ tiver\n  exatamente um autovalor igual a zero e todos os demais estritamente\n  positivos, então $A$ é semidefinida positiva, mas não definida\n  positiva.\n- □ A soma de duas matrizes simétricas definidas positivas de mesma\n  dimensão, $A+B$, é sempre definida positiva.\n- □ Num problema de otimização de portfólio financeiro, se a matriz de\n  covariância dos retornos dos ativos não fosse definida positiva (algum\n  autovalor exatamente zero), isso indicaria a existência de uma\n  combinação de ativos com variância nula — um portfólio livre de risco\n  a partir de ativos individualmente arriscados.\n- □ Como a forma quadrática $\\mathbf{x}^TA\\mathbf{x}$ de uma matriz\n  definida positiva nunca é negativa, isso implica que\n  $\\mathbf{x}^TA\\mathbf{x}=0$ é impossível para $A$ definida positiva e\n  $\\mathbf{x}$ não-nulo qualquer.\n:::\n\n::: {.callout-note icon=false}\n## Quociente de Rayleigh e número de condição\n\n- □ Se $\\mathbf{x}$ for exatamente um autovetor de $A$ associado ao\n  autovalor $\\lambda_{\\max}(A)$, então o quociente de Rayleigh\n  $\\mathbf{x}^TA\\mathbf{x}/\\mathbf{x}^T\\mathbf{x}$ avaliado nesse\n  $\\mathbf{x}$ é exatamente igual a $\\lambda_{\\max}(A)$.\n- □ Se todos os autovalores de uma matriz simétrica definida positiva\n  $A$ dobrarem de valor (cada $\\lambda_i\\to 2\\lambda_i$), o número de\n  condição de $A$ também dobra.\n- □ Num sistema de equações normais mal-condicionado por causa de dois\n  sensores redundantes (quase a mesma leitura), remover fisicamente um\n  dos dois sensores tende a aumentar o menor autovalor relativo de\n  $X^TX$ e, com isso, reduzir o número de condição.\n- □ Como o número de condição de uma matriz simétrica definida positiva\n  é sempre maior ou igual a $1$, isso implica que qualquer matriz com\n  número de condição exatamente igual a $1$ tem que ser, necessariamente,\n  a matriz identidade.\n:::\n\n::: {.callout-note icon=false}\n## $X^TX$: simetria e as duas faces desta aula\n\n- □ Se duas colunas de uma matriz de design $X$ fossem exatamente\n  ortogonais entre si (produto interno zero) e tivessem a mesma norma,\n  a submatriz $2\\times 2$ correspondente de $X^TX$ restrita a essas duas\n  colunas seria um múltiplo escalar da identidade, com número de\n  condição igual a $1$.\n- □ Para qualquer matriz retangular $X\\in\\mathbb{R}^{N\\times d}$ com\n  $N\\ne d$, a própria matriz $X$ (não $X^TX$) sempre tem $\\min(N,d)$\n  autovalores reais, pela mesma lógica do polinômio característico\n  aplicada a $X^TX$.\n- □ Numa matriz de covariância genética (relacionando a expressão de\n  vários genes numa amostra de pacientes), o mesmo raciocínio de\n  autovalor pequeno $\\Rightarrow$ direção quase redundante entre\n  variáveis se aplicaria, ainda que o domínio seja biológico, não\n  imobiliário.\n- □ Como $X^TX$ é sempre simétrica semidefinida positiva\n  (independentemente do posto de $X$), isso implica que $X^TX$ é sempre\n  invertível, qualquer que seja $X$.\n:::\n\n::: {.callout-note icon=false}\n## Covariância empírica e a semente de PCA\n\n- □ Se a matriz de covariância empírica de dois atributos tiver um dos\n  autovalores muito próximo de zero, isso indica que os dados, nesse\n  par de atributos, estão quase inteiramente concentrados ao longo de\n  uma única direção no plano.\n- □ Padronizar cada atributo (subtrair a média, dividir pelo\n  desvio-padrão) antes de calcular a covariância nunca muda a **direção**\n  do autovetor principal, só a magnitude do autovalor associado.\n- □ Num conjunto de dados de sensores industriais com escalas físicas\n  muito diferentes entre si (ex.: temperatura em graus Celsius e pressão\n  em milhares de Pascals), calcular a covariância bruta (sem padronizar)\n  tende a produzir um autovetor principal dominado pelo sensor de maior\n  variância numérica, não necessariamente o fisicamente mais relevante.\n- □ Como a matriz de covariância é sempre semidefinida positiva, isso\n  implica que a soma das variâncias de todos os atributos (o traço da\n  matriz) é sempre igual à soma dos quadrados das covariâncias fora da\n  diagonal.\n:::\n:::\n\n",
    "supporting": [
      "index_files/figure-revealjs"
    ],
    "filters": [],
    "includes": {}
  }
}