<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">

<title>Aula 4: Modelos de Mistura Gaussiana e o Algoritmo EM – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-f6f65eecdb8abf3e35b2d2c28dbef9f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#revisão-e-introdução" id="toc-revisão-e-introdução" class="nav-link active" data-scroll-target="#revisão-e-introdução"><span class="header-section-number">1</span> Revisão e Introdução</a>
  <ul class="collapse">
  <li><a href="#revisão-rápida-o-que-a-aula-3-deixou-pronto-e-onde-ela-parou" id="toc-revisão-rápida-o-que-a-aula-3-deixou-pronto-e-onde-ela-parou" class="nav-link" data-scroll-target="#revisão-rápida-o-que-a-aula-3-deixou-pronto-e-onde-ela-parou"><span class="header-section-number">1.1</span> Revisão Rápida: O Que a Aula 3 Deixou Pronto, e Onde Ela Parou</a></li>
  <li><a href="#ideia-central" id="toc-ideia-central" class="nav-link" data-scroll-target="#ideia-central"><span class="header-section-number">1.2</span> Ideia Central</a></li>
  <li><a href="#roteiro-da-aula" id="toc-roteiro-da-aula" class="nav-link" data-scroll-target="#roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</a></li>
  <li><a href="#problema-motivador" id="toc-problema-motivador" class="nav-link" data-scroll-target="#problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</a></li>
  <li><a href="#pergunta" id="toc-pergunta" class="nav-link" data-scroll-target="#pergunta"><span class="header-section-number">1.5</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#intuição-duas-nuvens" id="toc-intuição-duas-nuvens" class="nav-link" data-scroll-target="#intuição-duas-nuvens"><span class="header-section-number">2</span> Intuição — Duas Nuvens</a>
  <ul class="collapse">
  <li><a href="#pergunta-1" id="toc-pergunta-1" class="nav-link" data-scroll-target="#pergunta-1"><span class="header-section-number">2.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#o-modelo-de-mistura-gaussiana-variável-latente" id="toc-o-modelo-de-mistura-gaussiana-variável-latente" class="nav-link" data-scroll-target="#o-modelo-de-mistura-gaussiana-variável-latente"><span class="header-section-number">3</span> O Modelo de Mistura Gaussiana: Variável Latente</a>
  <ul class="collapse">
  <li><a href="#o-modelo-gerador-em-diagrama" id="toc-o-modelo-gerador-em-diagrama" class="nav-link" data-scroll-target="#o-modelo-gerador-em-diagrama"><span class="header-section-number">3.1</span> O Modelo Gerador, em Diagrama</a></li>
  </ul></li>
  <li><a href="#por-que-não-maximizar-a-verossimilhança-direto" id="toc-por-que-não-maximizar-a-verossimilhança-direto" class="nav-link" data-scroll-target="#por-que-não-maximizar-a-verossimilhança-direto"><span class="header-section-number">4</span> Por Que Não Maximizar a Verossimilhança Direto</a></li>
  <li><a href="#o-passo-e-responsabilidades-posteriores" id="toc-o-passo-e-responsabilidades-posteriores" class="nav-link" data-scroll-target="#o-passo-e-responsabilidades-posteriores"><span class="header-section-number">5</span> O Passo E: Responsabilidades Posteriores</a>
  <ul class="collapse">
  <li><a href="#pergunta-2" id="toc-pergunta-2" class="nav-link" data-scroll-target="#pergunta-2"><span class="header-section-number">5.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#o-passo-m-atualizações-ponderadas" id="toc-o-passo-m-atualizações-ponderadas" class="nav-link" data-scroll-target="#o-passo-m-atualizações-ponderadas"><span class="header-section-number">6</span> O Passo M: Atualizações Ponderadas</a></li>
  <li><a href="#o-algoritmo-em-completo-em-ação" id="toc-o-algoritmo-em-completo-em-ação" class="nav-link" data-scroll-target="#o-algoritmo-em-completo-em-ação"><span class="header-section-number">7</span> O Algoritmo EM Completo, em Ação</a></li>
  <li><a href="#o-kmeans-e-sua-relação-com-o-gmm" id="toc-o-kmeans-e-sua-relação-com-o-gmm" class="nav-link" data-scroll-target="#o-kmeans-e-sua-relação-com-o-gmm"><span class="header-section-number">8</span> O KMeans e Sua Relação com o GMM</a>
  <ul class="collapse">
  <li><a href="#pergunta-3" id="toc-pergunta-3" class="nav-link" data-scroll-target="#pergunta-3"><span class="header-section-number">8.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#fechamento-e-ponte-para-a-aula-5" id="toc-fechamento-e-ponte-para-a-aula-5" class="nav-link" data-scroll-target="#fechamento-e-ponte-para-a-aula-5"><span class="header-section-number">9</span> Fechamento e Ponte para a Aula 5</a>
  <ul class="collapse">
  <li><a href="#pergunta-4" id="toc-pergunta-4" class="nav-link" data-scroll-target="#pergunta-4"><span class="header-section-number">9.1</span> Pergunta</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula 4: Modelos de Mistura Gaussiana e o Algoritmo EM</h1>
<p class="subtitle lead">Aprendizado Não Supervisionado</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos M. Raimundo — Instituto de Computação, UNICAMP </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">7 de setembro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/unsupervised-learning/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="revisão-e-introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Revisão e Introdução</h1>
<section id="revisão-rápida-o-que-a-aula-3-deixou-pronto-e-onde-ela-parou" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="revisão-rápida-o-que-a-aula-3-deixou-pronto-e-onde-ela-parou"><span class="header-section-number">1.1</span> Revisão Rápida: O Que a Aula 3 Deixou Pronto, e Onde Ela Parou</h2>
<p>A Aula 3 definiu <strong>cluster</strong> como uma componente conexa de um conjunto de nível de densidade <span class="math inline">\(L_\lambda=\{\mathbf{x}:p(\mathbf{x})\ge\lambda\}\)</span>, e construiu um algoritmo computável para essa definição — o HDBSCAN — sem exigir nenhuma suposição de forma: primeiro a <strong>distância de alcançabilidade mútua</strong> <span class="math inline">\(d_{\mathrm{mreach}}(a,b)=\max(\mathrm{core}_K(a),
\mathrm{core}_K(b), d(a,b))\)</span>, depois a <strong>MST</strong> sobre essa distância (capturando toda a hierarquia de clusters possível de uma vez), e por fim a extração de clusters reais por <strong>persistência</strong> na árvore condensada, descartando o que é só flutuação amostral.</p>
<p>Aplicado ao Breast Cancer Wisconsin, usando só dois atributos (<code>radius_worst</code> e <code>concave points_worst</code>, sem o rótulo <code>diagnosis</code> durante o ajuste), o HDBSCAN encontrou dois clusters — um de <span class="math inline">\(54\)</span> pacientes <span class="math inline">\(100\%\)</span> malignos, outro de <span class="math inline">\(347\)</span> pacientes <span class="math inline">\(\approx90{,}8\%\)</span> benignos — e marcou <span class="math inline">\(168\)</span> pacientes (<span class="math inline">\(\approx29{,}5\%\)</span>) como <strong>ruído</strong>. Esse resultado é bom (ARI <span class="math inline">\(=0{,}644\)</span> excluindo o ruído da comparação, <span class="math inline">\(0{,}493\)</span> incluindo-o como um rótulo próprio), mas expõe uma limitação estrutural: o HDBSCAN entrega uma <strong>partição rígida</strong>. Cada paciente pertence a exatamente um cluster, ou vira ruído — nunca “um pouco de cada”. Um paciente cuja combinação de <code>radius_worst</code>/<code>concave points_worst</code> fica bem na fronteira entre o núcleo maligno denso e a massa benigna não é “um pouco maligno, um pouco benigno” para o HDBSCAN: ele é forçado para um lado, ou descartado.</p>
</section>
<section id="ideia-central" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="ideia-central"><span class="header-section-number">1.2</span> Ideia Central</h2>
<p>Essa rigidez é uma escolha do método, não um fato necessário sobre os dados. Se duas populações clínicas realmente se sobrepõem numa faixa contínua de biomarcadores — sem um vale de densidade genuíno separando-as —, forçar uma escolha binária esconde informação real: “quão parecido com cada grupo este paciente é” é, nesse caso, uma pergunta cuja resposta honesta é um número entre <span class="math inline">\(0\)</span> e <span class="math inline">\(1\)</span>, não um rótulo único. A ideia-ponte desta aula é justamente essa: trocar “a qual cluster este ponto pertence?” por “<strong>com que probabilidade</strong> este ponto pertence a cada cluster?” — a mesma tarefa de agrupamento, mas com uma resposta relaxada, probabilística, em vez de uma resposta binária.</p>
</section>
<section id="roteiro-da-aula" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</h2>
<p>Essa troca — de atribuição rígida para atribuição probabilística — se desdobra em quatro perguntas, cada uma resolvida em um bloco desta aula:</p>
<ol type="1">
<li>Formalmente, o que significa dizer que um ponto “nasceu de uma entre <span class="math inline">\(K\)</span> populações”, quando não se sabe <strong>qual</strong>?</li>
<li>Dado esse modelo gerador, como transformar a incerteza sobre a origem de cada ponto numa probabilidade concreta, calculável?</li>
<li>Uma vez com essas probabilidades, como usá-las para reajustar os parâmetros do próprio modelo — e por que esse processo precisa ser iterativo?</li>
<li>Essa ideia nova é uma generalização do que já se conhece (o KMeans), ou é uma ferramenta completamente diferente?</li>
</ol>
</section>
<section id="problema-motivador" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</h2>
<p>Volte ao resultado da Aula 3: <span class="math inline">\(168\)</span> pacientes marcados como ruído, dos quais <span class="math inline">\(126\)</span> eram malignos e <span class="math inline">\(42\)</span> benignos. O HDBSCAN não tem vocabulário para dizer mais nada sobre eles — “ruído” é um rótulo terminal, não um grau de pertencimento. A pergunta que abre esta aula é literal: e se, em vez de “ruído” ou “cluster <span class="math inline">\(k\)</span>”, cada um desses <span class="math inline">\(168\)</span> pacientes recebesse dois números — a probabilidade de pertencer ao grupo mais maligno, e a probabilidade de pertencer ao grupo mais benigno, somando <span class="math inline">\(1\)</span>? Essa é exatamente a saída que os <strong>Modelos de Mistura Gaussiana</strong> (GMM) produzem, e que o restante da aula constrói do zero.</p>
</section>
<section id="pergunta" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="pergunta"><span class="header-section-number">1.5</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um paciente marcado como ruído pelo HDBSCAN não pertence a nenhuma componente conexa de alta densidade nos dois atributos usados. Isso significa que ele é igualmente parecido com as duas populações (benigna e maligna), ou pode significar outra coisa?
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Um paciente marcado como ruído pode, sob um modelo de mistura gaussiana ajustado aos mesmos dados, receber uma responsabilidade bem próxima de <span class="math inline">\(1\)</span> para um único componente — “estar num vale geométrico local” e “ter atribuição probabilística ambígua sob um modelo global” não são a mesma coisa.</li>
<li>□ Se um paciente recebe responsabilidade exatamente <span class="math inline">\(0{,}5\)</span> para cada um dos dois componentes de um GMM, isso implica necessariamente que ele está geometricamente equidistante das duas médias <span class="math inline">\(\mu_1\)</span> e <span class="math inline">\(\mu_2\)</span> na distância euclidiana bruta.</li>
<li>□ Se as duas populações gaussianas subjacentes tivessem exatamente a mesma média e a mesma matriz de covariância (colapsando numa única gaussiana), a responsabilidade de qualquer ponto para cada componente seria exatamente <span class="math inline">\(\pi_k\)</span> (o peso de mistura), independente da posição do ponto.</li>
<li>□ Numa aplicação de perfil de consumo em que um cliente compra tanto itens “econômicos” quanto “premium” em proporções parecidas, um GMM ajustado ao histórico de gastos tenderia a atribuir a esse cliente responsabilidades intermediárias a ambos os segmentos, enquanto uma regra de corte único baseada em densidade local tenderia a isolá-lo como ruído ou a forçá-lo para um segmento só.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="intuição-duas-nuvens" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Intuição — Duas Nuvens</h1>
<p>Antes de qualquer fórmula, veja o resultado inteiro primeiro — só vai faltar nomear os passos. A figura abaixo mostra, lado a lado, os mesmos <span class="math inline">\(569\)</span> pacientes, nos mesmos dois atributos padronizados (<code>radius_worst</code> e <code>concave points_worst</code>) já usados na Aula 3. À esquerda, a partição rígida do HDBSCAN: cada ponto tem uma cor sólida — azul para o cluster majoritariamente benigno, laranja para o majoritariamente maligno, vermelho para ruído. À direita, o resultado de um Modelo de Mistura Gaussiana com <span class="math inline">\(2\)</span> componentes ajustado aos mesmos dados (ainda sem ter sido explicado como): cada ponto recebe uma cor <strong>misturada</strong>, interpolada entre azul e laranja de acordo com a sua probabilidade de pertencer a cada componente — quanto mais próximo do roxo, mais ambígua a origem daquele paciente.</p>
<div class="fig-resize" style="width: 70%; margin: 0 auto;">
<div id="0c38c86c" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Duas diferenças estruturais saltam aos olhos. Primeiro, o GMM <strong>nunca descarta ninguém</strong>: os <span class="math inline">\(168\)</span> pacientes que a Aula 3 jogou fora como ruído aparecem no painel direito com uma cor — talvez ambígua, talvez não, mas sempre uma resposta. Segundo, a cor não é binária: existe um gradiente contínuo entre azul e laranja, e os <span class="math inline">\(9\)</span> pacientes circulados em preto (responsabilidade entre <span class="math inline">\(0{,}45\)</span> e <span class="math inline">\(0{,}55\)</span> para cada componente) são o retrato exato do que “sobreposição real entre duas populações” deveria parecer — não um artefato de um algoritmo confuso, mas a honestidade de um modelo que admite que, para aquele paciente específico, a evidência realmente não pende para nenhum lado.</p>
<p>Isso já responde, em germe, à Pergunta da Abertura: a “ambiguidade” de um paciente não é mais uma falha do algoritmo (como seria com uma regra de corte único) — é uma <strong>quantidade calculável</strong>, um número entre <span class="math inline">\(0\)</span> e <span class="math inline">\(1\)</span> por componente, que soma exatamente <span class="math inline">\(1\)</span> por paciente. Falta nomear de onde esse número vem, e como o próprio modelo (as posições e formatos das duas “nuvens” coloridas) é ajustado a partir dos dados. Essas são as perguntas dos Blocos 3 a 6.</p>
<section id="pergunta-1" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="pergunta-1"><span class="header-section-number">2.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Os 9 pacientes circulados no painel direito têm responsabilidade próxima de 50/50. Isso significa que o modelo “não sabe nada” sobre eles, no mesmo sentido em que uma moeda não viciada “não sabe” se vai dar cara ou coroa?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense na diferença entre “incerteza sobre um evento futuro aleatório” (a moeda) e “incerteza sobre um fato já determinado, mas desconhecido” (a origem populacional de um paciente que já existe).</p>
<ul>
<li>□ A responsabilidade <span class="math inline">\(50/50\)</span> de um paciente reflete a melhor estimativa do modelo sobre um fato <strong>já fixado</strong> (o paciente pertence, de fato, a uma população só) — diferente da moeda, cujo resultado ainda não existe no momento da previsão.</li>
<li>□ Aumentar o número de atributos usados no ajuste do GMM (de <span class="math inline">\(2\)</span> para, digamos, <span class="math inline">\(10\)</span>) necessariamente reduziria a responsabilidade ambígua desses <span class="math inline">\(9\)</span> pacientes específicos, porque mais informação sempre reduz ambiguidade estatística em qualquer situação.</li>
<li>□ Um paciente com responsabilidade <span class="math inline">\(50/50\)</span> contribui, no Passo M (ainda não visto), com metade do seu peso para a reestimação de cada um dos dois componentes — ele não é ignorado, é dividido.</li>
<li>□ Se o GMM verdadeiro subjacente aos dados tivesse apenas <span class="math inline">\(1\)</span> componente (não <span class="math inline">\(2\)</span>), esperaríamos ver muito mais pacientes com responsabilidade próxima de <span class="math inline">\(50/50\)</span> do que os <span class="math inline">\(9\)</span> observados aqui.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="o-modelo-de-mistura-gaussiana-variável-latente" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> O Modelo de Mistura Gaussiana: Variável Latente</h1>
<p><strong>Premissas desta construção.</strong> Antes de escrever qualquer fórmula, anuncie o que está sendo assumido: (1) existem <span class="math inline">\(K\)</span> populações (“componentes”) distintas, cada uma gaussiana; (2) todo paciente nasce de exatamente uma dessas populações, nunca de uma mistura física real — a mistura está só na nossa incerteza sobre qual foi; (3) não observamos diretamente de qual população um paciente veio, só observamos <span class="math inline">\(\mathbf{x}\)</span> (seus atributos). A Aula 1 já assumiu uma única gaussiana para toda a população; o GMM generaliza isso permitindo <span class="math inline">\(K\)</span> gaussianas, cada paciente vindo de uma delas.</p>
<p><strong>Formalizando “de qual população”.</strong> Introduza uma variável aleatória <span class="math inline">\(\mathbf{z}\)</span> categórica, com codificação 1-de-<span class="math inline">\(K\)</span>: <span class="math inline">\(\mathbf{z}\)</span> é um vetor binário de tamanho <span class="math inline">\(K\)</span> com exatamente uma coordenada igual a <span class="math inline">\(1\)</span> (indicando a população de origem) e as demais iguais a <span class="math inline">\(0\)</span>. Escreva <span class="math inline">\(z_k=1\)</span> para “este ponto nasceu da população <span class="math inline">\(k\)</span>”. A probabilidade a priori de cada população é o <strong>peso de mistura</strong> <span class="math inline">\(\pi_k\)</span>:</p>
<p><span class="math display">\[p(z_k=1) = \pi_k, \qquad 0\le\pi_k\le 1, \qquad \sum_{k=1}^K \pi_k = 1.\]</span></p>
<p>Dado que o ponto nasceu da população <span class="math inline">\(k\)</span>, sua distribuição é uma gaussiana com média e covariância próprias dessa população:</p>
<p><span class="math display">\[p(\mathbf{x}\mid z_k=1) = \mathcal{N}(\mathbf{x}\mid \mu_k, \Sigma_k).\]</span></p>
<p>Bishop (PRML, 2006, p.&nbsp;430-431) descreve exatamente essa construção — tradução livre:</p>
<blockquote class="blockquote">
<p>“Vamos introduzir uma variável aleatória binária <span class="math inline">\(K\)</span>-dimensional <span class="math inline">\(z\)</span> com uma representação 1-de-<span class="math inline">\(K\)</span>, na qual um elemento particular <span class="math inline">\(z_k\)</span> é igual a <span class="math inline">\(1\)</span> e todos os outros elementos são iguais a <span class="math inline">\(0\)</span>. […] A distribuição marginal sobre <span class="math inline">\(z\)</span> é especificada em termos dos coeficientes de mistura <span class="math inline">\(\pi_k\)</span>, de tal forma que <span class="math inline">\(p(z_k=1)=\pi_k\)</span>.”</p>
</blockquote>
<p>A figura abaixo é o <strong>modelo gerador</strong> completo, em forma de diagrama: para cada paciente <span class="math inline">\(n\)</span>, primeiro sorteia-se a população de origem <span class="math inline">\(z_n\)</span> (com probabilidades <span class="math inline">\(\pi_1,\dots,\pi_K\)</span>), depois sorteia-se <span class="math inline">\(\mathbf{x}_n\)</span> da gaussiana daquela população específica (<span class="math inline">\(\mu_k,\Sigma_k\)</span>). O nó de <span class="math inline">\(\mathbf{x}_n\)</span> aparece preenchido porque é o único <strong>observado</strong> — <span class="math inline">\(z_n\)</span> (contorno vazio) nunca é visto diretamente, é justamente o que o restante da aula vai aprender a inferir.</p>
<section id="o-modelo-gerador-em-diagrama" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="o-modelo-gerador-em-diagrama"><span class="header-section-number">3.1</span> O Modelo Gerador, em Diagrama</h2>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<img src="index_files/mediabag/36faf184833c3a28a5698d589595dc0b3ca23b0f.svg" class="img-fluid">
</div>
<p><strong>Recuperando a mistura já conhecida.</strong> Somando (marginalizando) sobre os <span class="math inline">\(K\)</span> estados possíveis de <span class="math inline">\(\mathbf{z}\)</span>, a distribuição de <span class="math inline">\(\mathbf{x}\)</span> sozinho é</p>
<p><span class="math display">\[p(\mathbf{x}) = \sum_{k=1}^K p(z_k=1)\,p(\mathbf{x}\mid z_k=1) = \sum_{k=1}^K \pi_k\,\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k),\]</span></p>
<p>exatamente a soma ponderada de gaussianas que já era, em princípio, possível de escrever desde a Aula 1 (nada impede somar duas gaussianas). A diferença é que agora essa soma vem de uma <strong>história geradora explícita</strong>: não é só “uma função matemática que soma bem”, é “cada ponto nasceu de uma população específica, que não vemos”. Essa diferença importa porque é o que torna possível a pergunta central do resto da aula — dado um ponto <span class="math inline">\(\mathbf{x}\)</span> observado, qual é a probabilidade <strong>a posteriori</strong> de cada valor de <span class="math inline">\(z\)</span>, isto é, de cada origem possível?</p>
<p>Essa probabilidade a posteriori tem nome: <strong>responsabilidade</strong>, e por Bayes ela vale</p>
<p><span class="math display">\[\gamma(z_{nk}) \equiv p(z_k=1\mid\mathbf{x}_n) = \frac{\pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\sum_{j=1}^K \pi_j\,\mathcal{N}(\mathbf{x}_n\mid\mu_j,\Sigma_j)}\]</span></p>
<p>— a dedução completa dessa razão, passo a passo a partir da definição de probabilidade condicional, fica para o Passo E (Bloco 5), quando essa fórmula se torna parte do algoritmo; por ora, vale nomear a quantidade e ver a figura que ela produz. Bishop (PRML, 2006, p.&nbsp;432) nomeia essa quantidade — tradução livre:</p>
<blockquote class="blockquote">
<p>“Vamos considerar <span class="math inline">\(\pi_k\)</span> como a probabilidade a priori de <span class="math inline">\(z_k=1\)</span>, e a quantidade <span class="math inline">\(\gamma(z_{nk})\)</span> como a probabilidade a posteriori correspondente, uma vez observado <span class="math inline">\(\mathbf{x}_n\)</span>. […] <span class="math inline">\(\gamma(z_{nk})\)</span> também pode ser vista como a <strong>responsabilidade</strong> que o componente <span class="math inline">\(k\)</span> assume por ‘explicar’ a observação <span class="math inline">\(\mathbf{x}_n\)</span>.”</p>
</blockquote>
<p>Essa é exatamente a fórmula por trás da Figura do Bloco 2: para cada paciente <span class="math inline">\(n\)</span>, calcular <span class="math inline">\(\gamma(z_{nk})\)</span> para <span class="math inline">\(k=1,2\)</span> e usar esses dois números para misturar as cores azul e laranja. Falta só uma peça para poder calcular isso de verdade: de onde vêm <span class="math inline">\(\pi_k\)</span>, <span class="math inline">\(\mu_k\)</span>, <span class="math inline">\(\Sigma_k\)</span>? Eles não são conhecidos de antemão — precisam ser <strong>ajustados aos dados</strong>, e é aí que a dificuldade começa (Bloco 4).</p>
</section>
</section>
<section id="por-que-não-maximizar-a-verossimilhança-direto" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Por Que Não Maximizar a Verossimilhança Direto</h1>
<p>Na Aula 1, ajustar uma única gaussiana a um conjunto de dados por máxima verossimilhança teve solução fechada: derivar o log da verossimilhança em relação a <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\Sigma\)</span>, igualar a zero, e resolver — <span class="math inline">\(\hat\mu\)</span> e <span class="math inline">\(\hat\Sigma\)</span> saíram diretamente como média e covariância amostrais. A pergunta natural é: por que não fazer o mesmo aqui, só que para <span class="math inline">\(K\)</span> gaussianas de uma vez?</p>
<p>Para <span class="math inline">\(N\)</span> pacientes observados <span class="math inline">\(\mathbf{x}_1,\dots,\mathbf{x}_N\)</span> (assumidos i.i.d.), a log-verossimilhança do GMM é</p>
<p><span class="math display">\[\ln p(X\mid\pi,\mu,\Sigma) = \sum_{n=1}^N \ln\left\{\sum_{k=1}^K \pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)\right\}.\]</span></p>
<p>Compare com a Aula 1: lá, dentro do <span class="math inline">\(\ln\)</span>, havia só <strong>uma</strong> gaussiana — e <span class="math inline">\(\ln\)</span> de uma exponencial cancela limpo, sobrando uma expressão quadrática fácil de derivar. Aqui, dentro do <span class="math inline">\(\ln\)</span> há uma <strong>soma</strong> de <span class="math inline">\(K\)</span> termos. Bishop (PRML, 2006, p.&nbsp;433-434) nomeia exatamente essa dificuldade — tradução livre:</p>
<blockquote class="blockquote">
<p>“A dificuldade surge da presença do somatório sobre <span class="math inline">\(k\)</span> que aparece dentro do logaritmo em (9.14), de forma que a função logaritmo não age mais diretamente sobre a gaussiana. Se igualarmos as derivadas da log-verossimilhança a zero, não obteremos mais uma solução em forma fechada.”</p>
</blockquote>
<p>Derivar <span class="math inline">\(\ln p(X\mid\pi,\mu,\Sigma)\)</span> em relação a <span class="math inline">\(\mu_k\)</span> e igualar a zero ainda é possível — mas o resultado, como se verá no Bloco 6, <strong>não isola <span class="math inline">\(\mu_k\)</span></strong> algebricamente, porque <span class="math inline">\(\mu_k\)</span> continua aparecendo escondido dentro de uma razão de exponenciais somada com as outras <span class="math inline">\(K-1\)</span>. Não há como “resolver para <span class="math inline">\(\mu_k\)</span>” numa única passada.</p>
<p><strong>Um aviso técnico, sem aprofundar.</strong> Maximizar essa verossimilhança tem, além da dificuldade algébrica, um problema mais sério: degenerações (<em>singularidades</em>). Se a média de um componente colapsar exatamente sobre um único ponto de dado e a variância desse componente for levada a zero, a densidade naquele ponto tende a infinito, e a log-verossimilhança tende a infinito junto — um “ajuste perfeito” que não é generalização nenhuma, só <em>overfitting</em> patológico de um único ponto. Bishop (p.&nbsp;434), tradução livre:</p>
<blockquote class="blockquote">
<p>“Se considerarmos o limite <span class="math inline">\(\sigma_j\to 0\)</span>, veremos que esse termo tende ao infinito, e portanto a função de log-verossimilhança também tende ao infinito. Assim, a maximização da log-verossimilhança não é um problema bem posto, pois tais singularidades estarão sempre presentes.”</p>
</blockquote>
<p>Na prática, isso significa: ao ajustar um GMM, buscar um máximo local bem-comportado da verossimilhança, não o máximo global (que é sempre degenerado) — o <code>sklearn.mixture.GaussianMixture</code> usado no Bloco 7 já inclui salvaguardas para isso (um piso mínimo de variância), então não é algo que o código precisa tratar manualmente aqui.</p>
<p><strong>A saída.</strong> Já que não há solução fechada, mas as equações de derivada zero têm uma estrutura reconhecível (Bloco 6), a estratégia é <strong>iterativa</strong>: alternar entre calcular responsabilidades com os parâmetros atuais (Passo E) e reajustar os parâmetros com as responsabilidades atuais (Passo M), repetindo até convergir. Esse é o algoritmo <strong>EM</strong> (<em>Expectation-Maximization</em>).</p>
</section>
<section id="o-passo-e-responsabilidades-posteriores" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> O Passo E: Responsabilidades Posteriores</h1>
<p><strong>Premissa deste passo.</strong> Fixe os parâmetros atuais do modelo (<span class="math inline">\(\pi_k,\mu_k,\Sigma_k\)</span> para todo <span class="math inline">\(k\)</span>) — não importa se eles ainda estão longe do ajuste final, o Passo E só pergunta: “sob <strong>estes</strong> parâmetros, qual a probabilidade posterior de cada origem, para cada ponto observado?”</p>
<p><strong>Deduzindo a responsabilidade.</strong> Por definição de probabilidade condicional,</p>
<p><span class="math display">\[p(z_k=1\mid\mathbf{x}_n) = \frac{p(z_k=1,\mathbf{x}_n)}{p(\mathbf{x}_n)}.\]</span></p>
<p>O numerador é a probabilidade conjunta do evento “paciente <span class="math inline">\(n\)</span> nasceu da população <span class="math inline">\(k\)</span>” <strong>e</strong> “paciente <span class="math inline">\(n\)</span> tem atributos <span class="math inline">\(\mathbf{x}_n\)</span>” — pela regra da cadeia de probabilidade (<em>chain rule</em>), essa conjunta fatora como prior vezes verossimilhança condicional:</p>
<p><span class="math display">\[p(z_k=1,\mathbf{x}_n) = p(z_k=1)\,p(\mathbf{x}_n\mid z_k=1) = \pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k),\]</span></p>
<p>usando diretamente as duas premissas do modelo gerador (Bloco 3): <span class="math inline">\(p(z_k=1)=\pi_k\)</span> e <span class="math inline">\(p(\mathbf{x}_n\mid z_k=1)=\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)\)</span>. O denominador <span class="math inline">\(p(\mathbf{x}_n)\)</span> é a marginal — pela <strong>lei da probabilidade total</strong>, somando essa mesma conjunta sobre os <span class="math inline">\(K\)</span> estados de <span class="math inline">\(z_n\)</span> (mutuamente exclusivos e exaustivos, já que <span class="math inline">\(z_n\)</span> é 1-de-<span class="math inline">\(K\)</span>), exatamente como no Bloco 3:</p>
<p><span class="math display">\[p(\mathbf{x}_n) = \sum_{j=1}^K p(z_j=1,\mathbf{x}_n) = \sum_{j=1}^K \pi_j\,\mathcal{N}(\mathbf{x}_n\mid\mu_j,\Sigma_j).\]</span></p>
<p>Substituindo numerador e denominador na razão original:</p>
<p><span class="math display">\[\gamma(z_{nk}) \equiv p(z_k=1\mid\mathbf{x}_n) = \frac{\pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\displaystyle\sum_{j=1}^K \pi_j\,\mathcal{N}(\mathbf{x}_n\mid\mu_j,\Sigma_j)},\]</span></p>
<p>agora indexada por paciente <span class="math inline">\(n\)</span> e componente <span class="math inline">\(k\)</span> — cada um dos <span class="math inline">\(N\)</span> pacientes recebe seu próprio vetor de <span class="math inline">\(K\)</span> responsabilidades, somando <span class="math inline">\(1\)</span>. Note que, embora a fórmula pareça “só” um cálculo de Bayes, ela é o motor de toda a diferença desta aula em relação à Aula 3: em vez de uma regra de corte (dentro/fora de <span class="math inline">\(L_\lambda\)</span>), cada ponto participa, em algum grau, de <strong>todos</strong> os componentes.</p>
<p><strong>Verificação numérica.</strong> Aplicando essa fórmula aos <span class="math inline">\(569\)</span> pacientes do Breast Cancer Wisconsin (com os parâmetros de um GMM de <span class="math inline">\(2\)</span> componentes já ajustado — o ajuste completo é assunto do Passo M, Bloco 6; aqui só se <strong>avalia</strong> a fórmula do Passo E nos parâmetros finais, para ver a forma da resposta), <span class="math inline">\(9\)</span> pacientes caem na faixa <span class="math inline">\(|\gamma-0{,}5|&lt;0{,}05\)</span> — a mesma faixa já destacada na figura do Bloco 2. Três exemplos reais:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Paciente (índice)</th>
<th><code>radius_worst</code></th>
<th><code>concave points_worst</code></th>
<th>Diagnóstico</th>
<th><span class="math inline">\(\gamma\)</span>(comp. benigno)</th>
<th><span class="math inline">\(\gamma\)</span>(comp. maligno)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>41</td>
<td>12,84</td>
<td>0,1424</td>
<td>M</td>
<td>0,486</td>
<td>0,514</td>
</tr>
<tr class="even">
<td>112</td>
<td>15,30</td>
<td>0,1505</td>
<td>B</td>
<td>0,520</td>
<td>0,480</td>
</tr>
<tr class="odd">
<td>501</td>
<td>16,01</td>
<td>0,1521</td>
<td>M</td>
<td>0,481</td>
<td>0,519</td>
</tr>
</tbody>
</table>
<p>Repare que o diagnóstico real (nunca usado no ajuste) não decide para que lado a responsabilidade pende — o paciente 112 é benigno com responsabilidade levemente maior para o componente benigno, mas o paciente 501 é maligno com responsabilidade levemente maior para o componente maligno; ambos ficam a menos de <span class="math inline">\(2\)</span> pontos percentuais do empate. Isso é exatamente o que se espera de pacientes que, nesses dois atributos, ficam genuinamente na zona de transição entre as duas populações — nem o modelo “erra” ao hesitar, nem o rótulo real resolveria a hesitação de antemão (o modelo nunca o viu).</p>
<p>Uma checagem mais ampla: contando pacientes com responsabilidade máxima abaixo de <span class="math inline">\(0{,}9\)</span> (ambiguidade moderada, não só extrema) chega-se a <span class="math inline">\(101\)</span> dos <span class="math inline">\(569\)</span> pacientes (<span class="math inline">\(\approx17{,}7\%\)</span>) — uma fração bem maior do que os <span class="math inline">\(9\)</span> casos de ambiguidade quase perfeita, mostrando que a sobreposição entre as duas “nuvens” de densidade não é um fenômeno raro de pontuinhos isolados, é uma faixa de transição real com largura própria.</p>
<section id="pergunta-2" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="pergunta-2"><span class="header-section-number">5.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um paciente tem responsabilidade <span class="math inline">\(\gamma=0{,}9\)</span> para o componente maligno e <span class="math inline">\(\gamma=0{,}1\)</span> para o benigno. Se, no meio de uma sessão de reajuste do modelo, os parâmetros do componente maligno mudarem bastante (por exemplo, sua covariância <span class="math inline">\(\Sigma\)</span> dobrar de tamanho), o que necessariamente acontece com essa responsabilidade <span class="math inline">\(\gamma=0{,}9\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se <span class="math inline">\(\gamma(z_{nk})\)</span> é uma propriedade fixa do ponto <span class="math inline">\(\mathbf{x}_n\)</span>, ou uma função dos parâmetros correntes do modelo — e lembre que a fórmula de Bayes usada aqui depende de <span class="math inline">\(\mu_k\)</span> e <span class="math inline">\(\Sigma_k\)</span> dos dois lados da razão, não só do componente <span class="math inline">\(k\)</span>.</p>
<ul>
<li>□ A responsabilidade <span class="math inline">\(\gamma(z_{nk})\)</span> é recalculada do zero a cada vez que os parâmetros do modelo mudam — ela não é uma propriedade fixa do ponto <span class="math inline">\(\mathbf{x}_n\)</span>, é uma função corrente de <span class="math inline">\(\pi,\mu,\Sigma\)</span>.</li>
<li>□ Se a covariância do componente maligno dobrar de tamanho (ficando mais “espalhada”), isso necessariamente aumenta a responsabilidade <span class="math inline">\(\gamma(z_{n,\text{maligno}})\)</span> para qualquer ponto, porque uma gaussiana mais espalhada sempre atribui mais densidade a todo ponto do espaço.</li>
<li>□ Dois pacientes com exatamente a mesma responsabilidade <span class="math inline">\(\gamma=(0{,}9,0{,}1)\)</span> sob os parâmetros atuais do modelo podem ter responsabilidades bem diferentes entre si depois de uma rodada de reestimação de parâmetros (Passo M), mesmo que os dois tivessem originalmente o mesmo par de atributos observados.</li>
<li>□ Se <span class="math inline">\(K=1\)</span> (um único componente), a responsabilidade <span class="math inline">\(\gamma(z_{n1})\)</span> é sempre igual a <span class="math inline">\(1\)</span> para todo ponto, independentemente dos parâmetros — não há nenhum outro componente para “competir” na razão de Bayes.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="o-passo-m-atualizações-ponderadas" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> O Passo M: Atualizações Ponderadas</h1>
<p><strong>Premissa deste passo.</strong> Agora inverta o papel: fixe as responsabilidades <span class="math inline">\(\gamma(z_{nk})\)</span> calculadas no Passo E (tratando-as como constantes conhecidas, não mais como função dos parâmetros), e pergunte que novos valores de <span class="math inline">\(\pi_k,\mu_k,\Sigma_k\)</span> maximizam a log-verossimilhança <strong>esperada</strong> dos dados completos sob essas responsabilidades. Essa é uma maximização bem mais simples do que a do Bloco 4, porque, com <span class="math inline">\(\gamma(z_{nk})\)</span> fixo, o problema se separa em <span class="math inline">\(K\)</span> ajustes de máxima verossimilhança <strong>ponderada</strong>, um por componente — não há mais soma dentro do <span class="math inline">\(\ln\)</span> competindo entre componentes. A receita para maximizar é a de sempre para uma função diferenciável sem restrição ativa: <strong>derivar a log-verossimilhança em relação a cada parâmetro e igualar a zero</strong> — é exatamente isso que os três blocos a seguir fazem, um parâmetro de cada vez.</p>
<p><strong>Por que <span class="math inline">\(\gamma(z_{nk})\)</span> aparece em toda derivada.</strong> Antes de calcular cada atualização, vale isolar o mecanismo comum a <span class="math inline">\(\mu_k\)</span> e a <span class="math inline">\(\Sigma_k\)</span> — parâmetros <strong>privados</strong> do componente <span class="math inline">\(k\)</span>, não compartilhados com os outros <span class="math inline">\(K-1\)</span>. Escreva <span class="math inline">\(\mathcal{N}_k(\mathbf{x}_n)\equiv
\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)\)</span> e seja <span class="math inline">\(\theta_k\)</span> um desses parâmetros privados (<span class="math inline">\(\mu_k\)</span> ou <span class="math inline">\(\Sigma_k\)</span>). Dentro da soma <span class="math inline">\(\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)\)</span>, só o termo <span class="math inline">\(j=k\)</span> depende de <span class="math inline">\(\theta_k\)</span>, então</p>
<p><span class="math display">\[\frac{\partial}{\partial\theta_k}\ln\left(\sum_{j=1}^K\pi_j\mathcal{N}_j(\mathbf{x}_n)\right) = \frac{1}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)}\cdot\pi_k\,\frac{\partial \mathcal{N}_k(\mathbf{x}_n)}{\partial\theta_k}.\]</span></p>
<p>Pela regra da cadeia do logaritmo aplicada a <span class="math inline">\(\mathcal{N}_k\)</span> (isto é, <span class="math inline">\(\partial \mathcal{N}_k/\partial\theta_k = \mathcal{N}_k\cdot\partial\ln\mathcal{N}_k/\partial\theta_k\)</span>), o lado direito vira</p>
<p><span class="math display">\[\frac{\pi_k\,\mathcal{N}_k(\mathbf{x}_n)}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)}\cdot\frac{\partial\ln\mathcal{N}_k(\mathbf{x}_n)}{\partial\theta_k} = \gamma(z_{nk})\cdot\frac{\partial\ln\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\partial\theta_k}.\]</span></p>
<p>Somando sobre os <span class="math inline">\(N\)</span> pacientes (a log-verossimilhança é uma soma sobre <span class="math inline">\(n\)</span>):</p>
<p><span class="math display">\[\frac{\partial \ln p(X\mid\pi,\mu,\Sigma)}{\partial\theta_k} = \sum_{n=1}^N \gamma(z_{nk})\,\frac{\partial\ln\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\partial\theta_k}.\]</span></p>
<p>Essa identidade responde à pergunta natural: por que fixar <span class="math inline">\(\gamma\)</span> (tratando-a como constante) transforma um problema sem solução fechada (Bloco 4) num problema resolvível? Porque, com <span class="math inline">\(\gamma\)</span> fixo, a derivada da log-verossimilhança da mistura inteira, em relação a um parâmetro privado do componente <span class="math inline">\(k\)</span>, <strong>colapsa exatamente numa versão ponderada da equação de derivada de uma única gaussiana</strong> — a mesma do MLE da Aula 1 — com <span class="math inline">\(\gamma(z_{nk})\)</span> como peso de cada ponto na soma. É esse colapso que separa o problema em <span class="math inline">\(K\)</span> ajustes independentes.</p>
<p><strong>Atualização de <span class="math inline">\(\mu_k\)</span>.</strong> Falta a peça específica de <span class="math inline">\(\mu_k\)</span>: <span class="math inline">\(\partial\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k)/\partial\mu_k\)</span>. Escrevendo a densidade gaussiana por extenso,</p>
<p><span class="math display">\[\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k) = -\frac{D}{2}\ln(2\pi) - \frac12\ln|\Sigma_k| - \frac12(\mathbf{x}-\mu_k)^T\Sigma_k^{-1}(\mathbf{x}-\mu_k),\]</span></p>
<p>só o termo quadrático depende de <span class="math inline">\(\mu_k\)</span>. Para uma forma quadrática <span class="math inline">\((\mathbf{x}-\mu)^TA(\mathbf{x}-\mu)\)</span> com <span class="math inline">\(A\)</span> simétrica, o gradiente em relação a <span class="math inline">\(\mu\)</span> é <span class="math inline">\(-2A(\mathbf{x}-\mu)\)</span> — fazendo <span class="math inline">\(\mathbf{u}=\mathbf{x}-\mu\)</span> (logo <span class="math inline">\(\partial\mathbf{u}/\partial\mu=-I\)</span>) e usando que o gradiente de <span class="math inline">\(\mathbf{u}^TA\mathbf{u}\)</span> em <span class="math inline">\(\mathbf{u}\)</span> é <span class="math inline">\(2A\mathbf{u}\)</span>, a regra da cadeia dá <span class="math inline">\(\partial(\mathbf{u}^TA\mathbf{u})/\partial\mu = -2A\mathbf{u}\)</span>. Logo</p>
<p><span class="math display">\[\frac{\partial\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k)}{\partial\mu_k} = -\frac12\cdot(-2)\Sigma_k^{-1}(\mathbf{x}-\mu_k) = \Sigma_k^{-1}(\mathbf{x}-\mu_k).\]</span></p>
<p>Pela identidade geral acima (com <span class="math inline">\(\theta_k=\mu_k\)</span>):</p>
<p><span class="math display">\[\frac{\partial \ln p(X\mid\pi,\mu,\Sigma)}{\partial\mu_k} = \sum_{n=1}^N \gamma(z_{nk})\,\Sigma_k^{-1}(\mathbf{x}_n-\mu_k).\]</span></p>
<p>Igualando a zero e multiplicando por <span class="math inline">\(\Sigma_k\)</span> (assumida não-singular):</p>
<p><span class="math display">\[\sum_{n=1}^N \gamma(z_{nk})(\mathbf{x}_n-\mu_k) = \mathbf{0} \;\Longrightarrow\; \mu_k = \frac{1}{N_k}\sum_{n=1}^N \gamma(z_{nk})\,\mathbf{x}_n, \qquad\text{onde}\qquad N_k = \sum_{n=1}^N \gamma(z_{nk}).\]</span></p>
<p>Bishop (PRML, 2006, p.&nbsp;436) interpreta <span class="math inline">\(N_k\)</span> diretamente — tradução livre:</p>
<blockquote class="blockquote">
<p>“Podemos interpretar <span class="math inline">\(N_k\)</span> como o número efetivo de pontos atribuídos ao cluster <span class="math inline">\(k\)</span>.”</p>
</blockquote>
<p>A leitura de <span class="math inline">\(\mu_k\)</span> é direta: é uma <strong>média ponderada</strong> de todos os <span class="math inline">\(N\)</span> pacientes, em que o peso do paciente <span class="math inline">\(n\)</span> é a sua responsabilidade <span class="math inline">\(\gamma(z_{nk})\)</span> para o componente <span class="math inline">\(k\)</span> — pacientes com responsabilidade alta para <span class="math inline">\(k\)</span> pesam quase como um voto inteiro; pacientes ambíguos (como os <span class="math inline">\(9\)</span> do Bloco 5) contribuem uma fração pequena para <strong>os dois</strong> componentes ao mesmo tempo. Compare com a Aula 1: lá, a média amostral usava todos os pontos com peso igual (<span class="math inline">\(1/N\)</span>); aqui, o peso é a própria responsabilidade — a mesma ideia de MLE, generalizada para responder “quanto este ponto conta para este componente específico”.</p>
<p><strong>Atualização de <span class="math inline">\(\Sigma_k\)</span>.</strong> A mesma identidade geral vale com <span class="math inline">\(\theta_k=\Sigma_k\)</span>, mas a peça específica agora exige duas ferramentas de cálculo matricial (Bishop, PRML, Apêndice C, p.&nbsp;698): a derivada do log-determinante,</p>
<p><span class="math display">\[\frac{\partial\ln|\Sigma_k|}{\partial\Sigma_k} = \Sigma_k^{-1} \qquad\text{(eq. C.28, válida para $\Sigma_k$ simétrica)},\]</span></p>
<p>e a derivada da inversa de uma matriz em relação a um de seus elementos,</p>
<p><span class="math display">\[\frac{\partial\,\Sigma_k^{-1}}{\partial(\Sigma_k)_{ij}} = -\Sigma_k^{-1}E_{ij}\Sigma_k^{-1} \qquad\text{(eq. C.21)},\]</span></p>
<p>onde <span class="math inline">\(E_{ij}\)</span> é a matriz com <span class="math inline">\(1\)</span> na posição <span class="math inline">\((i,j)\)</span> e <span class="math inline">\(0\)</span> no resto (a derivada de <span class="math inline">\(\Sigma_k\)</span> em relação ao seu próprio elemento <span class="math inline">\((i,j)\)</span>). Usando a propriedade cíclica do traço (<span class="math inline">\(\mathrm{tr}(ABC)=\mathrm{tr}(BCA)\)</span>, válida sempre que os produtos estão definidos) para reescrever a forma quadrática como um traço, <span class="math inline">\((\mathbf{x}-\mu_k)^T\Sigma_k^{-1}(\mathbf{x}-\mu_k)
= \mathrm{tr}\big(\Sigma_k^{-1}M\big)\)</span> com <span class="math inline">\(M=(\mathbf{x}-\mu_k)(\mathbf{x}-\mu_k)^T\)</span> (constante em relação a <span class="math inline">\(\Sigma_k\)</span>), a eq. C.21 dá, elemento a elemento,</p>
<p><span class="math display">\[\frac{\partial}{\partial(\Sigma_k)_{ij}}\mathrm{tr}(\Sigma_k^{-1}M) = \mathrm{tr}\Big({-}\Sigma_k^{-1}E_{ij}\Sigma_k^{-1}M\Big) = -\mathrm{tr}\big(E_{ij}\,\Sigma_k^{-1}M\Sigma_k^{-1}\big) = -\big[\Sigma_k^{-1}M\Sigma_k^{-1}\big]_{ji},\]</span></p>
<p>isto é, em forma matricial (usando que <span class="math inline">\(\Sigma_k^{-1}M\Sigma_k^{-1}\)</span> é simétrica, por <span class="math inline">\(\Sigma_k\)</span> e <span class="math inline">\(M\)</span> serem ambas simétricas), <span class="math inline">\(\partial\,\mathrm{tr}(\Sigma_k^{-1}M)/\partial\Sigma_k = -\Sigma_k^{-1}M\Sigma_k^{-1}\)</span>. Combinando os dois termos da log-densidade:</p>
<p><span class="math display">\[\frac{\partial\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k)}{\partial\Sigma_k} = -\frac12\Sigma_k^{-1} + \frac12\Sigma_k^{-1}(\mathbf{x}-\mu_k)(\mathbf{x}-\mu_k)^T\Sigma_k^{-1}.\]</span></p>
<p>Pela identidade geral, <span class="math inline">\(\partial \ln p(X\mid\pi,\mu,\Sigma)/\partial\Sigma_k\)</span> é essa expressão ponderada por <span class="math inline">\(\gamma(z_{nk})\)</span> e somada em <span class="math inline">\(n\)</span>; igualando a zero e multiplicando por <span class="math inline">\(\Sigma_k\)</span> dos dois lados:</p>
<p><span class="math display">\[\Sigma_k\sum_{n=1}^N\gamma(z_{nk}) = \sum_{n=1}^N\gamma(z_{nk})(\mathbf{x}_n-\mu_k)(\mathbf{x}_n-\mu_k)^T \;\Longrightarrow\; \Sigma_k = \frac{1}{N_k}\sum_{n=1}^N \gamma(z_{nk})\,(\mathbf{x}_n-\mu_k)(\mathbf{x}_n-\mu_k)^T.\]</span></p>
<p>Bishop (p.&nbsp;436), tradução livre:</p>
<blockquote class="blockquote">
<p>“[Essa expressão] tem a mesma forma que o resultado correspondente para uma única gaussiana ajustada ao conjunto de dados, mas novamente com cada ponto de dado ponderado pela probabilidade a posteriori correspondente.”</p>
</blockquote>
<p><strong>Atualização de <span class="math inline">\(\pi_k\)</span>.</strong> Maximizar em relação a <span class="math inline">\(\pi_k\)</span> precisa respeitar a restrição <span class="math inline">\(\sum_k \pi_k=1\)</span> — isso pede um multiplicador de Lagrange <span class="math inline">\(\lambda\)</span>, maximizando</p>
<p><span class="math display">\[\ln p(X\mid\pi,\mu,\Sigma) + \lambda\left(\sum_{k=1}^K \pi_k - 1\right).\]</span></p>
<p>Diferente de <span class="math inline">\(\mu_k\)</span> e <span class="math inline">\(\Sigma_k\)</span>, <span class="math inline">\(\pi_k\)</span> não é um parâmetro “escondido dentro” de uma única gaussiana — ele multiplica <span class="math inline">\(\mathcal{N}_k(\mathbf{x}_n)\)</span> inteira, de forma linear, então a derivada é mais direta. Só o termo <span class="math inline">\(j=k\)</span> da soma <span class="math inline">\(\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)\)</span> depende de <span class="math inline">\(\pi_k\)</span>, e depende linearmente dele, então</p>
<p><span class="math display">\[\frac{\partial}{\partial\pi_k}\ln\left(\sum_{j=1}^K\pi_j\mathcal{N}_j(\mathbf{x}_n)\right) = \frac{\mathcal{N}_k(\mathbf{x}_n)}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)}.\]</span></p>
<p>Derivando o Lagrangiano acima em relação a <span class="math inline">\(\pi_k\)</span> e igualando a zero:</p>
<p><span class="math display">\[0 = \sum_{n=1}^N \frac{\mathcal{N}_k(\mathbf{x}_n)}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)} + \lambda.\]</span></p>
<p>Multiplicando a equação inteira por <span class="math inline">\(\pi_k\)</span> — e notando que <span class="math inline">\(\pi_k\,\mathcal{N}_k(\mathbf{x}_n)/\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)\)</span> é, pela própria definição do Bloco 5, <span class="math inline">\(\gamma(z_{nk})\)</span>:</p>
<p><span class="math display">\[0 = \sum_{n=1}^N \gamma(z_{nk}) + \lambda\pi_k = N_k + \lambda\pi_k.\]</span></p>
<p>Somando essa equação sobre <span class="math inline">\(k=1,\dots,K\)</span>: à esquerda, <span class="math inline">\(\sum_k N_k=\sum_k\sum_n\gamma(z_{nk})=\sum_n\big(\sum_k\gamma(z_{nk})\big)=\sum_n 1=N\)</span> (as <span class="math inline">\(K\)</span> responsabilidades de cada paciente somam <span class="math inline">\(1\)</span>); à direita, <span class="math inline">\(\lambda\sum_k\pi_k=\lambda\)</span> (pela própria restrição <span class="math inline">\(\sum_k\pi_k=1\)</span>). Logo <span class="math inline">\(N+\lambda=0\Rightarrow\lambda=-N\)</span>. Substituindo de volta em <span class="math inline">\(N_k+\lambda\pi_k=0\)</span>:</p>
<p><span class="math display">\[N_k - N\pi_k = 0 \;\Longrightarrow\; \pi_k = \frac{N_k}{N}.\]</span></p>
<p>Bishop (p.&nbsp;436), tradução livre:</p>
<blockquote class="blockquote">
<p>“de forma que o coeficiente de mistura do <span class="math inline">\(k\)</span>-ésimo componente é dado pela responsabilidade média que aquele componente assume por explicar os pontos de dados.”</p>
</blockquote>
<p>Essa é uma leitura elegante: o peso de mistura de um componente não é “quantos pontos foram atribuídos a ele” (isso exigiria uma atribuição rígida) — é a <strong>soma das responsabilidades fracionárias</strong>, dividida por <span class="math inline">\(N\)</span>. Um componente que “convence” <span class="math inline">\(50\)</span> pacientes por completo e mais <span class="math inline">\(20\)</span> pacientes pela metade tem <span class="math inline">\(N_k=60\)</span>, não <span class="math inline">\(50\)</span> nem <span class="math inline">\(70\)</span>.</p>
<p><strong>Um ciclo, não uma solução.</strong> As três atualizações (<span class="math inline">\(\mu_k,\Sigma_k,\pi_k\)</span>) não formam, juntas, uma solução fechada, porque <span class="math inline">\(\gamma(z_{nk})\)</span> (Bloco 5) depende dos próprios parâmetros que este bloco acabou de reestimar. É exatamente por isso que o processo é iterativo: Passo E com os parâmetros atuais, Passo M com as responsabilidades atuais, repetir — o algoritmo <strong>EM</strong> completo, reunido no próximo bloco.</p>
</section>
<section id="o-algoritmo-em-completo-em-ação" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> O Algoritmo EM Completo, em Ação</h1>
<p>Juntando os Blocos 5 e 6 num ciclo, o algoritmo <strong>EM para Misturas Gaussianas</strong> (Bishop, PRML, 2006, p.&nbsp;438-439, resumido e traduzido) é:</p>
<ol type="1">
<li>Inicializar <span class="math inline">\(\mu_k\)</span>, <span class="math inline">\(\Sigma_k\)</span> e <span class="math inline">\(\pi_k\)</span> (por exemplo, a partir de um KMeans rodado antes, como o <code>sklearn</code> faz por padrão), e avaliar a log-verossimilhança inicial.</li>
<li><strong>Passo E.</strong> Calcular <span class="math inline">\(\gamma(z_{nk})\)</span> para todo <span class="math inline">\(n,k\)</span>, usando os valores correntes dos parâmetros (Bloco 5).</li>
<li><strong>Passo M.</strong> Reestimar <span class="math inline">\(\mu_k,\Sigma_k,\pi_k\)</span> usando as responsabilidades do Passo E (Bloco 6) — calculando primeiro <span class="math inline">\(\mu_k\)</span>, depois usando o novo <span class="math inline">\(\mu_k\)</span> para <span class="math inline">\(\Sigma_k\)</span>, na mesma ordem da Aula 1 para uma única gaussiana.</li>
<li>Avaliar a log-verossimilhança; se a mudança (nos parâmetros ou na verossimilhança) for menor que um limiar, parar; senão, voltar ao Passo E.</li>
</ol>
<p>Bishop (p.&nbsp;437) garante uma propriedade importante deste ciclo — tradução livre:</p>
<blockquote class="blockquote">
<p>“Cada atualização dos parâmetros resultante de um Passo E seguido de um Passo M tem a garantia de aumentar a função de log-verossimilhança.”</p>
</blockquote>
<p>Isso não garante o <strong>máximo global</strong> (lembrando o aviso de singularidades do Bloco 4) — só que cada rodada não piora. Na prática, o EM converge tipicamente para um máximo local razoável, e rodar algumas inicializações diferentes (o parâmetro <code>n_init</code> do <code>sklearn.mixture.GaussianMixture</code>) reduz o risco de parar num máximo local ruim.</p>
<p><strong>Ajustando de verdade.</strong> Aplicando <code>GaussianMixture(n_components=2)</code> aos mesmos dois atributos do Breast Cancer Wisconsin usados desde a Aula 3 (sem usar <code>diagnosis</code>), o EM converge para:</p>
<ul>
<li>Pesos de mistura: <span class="math inline">\(\pi\approx(0{,}637,\ 0{,}363)\)</span> — o componente majoritariamente benigno é responsável, em média, por <span class="math inline">\(\approx63{,}7\%\)</span> da “massa” de responsabilidade.</li>
<li>Componente <span class="math inline">\(0\)</span> (o mais benigno): <span class="math inline">\(349\)</span> dos <span class="math inline">\(372\)</span> pacientes com responsabilidade máxima ali são benignos (<span class="math inline">\(23\)</span> malignos) — comparável ao cluster de <span class="math inline">\(347\)</span> pacientes (<span class="math inline">\(90{,}8\%\)</span> benigno) da Aula 3.</li>
<li>Componente <span class="math inline">\(1\)</span> (o mais maligno): <span class="math inline">\(189\)</span> dos <span class="math inline">\(197\)</span> pacientes com responsabilidade máxima ali são malignos (<span class="math inline">\(8\)</span> benignos) — mais puro até que o cluster de <span class="math inline">\(54\)</span> pacientes <span class="math inline">\(100\%\)</span> malignos da Aula 3, mas cobrindo quase 4 vezes mais pacientes malignos (<span class="math inline">\(189\)</span> vs.&nbsp;<span class="math inline">\(54\)</span>).</li>
<li>Acurácia da atribuição rígida (argmax da responsabilidade) contra o diagnóstico real: <span class="math inline">\(94{,}55\%\)</span>. Índice de Rand Ajustado (ARI): <span class="math inline">\(0{,}792\)</span> — bem acima do ARI do HDBSCAN da Aula 3 (<span class="math inline">\(0{,}644\)</span> excluindo ruído, <span class="math inline">\(0{,}493\)</span> incluindo-o).</li>
</ul>
<p>A comparação de ARI é honesta, não injusta com o HDBSCAN: o GMM tem uma vantagem estrutural aqui — ele <strong>atribui todo mundo</strong> a algum componente (via argmax da responsabilidade), enquanto o HDBSCAN deliberadamente se recusa a decidir sobre <span class="math inline">\(168\)</span> pacientes (<span class="math inline">\(29{,}5\%\)</span> do total), tratando-os como ruído. Essa é exatamente a troca anunciada na Abertura: o GMM nunca fica “sem resposta”, ao custo de forçar uma resposta (mesmo que parcial, via responsabilidade) mesmo em regiões onde a evidência é genuinamente fraca.</p>
<p>A figura abaixo mostra o resultado completo: os <span class="math inline">\(569\)</span> pacientes coloridos pela mistura azul-laranja de responsabilidade (mesma convenção do Bloco 2), com as elipses de <span class="math inline">\(2\)</span> desvios-padrão de cada componente ajustado sobrepostas — a forma exata que <span class="math inline">\(\Sigma_0\)</span> e <span class="math inline">\(\Sigma_1\)</span> assumiram depois de convergir.</p>
<div class="fig-resize" style="width: 47%; margin: 0 auto;">
<div id="871b99d7" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Note como as elipses se <strong>sobrepõem</strong> numa faixa central — é exatamente essa região de sobreposição geométrica que produz os pacientes de responsabilidade ambígua do Bloco 5. Diferente do HDBSCAN, que desenharia uma fronteira única entre “dentro” e “fora” de cada componente conexo, o GMM não tem fronteira: a transição de cor é suave, proporcional a quão dentro de cada elipse (ponderada pela respectiva covariância) um ponto está.</p>
</section>
<section id="o-kmeans-e-sua-relação-com-o-gmm" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> O KMeans e Sua Relação com o GMM</h1>
<p>Falta responder a última pergunta do Roteiro: essa ideia nova é uma ferramenta completamente diferente do que já se conhece, ou generaliza algo já visto? A resposta é concreta: o <strong>KMeans</strong> é exatamente o que sobra do GMM quando duas premissas adicionais são impostas — mas a Aula 3 só citou o KMeans de passagem, como um dos três paradigmas de clustering do ESL (Bloco 3 daquela aula), sem detalhar o algoritmo em si. Antes de mostrar a equivalência, é preciso conhecer o que está sendo comparado.</p>
<p><strong>O objetivo do KMeans.</strong> Dado um conjunto de <span class="math inline">\(N\)</span> pontos <span class="math inline">\(\mathbf{x}_1,\dots,\mathbf{x}_N\)</span> e um número fixo <span class="math inline">\(K\)</span> de clusters, o KMeans busca <span class="math inline">\(K\)</span> vetores protótipo <span class="math inline">\(\mu_1,\dots,\mu_K\)</span> (os centróides) e uma atribuição de cada ponto a exatamente um deles, de forma a minimizar a soma das distâncias ao quadrado entre cada ponto e o centróide ao qual foi atribuído. Para formalizar “atribuição”, define-se a variável indicadora</p>
<p><span class="math display">\[r_{nk} \in \{0,1\}, \qquad \sum_{k=1}^K r_{nk}=1 \text{ para todo } n\]</span></p>
<p>— a mesma ideia de codificação 1-de-<span class="math inline">\(K\)</span> usada para <span class="math inline">\(z_{nk}\)</span> no Bloco 3, só que aqui <strong>rígida e determinística</strong>, não uma variável latente aleatória. Bishop (PRML, 2006, p.&nbsp;424) define a medida de distorção que o KMeans minimiza — tradução livre:</p>
<blockquote class="blockquote">
<p>“[…] uma função objetivo, às vezes chamada de medida de distorção, dada por <span class="math inline">\(J=\sum_{n=1}^N\sum_{k=1}^K r_{nk}\|\mathbf{x}_n-\mu_k\|^2\)</span>, que representa a soma dos quadrados das distâncias de cada ponto de dado ao seu vetor <span class="math inline">\(\mu_k\)</span> atribuído.”</p>
</blockquote>
<p><span class="math display">\[J = \sum_{n=1}^N \sum_{k=1}^K r_{nk} \|\mathbf{x}_n - \mu_k\|^2.\]</span></p>
<p><strong>O algoritmo: dois passos alternados.</strong> <span class="math inline">\(J\)</span> depende de duas famílias de variáveis, <span class="math inline">\(\{r_{nk}\}\)</span> e <span class="math inline">\(\{\mu_k\}\)</span>, e minimizar as duas ao mesmo tempo não tem solução direta — mas, exatamente como será o caso do EM (Blocos 5 e 6), fixar uma família de cada vez torna cada subproblema tratável, e Bishop nomeia essas duas fases justamente de “passo E” e “passo M” do KMeans, para prefigurar o paralelo.</p>
<p>Fixando <span class="math inline">\(\mu_k\)</span> e minimizando <span class="math inline">\(J\)</span> sobre <span class="math inline">\(r_{nk}\)</span>: como <span class="math inline">\(J\)</span> é <strong>linear</strong> em cada <span class="math inline">\(r_{nk}\)</span> (nenhum produto <span class="math inline">\(r_{nk}r_{n'k'}\)</span> aparece na soma) e os termos de pacientes diferentes são independentes entre si, cada <span class="math inline">\(n\)</span> pode ser otimizado sozinho — a soma <span class="math inline">\(\sum_k r_{nk}\|\mathbf{x}_n-\mu_k\|^2\)</span> é minimizada colocando o único <span class="math inline">\(r_{nk}=1\)</span> no índice <span class="math inline">\(k\)</span> que dá o menor <span class="math inline">\(\|\mathbf{x}_n-\mu_k\|^2\)</span> (qualquer outra escolha soma um termo maior ou igual). Isso é exatamente (Bishop, PRML, eq. 9.2, p.&nbsp;425):</p>
<p><span class="math display">\[r_{nk} = \begin{cases}1 &amp; \text{se } k=\displaystyle\arg\min_j \|\mathbf{x}_n-\mu_j\|^2 \\ 0 &amp; \text{caso contrário,}\end{cases}\]</span></p>
<p>ou seja: <strong>atribua cada ponto ao centróide mais próximo</strong>.</p>
<p>Fixando <span class="math inline">\(r_{nk}\)</span> e minimizando <span class="math inline">\(J\)</span> sobre <span class="math inline">\(\mu_k\)</span>: para um componente <span class="math inline">\(k\)</span> fixo, só os termos com <span class="math inline">\(r_{nk}=1\)</span> dependem de <span class="math inline">\(\mu_k\)</span>, e cada um é uma forma quadrática em <span class="math inline">\(\mu_k\)</span>. Derivando essa soma em relação a <span class="math inline">\(\mu_k\)</span> (regra da cadeia sobre <span class="math inline">\(\|\mathbf{x}_n-\mu_k\|^2=(\mathbf{x}_n-\mu_k)^T(\mathbf{x}_n-\mu_k)\)</span>, cuja derivada em <span class="math inline">\(\mu_k\)</span> é <span class="math inline">\(-2(\mathbf{x}_n-\mu_k)\)</span>):</p>
<p><span class="math display">\[\frac{\partial J}{\partial \mu_k} = \sum_{n=1}^N r_{nk}\cdot\big({-2}\big)(\mathbf{x}_n-\mu_k).\]</span></p>
<p>Igualando a zero (Bishop, eq. 9.3, p.&nbsp;425) e isolando <span class="math inline">\(\mu_k\)</span> (eq. 9.4):</p>
<p><span class="math display">\[2\sum_{n=1}^N r_{nk}(\mathbf{x}_n-\mu_k)=0 \;\Longrightarrow\; \sum_n r_{nk}\mathbf{x}_n = \mu_k\sum_n r_{nk} \;\Longrightarrow\; \mu_k = \frac{\sum_n r_{nk}\,\mathbf{x}_n}{\sum_n r_{nk}}\]</span></p>
<p>— o novo centróide <span class="math inline">\(\mu_k\)</span> é simplesmente a <strong>média dos pontos atualmente atribuídos a ele</strong> (o denominador conta quantos pontos isso é). Compare com a atualização de <span class="math inline">\(\mu_k\)</span> do GMM (Bloco 6): a mesma estrutura de “média ponderada pela atribuição”, só que lá o peso é a responsabilidade fracionária <span class="math inline">\(\gamma(z_{nk})\in[0,1]\)</span>, aqui é o indicador rígido <span class="math inline">\(r_{nk}\in\{0,1\}\)</span>.</p>
<p><strong>Convergência por iteração.</strong> Cada uma das duas fases resolve exatamente seu subproblema de minimização, então nenhuma pode aumentar <span class="math inline">\(J\)</span> — alternar as duas até que <span class="math inline">\(r_{nk}\)</span> pare de mudar garante que <span class="math inline">\(J\)</span> converge (Bishop, p.&nbsp;425), embora possivelmente para um mínimo local, não o global. Por isso o ajuste abaixo usa <code>n_init=10</code>: repetir o algoritmo inteiro a partir de <span class="math inline">\(10\)</span> conjuntos de centróides iniciais diferentes, e manter o resultado de menor <span class="math inline">\(J\)</span> final.</p>
<div class="fig-resize" style="width: 78%; margin: 0 auto;">
<div id="07eda3a3" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>A diferença salta aos olhos. O KMeans (painel esquerdo) corta o espaço em duas regiões de <strong>fronteira reta</strong> — a mediatriz entre os dois centróides, já que qualquer tesselação por distância euclidiana a um conjunto de protótipos produz fronteiras retas entre vizinhos — e cada paciente pertence a exatamente uma delas, sem gradação nenhuma. O GMM (painel direito, o mesmo ajuste do Bloco 7) produz uma transição de cor suave, com uma faixa inteira de pacientes em tons intermediários — exatamente os pacientes ambíguos já identificados no Bloco 5. O KMeans nunca representa incerteza sobre a origem de um ponto: decide sempre, mesmo quando a decisão está quase empatada.</p>
<p>Essa diferença visual é a pista de que os dois métodos não são incomparáveis — o KMeans parece um GMM que <strong>perdeu a capacidade de hesitar</strong>. A próxima pergunta é: sob que condições precisas essa hesitação desaparece?</p>
<p><strong>Premissas deste resultado.</strong> (1) Todas as covariâncias são <strong>esféricas e idênticas</strong> entre componentes: <span class="math inline">\(\Sigma_k=\epsilon I\)</span> para todo <span class="math inline">\(k\)</span>, onde <span class="math inline">\(\epsilon\)</span> é um único parâmetro de variância compartilhado — não <span class="math inline">\(K\)</span> matrizes <span class="math inline">\(\Sigma_k\)</span> livres. (2) <span class="math inline">\(\epsilon\)</span> é tratado como uma <strong>constante fixa</strong>, não reestimada pelo Passo M — só <span class="math inline">\(\pi_k\)</span> e <span class="math inline">\(\mu_k\)</span> continuam sendo ajustados. Sob essas duas premissas, a densidade de cada componente é</p>
<p><span class="math display">\[p(\mathbf{x}\mid\mu_k,\Sigma_k) = \frac{1}{(2\pi\epsilon)^{D/2}}\exp\left\{-\frac{1}{2\epsilon}\|\mathbf{x}-\mu_k\|^2\right\},\]</span></p>
<p>e a responsabilidade (Bloco 5) se reduz a</p>
<p><span class="math display">\[\gamma(z_{nk}) = \frac{\pi_k\exp\{-\|\mathbf{x}_n-\mu_k\|^2/2\epsilon\}}{\sum_j \pi_j\exp\{-\|\mathbf{x}_n-\mu_j\|^2/2\epsilon\}}.\]</span></p>
<p><strong>O limite <span class="math inline">\(\epsilon\to 0\)</span>.</strong> Bishop (PRML, 2006, p.&nbsp;443-444) trabalha esse limite diretamente — tradução livre:</p>
<blockquote class="blockquote">
<p>“Consideremos um modelo de mistura gaussiana no qual as matrizes de covariância dos componentes da mistura são dadas por <span class="math inline">\(\epsilon I\)</span>, onde <span class="math inline">\(\epsilon\)</span> é um parâmetro de variância compartilhado por todos os componentes […] Tratamos <span class="math inline">\(\epsilon\)</span> como uma constante fixa, em vez de um parâmetro a ser reestimado.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“Se considerarmos o limite <span class="math inline">\(\epsilon\to 0\)</span>, veremos que, no denominador, o termo para o qual <span class="math inline">\(\|\mathbf{x}_n-\mu_j\|^2\)</span> é o menor tenderá a zero mais lentamente, e portanto as responsabilidades <span class="math inline">\(\gamma(z_{nk})\)</span> para o ponto de dado <span class="math inline">\(\mathbf{x}_n\)</span> tenderão todas a zero, exceto para o termo <span class="math inline">\(j\)</span>, para o qual a responsabilidade <span class="math inline">\(\gamma(z_{nj})\)</span> tenderá a um. […] Assim, nesse limite, obtemos uma atribuição rígida dos pontos de dados aos clusters, exatamente como no algoritmo KMeans.”</p>
</blockquote>
<p>A intuição por trás da matemática: com <span class="math inline">\(\epsilon\)</span> minúsculo, o termo <span class="math inline">\(\exp\{-\|\mathbf{x}_n-\mu_j\|^2/2\epsilon\}\)</span> do componente <strong>mais próximo</strong> de <span class="math inline">\(\mathbf{x}_n\)</span> domina exponencialmente todos os outros — a diferença de distância ao quadrado, dividida por um <span class="math inline">\(\epsilon\)</span> minúsculo, vira uma diferença enorme dentro da exponencial, e o componente perdedor é esmagado a zero relativo. Isso vale <strong>independentemente</strong> dos valores de <span class="math inline">\(\pi_k\)</span> (desde que nenhum seja exatamente zero) — o peso de mistura não consegue competir com uma exponencial indo a zero.</p>
<p><strong>A atualização de <span class="math inline">\(\mu_k\)</span> também converge.</strong> Bishop (p.&nbsp;444) continua:</p>
<blockquote class="blockquote">
<p>“A equação de reestimação do EM para os <span class="math inline">\(\mu_k\)</span> […] então se reduz ao resultado do KMeans […] a expectativa da log-verossimilhança de dados completos […] se torna <span class="math inline">\(-\dfrac{1}{2}\sum_n\sum_k r_{nk}\|\mathbf{x}_n-\mu_k\|^2 + \text{const}\)</span>. Assim vemos que, nesse limite, maximizar a log-verossimilhança esperada de dados completos é equivalente a minimizar a medida de distorção <span class="math inline">\(J\)</span> do algoritmo KMeans.”</p>
</blockquote>
<p>Ou seja: no limite <span class="math inline">\(\epsilon\to 0\)</span>, a atualização ponderada <span class="math inline">\(\mu_k=\dfrac{1}{N_k}\sum_n\gamma(z_{nk})\mathbf{x}_n\)</span> do Bloco 6 se reduz exatamente à média do KMeans <span class="math inline">\(\mu_k=\dfrac{\sum_n r_{nk}\mathbf{x}_n}{\sum_n
r_{nk}}\)</span> (Aula 3, Bloco 2), porque <span class="math inline">\(\gamma(z_{nk})\to r_{nk}\in\{0,1\}\)</span>. E o objetivo que o EM está implicitamente maximizando converge para exatamente <span class="math inline">\(-J/2\)</span> (a menos de uma constante), onde <span class="math inline">\(J\)</span> é a medida de distorção do KMeans. O KMeans não é uma ferramenta diferente — é o <strong>GMM com as mãos amarradas</strong>: covariância travada, esférica, compartilhada, e levada a zero.</p>
<p><strong>Verificação numérica própria.</strong> Para tornar esse limite tangível, tome as <span class="math inline">\(2\)</span> médias do KMeans ajustado ao Breast Cancer Wisconsin como referência (<span class="math inline">\(\mu_1,\mu_2\)</span> fixos) e calcule a responsabilidade <span class="math inline">\(\gamma(z_{nk})\)</span> pela fórmula acima, para três valores decrescentes de <span class="math inline">\(\epsilon\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\epsilon\)</span></th>
<th>Responsabilidade média máxima</th>
<th>Acurácia da atribuição rígida vs.&nbsp;KMeans</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(1{,}0\)</span></td>
<td><span class="math inline">\(0{,}904\)</span></td>
<td><span class="math inline">\(95{,}78\%\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0{,}1\)</span></td>
<td><span class="math inline">\(0{,}9916\)</span></td>
<td><span class="math inline">\(99{,}30\%\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0{,}01\)</span></td>
<td><span class="math inline">\(0{,}9996\)</span></td>
<td><span class="math inline">\(100{,}00\%\)</span></td>
</tr>
</tbody>
</table>
<p>Conforme <span class="math inline">\(\epsilon\)</span> cai, a responsabilidade média máxima sobe em direção a <span class="math inline">\(1\)</span> (atribuição cada vez mais rígida) e a concordância entre a atribuição por argmax e o KMeans de referência sobe até <span class="math inline">\(100\%\)</span> — exatamente o comportamento previsto pela derivação acima, confirmado numericamente, não só afirmado.</p>
<p><strong>O que o KMeans perde ao ganhar simplicidade.</strong> Bishop (p.&nbsp;444) nota uma consequência importante:</p>
<blockquote class="blockquote">
<p>“Note que o algoritmo KMeans não estima as covariâncias dos clusters, apenas as médias dos clusters.”</p>
</blockquote>
<p>Isso é o preço da premissa (1): ao forçar <span class="math inline">\(\Sigma_k=\epsilon I\)</span> igual para todos os componentes, o KMeans perde a capacidade de representar clusters com formatos, orientações ou espalhamentos diferentes entre si — a elipse do componente maligno do Bloco 7, mais alongada e maior que a do benigno, simplesmente não existiria sob KMeans; ambos os clusters seriam forçados a “bolas” circulares do mesmo tamanho. Uma versão de atribuição rígida que mantém covariâncias gerais por componente existe (o <em>elliptical K-means</em>, citado por Bishop a partir de Sung &amp; Poggio, 1994), mas isso já é um meio-termo entre KMeans puro e GMM completo, não coberto nesta aula.</p>
<div class="fig-resize" style="width: 85%; margin: 0 auto;">
<div id="cf2734ed" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Da esquerda para a direita, a transição de cor entre azul e laranja fica cada vez mais <strong>abrupta</strong> — quase toda a área do gráfico já é azul sólido ou laranja sólido em <span class="math inline">\(\epsilon=0{,}01\)</span>, com uma fronteira fina exatamente onde o KMeans traçaria sua bissetriz perpendicular entre os dois centróides.</p>
<section id="pergunta-3" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="pergunta-3"><span class="header-section-number">8.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O KMeans, no limite <span class="math inline">\(\epsilon\to 0\)</span>, não estima covariância nenhuma — só médias. Isso significa que um GMM com covariâncias esféricas gerais (não travadas em <span class="math inline">\(\epsilon\)</span> fixo) é sempre estritamente melhor que o KMeans para qualquer conjunto de dados?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que “melhor” significaria aqui — ajuste mais fiel à verossimilhança dos dados observados, ou algum outro critério prático (velocidade, interpretabilidade, robustez a pouco dado).</p>
<ul>
<li>□ Um GMM com covariâncias livres tem mais parâmetros a estimar do que o KMeans (que só estima médias) — com poucos dados por cluster, isso pode fazer o GMM overfitar a covariância, enquanto o KMeans, mais restrito, generalizaria melhor.</li>
<li>□ Se os clusters verdadeiros nos dados tiverem, de fato, covariâncias esféricas idênticas entre si, o GMM completo, ao convergir, deve recuperar covariâncias estimadas próximas dessa forma esférica comum — e nesse cenário específico, a vantagem prática do GMM sobre o KMeans se estreita.</li>
<li>□ Um cluster alongado (covariância muito diferente entre duas direções) é sempre mais bem representado pelo GMM do que pelo KMeans, porque o GMM pode orientar e esticar a elipse; o KMeans, restrito a bolas circulares de mesmo tamanho, cortaria esse cluster de forma artificial se ele fizer fronteira com outro.</li>
<li>□ Como o KMeans é matematicamente um caso particular do GMM, o KMeans nunca pode convergir mais rápido (em menos iterações até estabilizar) do que o GMM completo no mesmo conjunto de dados.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="fechamento-e-ponte-para-a-aula-5" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Fechamento e Ponte para a Aula 5</h1>
<p>Retomando as quatro perguntas da Abertura, uma frase cada:</p>
<ol type="1">
<li><strong>O que significa “nascer de uma população desconhecida”?</strong> Uma variável latente categórica <span class="math inline">\(z\)</span>, 1-de-<span class="math inline">\(K\)</span>, com prior <span class="math inline">\(\pi_k\)</span> — o ponto observado <span class="math inline">\(\mathbf{x}\)</span> vem de <span class="math inline">\(\mathcal{N}(\mu_k,\Sigma_k)\)</span> para o <span class="math inline">\(k\)</span> sorteado, mas <span class="math inline">\(k\)</span> nunca é visto.</li>
<li><strong>Como transformar a incerteza numa probabilidade concreta?</strong> Bayes — a responsabilidade <span class="math inline">\(\gamma(z_{nk})\)</span>, calculada no Passo E a partir dos parâmetros correntes.</li>
<li><strong>Como reajustar os parâmetros, e por que iterar?</strong> MLE ponderada pelas responsabilidades (Passo M) — <span class="math inline">\(\mu_k,\Sigma_k,\pi_k\)</span> não têm solução fechada porque dependem de <span class="math inline">\(\gamma\)</span>, que depende deles; por isso EM alterna E e M até convergir, cada rodada garantidamente não piorando a log-verossimilhança.</li>
<li><strong>Isso generaliza o KMeans, ou é outra coisa?</strong> Generaliza: KMeans é o GMM com covariâncias esféricas, idênticas, e levadas a <span class="math inline">\(\epsilon\to 0\)</span> — verificado tanto analiticamente (PRML) quanto numericamente (Bloco 8).</li>
</ol>
<p><strong>O que fica em aberto.</strong> O GMM resolve o problema da atribuição rígida, mas introduz um problema novo, silenciosamente adiado ao longo de toda esta aula: em nenhum momento se discutiu <strong>como escolher <span class="math inline">\(K\)</span></strong>, o número de componentes — foi sempre fixado em <span class="math inline">\(2\)</span>, escolhido porque já se sabia (do rótulo <code>diagnosis</code>, usado só para <em>avaliar</em>, nunca para ajustar) que fazia sentido nesse dataset. Em um problema real de verdade, sem rótulo nenhum, <span class="math inline">\(K\)</span> é uma escolha aberta — e o instinto óbvio, “escolher <span class="math inline">\(K\)</span> que maximiza a log-verossimilhança”, falha: aumentar <span class="math inline">\(K\)</span> sempre pode aumentar (ou no mínimo não piorar) a verossimilhança, no limite ajustando um componente minúsculo a cada ponto individual — o mesmo problema de <em>overfitting</em> já anunciado como singularidade no Bloco 4, agora em escala maior.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Ponte para a Aula 5
</div>
</div>
<div class="callout-body-container callout-body">
<p>A Aula 5 ataca exatamente essa lacuna: <strong>como escolher <span class="math inline">\(K\)</span></strong> sem cair no overfitting da pura verossimilhança. A resposta começa mostrando por que o próprio Algoritmo EM desta aula, do jeito que foi apresentado — sem nenhuma priori sobre <span class="math inline">\(\theta\)</span> —, não pode penalizar complexidade por construção; a correção introduz a divergência de <strong>Kullback-Leibler</strong> e uma decomposição geral que, tratando <span class="math inline">\(\theta\)</span> como variável (não como ponto fixo) com uma priori de verdade, produz o <strong>ELBO</strong> com uma penalidade de complexidade genuína (a Navalha de Occam). Como isso troca “escolher <span class="math inline">\(K\)</span>” por “calibrar hiperparâmetros de priori”, a Aula 5 também desenvolve formas de <strong>validação empírica</strong> — testar a estrutura escolhida em dados nunca vistos no ajuste — para quando não existe via analítica disponível, como no K-Means.</p>
</div>
</div>
<p><a href="../../../teaching/unsupervised-learning/aula04/exercicios.html" class="see-all exercicios-link" aria-label="Ver exercícios" title="Ver exercícios">Exercícios</a> <a href="../../../teaching/unsupervised-learning/aula04/soluções.html" class="see-all solucoes-link" aria-label="Ver soluções" title="Ver soluções">Soluções</a></p>
<section id="pergunta-4" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="pergunta-4"><span class="header-section-number">9.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se, em vez de fixar <span class="math inline">\(K=2\)</span>, alguém rodasse o GMM desta aula com <span class="math inline">\(K=10\)</span> no mesmo par de atributos do Breast Cancer Wisconsin, o que aconteceria com a log-verossimilhança final, comparada à obtida com <span class="math inline">\(K=2\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se adicionar componentes pode, na pior das hipóteses, só “copiar” o comportamento de uma solução com menos componentes (por exemplo, atribuindo peso <span class="math inline">\(\pi_k\approx0\)</span> a componentes extras) — e o que isso implica sobre a direção da mudança na verossimilhança.</p>
<ul>
<li>□ A log-verossimilhança ótima obtida com <span class="math inline">\(K=10\)</span> nunca pode ser pior (menor) do que a obtida com <span class="math inline">\(K=2\)</span>, porque qualquer solução de <span class="math inline">\(K=2\)</span> pode ser reproduzida com <span class="math inline">\(K=10\)</span> atribuindo peso <span class="math inline">\(\pi_k\approx0\)</span> aos <span class="math inline">\(8\)</span> componentes extras.</li>
<li>□ Escolher o valor de <span class="math inline">\(K\)</span> que maximiza a log-verossimilhança nos dados de treino é, por esse motivo, um critério confiável para encontrar o número “certo” de componentes.</li>
<li>□ O mesmo tipo de problema (mais parâmetros sempre ajustando melhor aos dados observados, sem necessariamente generalizar melhor) já apareceu nesta disciplina antes desta aula, embora em outro contexto matemático.</li>
<li>□ Se um dos <span class="math inline">\(10\)</span> componentes colapsar sua covariância sobre um único ponto de dado (a singularidade do Bloco 4), isso tornaria a log-verossimilhança bem definida, porém artificialmente baixa.</li>
</ul>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>