<!DOCTYPE html>
<html lang="pt-BR"><head>
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">
  <meta name="dcterms.date" content="2026-09-07">
  <title>Marcos M. Raimundo – Aula 4: Modelos de Mistura Gaussiana e o Algoritmo EM</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-9af0d15343d0ec36e497a4ab60ddbc72.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- O tema "simple" do RevealJS não carrega bootstrap-icons.css sozinho
       (isso só acontece no formato HTML, via bootstrap) — sem este link, um
       ícone `<i class="bi bi-...">` usado em qualquer include do RevealJS
       (ex.: ../../logos-footer.html) fica invisível nos slides. Caminho
       relativo à página de SAÍDA (aulaNN/slides.html), não a este arquivo:
       site_libs/ mora na raiz do site, três níveis acima de aulaNN/. -->
  <link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="../../UNICAMP.png, ../../IC.png" data-background-position="5% 8%, 95% 8%" data-background-size="140px, 140px" class="quarto-title-block center">
  <h1 class="title">Aula 4: Modelos de Mistura Gaussiana e o Algoritmo EM</h1>
  <p class="subtitle">Aprendizado Não Supervisionado</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Marcos M. Raimundo — Instituto de Computação, UNICAMP 
</div>
</div>
</div>

  <p class="date">2026-09-07</p>
</section>
<section>
<section id="revisão-e-introdução" class="title-slide slide level1 center">
<h1>Revisão e Introdução</h1>

</section>
<section id="da-aula-3-o-que-já-temos" class="slide level2">
<h2>Da Aula 3: O Que Já Temos</h2>
<div class="fragment">
<p><strong>Cluster</strong> = componente conexa de <span class="math inline">\(L_\lambda=\{\mathbf{x}:p(\mathbf{x})
\ge\lambda\}\)</span>. Construído via <span class="math inline">\(d_{\mathrm{mreach}}\)</span> + MST + persistência na árvore condensada — o <strong>HDBSCAN</strong>.</p>
</div>
<div class="fragment">
<p>No Breast Cancer Wisconsin (<code>radius_worst</code>/<code>concave points_worst</code>, sem rótulo): <span class="math inline">\(54\)</span> pacientes <span class="math inline">\(100\%\)</span> malignos num cluster; <span class="math inline">\(347\)</span> <span class="math inline">\(\approx90{,}8\%\)</span> benignos noutro; <span class="math inline">\(168\)</span> (<span class="math inline">\(\approx29{,}5\%\)</span>) viram <strong>ruído</strong>. ARI <span class="math inline">\(=0{,}644\)</span> (excl. ruído) / <span class="math inline">\(0{,}493\)</span> (incl.&nbsp;ruído).</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Limitação estrutural: o HDBSCAN entrega uma <strong>partição rígida</strong> — cada paciente é de um cluster, ou é ruído. Sem meio-termo.</p>
</div>
</div>
</div>
</div>
</section>
<section id="ideia-central-1" class="slide level2">
<h2>Ideia Central</h2>
<div class="fragment">
<p>Rigidez é uma escolha do método, não um fato necessário sobre os dados. Se duas populações se sobrepõem numa faixa contínua — sem vale de densidade genuíno — forçar um rótulo único esconde informação real.</p>
</div>
<div class="fragment">
<p>Troca proposta: em vez de “a qual cluster pertence?”, perguntar <strong>“com que probabilidade pertence a cada cluster?”</strong> Mesma tarefa, resposta relaxada.</p>
</div>
</section>
<section id="roteiro-da-aula-1" class="slide level2">
<h2>Roteiro da Aula</h2>
<div class="fragment">
<p><strong>1.</strong> O que significa “nascer de uma entre <span class="math inline">\(K\)</span> populações”, sem saber qual?</p>
</div>
<div class="fragment">
<p><strong>2.</strong> Como transformar essa incerteza numa probabilidade concreta por ponto?</p>
</div>
<div class="fragment">
<p><strong>3.</strong> Como usar essas probabilidades para reajustar os parâmetros do modelo — por que isso é iterativo?</p>
</div>
<div class="fragment">
<p><strong>4.</strong> Isso generaliza o KMeans já conhecido, ou é outra coisa?</p>
</div>
</section>
<section id="problema-motivador-1" class="slide level2">
<h2>Problema Motivador</h2>
<div class="fragment">
<p>Dos <span class="math inline">\(168\)</span> pacientes marcados como <strong>ruído</strong> na Aula 3, <span class="math inline">\(126\)</span> eram malignos e <span class="math inline">\(42\)</span> benignos — o HDBSCAN não tem vocabulário para dizer mais nada sobre eles.</p>
</div>
<div class="fragment">
<p>E se, em vez de “ruído”, cada um recebesse <strong>dois números</strong>: a probabilidade de vir do grupo mais maligno, e a de vir do mais benigno, somando <span class="math inline">\(1\)</span>? É exatamente o que o <strong>GMM</strong> produz — construído do zero a partir daqui.</p>
</div>
</section>
<section id="pergunta" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Um paciente marcado como ruído pelo HDBSCAN não pertence a nenhuma componente conexa de alta densidade nos dois atributos usados. Isso significa que ele é igualmente parecido com as duas populações (benigna e maligna), ou pode significar outra coisa?</strong></p>
</div>
<div class="callout-content">
<ul>
<li>□ Um paciente marcado como ruído pode, sob um modelo de mistura gaussiana ajustado aos mesmos dados, receber uma responsabilidade bem próxima de <span class="math inline">\(1\)</span> para um único componente — “estar num vale geométrico local” e “ter atribuição probabilística ambígua sob um modelo global” não são a mesma coisa.</li>
<li>□ Se um paciente recebe responsabilidade exatamente <span class="math inline">\(0{,}5\)</span> para cada um dos dois componentes de um GMM, isso implica necessariamente que ele está geometricamente equidistante das duas médias <span class="math inline">\(\mu_1\)</span> e <span class="math inline">\(\mu_2\)</span> na distância euclidiana bruta.</li>
<li>□ Se as duas populações gaussianas subjacentes tivessem exatamente a mesma média e a mesma matriz de covariância (colapsando numa única gaussiana), a responsabilidade de qualquer ponto para cada componente seria exatamente <span class="math inline">\(\pi_k\)</span> (o peso de mistura), independente da posição do ponto.</li>
<li>□ Numa aplicação de perfil de consumo em que um cliente compra tanto itens “econômicos” quanto “premium” em proporções parecidas, um GMM ajustado ao histórico de gastos tenderia a atribuir a esse cliente responsabilidades intermediárias a ambos os segmentos, enquanto uma regra de corte único baseada em densidade local tenderia a isolá-lo como ruído ou a forçá-lo para um segmento só.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resposta — ruído do HDBSCAN vs.&nbsp;ambiguidade do GMM</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Vale geométrico local <span class="math inline">\(\ne\)</span> ambiguidade probabilística global — um ponto pode escapar da densidade local exigida pelo HDBSCAN e, ainda assim, ficar claramente mais próximo de um componente sob o GMM.</li>
<li>✗ Responsabilidade <span class="math inline">\(0{,}5/0{,}5\)</span> depende da densidade ponderada por <span class="math inline">\(\pi_k\)</span> e <span class="math inline">\(\Sigma_k\)</span>, não só da distância euclidiana bruta às médias — covariâncias ou pesos diferentes deslocam o ponto de equilíbrio.</li>
<li>✔ Com densidades idênticas nos dois componentes, o termo de densidade cancela na razão de Bayes, sobrando só <span class="math inline">\(\pi_k\)</span> — verdade para qualquer <span class="math inline">\(\mathbf{x}\)</span>.</li>
<li>✔ A mesma lógica de “sobreposição contínua pede resposta contínua” transfere para qualquer domínio com segmentos que se misturam, não só para pacientes.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> os dois métodos respondem perguntas diferentes — um mede densidade local geométrica, o outro mede probabilidade sob um modelo global. O resto da aula constrói esse segundo modelo.</p>
</div>
</section></section>
<section>
<section id="intuição-duas-nuvens" class="title-slide slide level1 center">
<h1>Intuição — Duas Nuvens</h1>

</section>
<section id="o-resultado-final-antes-da-matemática" class="slide level2">
<h2>O Resultado Final, Antes da Matemática</h2>
<div class="fragment">
<p>Mesmos <span class="math inline">\(569\)</span> pacientes, mesmos dois atributos padronizados (<code>radius_worst</code>, <code>concave points_worst</code>) da Aula 3.</p>
</div>
<div class="fragment">
<p><strong>Esquerda:</strong> HDBSCAN — cor sólida por ponto (azul/laranja/vermelho para ruído).</p>
</div>
<div class="fragment">
<p><strong>Direita:</strong> GMM com <span class="math inline">\(2\)</span> componentes — cor <strong>misturada</strong>, interpolada por probabilidade de pertencimento; mais roxo = mais ambíguo.</p>
</div>
<div class="fig-resize" style="width: 70%; margin: 0 auto;">
<div id="0c38c86c" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="duas-diferenças-estruturais" class="slide level2">
<h2>Duas Diferenças Estruturais</h2>
<div class="fragment">
<p><strong>GMM nunca descarta ninguém</strong> — os <span class="math inline">\(168\)</span> pacientes que viraram ruído na Aula 3 aparecem à direita com uma cor, ambígua ou não.</p>
</div>
<div class="fragment">
<p><strong>Cor não é binária</strong> — gradiente contínuo azul↔︎laranja; os <span class="math inline">\(9\)</span> pacientes circulados (responsabilidade <span class="math inline">\(\approx0{,}5/0{,}5\)</span>) são sobreposição real, não confusão do algoritmo.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Ambiguidade vira uma <strong>quantidade calculável</strong> — um número por componente, somando <span class="math inline">\(1\)</span> por paciente. Falta nomear de onde vem, e como o modelo (posição/formato das nuvens) é ajustado — Blocos 3 a 6.</p>
</div>
</div>
</div>
</div>
</section>
<section id="pergunta-1" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Os 9 pacientes circulados no painel direito têm responsabilidade próxima de 50/50. Isso significa que o modelo “não sabe nada” sobre eles, no mesmo sentido em que uma moeda não viciada “não sabe” se vai dar cara ou coroa?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense na diferença entre “incerteza sobre um evento futuro aleatório” (a moeda) e “incerteza sobre um fato já determinado, mas desconhecido” (a origem populacional de um paciente que já existe).</p>
<ul>
<li>□ A responsabilidade <span class="math inline">\(50/50\)</span> de um paciente reflete a melhor estimativa do modelo sobre um fato <strong>já fixado</strong> (o paciente pertence, de fato, a uma população só) — diferente da moeda, cujo resultado ainda não existe no momento da previsão.</li>
<li>□ Aumentar o número de atributos usados no ajuste do GMM (de <span class="math inline">\(2\)</span> para, digamos, <span class="math inline">\(10\)</span>) necessariamente reduziria a responsabilidade ambígua desses <span class="math inline">\(9\)</span> pacientes específicos, porque mais informação sempre reduz ambiguidade estatística em qualquer situação.</li>
<li>□ Um paciente com responsabilidade <span class="math inline">\(50/50\)</span> contribui, no Passo M (ainda não visto), com metade do seu peso para a reestimação de cada um dos dois componentes — ele não é ignorado, é dividido.</li>
<li>□ Se o GMM verdadeiro subjacente aos dados tivesse apenas <span class="math inline">\(1\)</span> componente (não <span class="math inline">\(2\)</span>), esperaríamos ver muito mais pacientes com responsabilidade próxima de <span class="math inline">\(50/50\)</span> do que os <span class="math inline">\(9\)</span> observados aqui.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-1" class="slide level2 scrollable">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resposta — o que significa responsabilidade 50/50</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ É incerteza sobre um fato já determinado (de qual população o paciente veio), não sobre um evento aleatório futuro — a moeda é uma analogia imperfeita.</li>
<li>✗ Mais atributos não garante menos ambiguidade para pontos específicos — pode até aumentar (maldição da dimensionalidade, Aula
<ol start="2" type="1">
<li>ou revelar que a sobreposição é real em mais dimensões também.</li>
</ol></li>
<li>✔ Responsabilidade fracionária = peso fracionário no Passo M — nunca descartado, sempre dividido proporcionalmente.</li>
<li>✔ Com um único componente verdadeiro, todo mundo tenderia a responsabilidade <span class="math inline">\(\approx\pi_k\)</span> (Bloco 3) — muito mais gente perto de <span class="math inline">\(50/50\)</span> do que os <span class="math inline">\(9\)</span> casos genuinamente raros observados aqui.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> a responsabilidade fracionária não é uma falha de informação recuperável por mais dados — é a resposta correta quando a sobreposição entre populações é real. O Bloco 3 formaliza de onde esse número vem.</p>
</div>
</section></section>
<section>
<section id="o-modelo-de-mistura-gaussiana-variável-latente" class="title-slide slide level1 center">
<h1>O Modelo de Mistura Gaussiana: Variável Latente</h1>

</section>
<section id="premissas-desta-construção" class="slide level2">
<h2>Premissas Desta Construção</h2>
<div class="fragment">
<p><strong>(1)</strong> Existem <span class="math inline">\(K\)</span> populações distintas, cada uma gaussiana.</p>
</div>
<div class="fragment">
<p><strong>(2)</strong> Todo paciente nasce de exatamente <strong>uma</strong> população — a mistura está na nossa incerteza sobre qual, não numa origem física misturada.</p>
</div>
<div class="fragment">
<p><strong>(3)</strong> Não observamos a população de origem, só <span class="math inline">\(\mathbf{x}\)</span>. A Aula 1 assumiu <span class="math inline">\(1\)</span> gaussiana para todos; o GMM permite <span class="math inline">\(K\)</span>.</p>
</div>
</section>
<section id="formalizando-de-qual-população" class="slide level2">
<h2>Formalizando “De Qual População”</h2>
<div class="fragment">
<p><span class="math inline">\(\mathbf{z}\)</span>: vetor binário 1-de-<span class="math inline">\(K\)</span> — <span class="math inline">\(z_k=1\)</span> indica “nasceu da população <span class="math inline">\(k\)</span>”.</p>
</div>
<div class="fragment">
<p><span class="math display">\[p(z_k=1) = \pi_k, \qquad 0\le\pi_k\le 1, \qquad \sum_{k=1}^K \pi_k = 1\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[p(\mathbf{x}\mid z_k=1) = \mathcal{N}(\mathbf{x}\mid \mu_k, \Sigma_k)\]</span></p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;430-431), tradução livre: <em>“a distribuição marginal sobre <span class="math inline">\(z\)</span> é especificada em termos dos coeficientes de mistura <span class="math inline">\(\pi_k\)</span>, de tal forma que <span class="math inline">\(p(z_k=1)=\pi_k\)</span>.”</em></p>
</div>
</section>
<section id="o-modelo-gerador-em-diagrama-1" class="slide level2">
<h2>O Modelo Gerador, em Diagrama</h2>
<div class="fragment">
<p>Para cada paciente <span class="math inline">\(n\)</span>: sorteia-se <span class="math inline">\(z_n\)</span> (probabilidades <span class="math inline">\(\pi_1,\dots,\pi_K\)</span>), depois <span class="math inline">\(\mathbf{x}_n\)</span> da gaussiana da população sorteada.</p>
</div>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<img data-src="index_files/mediabag/36faf184833c3a28a5698d589595dc0b3ca23b0f.svg" class="img-fluid">
</div>
</section>
<section id="recuperando-a-mistura-já-conhecida" class="slide level2">
<h2>Recuperando a Mistura Já Conhecida</h2>
<div class="fragment">
<p>Marginalizando sobre os <span class="math inline">\(K\)</span> estados de <span class="math inline">\(\mathbf{z}\)</span>: <span class="math display">\[p(\mathbf{x}) = \sum_{k=1}^K \pi_k\,\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k)\]</span></p>
</div>
<div class="fragment">
<p>Já era possível escrever essa soma desde a Aula 1 — a diferença é a <strong>história geradora explícita</strong> por trás dela: cada ponto nasceu de uma população específica, não observada.</p>
</div>
<div class="fragment">
<p>Isso abre a pergunta central: dado <span class="math inline">\(\mathbf{x}\)</span> observado, qual a probabilidade <strong>a posteriori</strong> de cada origem <span class="math inline">\(z\)</span>?</p>
</div>
</section>
<section id="responsabilidade-a-probabilidade-a-posteriori" class="slide level2">
<h2>Responsabilidade: A Probabilidade a Posteriori</h2>
<div class="fragment">
<p>Por Bayes: <span class="math display">\[\gamma(z_{nk}) \equiv p(z_k=1\mid\mathbf{x}_n) = \frac{\pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\sum_{j=1}^K \pi_j\,\mathcal{N}(\mathbf{x}_n\mid\mu_j,\Sigma_j)}\]</span> Dedução completa: Passo E, Bloco 5.</p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;432), tradução livre: <em>“<span class="math inline">\(\gamma(z_{nk})\)</span> também pode ser vista como a <strong>responsabilidade</strong> que o componente <span class="math inline">\(k\)</span> assume por ‘explicar’ a observação <span class="math inline">\(\mathbf{x}_n\)</span>.”</em></p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>É exatamente essa fórmula por trás da mistura de cores do Bloco 2. Falta uma peça: de onde vêm <span class="math inline">\(\pi_k,\mu_k,\Sigma_k\)</span>? Precisam ser ajustados aos dados (Bloco 4 em diante).</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="por-que-não-maximizar-a-verossimilhança-direto" class="title-slide slide level1 center">
<h1>Por Que Não Maximizar a Verossimilhança Direto</h1>

</section>
<section id="por-que-não-repetir-a-solução-fechada-da-aula-1" class="slide level2">
<h2>Por Que Não Repetir a Solução Fechada da Aula 1?</h2>
<div class="fragment">
<p>Aula 1: uma única gaussiana, <span class="math inline">\(\ln\)</span> de uma exponencial cancela limpo — solução fechada para <span class="math inline">\(\hat\mu,\hat\Sigma\)</span>.</p>
</div>
<div class="fragment">
<p>GMM: <span class="math display">\[\ln p(X\mid\pi,\mu,\Sigma) = \sum_{n=1}^N \ln\left\{\sum_{k=1}^K \pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)\right\}\]</span></p>
</div>
<div class="fragment">
<p><strong>Soma dentro do <span class="math inline">\(\ln\)</span></strong> — o <span class="math inline">\(\ln\)</span> não age mais direto sobre a gaussiana. PRML (p.&nbsp;433-434), tradução livre: <em>“a função logaritmo não age mais diretamente sobre a gaussiana […] não obteremos mais uma solução em forma fechada.”</em></p>
</div>
<div class="fragment">
<p>Derivar e igualar a zero ainda é possível, mas <span class="math inline">\(\mu_k\)</span> fica escondido numa razão de exponenciais somada com as outras <span class="math inline">\(K-1\)</span> — não dá para isolar numa passada só.</p>
</div>
</section>
<section id="aviso-técnico-singularidades" class="slide level2">
<h2>Aviso Técnico: Singularidades</h2>
<div class="fragment">
<p>Se a média de um componente colapsa sobre um único ponto e a variância <span class="math inline">\(\to 0\)</span>: densidade <span class="math inline">\(\to\infty\)</span>, log-verossimilhança <span class="math inline">\(\to\infty\)</span> — <em>overfitting</em> patológico, não generalização.</p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;434), tradução livre: <em>“a maximização da log-verossimilhança não é um problema bem posto, pois tais singularidades estarão sempre presentes.”</em></p>
</div>
<div class="fragment">
<p>Na prática: buscar um máximo local bem-comportado, não o global (sempre degenerado). <code>GaussianMixture</code> do scikit-learn já tem salvaguardas (piso mínimo de variância).</p>
</div>
</section>
<section id="a-saída-iterar" class="slide level2">
<h2>A Saída: Iterar</h2>
<div class="fragment">
<p>Sem solução fechada, mas as equações de derivada zero têm estrutura reconhecível (Bloco 6) — a estratégia é <strong>iterativa</strong>.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Alternar: responsabilidades com parâmetros atuais (<strong>Passo E</strong>) <span class="math inline">\(\to\)</span> reajustar parâmetros com responsabilidades atuais (<strong>Passo M</strong>) <span class="math inline">\(\to\)</span> repetir até convergir. O algoritmo <strong>EM</strong>.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="o-passo-e-responsabilidades-posteriores" class="title-slide slide level1 center">
<h1>O Passo E: Responsabilidades Posteriores</h1>

</section>
<section id="premissa-do-passo-e" class="slide level2">
<h2>Premissa do Passo E</h2>
<div class="fragment">
<p>Fixar os parâmetros atuais <span class="math inline">\(\pi_k,\mu_k,\Sigma_k\)</span> — não importa se ainda estão longe do ajuste final. Perguntar: sob <strong>estes</strong> parâmetros, qual a probabilidade posterior de cada origem, por ponto?</p>
</div>
<div class="fragment">
<p>Definição de probabilidade condicional: <span class="math display">\[p(z_k=1\mid\mathbf{x}_n) = \frac{p(z_k=1,\mathbf{x}_n)}{p(\mathbf{x}_n)}\]</span></p>
</div>
<div class="fragment">
<p>Numerador, pela regra da cadeia (<em>chain rule</em>): <span class="math inline">\(p(z_k=1,\mathbf{x}_n)
= p(z_k=1)\,p(\mathbf{x}_n\mid z_k=1) = \pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)\)</span> — as duas premissas do modelo gerador (Bloco 3).</p>
</div>
<div class="fragment">
<p>Denominador, pela lei da probabilidade total (soma sobre os <span class="math inline">\(K\)</span> estados de <span class="math inline">\(z_n\)</span>, mutuamente exclusivos e exaustivos): <span class="math display">\[p(\mathbf{x}_n) = \sum_{j=1}^K \pi_j\,\mathcal{N}(\mathbf{x}_n\mid\mu_j,\Sigma_j)\]</span></p>
</div>
</section>
<section id="o-resultado" class="slide level2">
<h2>O Resultado</h2>
<div class="fragment">
<p>Substituindo numerador e denominador: <span class="math display">\[\gamma(z_{nk}) \equiv p(z_k=1\mid\mathbf{x}_n) = \frac{\pi_k\,\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\displaystyle\sum_{j=1}^K \pi_j\,\mathcal{N}(\mathbf{x}_n\mid\mu_j,\Sigma_j)}\]</span></p>
</div>
<div class="fragment">
<p>Cada um dos <span class="math inline">\(N\)</span> pacientes recebe seu próprio vetor de <span class="math inline">\(K\)</span> responsabilidades, somando <span class="math inline">\(1\)</span> — em vez de uma regra de corte, cada ponto participa, em algum grau, de <strong>todos</strong> os componentes.</p>
</div>
</section>
<section id="verificação-numérica-3-pacientes-reais" class="slide level2">
<h2>Verificação Numérica: 3 Pacientes Reais</h2>
<div class="fragment">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Paciente</th>
<th><code>radius_worst</code></th>
<th><code>concave pts._worst</code></th>
<th>Diagnóstico</th>
<th><span class="math inline">\(\gamma\)</span>(benigno)</th>
<th><span class="math inline">\(\gamma\)</span>(maligno)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>41</td>
<td>12,84</td>
<td>0,1424</td>
<td>M</td>
<td>0,486</td>
<td>0,514</td>
</tr>
<tr class="even">
<td>112</td>
<td>15,30</td>
<td>0,1505</td>
<td>B</td>
<td>0,520</td>
<td>0,480</td>
</tr>
<tr class="odd">
<td>501</td>
<td>16,01</td>
<td>0,1521</td>
<td>M</td>
<td>0,481</td>
<td>0,519</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>O diagnóstico real (nunca visto no ajuste) não decide o lado — 112 é benigno com <span class="math inline">\(\gamma\)</span> levemente maior para benigno; 501 é maligno com <span class="math inline">\(\gamma\)</span> levemente maior para maligno. Ambos a <span class="math inline">\(&lt;2\)</span> p.p. do empate.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(101\)</span> de <span class="math inline">\(569\)</span> pacientes (<span class="math inline">\(\approx17{,}7\%\)</span>) têm responsabilidade máxima <span class="math inline">\(&lt;0{,}9\)</span> — ambiguidade moderada é uma faixa de transição real, não um fenômeno raro de pontos isolados.</p>
</div>
</div>
</div>
</div>
</section>
<section id="pergunta-2" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Um paciente tem responsabilidade <span class="math inline">\(\gamma=0{,}9\)</span> para o componente maligno e <span class="math inline">\(\gamma=0{,}1\)</span> para o benigno. Se, no meio de uma sessão de reajuste do modelo, os parâmetros do componente maligno mudarem bastante (por exemplo, sua covariância <span class="math inline">\(\Sigma\)</span> dobrar de tamanho), o que necessariamente acontece com essa responsabilidade <span class="math inline">\(\gamma=0{,}9\)</span>?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense se <span class="math inline">\(\gamma(z_{nk})\)</span> é uma propriedade fixa do ponto <span class="math inline">\(\mathbf{x}_n\)</span>, ou uma função dos parâmetros correntes do modelo — e lembre que a fórmula de Bayes usada aqui depende de <span class="math inline">\(\mu_k\)</span> e <span class="math inline">\(\Sigma_k\)</span> dos dois lados da razão, não só do componente <span class="math inline">\(k\)</span>.</p>
<ul>
<li>□ A responsabilidade <span class="math inline">\(\gamma(z_{nk})\)</span> é recalculada do zero a cada vez que os parâmetros do modelo mudam — ela não é uma propriedade fixa do ponto <span class="math inline">\(\mathbf{x}_n\)</span>, é uma função corrente de <span class="math inline">\(\pi,\mu,\Sigma\)</span>.</li>
<li>□ Se a covariância do componente maligno dobrar de tamanho (ficando mais “espalhada”), isso necessariamente aumenta a responsabilidade <span class="math inline">\(\gamma(z_{n,\text{maligno}})\)</span> para qualquer ponto, porque uma gaussiana mais espalhada sempre atribui mais densidade a todo ponto do espaço.</li>
<li>□ Dois pacientes com exatamente a mesma responsabilidade <span class="math inline">\(\gamma=(0{,}9,0{,}1)\)</span> sob os parâmetros atuais do modelo podem ter responsabilidades bem diferentes entre si depois de uma rodada de reestimação de parâmetros (Passo M), mesmo que os dois tivessem originalmente o mesmo par de atributos observados.</li>
<li>□ Se <span class="math inline">\(K=1\)</span> (um único componente), a responsabilidade <span class="math inline">\(\gamma(z_{n1})\)</span> é sempre igual a <span class="math inline">\(1\)</span> para todo ponto, independentemente dos parâmetros — não há nenhum outro componente para “competir” na razão de Bayes.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-2" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resposta — responsabilidade muda com os parâmetros</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ <span class="math inline">\(\gamma(z_{nk})\)</span> é função corrente dos parâmetros — recalculada a cada rodada, nunca fixa ao ponto.</li>
<li>✗ Uma covariância maior espalha densidade, mas também <strong>reduz o pico</strong> (a densidade se normaliza a <span class="math inline">\(1\)</span>); o efeito líquido sobre <span class="math inline">\(\gamma\)</span> depende de onde <span class="math inline">\(\mathbf{x}_n\)</span> está, não é sempre “aumenta”.</li>
<li>✔ Dois pacientes idênticos em atributos, com a mesma <span class="math inline">\(\gamma\)</span> hoje, divergem se entrarem com pesos diferentes nas somas do Passo M (por exemplo, se um deles for repetido no dataset e o outro não) — a reestimação usa todos os pontos conjuntamente, não cada um isolado.</li>
<li>✔ Com <span class="math inline">\(K=1\)</span> não há denominador com mais de um termo — a razão de Bayes degenera em <span class="math inline">\(1\)</span> para o único componente, sempre.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> a responsabilidade é uma função dos parâmetros correntes, não uma etiqueta fixa — é exatamente por isso que o algoritmo pode iterar: mudar os parâmetros (Passo M) muda as responsabilidades (novo Passo E), e vice-versa, até estabilizar.</p>
</div>
</section></section>
<section>
<section id="o-passo-m-atualizações-ponderadas" class="title-slide slide level1 center">
<h1>O Passo M: Atualizações Ponderadas</h1>

</section>
<section id="premissa-do-passo-m" class="slide level2">
<h2>Premissa do Passo M</h2>
<div class="fragment">
<p>Fixar as responsabilidades <span class="math inline">\(\gamma(z_{nk})\)</span> do Passo E (agora constantes) — perguntar que <span class="math inline">\(\pi_k,\mu_k,\Sigma_k\)</span> maximizam a log-verossimilhança esperada sob elas.</p>
</div>
<div class="fragment">
<p>Com <span class="math inline">\(\gamma\)</span> fixo, o problema se separa em <span class="math inline">\(K\)</span> ajustes de MLE <strong>ponderada</strong> — sem soma dentro do <span class="math inline">\(\ln\)</span> competindo entre componentes.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>A receita de sempre: <strong>derivar em relação a cada parâmetro e igualar a zero</strong> — um parâmetro de cada vez, a seguir.</p>
</div>
</div>
</div>
</div>
</section>
<section id="por-que-gammaz_nk-aparece-em-toda-derivada" class="slide level2">
<h2>Por Que <span class="math inline">\(\gamma(z_{nk})\)</span> Aparece em Toda Derivada</h2>
<div class="fragment">
<p><span class="math inline">\(\mu_k,\Sigma_k\)</span> são <strong>privados</strong> do componente <span class="math inline">\(k\)</span>: dentro de <span class="math inline">\(\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)\)</span>, só o termo <span class="math inline">\(j=k\)</span> depende deles. Para <span class="math inline">\(\theta_k\in\{\mu_k,\Sigma_k\}\)</span>: <span class="math display">\[\frac{\partial}{\partial\theta_k}\ln\Big(\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)\Big) = \frac{\pi_k}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)}\frac{\partial \mathcal{N}_k(\mathbf{x}_n)}{\partial\theta_k}\]</span></p>
</div>
<div class="fragment">
<p>Regra da cadeia do <span class="math inline">\(\ln\)</span> (<span class="math inline">\(\partial\mathcal N_k/\partial\theta_k=\mathcal N_k\cdot\partial\ln\mathcal N_k/\partial\theta_k\)</span>) faz o lado direito virar exatamente <span class="math inline">\(\gamma(z_{nk})\cdot\partial\ln\mathcal{N}_k/\partial\theta_k\)</span>. Somando sobre <span class="math inline">\(n\)</span>: <span class="math display">\[\frac{\partial \ln p(X\mid\pi,\mu,\Sigma)}{\partial\theta_k} = \sum_{n=1}^N \gamma(z_{nk})\,\frac{\partial\ln\mathcal{N}(\mathbf{x}_n\mid\mu_k,\Sigma_k)}{\partial\theta_k}\]</span></p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Com <span class="math inline">\(\gamma\)</span> fixo, a derivada da mistura <strong>colapsa</strong> numa versão ponderada da equação de derivada de uma única gaussiana (Aula 1) — é esse colapso que separa o problema em <span class="math inline">\(K\)</span> ajustes independentes.</p>
</div>
</div>
</div>
</div>
</section>
<section id="atualização-de-mu_k-a-peça-que-falta" class="slide level2">
<h2>Atualização de <span class="math inline">\(\mu_k\)</span>: a Peça Que Falta</h2>
<div class="fragment">
<p><span class="math inline">\(\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k) = \text{const} - \dfrac12\ln|\Sigma_k| - \dfrac12(\mathbf{x}-\mu_k)^T\Sigma_k^{-1}(\mathbf{x}-\mu_k)\)</span> — só o termo quadrático depende de <span class="math inline">\(\mu_k\)</span>.</p>
</div>
<div class="fragment">
<p>Gradiente de forma quadrática (<span class="math inline">\(\mathbf{u}=\mathbf{x}-\mu\)</span>, <span class="math inline">\(\partial\mathbf{u}/\partial\mu=-I\)</span>, gradiente de <span class="math inline">\(\mathbf{u}^TA\mathbf{u}\)</span> em <span class="math inline">\(\mathbf{u}\)</span> é <span class="math inline">\(2A\mathbf{u}\)</span>): <span class="math display">\[\frac{\partial\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k)}{\partial\mu_k} = \Sigma_k^{-1}(\mathbf{x}-\mu_k)\]</span></p>
</div>
</section>
<section id="atualização-de-mu_k-o-resultado" class="slide level2">
<h2>Atualização de <span class="math inline">\(\mu_k\)</span>: o Resultado</h2>
<div class="fragment">
<p>Pela identidade geral (slide anterior), com <span class="math inline">\(\theta_k=\mu_k\)</span>: <span class="math display">\[\frac{\partial \ln p(X\mid\pi,\mu,\Sigma)}{\partial\mu_k} = \sum_{n=1}^N \gamma(z_{nk})\,\Sigma_k^{-1}(\mathbf{x}_n-\mu_k)\]</span> Igualando a zero e multiplicando por <span class="math inline">\(\Sigma_k\)</span>: <span class="math display">\[\mu_k = \frac{1}{N_k}\sum_{n=1}^N \gamma(z_{nk})\,\mathbf{x}_n, \qquad N_k = \sum_{n=1}^N \gamma(z_{nk})\]</span></p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;436): <em>“podemos interpretar <span class="math inline">\(N_k\)</span> como o número efetivo de pontos atribuídos ao cluster <span class="math inline">\(k\)</span>.”</em></p>
</div>
<div class="fragment">
<p><span class="math inline">\(\mu_k\)</span> é <strong>média ponderada</strong> por <span class="math inline">\(\gamma(z_{nk})\)</span> — pacientes de alta responsabilidade pesam quase um voto inteiro; ambíguos contribuem uma fração pequena para <strong>os dois</strong> componentes. Compare com a Aula 1: lá o peso era <span class="math inline">\(1/N\)</span> para todos; aqui é a própria responsabilidade.</p>
</div>
</section>
<section id="atualização-de-sigma_k-as-ferramentas" class="slide level2">
<h2>Atualização de <span class="math inline">\(\Sigma_k\)</span>: as Ferramentas</h2>
<div class="fragment">
<p>Duas identidades de cálculo matricial (Bishop, PRML, Apêndice C, p.&nbsp;698): <span class="math display">\[\frac{\partial\ln|\Sigma_k|}{\partial\Sigma_k} = \Sigma_k^{-1} \;\text{(C.28)}, \qquad \frac{\partial\,\Sigma_k^{-1}}{\partial(\Sigma_k)_{ij}} = -\Sigma_k^{-1}E_{ij}\Sigma_k^{-1} \;\text{(C.21)}\]</span> onde <span class="math inline">\(E_{ij}\)</span> tem <span class="math inline">\(1\)</span> na posição <span class="math inline">\((i,j)\)</span> e <span class="math inline">\(0\)</span> no resto.</p>
</div>
<div class="fragment">
<p>Propriedade cíclica do traço (<span class="math inline">\(\mathrm{tr}(ABC)=\mathrm{tr}(BCA)\)</span>) reescreve a forma quadrática como traço: <span class="math inline">\((\mathbf{x}-\mu_k)^T\Sigma_k^{-1}(\mathbf{x}-\mu_k)=\mathrm{tr}(\Sigma_k^{-1}M)\)</span>, <span class="math inline">\(M=(\mathbf{x}-\mu_k)(\mathbf{x}-\mu_k)^T\)</span>.</p>
</div>
<div class="fragment">
<p>Aplicando C.21 elemento a elemento: <span class="math display">\[\frac{\partial}{\partial(\Sigma_k)_{ij}}\mathrm{tr}(\Sigma_k^{-1}M) = -\big[\Sigma_k^{-1}M\Sigma_k^{-1}\big]_{ji} \;\Longrightarrow\; \frac{\partial\,\mathrm{tr}(\Sigma_k^{-1}M)}{\partial\Sigma_k} = -\Sigma_k^{-1}M\Sigma_k^{-1}\]</span></p>
</div>
</section>
<section id="atualização-de-sigma_k-o-resultado" class="slide level2">
<h2>Atualização de <span class="math inline">\(\Sigma_k\)</span>: o Resultado</h2>
<div class="fragment">
<p>Combinando as duas partes da log-densidade: <span class="math display">\[\frac{\partial\ln\mathcal{N}(\mathbf{x}\mid\mu_k,\Sigma_k)}{\partial\Sigma_k} = -\frac12\Sigma_k^{-1} + \frac12\Sigma_k^{-1}(\mathbf{x}-\mu_k)(\mathbf{x}-\mu_k)^T\Sigma_k^{-1}\]</span></p>
</div>
<div class="fragment">
<p>Pela identidade geral, ponderando por <span class="math inline">\(\gamma(z_{nk})\)</span>, somando em <span class="math inline">\(n\)</span>, igualando a zero e multiplicando por <span class="math inline">\(\Sigma_k\)</span> dos dois lados: <span class="math display">\[\Sigma_k = \frac{1}{N_k}\sum_{n=1}^N \gamma(z_{nk})\,(\mathbf{x}_n-\mu_k)(\mathbf{x}_n-\mu_k)^T\]</span></p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;436): <em>“tem a mesma forma que o resultado […] para uma única gaussiana, mas com cada ponto ponderado pela probabilidade a posteriori.”</em></p>
</div>
</section>
<section id="atualização-de-pi_k-a-derivada" class="slide level2">
<h2>Atualização de <span class="math inline">\(\pi_k\)</span>: a Derivada</h2>
<div class="fragment">
<p><span class="math inline">\(\pi_k\)</span> não está “escondido” numa gaussiana — multiplica <span class="math inline">\(\mathcal{N}_k(\mathbf{x}_n)\)</span> inteira, <strong>linearmente</strong>: <span class="math display">\[\frac{\partial}{\partial\pi_k}\ln\Big(\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)\Big) = \frac{\mathcal{N}_k(\mathbf{x}_n)}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)}\]</span></p>
</div>
<div class="fragment">
<p>Restrição <span class="math inline">\(\sum_k\pi_k=1\)</span> pede multiplicador de Lagrange — derivando <span class="math inline">\(\ln p(X\mid\pi,\mu,\Sigma)+\lambda(\sum_k\pi_k-1)\)</span> em <span class="math inline">\(\pi_k\)</span>: <span class="math display">\[0 = \sum_{n=1}^N \frac{\mathcal{N}_k(\mathbf{x}_n)}{\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)} + \lambda\]</span></p>
</div>
</section>
<section id="atualização-de-pi_k-eliminando-lambda" class="slide level2">
<h2>Atualização de <span class="math inline">\(\pi_k\)</span>: Eliminando <span class="math inline">\(\lambda\)</span></h2>
<div class="fragment">
<p>Multiplicando por <span class="math inline">\(\pi_k\)</span> (e usando que <span class="math inline">\(\pi_k\mathcal{N}_k(\mathbf{x}_n)/\sum_j\pi_j\mathcal{N}_j(\mathbf{x}_n)=\gamma(z_{nk})\)</span>): <span class="math display">\[0 = \sum_{n=1}^N \gamma(z_{nk}) + \lambda\pi_k = N_k + \lambda\pi_k\]</span></p>
</div>
<div class="fragment">
<p>Somando sobre <span class="math inline">\(k\)</span>: <span class="math inline">\(\sum_k N_k = \sum_n\sum_k\gamma(z_{nk}) = \sum_n 1 = N\)</span>, e <span class="math inline">\(\lambda\sum_k\pi_k=\lambda\)</span> — logo <span class="math inline">\(\lambda=-N\)</span>. Substituindo: <span class="math display">\[N_k - N\pi_k = 0 \;\Longrightarrow\; \pi_k = \frac{N_k}{N}\]</span></p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;436): <em>“o coeficiente de mistura […] é dado pela responsabilidade média que aquele componente assume por explicar os pontos de dados.”</em></p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(N_k\)</span> é <strong>soma de responsabilidades fracionárias</strong>, não contagem rígida: um componente que “convence” <span class="math inline">\(50\)</span> pacientes por completo e <span class="math inline">\(20\)</span> pela metade tem <span class="math inline">\(N_k=60\)</span>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="um-ciclo-não-uma-solução" class="slide level2">
<h2>Um Ciclo, Não Uma Solução</h2>
<div class="fragment">
<p><span class="math inline">\(\mu_k,\Sigma_k,\pi_k\)</span> <strong>não</strong> formam solução fechada — <span class="math inline">\(\gamma(z_{nk})\)</span> (Bloco 5) depende dos parâmetros que este bloco acabou de reestimar.</p>
</div>
<div class="fragment">
<p>Por isso é iterativo: Passo E <span class="math inline">\(\to\)</span> Passo M <span class="math inline">\(\to\)</span> repetir. O algoritmo <strong>EM</strong> completo, no próximo bloco.</p>
</div>
</section></section>
<section>
<section id="o-algoritmo-em-completo-em-ação" class="title-slide slide level1 center">
<h1>O Algoritmo EM Completo, em Ação</h1>

</section>
<section id="o-algoritmo-completo-prml-p.-438-439" class="slide level2">
<h2>O Algoritmo Completo (PRML, p.&nbsp;438-439)</h2>
<div class="fragment">
<p><strong>1.</strong> Inicializar <span class="math inline">\(\mu_k,\Sigma_k,\pi_k\)</span> (tipicamente a partir de um KMeans); avaliar log-verossimilhança inicial.</p>
</div>
<div class="fragment">
<p><strong>2. Passo E.</strong> Calcular <span class="math inline">\(\gamma(z_{nk})\)</span> com os parâmetros correntes.</p>
</div>
<div class="fragment">
<p><strong>3. Passo M.</strong> Reestimar <span class="math inline">\(\mu_k\)</span>, depois <span class="math inline">\(\Sigma_k\)</span> (usando o novo <span class="math inline">\(\mu_k\)</span>), depois <span class="math inline">\(\pi_k\)</span> — mesma ordem da Aula 1.</p>
</div>
<div class="fragment">
<p><strong>4.</strong> Reavaliar log-verossimilhança; parar se a mudança for pequena; senão, voltar ao Passo E.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>PRML (p.&nbsp;437): <em>“cada atualização […] tem a garantia de aumentar a função de log-verossimilhança.”</em> Não garante o máximo global — <code>n_init</code> com múltiplas inicializações reduz o risco de máximo local ruim.</p>
</div>
</div>
</div>
</div>
</section>
<section id="ajustando-de-verdade-breast-cancer-wisconsin" class="slide level2">
<h2>Ajustando de Verdade: Breast Cancer Wisconsin</h2>
<div class="fragment">
<p><code>GaussianMixture(n_components=2)</code>, mesmos 2 atributos da Aula 3, sem <code>diagnosis</code>: <span class="math inline">\(\pi\approx(0{,}637,\ 0{,}363)\)</span>.</p>
</div>
<div class="fragment">
<p>Componente <span class="math inline">\(0\)</span> (benigno): <span class="math inline">\(349\)</span>B / <span class="math inline">\(23\)</span>M. Componente <span class="math inline">\(1\)</span> (maligno): <span class="math inline">\(189\)</span>M / <span class="math inline">\(8\)</span>B — mais puro que o cluster <span class="math inline">\(100\%\)</span> maligno da Aula 3, mas cobrindo <span class="math inline">\(189\)</span> vs.&nbsp;<span class="math inline">\(54\)</span> malignos.</p>
</div>
<div class="fragment">
<p>Comparação honesta: GMM atribui <strong>todo mundo</strong>; HDBSCAN se recusa a decidir sobre <span class="math inline">\(29{,}5\%\)</span> dos pacientes. Troca anunciada na Abertura — nunca “sem resposta”, ao custo de forçar decisão mesmo onde a evidência é fraca.</p>
</div>
<div class="fig-resize" style="width: 47%; margin: 0 auto;">
<div id="871b99d7" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="onde-as-elipses-se-sobrepõem" class="slide level2">
<h2>Onde as Elipses se Sobrepõem</h2>
<div class="fragment">
<p>Faixa central de sobreposição geométrica = exatamente a região dos pacientes de responsabilidade ambígua (Bloco 5).</p>
</div>
<div class="fragment">
<p>Sem fronteira única (diferente do HDBSCAN): transição de cor suave, proporcional a quão “dentro” de cada elipse ponderada um ponto está.</p>
</div>
</section></section>
<section>
<section id="o-kmeans-e-sua-relação-com-o-gmm" class="title-slide slide level1 center">
<h1>O KMeans e Sua Relação com o GMM</h1>

</section>
<section id="o-objetivo-do-kmeans" class="slide level2">
<h2>O Objetivo do KMeans</h2>
<div class="fragment">
<p>Dados <span class="math inline">\(N\)</span> pontos e <span class="math inline">\(K\)</span> fixo: achar <span class="math inline">\(K\)</span> centróides <span class="math inline">\(\mu_1,\dots,\mu_K\)</span> e uma atribuição de cada ponto a um deles, minimizando a soma das distâncias ao quadrado ponto–centróide.</p>
</div>
<div class="fragment">
<p>Indicador rígido: <span class="math inline">\(r_{nk}\in\{0,1\}\)</span>, <span class="math inline">\(\sum_k r_{nk}=1\)</span> — mesma codificação 1-de-<span class="math inline">\(K\)</span> de <span class="math inline">\(z_{nk}\)</span> (Bloco 3), mas determinística, não latente.</p>
</div>
<div class="fragment">
<p>PRML (p.&nbsp;424), tradução livre: <em>“medida de distorção <span class="math inline">\(J=\sum_n\sum_k r_{nk}\|\mathbf{x}_n-\mu_k\|^2\)</span>, a soma dos quadrados das distâncias de cada ponto ao seu <span class="math inline">\(\mu_k\)</span> atribuído.”</em> <span class="math display">\[J = \sum_{n=1}^N \sum_{k=1}^K r_{nk} \|\mathbf{x}_n - \mu_k\|^2\]</span></p>
</div>
</section>
<section id="dois-passos-alternados" class="slide level2">
<h2>Dois Passos Alternados</h2>
<div class="fragment">
<p><span class="math inline">\(J\)</span> tem duas famílias de variáveis, <span class="math inline">\(\{r_{nk}\}\)</span> e <span class="math inline">\(\{\mu_k\}\)</span> — minimizar as duas juntas não é direto, mas fixar uma de cada vez torna cada subproblema tratável. Bishop já chama as duas fases de “passo E” e “passo M” do KMeans, prefigurando o EM (Blocos 5-6).</p>
</div>
</section>
<section id="passo-1-fixar-mu_k-resolver-r_nk" class="slide level2">
<h2>Passo 1: Fixar <span class="math inline">\(\mu_k\)</span>, Resolver <span class="math inline">\(r_{nk}\)</span></h2>
<div class="fragment">
<p><span class="math inline">\(J\)</span> é <strong>linear</strong> em cada <span class="math inline">\(r_{nk}\)</span>, termos de pacientes diferentes são independentes — cada <span class="math inline">\(n\)</span> se resolve sozinho, escolhendo o <span class="math inline">\(k\)</span> de menor <span class="math inline">\(\|\mathbf{x}_n-\mu_k\|^2\)</span>.</p>
</div>
<div class="fragment">
<p>PRML (eq. 9.2, p.&nbsp;425): <span class="math display">\[r_{nk} = \begin{cases}1 &amp; \text{se } k=\arg\min_j \|\mathbf{x}_n-\mu_j\|^2 \\ 0 &amp; \text{caso contrário}\end{cases}\]</span> <strong>Atribua cada ponto ao centróide mais próximo.</strong></p>
</div>
</section>
<section id="passo-2-fixar-r_nk-resolver-mu_k" class="slide level2">
<h2>Passo 2: Fixar <span class="math inline">\(r_{nk}\)</span>, Resolver <span class="math inline">\(\mu_k\)</span></h2>
<div class="fragment">
<p>Para <span class="math inline">\(k\)</span> fixo, só os pontos com <span class="math inline">\(r_{nk}=1\)</span> importam — forma quadrática em <span class="math inline">\(\mu_k\)</span>. Derivada de <span class="math inline">\(\|\mathbf{x}_n-\mu_k\|^2\)</span> em <span class="math inline">\(\mu_k\)</span> é <span class="math inline">\(-2(\mathbf{x}_n-\mu_k)\)</span>: <span class="math display">\[\frac{\partial J}{\partial \mu_k} = \sum_{n=1}^N r_{nk}\cdot(-2)(\mathbf{x}_n-\mu_k)\]</span></p>
</div>
<div class="fragment">
<p>Igualando a zero (eq. 9.3-9.4, p.&nbsp;425) e isolando: <span class="math display">\[\mu_k = \frac{\sum_n r_{nk}\,\mathbf{x}_n}{\sum_n r_{nk}}\]</span> Centróide = <strong>média dos pontos atribuídos a ele</strong>.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Mesma estrutura da atualização de <span class="math inline">\(\mu_k\)</span> do GMM (Bloco 6) — “média ponderada pela atribuição” — só que lá o peso é <span class="math inline">\(\gamma(z_{nk})\in[0,1]\)</span> fracionário, aqui é <span class="math inline">\(r_{nk}\in\{0,1\}\)</span> rígido.</p>
</div>
</div>
</div>
</div>
</section>
<section id="convergência" class="slide level2">
<h2>Convergência</h2>
<div class="fragment">
<p>Cada fase resolve seu subproblema exatamente — nenhuma pode aumentar <span class="math inline">\(J\)</span>. Alternar até <span class="math inline">\(r_{nk}\)</span> estabilizar garante convergência de <span class="math inline">\(J\)</span> (Bishop, p.&nbsp;425), possivelmente para um <strong>mínimo local</strong>.</p>
</div>
<div class="fragment">
<p>Por isso <code>n_init=10</code> no ajuste: repetir com centróides iniciais diferentes, manter o menor <span class="math inline">\(J\)</span> final.</p>
</div>
<div class="fig-resize" style="width: 78%; margin: 0 auto;">
<div id="07eda3a3" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="kmeans-vs.-gmm-mesmos-dados" class="slide level2">
<h2>KMeans vs.&nbsp;GMM, Mesmos Dados</h2>
<div class="fragment">
<p>KMeans (esquerda): fronteira <strong>reta</strong> (mediatriz dos centróides), cada paciente numa região só, sem gradação.</p>
</div>
<div class="fragment">
<p>GMM (direita, Bloco 7): transição <strong>suave</strong>, com uma faixa de pacientes em tons intermediários — os mesmos ambíguos do Bloco 5.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>O KMeans parece um GMM que <strong>perdeu a capacidade de hesitar</strong>. Sob que condições precisas essa hesitação desaparece?</p>
</div>
</div>
</div>
</div>
</section>
<section id="premissas-do-resultado" class="slide level2">
<h2>Premissas do Resultado</h2>
<div class="fragment">
<p><strong>(1)</strong> <span class="math inline">\(\Sigma_k=\epsilon I\)</span> para todo <span class="math inline">\(k\)</span> — esféricas, <strong>idênticas</strong> entre componentes, não <span class="math inline">\(K\)</span> matrizes livres.</p>
</div>
<div class="fragment">
<p><strong>(2)</strong> <span class="math inline">\(\epsilon\)</span> tratado como <strong>constante fixa</strong>, não reestimada — só <span class="math inline">\(\pi_k,\mu_k\)</span> continuam sendo ajustados.</p>
</div>
<div class="fragment">
<p><span class="math display">\[\gamma(z_{nk}) = \frac{\pi_k\exp\{-\|\mathbf{x}_n-\mu_k\|^2/2\epsilon\}}{\sum_j \pi_j\exp\{-\|\mathbf{x}_n-\mu_j\|^2/2\epsilon\}}\]</span></p>
</div>
</section>
<section id="o-limite-epsilonto-0-prml-p.-443-444" class="slide level2">
<h2>O Limite <span class="math inline">\(\epsilon\to 0\)</span> (PRML, p.&nbsp;443-444)</h2>
<div class="fragment">
<p>Tradução livre: <em>“o termo para o qual <span class="math inline">\(\|\mathbf{x}_n-\mu_j\|^2\)</span> é o menor tenderá a zero mais lentamente […] obtemos uma atribuição rígida […] exatamente como no algoritmo KMeans.”</em></p>
</div>
<div class="fragment">
<p>Intuição: com <span class="math inline">\(\epsilon\)</span> minúsculo, o componente <strong>mais próximo</strong> domina exponencialmente — a diferença de distância ao quadrado, dividida por <span class="math inline">\(\epsilon\to0\)</span>, vira diferença enorme na exponencial. Vale independente de <span class="math inline">\(\pi_k\)</span> (se nenhum for zero).</p>
</div>
</section>
<section id="a-atualização-de-mu_k-também-converge" class="slide level2">
<h2>A Atualização de <span class="math inline">\(\mu_k\)</span> Também Converge</h2>
<div class="fragment">
<p>PRML (p.&nbsp;444): <em>“a equação de reestimação […] se reduz ao resultado do KMeans […] maximizar a log-verossimilhança esperada é equivalente a minimizar a medida de distorção <span class="math inline">\(J\)</span> do KMeans.”</em></p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>No limite, <span class="math inline">\(\gamma(z_{nk})\to r_{nk}\in\{0,1\}\)</span>: a média ponderada do Bloco 6 vira exatamente a média do KMeans (Aula 3). O KMeans é o <strong>GMM de mãos amarradas</strong> — covariância travada, esférica, <span class="math inline">\(\to 0\)</span>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="verificação-numérica-própria" class="slide level2">
<h2>Verificação Numérica Própria</h2>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(\epsilon\)</span></th>
<th>Resp. média máx.</th>
<th>Acurácia vs.&nbsp;KMeans</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(1{,}0\)</span></td>
<td><span class="math inline">\(0{,}904\)</span></td>
<td><span class="math inline">\(95{,}78\%\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0{,}1\)</span></td>
<td><span class="math inline">\(0{,}9916\)</span></td>
<td><span class="math inline">\(99{,}30\%\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0{,}01\)</span></td>
<td><span class="math inline">\(0{,}9996\)</span></td>
<td><span class="math inline">\(100{,}00\%\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>Conforme <span class="math inline">\(\epsilon\)</span> cai: responsabilidade <span class="math inline">\(\to\)</span> rígida, concordância com KMeans <span class="math inline">\(\to100\%\)</span> — confirmado numericamente, não só afirmado.</p>
</div>
<div class="fig-resize" style="width: 85%; margin: 0 auto;">
<div id="cf2734ed" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="da-transição-suave-à-fronteira-rígida" class="slide level2">
<h2>Da Transição Suave à Fronteira Rígida</h2>
<div class="fragment">
<p>Cor cada vez mais <strong>abrupta</strong> da esquerda para a direita — em <span class="math inline">\(\epsilon=0{,}01\)</span> quase tudo é azul ou laranja sólido, fronteira fina exatamente na bissetriz do KMeans.</p>
</div>
</section>
<section id="pergunta-3" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>O KMeans, no limite <span class="math inline">\(\epsilon\to 0\)</span>, não estima covariância nenhuma — só médias. Isso significa que um GMM com covariâncias esféricas gerais (não travadas em <span class="math inline">\(\epsilon\)</span> fixo) é sempre estritamente melhor que o KMeans para qualquer conjunto de dados?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense no que “melhor” significaria aqui — ajuste mais fiel à verossimilhança dos dados observados, ou algum outro critério prático (velocidade, interpretabilidade, robustez a pouco dado).</p>
<ul>
<li>□ Um GMM com covariâncias livres tem mais parâmetros a estimar do que o KMeans (que só estima médias) — com poucos dados por cluster, isso pode fazer o GMM overfitar a covariância, enquanto o KMeans, mais restrito, generalizaria melhor.</li>
<li>□ Se os clusters verdadeiros nos dados tiverem, de fato, covariâncias esféricas idênticas entre si, o GMM completo, ao convergir, deve recuperar covariâncias estimadas próximas dessa forma esférica comum — e nesse cenário específico, a vantagem prática do GMM sobre o KMeans se estreita.</li>
<li>□ Um cluster alongado (covariância muito diferente entre duas direções) é sempre mais bem representado pelo GMM do que pelo KMeans, porque o GMM pode orientar e esticar a elipse; o KMeans, restrito a bolas circulares de mesmo tamanho, cortaria esse cluster de forma artificial se ele fizer fronteira com outro.</li>
<li>□ Como o KMeans é matematicamente um caso particular do GMM, o KMeans nunca pode convergir mais rápido (em menos iterações até estabilizar) do que o GMM completo no mesmo conjunto de dados.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-3" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resposta — GMM completo é sempre melhor?</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Mais parâmetros (covariância livre) com poucos dados por cluster pode overfitar — KMeans, mais restrito, generaliza melhor nesse regime.</li>
<li>✔ Com covariâncias verdadeiramente esféricas e idênticas, o GMM convergiria para algo próximo do que o KMeans já assume — a vantagem prática do GMM encolhe nesse cenário específico.</li>
<li>✔ Cluster alongado: GMM pode orientar/esticar a elipse; KMeans, restrito a bolas do mesmo tamanho, corta artificialmente na fronteira.</li>
<li>✗ “Caso particular” é uma relação matemática de limite, não uma relação de velocidade de convergência — o KMeans, sendo mais simples por iteração e com menos parâmetros, tipicamente converge em <strong>menos</strong> iterações, não mais.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> não existe “sempre melhor” — o GMM generaliza o KMeans matematicamente, mas essa generalidade custa mais parâmetros para estimar, o que só compensa quando os dados de fato sustentam essa riqueza extra.</p>
</div>
</section></section>
<section>
<section id="fechamento-e-ponte-para-a-aula-5" class="title-slide slide level1 center">
<h1>Fechamento e Ponte para a Aula 5</h1>

</section>
<section id="retomando-as-quatro-perguntas" class="slide level2">
<h2>Retomando as Quatro Perguntas</h2>
<div class="fragment">
<p><strong>1.</strong> Variável latente <span class="math inline">\(z\)</span> (1-de-<span class="math inline">\(K\)</span>, prior <span class="math inline">\(\pi_k\)</span>); <span class="math inline">\(\mathbf{x}\mid
z_k=1\sim\mathcal{N}(\mu_k,\Sigma_k)\)</span>; <span class="math inline">\(z\)</span> nunca observado.</p>
</div>
<div class="fragment">
<p><strong>2.</strong> Bayes <span class="math inline">\(\to\)</span> responsabilidade <span class="math inline">\(\gamma(z_{nk})\)</span> (Passo E, a partir dos parâmetros correntes).</p>
</div>
<div class="fragment">
<p><strong>3.</strong> MLE ponderada (Passo M) — sem solução fechada (<span class="math inline">\(\gamma\)</span> depende dos parâmetros que ela mesma ajuda a reestimar); EM itera E/M, garantidamente sem piorar a cada rodada.</p>
</div>
<div class="fragment">
<p><strong>4.</strong> Generaliza: KMeans = GMM com <span class="math inline">\(\Sigma_k=\epsilon I\)</span> idêntico, <span class="math inline">\(\epsilon\to0\)</span> — analítico (PRML) e numérico (Bloco 8).</p>
</div>
</section>
<section id="o-que-fica-em-aberto" class="slide level2">
<h2>O Que Fica em Aberto</h2>
<div class="fragment">
<p><span class="math inline">\(K\)</span> foi sempre <span class="math inline">\(2\)</span>, fixado porque o rótulo (usado só para avaliar) já sugeria isso. Sem rótulo, <span class="math inline">\(K\)</span> é uma escolha aberta.</p>
</div>
<div class="fragment">
<p>“Maximizar a verossimilhança” para escolher <span class="math inline">\(K\)</span> falha: mais componentes sempre pode aumentar (ou não piorar) a verossimilhança — no limite, um componente minúsculo por ponto. Mesma singularidade do Bloco 4, em escala maior.</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ponte para a Aula 5</strong></p>
</div>
<div class="callout-content">
<p>Como escolher <span class="math inline">\(K\)</span> sem esse overfitting: o EM desta aula, sem priori sobre <span class="math inline">\(\theta\)</span>, não pode penalizar complexidade por construção. Uma priori de verdade sobre <span class="math inline">\(\theta\)</span> devolve essa penalidade via KL (o <strong>ELBO</strong> com Navalha de Occam) — complementado por validação <strong>empírica</strong> (dados nunca vistos no ajuste) quando não há via analítica.</p>
</div>
</div>
</div>
<p><a href="../../../teaching/unsupervised-learning/aula04/exercicios.html" class="see-all exercicios-link" aria-label="Ver exercícios" title="Ver exercícios">Exercícios</a> <a href="../../../teaching/unsupervised-learning/aula04/soluções.html" class="see-all solucoes-link" aria-label="Ver soluções" title="Ver soluções">Soluções</a></p>
</section>
<section id="pergunta-4" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se, em vez de fixar <span class="math inline">\(K=2\)</span>, alguém rodasse o GMM desta aula com <span class="math inline">\(K=10\)</span> no mesmo par de atributos do Breast Cancer Wisconsin, o que aconteceria com a log-verossimilhança final, comparada à obtida com <span class="math inline">\(K=2\)</span>?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense se adicionar componentes pode, na pior das hipóteses, só “copiar” o comportamento de uma solução com menos componentes (por exemplo, atribuindo peso <span class="math inline">\(\pi_k\approx0\)</span> a componentes extras) — e o que isso implica sobre a direção da mudança na verossimilhança.</p>
<ul>
<li>□ A log-verossimilhança ótima obtida com <span class="math inline">\(K=10\)</span> nunca pode ser pior (menor) do que a obtida com <span class="math inline">\(K=2\)</span>, porque qualquer solução de <span class="math inline">\(K=2\)</span> pode ser reproduzida com <span class="math inline">\(K=10\)</span> atribuindo peso <span class="math inline">\(\pi_k\approx0\)</span> aos <span class="math inline">\(8\)</span> componentes extras.</li>
<li>□ Escolher o valor de <span class="math inline">\(K\)</span> que maximiza a log-verossimilhança nos dados de treino é, por esse motivo, um critério confiável para encontrar o número “certo” de componentes.</li>
<li>□ O mesmo tipo de problema (mais parâmetros sempre ajustando melhor aos dados observados, sem necessariamente generalizar melhor) já apareceu nesta disciplina antes desta aula, embora em outro contexto matemático.</li>
<li>□ Se um dos <span class="math inline">\(10\)</span> componentes colapsar sua covariância sobre um único ponto de dado (a singularidade do Bloco 4), isso tornaria a log-verossimilhança bem definida, porém artificialmente baixa.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-4" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resposta — mais componentes, mais verossimilhança?</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ <span class="math inline">\(K=10\)</span> nunca fica pior que <span class="math inline">\(K=2\)</span> no treino — pode sempre “imitar” a solução menor zerando o peso dos componentes extras.</li>
<li>✗ Justamente por isso não é confiável — o critério tende sempre a favorecer mais componentes, não o número real.</li>
<li>✔ Sim — é a mesma lógica de overfitting já vista (por exemplo, mais atributos/flexibilidade sempre ajustando melhor os dados de treino, sem generalizar).</li>
<li>✗ Colapsar sobre um ponto <strong>não</strong> dá uma verossimilhança baixa — dá uma verossimilhança tendendo a <strong>infinito</strong> (Bloco 4), o oposto de “baixa” e ainda mais artificial.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> mais componentes sempre ajuda a verossimilhança de treino — por isso ela sozinha não serve para escolher <span class="math inline">\(K\)</span>. A Aula 5 mostra por que penalizar essa flexibilidade exige colocar os parâmetros dentro do próprio critério de ajuste (uma priori de verdade, não só mais dados) — e o que fazer quando isso não é possível analiticamente.</p>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>UNICAMP — Instituto de Computação</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"boardmarkerWidth":3,"chalkWidth":3},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 800,

        // Factor of the display size that should remain empty around the content
        margin: 2.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <div class="custom-footer-logos">
      <a href="notas.html" class="back-arrow-slide" title="Voltar às notas" aria-label="Voltar às notas"><i class="bi bi-book-half" aria-hidden="true"></i></a>
      <img src="../../UNICAMP.png" alt="UNICAMP">
      <img src="../../IC.png" alt="Instituto de Computação">
    </div>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>