{
  "hash": "48174c9911373b2381fb5052c1ce6a2f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Regressão Linear e Máxima Verossimilhança\"\nsubtitle: \"Aula 6 — Por Que Mínimos Quadrados É Máxima Verossimilhança Sob Ruído Gaussiano\"\nauthor: \"Marcos M. Raimundo — Instituto de Computação, UNICAMP\"\ndate: \"2026-09-07\"\nlang: pt-BR\nformat:\n  html:\n    include-after-body: ../../lesson-toc-accordion.html\n    output-file: notas.html\n    theme: [flatly, ../../../custom.scss, ../../lesson-theme.scss]\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    fig-width: 6\n    fig-height: 3.5\n  revealjs:\n    transition: slide\n    width: 1280\n    height: 800\n    margin: 0.02\n    fig-responsive: true\n    fig-format: \"svg\"\n    footer: \"UNICAMP — Instituto de Computação\"\n    chalkboard:\n      boardmarker-width: 3\n      chalk-width: 3\n    include-in-header: ../../bootstrap-icons-header.html\n    include-after-body: ../../logos-footer.html\n    title-slide-attributes:\n      data-background-image: \"../../UNICAMP.png, ../../IC.png\"\n      data-background-size: \"140px, 140px\"\n      data-background-position: \"5% 8%, 95% 8%\"\n    output-file: slides.html\n    slide-number: true\n    smaller: true\n    scrollable: true\n    theme: [simple, ../../lesson-theme.scss]\njupyter: homepage\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n[Slides](slides.html){.see-all aria-label=\"Ver slides\" title=\"Ver slides\"}\n[Lista de aulas](../index.qmd){.see-all .lesson-list-link aria-label=\"Lista de aulas\" title=\"Lista de aulas\"}\n:::\n\n\n\n# Abertura — Da Estrutura de Três Peças a um Alvo Contínuo\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nA Aula 5 revisou as quatro primeiras aulas do curso e mostrou que, por trás\nda fachada de \"algoritmos diferentes\" (Beta e limiar, Naive Bayes, árvores,\nCV/Bootstrap), havia sempre a mesma estrutura de três peças: uma\n**distribuição** assumida sobre os dados, uma **verossimilhança** usada\npara ajustá-la, e uma **decisão** fundamentada em risco. A aula terminou\nanunciando exatamente o que faltava: em nenhuma das quatro lentes a\nverossimilhança foi construída sobre um **alvo contínuo ligado linearmente\naos atributos** — sempre foi sobre uma densidade unidimensional, uma\nfatoração de independência, ou uma proporção categórica numa folha.\n\nHoje fechamos essa lacuna e abrimos a \"Parte 2: A História Linear\nParamétrica\" do curso. O objeto de hoje — Regressão Linear — é, à primeira\nvista, o modelo mais simples que existe: ajustar uma reta (ou, em mais\ndimensões, um hiperplano) que atravesse uma nuvem de pontos. Mas por trás\ndessa simplicidade geométrica mora exatamente a mesma estrutura\ndistribuição $\\to$ verossimilhança $\\to$ decisão da Aula 5 — só que, desta\nvez, vamos **provar** algebricamente a conexão entre a versão geométrica\n(mínimos quadrados) e a versão estatística (máxima verossimilhança sob\nruído gaussiano), em vez de apenas apontá-la.\n\n**O roteiro de hoje, em quatro perguntas:**\n\n1. Geometricamente, o que significa \"a melhor reta\" — e por que elevar o\n   erro ao quadrado, em vez de somar os erros diretamente ou usar valor\n   absoluto?\n2. Como escrever esse problema em notação matricial, e por que a solução\n   tem uma forma fechada exata (as \"equações normais\")?\n3. O que muda se, em vez de só minimizar um erro, assumirmos uma história\n   probabilística completa — ruído gaussiano em torno da reta — e\n   construirmos a verossimilhança dessa história?\n4. Por que maximizar essa verossimilhança **é**, algebricamente, minimizar\n   a soma de quadrados — e o que essa coincidência revela sobre o resto do\n   curso?\n\n**O problema motivador.** *California Housing* já apareceu na Aula 3 —\n`MedInc` (renda mediana da região, em dezenas de milhares de dólares) e\n`HouseAge` (idade mediana dos imóveis) foram usados como atributos de uma\nárvore. Hoje usamos `MedInc` para prever `MedHouseVal` (preço mediano do\nimóvel, em centenas de milhares de dólares) diretamente — um alvo\ncontínuo, não mais uma classe. Olhando para a nuvem de pontos completa\n($N=16\\,640$ regiões), a pergunta é simples de fazer e nada óbvia de\nresponder com precisão: **qual é a melhor reta que passa por essa nuvem, e\no que \"melhor\" quer dizer aqui?**\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Da Aula 5 para Hoje\n\nA Aula 5 revisou 4 aulas: sempre a mesma estrutura — **distribuição $\\to$ verossimilhança $\\to$ decisão**.\n\n::: {.fragment}\nMas nenhuma das quatro verossimilhanças foi sobre um **alvo contínuo ligado linearmente aos atributos**. Sempre densidade 1D, fatoração, ou proporção categórica.\n:::\n\n::: {.fragment}\n**Hoje:** Regressão Linear — o modelo mais simples que existe, geometricamente (ajustar uma reta). Mas por trás, a mesma estrutura de sempre — e desta vez vamos **provar** a conexão, não só apontá-la.\n:::\n\n## Roteiro — Quatro Perguntas\n\n::: {.fragment}\n**1.** O que é \"a melhor reta\" geometricamente — e por que elevar o erro ao quadrado?\n:::\n\n::: {.fragment}\n**2.** Como escrever isso em notação matricial, com solução fechada exata?\n:::\n\n::: {.fragment}\n**3.** O que muda ao assumir uma história probabilística completa — ruído gaussiano — e construir sua verossimilhança?\n:::\n\n::: {.fragment}\n**4.** Por que maximizar essa verossimilhança **é** minimizar soma de quadrados — o que isso revela para o resto do curso?\n:::\n\n## O Problema de Hoje\n\n- *California Housing*: já usado na Aula 3 (`MedInc`, `HouseAge` como atributos de árvore).\n- Hoje: `MedInc` (renda mediana, US\\$10 mil) prevendo `MedHouseVal` (preço mediano, US\\$100 mil) — um **alvo contínuo**, não mais uma classe.\n\n::: {.fragment}\n$N=16\\,640$ regiões. **Qual é a melhor reta pela nuvem de pontos — e o que \"melhor\" quer dizer?**\n:::\n\n:::\n\n::: {#e01e8117 .cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\nN = 16640\ncorrelação(MedInc, MedHouseVal) = 0.672\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Se eu te desse duas retas diferentes, ambas passando \"no meio\" da nuvem de pontos, como você decidiria qual é \"melhor\" sem fazer nenhuma conta?\n\nDica: pense no que aconteceria com pontos muito distantes da reta em cada caso — os dois candidatos tratam esses pontos da mesma forma?\n:::\n\n::: {.callout-tip}\n## Antes de Ajustar: O que \"Melhor Reta\" Já Pressupõe?\n\n- □ Duas retas que passam pelo mesmo ponto médio $(\\bar x,\\bar y)$ da nuvem de dados são necessariamente igualmente boas, pois ambas capturam a tendência central dos dados.\n- □ Se todos os pontos da nuvem estivessem exatamente sobre uma única reta (sem nenhum ruído), qualquer critério razoável de \"melhor reta\" — soma de quadrados, soma de valores absolutos, ou até maior desvio único — apontaria para essa mesma reta.\n- □ Um termostato que tenta prever a temperatura de amanhã a partir da temperatura de hoje enfrenta exatamente o mesmo problema estrutural de \"ajustar a melhor reta\" que o preço de imóveis enfrenta aqui, ainda que o contexto seja completamente diferente — e por isso a inclinação ótima nesse problema seria necessariamente próxima de 1 (a temperatura de amanhã imita quase exatamente a de hoje), assim como aqui a inclinação relaciona renda a preço de forma direta.\n- □ Se decidíssemos julgar \"melhor reta\" pela soma dos desvios (não ao quadrado, sem valor absoluto) entre pontos e reta, qualquer reta que passasse pela média dos dados $(\\bar x,\\bar y)$ teria soma de desvios exatamente zero — inclusive retas claramente ruins, giradas em ângulos absurdos.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Antes de Ajustar: O que \"Melhor Reta\" Já Pressupõe? — Resposta\n\n::: {.callout-tip}\n- ✗ Mesmo ponto médio não implica mesma inclinação nem mesma qualidade de ajuste — duas retas girando em torno de $(\\bar x,\\bar y)$ com inclinações muito diferentes tratam os desvios de forma completamente distinta.\n- ✔ Sem ruído, todos os critérios razoáveis concordam porque existe uma reta com erro zero em qualquer medida — a distinção entre critérios só importa quando há ruído genuíno.\n- ✗ A estrutura do problema (ajustar a melhor reta a pares $(x,y)$) é a mesma, mas nada garante que a inclinação ótima seja próxima de 1 — isso dependeria inteiramente de quão preditivo $x$ é de $y$ naquele domínio específico, não da forma do problema.\n- ✔ Este é o ponto central: somar desvios sem elevar ao quadrado é degenerado — **qualquer** reta pela média tem soma de desvios zero, inclusive as absurdas. É exatamente por isso que \"melhor reta\" precisa de um critério mais informativo, como a soma de quadrados.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** \"melhor\" não pode ser só \"passa perto da média\" — precisa penalizar desvios de um jeito que distinga retas boas de ruins. É isso que a soma de quadrados resolve, e é para lá que vamos agora.\n:::\n\n:::\n\n# Intuição — A Ideia Geométrica de Mínimos Quadrados\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nAntes de qualquer matriz, vale fixar a ideia em sua forma mais simples. Para\ncada imóvel $i$, a reta candidata prediz $\\hat y_i = \\beta_0+\\beta_1 x_i$;\no **resíduo** é a diferença $e_i = y_i-\\hat y_i$ entre o valor real e o\nvalor predito. A pausa ativa que acabamos de resolver já revelou o\nproblema de somar os $e_i$ diretamente: o resultado é zero para *qualquer*\nreta que passe pela média dos dados, boa ou ruim, porque resíduos positivos\ne negativos se cancelam.\n\nA solução clássica é somar o **quadrado** dos resíduos,\n$\\sum_i e_i^2$, e escolher $\\beta_0,\\beta_1$ que minimizem essa soma. O\nquadrado resolve o problema do cancelamento (todo termo é não-negativo) e\ntem duas vantagens adicionais que vão importar mais adiante: é diferenciável\nem toda parte (ao contrário do valor absoluto, que tem um \"bico\" em zero,\ncomplicando a busca pelo mínimo), e penaliza desvios grandes\ndesproporcionalmente mais que desvios pequenos — um resíduo de $2$ pesa\nquatro vezes mais que um resíduo de $1$, não duas.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resíduo: A Distância Entre Predição e Realidade\n\n- Reta candidata: $\\hat y_i=\\beta_0+\\beta_1 x_i$. **Resíduo:** $e_i=y_i-\\hat y_i$.\n- A pausa anterior já mostrou: somar $e_i$ direto é degenerado (zero para qualquer reta pela média).\n\n::: {.fragment}\n**Solução clássica:** minimizar $\\sum_i e_i^2$, não $\\sum_i e_i$.\n:::\n\n::: {.fragment}\nPor quê o quadrado? (1) elimina o cancelamento — todo termo $\\ge 0$; (2) diferenciável em toda parte, ao contrário do valor absoluto (que tem um \"bico\" em zero); (3) penaliza desvios grandes desproporcionalmente mais — resíduo $2$ pesa $4\\times$ mais que resíduo $1$, não $2\\times$.\n:::\n\n:::\n\n::: {#6eaec305 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-4-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n::: {.fig-resize style=\"width: 90%; margin: 0 auto;\"}\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nA figura mostra $45$ imóveis reais (amostra para não poluir o gráfico) com\nseus resíduos verticais em relação à reta que vamos justificar como \"a\nmelhor\" ao longo desta aula. Note que a reta não passa exatamente por\nnenhum ponto — isso é esperado: com ruído genuíno nos dados, nenhuma reta\núnica acerta todos os pontos, e o objetivo nunca foi acertar todos, e sim\nminimizar o total de erro ao quadrado.\n\n:::\n\n# Bloco 1 — Formalização: RSS, Equações Normais e Projeção\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nGeneralizando a intuição anterior para $p$ atributos e $N$ observações,\norganizamos os dados numa **matriz de projeto** $X$, de dimensão\n$N\\times(p{+}1)$: cada linha é um imóvel, a primeira coluna é constante\nigual a $1$ (o intercepto), e as demais colunas são os atributos. O vetor\nde coeficientes é $\\beta=(\\beta_0,\\beta_1,\\ldots,\\beta_p)^T$, e a predição\npara todos os $N$ imóveis de uma vez é o produto matricial $X\\beta$.\nSeguindo a notação de ESL (Hastie, Tibshirani & Friedman), a **soma de\nquadrados dos resíduos** é\n\n$$\n\\text{RSS}(\\beta) = \\sum_{i=1}^N \\big(y_i - f(x_i)\\big)^2 = \\lVert y - X\\beta\\rVert^2.\n$$\n\nComo o próprio livro descreve o critério (ESL, §3.2, p. 44, tradução\nnossa): \"o método de estimação mais popular é mínimos quadrados, no qual\nescolhemos os coeficientes $\\beta=(\\beta_0,\\beta_1,\\ldots,\\beta_p)^T$ para\nminimizar a soma residual de quadrados $\\text{RSS}(\\beta)=\\sum_{i=1}^N(y_i-f(x_i))^2$.\"\n\n**Derivando a solução.** $\\text{RSS}(\\beta)$ é uma função quadrática (logo\nconvexa) de $\\beta$ — diferenciando em relação a $\\beta$ (ESL, §3.2, p. 45,\ntradução nossa):\n\n> \"Diferenciando em relação a $\\beta$ obtemos $\\partial\\text{RSS}/\\partial\\beta=-2X^T(y-X\\beta)$\n> [...] Assumindo (por enquanto) que $X$ tem posto de coluna completo, e\n> portanto $X^TX$ é positiva definida, igualamos a primeira derivada a\n> zero $X^T(y-X\\beta)=0$ para obter a solução única $\\hat\\beta=(X^TX)^{-1}X^Ty$.\"\n\nEssas são as chamadas **equações normais**. Não são um truque isolado: o\nPRML chega ao mesmo lugar por outro caminho (o gradiente da\nlog-verossimilhança gaussiana, que vamos percorrer no Bloco 3), e nomeia o\nmesmo resultado (PRML, §3.1.1, p. 142, tradução nossa): \"resolvendo para\n$w$ obtemos $w_{\\text{ML}}=(\\Phi^T\\Phi)^{-1}\\Phi^Tt$, conhecidas como as\nequações normais para o problema de mínimos quadrados.\"\n\n::: {.callout-note}\n## O caso geral: hiperplanos, não só retas\n\nCom $p=1$ atributo (nosso exemplo de hoje), $X\\beta$ é uma reta no plano\n$(x,y)$. Com $p>1$ atributos, exatamente a mesma equação\n$\\hat\\beta=(X^TX)^{-1}X^Ty$ vale sem nenhuma mudança — só que agora\n$X\\beta$ descreve um **hiperplano** no espaço de $p{+}1$ dimensões. Um\najuste rápido usando os $8$ atributos do *California Housing* (não só\n`MedInc`) chega a $R^2\\approx0{,}584$, contra $R^2\\approx0{,}451$ usando só\n`MedInc` — mais atributos explicam mais variação, mas a equação que os\ncombina é a mesma.\n:::\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Notação Matricial: RSS\n\n- Matriz de projeto $X$ ($N\\times(p{+}1)$): cada linha um imóvel, 1ª coluna $=1$ (intercepto), demais colunas atributos.\n- $\\beta=(\\beta_0,\\ldots,\\beta_p)^T$; predição para todos de uma vez: $X\\beta$.\n\n::: {.fragment}\n$$\\text{RSS}(\\beta) = \\sum_{i=1}^N(y_i-f(x_i))^2 = \\lVert y-X\\beta\\rVert^2$$\n\nESL, §3.2: \"o método de estimação mais popular é mínimos quadrados, no qual escolhemos $\\beta$ para minimizar a soma residual de quadrados.\"\n:::\n\n## Derivando as Equações Normais\n\n::: {.fragment}\n$\\text{RSS}(\\beta)$ é quadrática (convexa) em $\\beta$: $\\dfrac{\\partial\\text{RSS}}{\\partial\\beta}=-2X^T(y-X\\beta)$.\n:::\n\n::: {.fragment}\nAssumindo $X$ com posto de coluna completo ($X^TX$ positiva definida), igualamos a zero: $X^T(y-X\\beta)=0$.\n:::\n\n::: {.fragment}\n**Solução única:** $\\hat\\beta=(X^TX)^{-1}X^Ty$ — as **equações normais** (ESL, p. 45; PRML chega ao mesmo resultado via gradiente da log-verossimilhança, Bloco 3).\n:::\n\n## O Caso Geral: Hiperplanos\n\n- $p=1$ (hoje): $X\\beta$ é uma **reta** no plano $(x,y)$.\n- $p>1$: mesma equação $\\hat\\beta=(X^TX)^{-1}X^Ty$, sem mudança — $X\\beta$ vira um **hiperplano**.\n\n::: {.fragment}\nAjuste com os $8$ atributos do *California Housing*: $R^2\\approx0{,}584$ vs. $R^2\\approx0{,}451$ só com `MedInc`. Mais atributos, mais variação explicada — mesma equação.\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 78%; margin: 0 auto;\"}\n```{.tikz}\n\\definecolor{colobs}{RGB}{192,57,43}\n\\definecolor{colproj}{RGB}{36,113,163}\n\\definecolor{colresid}{RGB}{93,109,126}\n\n\\begin{tikzpicture}[>=stealth, line width=1pt, font=\\small]\n  \\fill[colproj!12] (-1.2,-0.8) -- (5.2,-1.6) -- (6.2,2.2) -- (-0.2,3.0) -- cycle;\n  \\draw[colproj, thick] (-1.2,-0.8) -- (5.2,-1.6) -- (6.2,2.2) -- (-0.2,3.0) -- cycle;\n  \\node[colproj] at (2.0,-1.35) {$\\mathcal S=\\text{span}(\\varphi_1,\\varphi_2)$};\n\n  \\draw[->, colproj, thick] (0,0) -- (4.0,-0.9) node[below right] {$\\varphi_1$ (coluna do intercepto)};\n  \\draw[->, colproj, thick] (0,0) -- (1.1,2.1) node[above left] {$\\varphi_2$ (coluna de \\texttt{MedInc})};\n\n  \\draw[->, colproj!65!black, ultra thick] (0,0) -- (3.0,0.6) node[below right] {$\\hat y = X\\hat\\beta$};\n  \\draw[->, colobs, ultra thick] (0,0) -- (3.6,3.4) node[above] {$y$ (\\texttt{MedHouseVal} observado)};\n  \\draw[dashed, colresid, thick] (3.0,0.6) -- (3.6,3.4);\n  \\node[colresid, align=left] at (5.4,2.3) {$y-\\hat y$\\\\resíduo, $\\perp$ a $\\mathcal S$};\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nO diagrama redesenha a interpretação geométrica que PRML (§3.1.2, p. 143)\ne ESL (§3.2, p. 46) descrevem de formas equivalentes. No PRML, cada\ncoluna da matriz de projeto é vista como um vetor $\\varphi_j$ num espaço\nde dimensão $N$ (tradução nossa): \"a esse ponto, é instrutivo considerar a\ninterpretação geométrica da solução de mínimos quadrados [...] a solução\nde mínimos quadrados para $w$ corresponde à escolha de $y$ que está no\nsubespaço $\\mathcal S$ mais próxima de $t$ [...] antecipamos que essa\nsolução corresponde à projeção ortogonal de $t$ sobre o subespaço\n$\\mathcal S$.\" O ESL descreve a mesma figura assim (tradução nossa,\nlegenda da Fig. 3.2 do livro): \"o vetor de resultados $y$ é projetado\nortogonalmente sobre o hiperplano gerado pelos vetores de entrada $x_1$ e\n$x_2$ [...] essa ortogonalidade está expressa em (3.5), e a estimativa\nresultante $\\hat y$ é, portanto, a projeção ortogonal de $y$ sobre esse\nsubespaço.\"\n\nAqui, com apenas `MedInc` como atributo, $\\mathcal S$ é gerado por só dois\nvetores: $\\varphi_1$ (a coluna constante do intercepto) e $\\varphi_2$ (a\ncoluna com os valores de `MedInc` de cada imóvel), ambos vetores em\n$\\mathbb R^N$ com $N=16\\,640$ coordenadas — uma por imóvel. $\\hat y$\nprecisa estar **dentro** desse subespaço porque é, por definição, uma\ncombinação linear das colunas de $X$ ($\\hat y=X\\hat\\beta=\\hat\\beta_0\\varphi_1+\\hat\\beta_1\\varphi_2$);\nnão existe combinação de $\\varphi_1,\\varphi_2$ que produza qualquer vetor\nfora de $\\mathcal S$. O ponto de $\\mathcal S$ mais próximo do vetor\nobservado $y$ (a distância euclidiana em $\\mathbb R^N$ é exatamente\n$\\sqrt{\\text{RSS}}$) é a projeção ortogonal — e é exatamente isso que a\nequação normal calcula.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## A Geometria: Projeção Ortogonal\n\n- Cada coluna de $X$ é um vetor $\\varphi_j\\in\\mathbb R^N$ ($N=16\\,640$ imóveis, uma coordenada por imóvel).\n- $\\hat y=X\\hat\\beta$ está sempre **dentro** de $\\mathcal S=\\text{span}(\\varphi_1,\\varphi_2)$ — é uma combinação linear das colunas, por definição.\n\n::: {.fragment}\nPRML: \"a solução de mínimos quadrados para $w$ corresponde à escolha de $y$ que está no subespaço $\\mathcal S$ mais próxima de $t$ [...] a projeção ortogonal de $t$ sobre $\\mathcal S$.\"\n:::\n\n::: {.fragment}\nESL: \"$y$ é projetado ortogonalmente sobre o hiperplano gerado pelos vetores de entrada [...] $\\hat y$ é a projeção ortogonal de $y$ sobre esse subespaço.\"\n:::\n\n::: {.fragment}\n$\\lVert y-\\hat y\\rVert=\\sqrt{\\text{RSS}}$: a distância entre o ponto observado e o subespaço — minimizada exatamente pela equação normal.\n:::\n\n:::\n\n::: {#281adaf4 .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\nbeta_hat (equações normais) = (0.4707, 0.4076)\nRSS = 11710.64\nR^2 = 0.451\n```\n:::\n:::\n\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#5903c1ac .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-7-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nSobre a base completa de treino ($N=16\\,640$), a equação normal dá\n$\\hat\\beta=(0{,}4707,\\,0{,}4076)$: cada aumento de US\\$$10$ mil na renda\nmediana da região está associado a um acréscimo médio de US\\$$40{,}76$ mil\nno preço mediano do imóvel, com um intercepto de US\\$$47{,}07$ mil.\nO ajuste explica $R^2\\approx0{,}451$ da variância de `MedHouseVal` — nem\nperfeito, nem inútil: a correlação entre as duas variáveis é\n$0{,}672$, moderada a forte, mas claramente longe de $1$ (a figura mostra\numa nuvem larga em torno da reta, não uma linha fina de pontos). Guarde\n$\\hat\\beta$ e $\\text{RSS}\\approx11\\,710{,}64$ — esses números vão\nreaparecer, sem nenhuma conta nova, quando provarmos no Bloco 3 que a\nmáxima verossimilhança gaussiana leva exatamente a esse mesmo ponto.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## O Ajuste, Sobre Dado Real\n\n- $N=16\\,640$: $\\hat\\beta=(0{,}4707,\\ 0{,}4076)$ — cada US\\$$10$ mil de renda mediana $\\to{+}$US\\$$40{,}76$ mil de preço mediano.\n- $R^2\\approx0{,}451$; correlação $=0{,}672$ (moderada-forte, longe de $1$ — nuvem larga em torno da reta).\n\n::: {.fragment}\n**Guardar:** $\\hat\\beta=(0{,}4707,0{,}4076)$ e $\\text{RSS}\\approx11\\,710{,}64$ — vão reaparecer intactos no Bloco 3, vindos de máxima verossimilhança.\n:::\n\n:::\n\n::: {.callout-tip}\n## Geometricamente, por que o vetor de resíduos $y-\\hat y$ ser ortogonal ao subespaço gerado pelas colunas de $X$ é exatamente a condição que caracteriza a MELHOR aproximação, e não uma coincidência do cálculo?\n\nDica: pense em o que aconteceria com a distância $\\lVert y-\\hat y\\rVert$ se $\\hat y$ se movesse um pouco dentro do subespaço, saindo do ponto ortogonal.\n:::\n\n::: {.callout-tip}\n## Projeção, Resíduos e Equações Normais\n\n- □ Se, em vez de minimizar $\\lVert y-X\\beta\\rVert^2$, o critério fosse minimizar $\\lVert y-X\\beta\\rVert$ (a distância, sem elevar ao quadrado), o mesmo $\\hat\\beta$ ainda resolveria o problema, porque minimizar uma distância e minimizar seu quadrado são operações que sempre produzem o mesmo ponto de mínimo (a raiz quadrada é crescente para distâncias não-negativas).\n- □ Se as colunas de $X$ fossem linearmente dependentes (por exemplo, uma coluna sendo o dobro exato da outra), $X^TX$ deixaria de ser invertível, e a equação $\\hat\\beta=(X^TX)^{-1}X^Ty$ deixaria de ter solução única — mas a projeção $\\hat y=X\\hat\\beta$ continuaria bem definida e única.\n- □ Num algoritmo de recomendação que aproxima as avaliações de um usuário como combinação linear de \"perfis latentes\" pré-definidos, a mesma lógica de projeção ortogonal sobre o subespaço gerado pelos perfis ainda encontraria a melhor aproximação, no mesmo sentido de menor distância euclidiana — e essa melhor aproximação seria sempre única, mesmo que os perfis latentes fossem linearmente dependentes entre si.\n- □ Como a equação normal $X^T(y-X\\hat\\beta)=0$ garante que o resíduo é ortogonal a todas as colunas de $X$, conclui-se que o resíduo $y-X\\hat\\beta$ é necessariamente o vetor nulo sempre que $X$ tiver pelo menos uma coluna.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Projeção, Resíduos e Equações Normais — Resposta\n\n::: {.callout-tip}\n- ✔ Correto: como a raiz quadrada é estritamente crescente em distâncias não-negativas, o ponto que minimiza $\\lVert y-X\\beta\\rVert^2$ é o mesmo que minimiza $\\lVert y-X\\beta\\rVert$.\n- ✔ Exatamente o caso não-full-rank do ESL (p. 46): $X^TX$ singular quebra a unicidade de $\\hat\\beta$, mas $\\hat y=X\\hat\\beta$ continua sendo a (única) projeção de $y$ sobre $\\mathcal S$ — só há mais de uma forma de escrevê-la.\n- ✗ A lógica de projeção continua valendo, mas a unicidade **não**: perfis latentes linearmente dependentes tornam $X^TX$ singular, e nesse caso há infinitas combinações de coeficientes que atingem a mesma projeção — a mesma ressalva do item anterior.\n- ✗ Ortogonalidade ao subespaço não implica resíduo nulo — só implica que o resíduo não tem nenhuma componente **dentro** de $\\mathcal S$. Se $y$ não estiver em $\\mathcal S$ para começo de conversa (o caso típico com ruído real), o resíduo é não-nulo e ainda assim ortogonal a $\\mathcal S$.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** não é coincidência — mover $\\hat y$ para qualquer outro ponto de $\\mathcal S$ só pode *aumentar* $\\lVert y-\\hat y\\rVert$ (Pitágoras: qualquer componente de deslocamento dentro de $\\mathcal S$ soma um termo positivo à distância). Ortogonalidade é a única forma de $\\hat y$ não deixar \"sobra\" evitável dentro do subespaço.\n:::\n\n:::\n\n# Bloco 2 — O Modelo de Ruído Gaussiano Homocedástico\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nAté aqui, tudo foi álgebra: minimizar uma soma de quadrados não pressupõe\nnenhuma distribuição de probabilidade — funciona mesmo que os dados não\ntenham vindo de nenhum \"processo aleatório\" reconhecível (ESL já observa\nisso, p. 45: \"mínimos quadrados é intuitivamente satisfatório não importa\ncomo os dados surjam\"). Mas, seguindo o mesmo padrão de todas as aulas\nanteriores (Aula 5, Bloco 5), queremos ir além do critério algébrico e\nperguntar: **que história estatística sobre como os dados foram gerados\ntornaria mínimos quadrados a escolha *certa*, não apenas conveniente?**\n\nSeguindo a regra desta disciplina de anunciar premissas antes de usá-las,\no modelo assumido hoje é (PRML, §3.1.1, p. 140, tradução nossa):\n\n> \"Como antes, assumimos que a variável-alvo $t$ é dada por uma função\n> determinística $y(\\mathbf x,\\mathbf w)$ com ruído gaussiano aditivo, de\n> forma que $t=y(\\mathbf x,\\mathbf w)+\\epsilon$, onde $\\epsilon$ é uma\n> variável aleatória gaussiana de média zero com precisão (variância\n> inversa) $\\beta$. Assim podemos escrever\n> $p(t\\mid\\mathbf x,\\mathbf w,\\beta)=\\mathcal N(t\\mid y(\\mathbf x,\\mathbf w),\\beta^{-1})$.\"\n\nTraduzindo para a notação desta disciplina (usamos $\\sigma^2$ no lugar da\nprecisão $\\beta$ do PRML, para não colidir com o $\\beta$ que já reservamos\npara os coeficientes da reta — mais uma vez, uma colisão de símbolos entre\nlivros diferentes, do tipo que a Aula 5 já avisou existir), as premissas\ncompletas são:\n\n1. **Linearidade condicional:** $\\mathbb E[Y\\mid X=x]=\\beta^Tx$ — a média\n   da resposta é exatamente a reta/hiperplano.\n2. **Ruído gaussiano aditivo:** $Y=\\beta^TX+\\epsilon$, com\n   $\\epsilon\\sim\\mathcal N(0,\\sigma^2)$.\n3. **Homocedasticidade:** $\\sigma^2$ é a **mesma constante** para todo\n   valor de $x$ — o \"tamanho típico\" do ruído não muda com a renda, a\n   idade do imóvel, ou qualquer outro atributo.\n4. **Independência entre observações:** os erros $\\epsilon_1,\\ldots,\\epsilon_N$\n   são mutuamente independentes.\n\nJuntas, essas quatro premissas equivalem a dizer\n$Y\\mid X=x \\sim \\mathcal N(\\beta^Tx,\\sigma^2)$ — uma gaussiana cuja média\nse desloca com $x$, mas cuja variância nunca muda.\n\n**Construindo a verossimilhança, passo a passo.** Com $N$ observações\n$(x_i,y_i)$ e a premissa de independência (4), a densidade conjunta dos\ndados é o **produto** das densidades individuais (PRML, §3.1.1, p. 141,\ntradução nossa):\n\n> \"Considere agora um conjunto de dados de entradas\n> $X=\\{\\mathbf x_1,\\ldots,\\mathbf x_N\\}$ com valores-alvo correspondentes\n> $t_1,\\ldots,t_N$. [...] Assumindo que esses pontos de dados são obtidos\n> independentemente da distribuição (3.8), obtemos a seguinte expressão\n> para a função de verossimilhança, que é uma função dos parâmetros\n> ajustáveis $\\mathbf w$ e $\\beta$, na forma\n> $p(\\mathbf t\\mid X,\\mathbf w,\\beta)=\\prod_{n=1}^N\\mathcal N(t_n\\mid\\mathbf w^T\\boldsymbol\\phi(\\mathbf x_n),\\beta^{-1})$.\"\n\nNa notação de $\\beta$-coeficientes e $\\sigma^2$-variância desta aula:\n\n$$\nL(\\beta,\\sigma^2) = p(y_1,\\ldots,y_N\\mid X,\\beta,\\sigma^2) = \\prod_{i=1}^N \\mathcal N(y_i\\mid\\beta^Tx_i,\\sigma^2) = \\prod_{i=1}^N \\frac{1}{\\sqrt{2\\pi\\sigma^2}}\\exp\\left\\{-\\frac{(y_i-\\beta^Tx_i)^2}{2\\sigma^2}\\right\\}.\n$$\n\nProdutos de exponenciais são desconfortáveis de derivar; tomamos o\nlogaritmo (uma função estritamente crescente, então o ponto de máximo não\nmuda) para transformar o produto em soma:\n\n$$\n\\ell(\\beta,\\sigma^2) = \\ln L(\\beta,\\sigma^2) = \\sum_{i=1}^N \\left[-\\tfrac12\\ln(2\\pi\\sigma^2) - \\frac{(y_i-\\beta^Tx_i)^2}{2\\sigma^2}\\right] = -\\frac N2\\ln(2\\pi) - N\\ln\\sigma - \\frac{1}{2\\sigma^2}\\sum_{i=1}^N(y_i-\\beta^Tx_i)^2.\n$$\n\nNote que $\\sum_{i=1}^N(y_i-\\beta^Tx_i)^2$ é exatamente $\\text{RSS}(\\beta)$\ndo Bloco 1 — a mesma quantidade, chegando por um caminho completamente\ndiferente (uma história sobre ruído aleatório, não um critério algébrico\narbitrário). Essa coincidência não é acidental: é o que o Bloco 3 vai\nprovar.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Além da Álgebra: Que História Gera os Dados?\n\n- Minimizar RSS não pressupõe nenhuma distribuição — funciona \"não importa como os dados surjam\" (ESL, p. 45).\n- **Pergunta de hoje:** que história estatística tornaria mínimos quadrados a escolha *certa*, não só conveniente?\n\n::: {.fragment}\nPRML: \"assumimos que a variável-alvo $t$ é dada por uma função determinística $y(\\mathbf x,\\mathbf w)$ com ruído gaussiano aditivo [...] $p(t\\mid\\mathbf x,\\mathbf w,\\beta)=\\mathcal N(t\\mid y(\\mathbf x,\\mathbf w),\\beta^{-1})$.\"\n:::\n\n## As Quatro Premissas (Anunciadas Antes de Usar)\n\n::: {.fragment}\n**1. Linearidade condicional:** $\\mathbb E[Y\\mid X=x]=\\beta^Tx$.\n:::\n::: {.fragment}\n**2. Ruído gaussiano aditivo:** $Y=\\beta^TX+\\epsilon$, $\\epsilon\\sim\\mathcal N(0,\\sigma^2)$.\n:::\n::: {.fragment}\n**3. Homocedasticidade:** $\\sigma^2$ **constante**, não muda com $x$.\n:::\n::: {.fragment}\n**4. Independência** entre observações.\n:::\n::: {.fragment}\nJuntas: $Y\\mid X=x\\sim\\mathcal N(\\beta^Tx,\\sigma^2)$. Note $\\sigma^2$ (não a precisão $\\beta$ do PRML) — evitando colisão com o $\\beta$ dos coeficientes.\n:::\n\n## Construindo a Verossimilhança — Passo 1: o Produto\n\n::: {.fragment}\nIndependência $\\Rightarrow$ densidade conjunta $=$ **produto** das individuais (PRML, p. 141): \"obtemos [...] $p(\\mathbf t\\mid X,\\mathbf w,\\beta)=\\prod_{n=1}^N\\mathcal N(t_n\\mid\\mathbf w^T\\boldsymbol\\phi(\\mathbf x_n),\\beta^{-1})$.\"\n:::\n\n::: {.fragment}\n$$L(\\beta,\\sigma^2)=\\prod_{i=1}^N \\frac{1}{\\sqrt{2\\pi\\sigma^2}}\\exp\\left\\{-\\frac{(y_i-\\beta^Tx_i)^2}{2\\sigma^2}\\right\\}$$\n:::\n\n## Construindo a Verossimilhança — Passo 2: o Logaritmo\n\n::: {.fragment}\nLog é crescente $\\Rightarrow$ mesmo ponto de máximo, soma em vez de produto:\n:::\n\n::: {.fragment}\n$$\\ell(\\beta,\\sigma^2) = -\\frac N2\\ln(2\\pi) - N\\ln\\sigma - \\frac{1}{2\\sigma^2}\\underbrace{\\sum_{i=1}^N(y_i-\\beta^Tx_i)^2}_{=\\ \\text{RSS}(\\beta),\\ \\text{Bloco 1}}$$\n:::\n\n::: {.fragment}\n**A mesma quantidade do Bloco 1**, chegando por um caminho totalmente diferente — não é acidente. É o que provamos a seguir.\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#19c44adc .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-8-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nA figura torna visível a diferença de perspectiva entre o Bloco 1 e o\nBloco 2. No Bloco 1, a reta era \"o ponto mais próximo\" de $y$ dentro de um\nsubespaço — uma afirmação puramente geométrica. Aqui, a mesma reta é a\nsequência de **médias condicionais**: para cada valor de renda $x$, o\nmodelo afirma que os preços observados são amostras de uma gaussiana\ncentrada em $\\hat\\beta^Tx$ com o mesmo desvio-padrão $\\hat\\sigma=0{,}8389$\nem toda parte (as quatro \"corcovas\" desenhadas têm exatamente a mesma\nlargura) — essa largura constante é, literalmente, a homocedasticidade\ndesenhada.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## A Mesma Reta, Duas Leituras\n\n- **Bloco 1 (geométrica):** a reta é \"o ponto mais próximo\" de $y$ dentro de um subespaço.\n- **Bloco 2 (probabilística):** a reta é a sequência de **médias condicionais** — para cada $x$, $y$ é gaussiano em torno de $\\hat\\beta^Tx$.\n\n::: {.fragment}\nAs quatro \"corcovas\" têm a **mesma largura** ($\\hat\\sigma=0{,}8389$ em toda parte) — isso é a homocedasticidade, desenhada.\n:::\n\n:::\n\n::: {.callout-tip}\n## Se a variância do ruído crescesse conforme a renda mediana aumenta — imóveis mais caros têm preços mais \"espalhados\" — o que exatamente, na construção da verossimilhança de hoje, deixaria de valer?\n\nDica: pense em qual símbolo da verossimilhança conjunta carregaria (ou deixaria de carregar) um índice $n$.\n:::\n\n::: {.callout-tip}\n## Premissas do Ruído Gaussiano Homocedástico\n\n- □ Se $\\sigma^2$ dependesse de $x_n$ (heterocedasticidade), a verossimilhança conjunta ainda seria o produto das densidades individuais (assumindo observações independentes), mas cada fator teria sua própria variância $\\sigma^2(x_n)$ em vez de uma variância comum — mudando a forma da log-verossimilhança final.\n- □ No limite em que $\\sigma^2\\to 0$, a densidade gaussiana $\\mathcal N(y_n\\mid\\beta^Tx_n,\\sigma^2)$ se concentra inteiramente sobre o valor predito $\\beta^Tx_n$, e o modelo probabilístico se aproxima do caso determinístico $y=\\beta^Tx$ sem ruído algum.\n- □ Num sensor de temperatura cujo erro de medição tem desvio-padrão constante independentemente da temperatura real medida, a suposição de homocedasticidade se aplicaria de forma genuína — e, uma vez verificada genuína para esse sensor, permaneceria válida para qualquer outro sensor do mesmo fabricante, sem necessidade de checagem individual.\n- □ Como a verossimilhança de hoje assume que os erros são gaussianos, qualquer conjunto de dados cujos erros não sejam exatamente gaussianos torna a estimativa de mínimos quadrados $\\hat\\beta$ inválida ou inutilizável.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Premissas do Ruído Gaussiano Homocedástico — Resposta\n\n::: {.callout-tip}\n- ✔ Correto — a fatoração em produto (item 4, independência) continua de pé, mas cada fator carregaria seu próprio $\\sigma^2(x_n)$, e a log-verossimilhança teria um termo $\\ln\\sigma(x_n)$ dentro do somatório em vez de um único $N\\ln\\sigma$ fora dele.\n- ✔ Correto — $\\sigma^2\\to0$ colapsa a gaussiana num ponto de massa em $\\beta^Tx_n$, recuperando o caso determinístico como caso-limite do probabilístico.\n- ✗ Verificar homocedasticidade num sensor não garante nada sobre outro sensor, nem do mesmo fabricante — variação de fabricação, calibração e uso exige checagem individual; a suposição nunca \"generaliza de graça\".\n- ✗ Falso: a estimativa de mínimos quadrados continua sendo uma escolha razoável mesmo sem normalidade exata (ela minimiza RSS por construção, independentemente da distribuição do ruído) — o que se perde sem normalidade é a interpretação como MLE e certas garantias de inferência exata, não a validade do ponto estimado em si.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** o símbolo que ganharia um índice $n$ é justamente $\\sigma^2$ — de $\\sigma^2$ (uma constante) para $\\sigma^2(x_n)$ (uma função de $x$). A fatoração em produto sobrevive; a forma de cada fator, não.\n:::\n\n:::\n\n# Bloco 3 — O Teorema Central: OLS É MLE Sob Normalidade\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nChegamos ao pagamento matemático da aula. Temos a log-verossimilhança do\nBloco 2,\n\n$$\n\\ell(\\beta,\\sigma^2) = -\\frac N2\\ln(2\\pi) - N\\ln\\sigma - \\frac{1}{2\\sigma^2}\\text{RSS}(\\beta),\n$$\n\ne queremos os valores de $\\beta$ e $\\sigma^2$ que a maximizam. A observação\ncentral — a mesma que o PRML nomeia explicitamente (§3.1.1, p. 141,\ntradução nossa) — é:\n\n> \"Tendo escrito a função de verossimilhança, podemos usar máxima\n> verossimilhança para determinar $\\mathbf w$ e $\\beta$. Considere primeiro\n> a maximização em relação a $\\mathbf w$. [...] vemos que a maximização da\n> função de verossimilhança sob uma distribuição de ruído gaussiano\n> condicional para um modelo linear é equivalente a minimizar uma função\n> de erro de soma de quadrados dada por $E_D(\\mathbf w)$.\"\n\n**A prova, passo a passo.** Observe $\\ell(\\beta,\\sigma^2)$ como função só\nde $\\beta$, com $\\sigma^2$ momentaneamente fixo: os dois primeiros termos\n($-\\frac N2\\ln(2\\pi)$ e $-N\\ln\\sigma$) **não dependem de $\\beta$** — são\nconstantes para efeitos da maximização em $\\beta$. O único termo que\ndepende de $\\beta$ é\n\n$$\n-\\frac{1}{2\\sigma^2}\\text{RSS}(\\beta),\n$$\n\ne, como $\\sigma^2>0$, o fator $\\frac{1}{2\\sigma^2}$ é uma constante\n**positiva**. Maximizar $-c\\cdot\\text{RSS}(\\beta)$ para uma constante\npositiva $c$ é, por definição, **minimizar** $\\text{RSS}(\\beta)$. Ou seja:\n\n$$\n\\hat\\beta_{\\text{MLE}} = \\arg\\max_\\beta \\ell(\\beta,\\sigma^2) = \\arg\\min_\\beta \\text{RSS}(\\beta) = \\hat\\beta_{\\text{OLS}}.\n$$\n\nIsso não é uma coincidência numérica nem uma analogia — é uma **identidade\nalgébrica**: o mesmo tipo de identidade que a Aula 3 já tinha provado para\nárvores de regressão ($\\ell_\\tau(y_\\tau)$ gaussiana $\\to$ minimizar\n$Q_\\tau$), agora estabelecida para o modelo linear completo, com a mesma\nprova do PRML confirmando (p. 142): \"resolvendo para $w$ obtemos\n$w_{\\text{ML}}=(\\Phi^T\\Phi)^{-1}\\Phi^Tt}$\" — exatamente a mesma equação\nnormal do Bloco 1, agora deduzida do gradiente da log-verossimilhança em\nvez do gradiente de RSS diretamente. Os dois caminhos (Bloco 1: minimizar\nRSS; Bloco 3: maximizar verossimilhança gaussiana) convergem, porque são\nalgebricamente o mesmo problema.\n\n**Estimando $\\sigma^2$.** Com $\\hat\\beta_{\\text{MLE}}=\\hat\\beta_{\\text{OLS}}$\nfixo, maximizamos $\\ell$ em relação a $\\sigma$: derivando\n$-N\\ln\\sigma-\\frac{1}{2\\sigma^2}\\text{RSS}(\\hat\\beta)$ em relação a\n$\\sigma$ e igualando a zero,\n\n$$\n-\\frac N\\sigma + \\frac{\\text{RSS}(\\hat\\beta)}{\\sigma^3} = 0 \\quad\\Longrightarrow\\quad \\hat\\sigma^2_{\\text{MLE}} = \\frac{\\text{RSS}(\\hat\\beta)}{N}.\n$$\n\nComo a Aula 3 já registrou para o caso gaussiano mais simples (uma única\nmédia, sem regressão), esse estimador é **viesado para baixo**: ele usa os\nmesmos dados para estimar $N$ coisas ($\\beta$, via $\\text{RSS}$ minimizado)\ne depois medir a dispersão restante, o que sistematicamente subestima a\nvariância verdadeira. O estimador não-viesado divide por $N-p-1$ (graus de\nliberdade, descontando os $p{+}1$ parâmetros de $\\beta$ já estimados) em\nvez de $N$.\n\n**Verificação numérica.** Álgebra à parte, podemos *checar* o resultado\nnumericamente: maximizar $\\ell(\\beta,\\sigma^2)$ diretamente por busca\nnumérica (sem usar a fórmula fechada em nenhum momento) e comparar com\n$\\hat\\beta_{\\text{OLS}}$ do Bloco 1.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## O Teorema: Maximizar $\\ell$ É Minimizar RSS\n\n::: {.fragment}\n$$\\ell(\\beta,\\sigma^2) = \\underbrace{-\\frac N2\\ln(2\\pi) - N\\ln\\sigma}_{\\text{não depende de }\\beta} - \\frac{1}{2\\sigma^2}\\text{RSS}(\\beta)$$\n:::\n\n::: {.fragment}\nPRML: \"a maximização da função de verossimilhança sob ruído gaussiano condicional é equivalente a minimizar uma função de erro de soma de quadrados.\"\n:::\n\n::: {.fragment}\n$\\frac{1}{2\\sigma^2}>0$ constante $\\Rightarrow$ maximizar $-c\\cdot\\text{RSS}(\\beta)$ ($c>0$) $\\equiv$ **minimizar** $\\text{RSS}(\\beta)$.\n:::\n\n## A Conclusão — Identidade, Não Coincidência\n\n::: {.fragment}\n$$\\hat\\beta_{\\text{MLE}} = \\arg\\max_\\beta \\ell(\\beta,\\sigma^2) = \\arg\\min_\\beta \\text{RSS}(\\beta) = \\hat\\beta_{\\text{OLS}}$$\n:::\n\n::: {.fragment}\nMesmo tipo de identidade já visto na Aula 3 (folha gaussiana: $\\ell_\\tau\\to$ minimizar $Q_\\tau$) — aqui para o modelo linear completo. PRML chega à mesma equação normal via gradiente de $\\ell$, não de RSS.\n:::\n\n## Estimando $\\sigma^2$ — E Seu Viés\n\n::: {.fragment}\nDerivando $\\ell$ em $\\sigma$ com $\\hat\\beta$ fixo: $-\\dfrac N\\sigma+\\dfrac{\\text{RSS}(\\hat\\beta)}{\\sigma^3}=0 \\ \\Rightarrow\\ \\hat\\sigma^2_{\\text{MLE}}=\\dfrac{\\text{RSS}(\\hat\\beta)}{N}$.\n:::\n\n::: {.fragment}\n**Viesado para baixo** (mesmo fenômeno da Aula 3): usa os dados 2×, para ajustar $\\beta$ e para medir a dispersão restante. Não-viesado divide por $N-p-1$, não $N$.\n:::\n\n:::\n\n::: {#b532dd7e .cell execution_count=8}\n``` {.python .cell-code}\ndef neg_log_verossimilhanca(params, x, y):\n    b0, b1, log_sigma = params\n    sigma = np.exp(log_sigma)          # reparametriza p/ garantir sigma > 0\n    pred = b0 + b1 * x\n    n = len(y)\n    ll = (-n/2*np.log(2*np.pi) - n*np.log(sigma)\n          - np.sum((y - pred)**2) / (2*sigma**2))\n    return -ll\n\nresultado = optimize.minimize(\n    neg_log_verossimilhanca, x0=[0.0, 0.0, 0.0], args=(x, y),\n    method=\"Nelder-Mead\",\n    options={\"xatol\": 1e-10, \"fatol\": 1e-10, \"maxiter\": 40000, \"maxfev\": 40000},\n)\nb0_opt, b1_opt, log_sigma_opt = resultado.x\nsigma_opt = np.exp(log_sigma_opt)\n\nprint(f\"beta OLS (forma fechada) = ({beta_hat[0]:.8f}, {beta_hat[1]:.8f}),  sigma = {sigma_mle:.8f}\")\nprint(f\"beta MLE (busca numérica) = ({b0_opt:.8f}, {b1_opt:.8f}),  sigma = {sigma_opt:.8f}\")\nprint(f\"diferença máxima entre os dois caminhos: {max(abs(b0_opt-beta_hat[0]), abs(b1_opt-beta_hat[1]), abs(sigma_opt-sigma_mle)):.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbeta OLS (forma fechada) = (0.47068209, 0.40756945),  sigma = 0.83890652\nbeta MLE (busca numérica) = (0.47068210, 0.40756945),  sigma = 0.83890653\ndiferença máxima entre os dois caminhos: 1.80e-08\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nA busca numérica (`scipy.optimize.minimize`, método Nelder-Mead, sem\ngradiente analítico, partindo de $\\beta_0=\\beta_1=0,\\ \\sigma=1$) encontra\n$\\hat\\beta=(0{,}47068210,\\,0{,}40756945)$ e $\\hat\\sigma=0{,}83890653$ —\nidênticos à forma fechada até a **oitava casa decimal**\n(diferença máxima $\\approx 1{,}8\\times10^{-8}$, na faixa da própria\nprecisão numérica do otimizador, não um erro sistemático). A prova\nalgébrica do Bloco 3 não precisava dessa confirmação para ser válida, mas\na confirmação numérica tem valor pedagógico próprio: mostra que o\nresultado teórico não é frágil a pequenas perturbações do procedimento de\notimização, e que os mesmos números que apareceram \"de graça\" via álgebra\nlinear no Bloco 1 reaparecem numa busca cega que nunca usou a fórmula\nfechada.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Confirmação Numérica: Dois Caminhos, Um Ponto\n\n- `scipy.optimize.minimize` (Nelder-Mead, sem gradiente, sem fórmula fechada) parte de $\\beta_0=\\beta_1=0,\\sigma=1$.\n\n::: {.fragment}\nEncontra $\\hat\\beta=(0{,}47068210,\\,0{,}40756945)$, $\\hat\\sigma=0{,}83890653$ — **idêntico** à forma fechada até a $8^a$ casa decimal.\n:::\n\n::: {.fragment}\nDiferença $\\approx1{,}8\\times10^{-8}$: ruído numérico do otimizador, não erro sistemático. A prova algébrica não precisava disso — mas a confirmação mostra que os dois caminhos (álgebra linear e busca cega) levam ao mesmo ponto.\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 82%; margin: 0 auto;\"}\n\n::: {#36924b22 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-10-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nA superfície de log-verossimilhança, calculada numa grade de\n$150\\times150$ pontos $(\\beta_0,\\beta_1)$ com $\\sigma$ fixo no valor de\nMLE, tem um único pico — exatamente no ponto marcado com estrela, o mesmo\n$\\hat\\beta$ da forma fechada e da busca numérica. A superfície é uma\nparabolóide invertida (RSS é quadrática em $\\beta$, e $\\ell$ é RSS com\nsinal trocado e escalado), o que garante que não existe nenhum outro\nmáximo local escondido em algum canto do espaço de parâmetros — uma\npropriedade que problemas de otimização mais gerais (redes neurais, por\nexemplo) não têm.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## A Superfície Tem Um Único Pico\n\n::: {.fragment}\nGrade $150\\times150$ em $(\\beta_0,\\beta_1)$, $\\sigma$ fixo no MLE: um único pico, exatamente onde a forma fechada e a busca numérica já haviam apontado.\n:::\n\n::: {.fragment}\n$\\ell$ é RSS com sinal trocado e escalado $\\Rightarrow$ superfície é uma parabolóide invertida — **sem** máximos locais escondidos. Propriedade que otimização mais geral (redes neurais) não tem.\n:::\n\n:::\n\n::: {.callout-tip}\n## A busca numérica encontrou exatamente o mesmo $\\hat\\beta$ que a fórmula fechada, a menos de $10^{-8}$. Isso prova que maximizar a log-verossimilhança SEMPRE encontra o mínimo de RSS, para qualquer distribuição de ruído — ou é uma coincidência do caso gaussiano?\n\nDica: releia qual passo da prova algébrica dependia especificamente da forma da densidade gaussiana.\n:::\n\n::: {.callout-tip}\n## OLS = MLE: O Que a Prova Realmente Diz\n\n- □ Se o ruído fosse Laplace (dupla-exponencial) em vez de gaussiano, maximizar a verossimilhança correspondente levaria a minimizar a soma dos valores absolutos dos resíduos, não a soma de quadrados — porque é a forma funcional específica da densidade gaussiana ($\\propto\\exp(-\\cdot^2)$) que produz o termo quadrático.\n- □ No limite em que $N\\to\\infty$ com o modelo verdadeiro sendo exatamente linear e gaussiano, $\\hat\\beta_{\\text{MLE}}$ e $\\hat\\sigma^2_{\\text{MLE}}$ convergem para os valores populacionais verdadeiros, incluindo o viés de $\\hat\\sigma^2_{\\text{MLE}}$ (que usa $N$ no denominador em vez de $N-p-1$), que desaparece assintoticamente.\n- □ Num problema de classificação binária ajustado por máxima verossimilhança sob um modelo Bernoulli (fora do escopo desta aula, mas o mesmo princípio), o objeto que se maximiza também terá, por construção do modelo, um termo cuja otimização coincide com minimizar alguma função de erro específica daquela distribuição, não necessariamente a soma de quadrados — e, por essa razão, comparar diretamente o valor numérico da log-verossimilhança máxima entre o modelo gaussiano desta aula e esse modelo Bernoulli diria qual dos dois descreve melhor seus respectivos dados.\n- □ Como a otimização numérica confirmou que o ponto de máximo da log-verossimilhança coincide com $\\hat\\beta_{\\text{OLS}}$, conclui-se que qualquer método de otimização numérica (incluindo os que não convergem corretamente) chegaria ao mesmo resultado, tornando a forma fechada desnecessária na prática.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## OLS = MLE: O Que a Prova Realmente Diz — Resposta\n\n::: {.callout-tip}\n- ✔ Correto — a prova do Bloco 3 usou explicitamente a forma $\\exp\\{-(\\cdot)^2/2\\sigma^2\\}$ da gaussiana; trocar por Laplace ($\\propto\\exp\\{-|\\cdot|/b\\}$) produz $\\sum|y_i-\\beta^Tx_i|$ na log-verossimilhança, não uma soma de quadrados.\n- ✔ Correto — consistência assintótica do MLE é uma propriedade geral, e $N/(N-p-1)\\to1$ conforme $N\\to\\infty$, eliminando o viés relativo no limite.\n- ✗ A primeira parte é verdadeira (Bernoulli levaria a outra função de erro, não soma de quadrados — de fato, entropia cruzada, Aula 7), mas comparar log-verossimilhanças máximas **entre famílias distribucionais diferentes** não é válido sem correção — as escalas e normalizações de gaussiana e Bernoulli não são diretamente comparáveis; precisaria de critérios como AIC/BIC, não o valor bruto.\n- ✗ Confirmar numericamente **para um dataset e um otimizador que convergiu corretamente** não estende a garantia a qualquer otimizador — um método que não converge (parar cedo, ficar preso, divergir numericamente) não chegaria ao mesmo ponto; a forma fechada continua sendo o padrão de referência, exata e sem essas contingências.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** é uma propriedade do caso gaussiano especificamente — a prova do Bloco 3 usou a forma exponencial-quadrática da densidade gaussiana em um passo específico (isolar o termo em $\\beta$). Outra distribuição de ruído produziria outra função de erro a minimizar, pela mesma lógica geral, mas não a mesma soma de quadrados.\n:::\n\n:::\n\n# Síntese e Limitações\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nO modelo de hoje repousa sobre quatro premissas (Bloco 2): linearidade\ncondicional, ruído gaussiano aditivo, homocedasticidade e independência.\nVale perguntar, com a mesma honestidade que a Aula 4 exigiu para números de\nvalidação: **essas premissas se sustentam nos próprios dados usados\nhoje?** A resposta, olhando os resíduos reais do ajuste, é só\nparcialmente.\n\n**Achado real 1 — censura no alvo.** `MedHouseVal` é artificialmente\ntruncado em $5{,}00001$ (o valor máximo que a variável assume no dataset\noriginal, por decisão de quem o construiu) — $747$ das $16\\,640$\nobservações de treino ($4{,}49\\%$) estão exatamente nesse teto. Isso\ndistorce qualquer estimativa de $\\beta_1$: os imóveis mais caros de\nverdade — provavelmente concentrados entre as regiões de renda mais alta —\ntêm seu valor real escondido atrás do teto, empurrando a inclinação\nestimada para baixo do valor que seria observado sem censura.\n\n**Achado real 2 — heterocedasticidade real.** Dividindo as observações em\nquartis de `MedInc` e medindo a variância dos resíduos em cada quartil:\n\n| Quartil de `MedInc` | Renda média (US\\$10 mil) | Variância dos resíduos |\n|---|---|---|\n| 1º (mais baixo) | $1{,}92$ | $0{,}486$ |\n| 2º | $2{,}99$ | $0{,}653$ |\n| 3º | $4{,}00$ | $0{,}849$ |\n| 4º (mais alto) | $6{,}28$ | $0{,}825$ |\n\nA variância quase dobra do 1º para o 3º quartil — uma violação genuína e\nmensurável da premissa de homocedasticidade do Bloco 2, não uma\npossibilidade hipotética. Isso não torna o modelo inútil (o Gauss-Markov\ngarante que $\\hat\\beta_{\\text{OLS}}$ continua não-viesado mesmo sem\nhomocedasticidade), mas invalida a interpretação de $\\hat\\sigma$ como \"um\núnico tamanho de erro\" em toda a faixa de renda, e enfraquece garantias de\ninferência exata (intervalos de confiança, testes de hipótese) que\ndependeriam dessa premissa.\n\n**A ponte para a Aula 7.** A estrutura de hoje — assumir uma distribuição,\nconstruir sua verossimilhança, mostrar que maximizá-la equivale a\nminimizar algum erro específico daquela distribuição — não é exclusiva da\ngaussiana. A Aula 7 troca a Gaussiana por uma **Bernoulli** (alvo binário,\nnão contínuo) e mostra que a mesma receita produz, no lugar da soma de\nquadrados, a **entropia cruzada** — a função de erro por trás da Regressão\nLogística. O \"prato\" muda; a \"receita\" (distribuição $\\to$ verossimilhança\n$\\to$ erro que a maximização revela) é a mesma que hoje.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## As Premissas Se Sustentam Nos Próprios Dados?\n\n- Bloco 2 assumiu: linearidade, ruído gaussiano, **homocedasticidade**, independência.\n\n::: {.fragment}\n**Achado real 1 — censura:** `MedHouseVal` truncado em $5{,}00001$ — $747/16\\,640$ ($4{,}49\\%$) no teto. Empurra $\\hat\\beta_1$ para baixo do valor sem censura.\n:::\n\n::: {.fragment}\n**Achado real 2 — heterocedasticidade real:** variância dos resíduos $0{,}486\\to0{,}653\\to0{,}849\\to0{,}825$ do 1º ao 4º quartil de renda — quase dobra.\n:::\n\n::: {.fragment}\nNão torna o modelo inútil ($\\hat\\beta_{\\text{OLS}}$ segue não-viesado, Gauss-Markov), mas enfraquece a interpretação de \"um único $\\hat\\sigma$\" e a inferência exata (ICs, testes).\n:::\n\n## Ponte Para a Aula 7\n\n::: {.fragment}\nA receita de hoje — distribuição $\\to$ verossimilhança $\\to$ erro revelado pela maximização — **não é exclusiva da gaussiana**.\n:::\n\n::: {.fragment}\n**Aula 7:** troca Gaussiana por **Bernoulli** (alvo binário). Mesma receita $\\Rightarrow$ **entropia cruzada** no lugar de soma de quadrados — o erro por trás da Regressão Logística.\n:::\n\n:::\n\n::: {#50c9cf7e .cell execution_count=10}\n\n::: {.cell-output .cell-output-stdout}\n```\ncensura: 747/16640 = 0.0449\nquartil 1: renda média=1.92, var(resíduo)=0.486\nquartil 2: renda média=2.99, var(resíduo)=0.653\nquartil 3: renda média=4.00, var(resíduo)=0.849\nquartil 4: renda média=6.28, var(resíduo)=0.825\n```\n:::\n:::\n\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#7bfb2721 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-12-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n# Fechamento\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nVoltando ao roteiro de abertura, uma frase cada:\n\n1. **O que é \"a melhor reta\":** a que minimiza a soma de quadrados dos\n   resíduos — elevar ao quadrado evita o cancelamento degenerado de somar\n   resíduos com sinal, é diferenciável em toda parte, e penaliza desvios\n   grandes desproporcionalmente mais.\n2. **A notação matricial e sua solução fechada:** $\\text{RSS}(\\beta)=\\lVert y-X\\beta\\rVert^2$\n   é minimizada por $\\hat\\beta=(X^TX)^{-1}X^Ty$ — as equações normais —,\n   que é também a projeção ortogonal de $y$ sobre o subespaço gerado pelas\n   colunas de $X$.\n3. **A história probabilística:** assumir\n   $Y\\mid X=x\\sim\\mathcal N(\\beta^Tx,\\sigma^2)$ (homocedástico, erros\n   independentes) permite construir a verossimilhança dos dados como um\n   produto de gaussianas, e sua log-verossimilhança como uma soma.\n4. **Por que maximizar $\\equiv$ minimizar soma de quadrados:** porque o\n   único termo da log-verossimilhança que depende de $\\beta$ é\n   $-\\frac{1}{2\\sigma^2}\\text{RSS}(\\beta)$, e maximizar isso, com\n   $\\sigma^2>0$ fixo, é minimizar $\\text{RSS}(\\beta)$ — uma identidade\n   algébrica, confirmada numericamente a $10^{-8}$ nesta aula, não uma\n   coincidência do caso gaussiano.\n\n**O que fica em aberto:** o modelo de hoje assume ruído gaussiano\nhomocedástico — a Seção de Limitações mostrou que os próprios dados usados\nhoje violam essa premissa (heterocedasticidade real, censura no alvo).\nA Aula 8 vai retomar $\\hat\\beta_{\\text{OLS}}$ deste modelo e mostrar que\nadicionar uma penalidade (Ridge/Lasso) equivale a assumir uma **priori**\nsobre $\\beta$ — o primeiro passo em direção ao raciocínio bayesiano. A\nAula 9 vai decompor formalmente o erro esperado de qualquer estimador\n(incluindo o de hoje) em viés, variância e ruído irredutível — dando nome\nmatemático ao trade-off que o viés de $\\hat\\sigma^2_{\\text{MLE}}$ já\ninsinuou. E a Aula 7, logo a seguir, troca a Gaussiana por uma Bernoulli\npara tratar alvos binários pela mesma receita.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## O que Aprendemos Hoje\n\n1. \"Melhor reta\" $=$ minimizar $\\sum e_i^2$ — evita cancelamento, é diferenciável, penaliza desvios grandes mais que proporcionalmente.\n2. $\\text{RSS}(\\beta)=\\lVert y-X\\beta\\rVert^2$ minimizado por $\\hat\\beta=(X^TX)^{-1}X^Ty$ — projeção ortogonal de $y$ sobre o espaço-coluna de $X$.\n3. $Y\\mid X\\sim\\mathcal N(\\beta^Tx,\\sigma^2)$ homocedástico $\\Rightarrow$ verossimilhança $=$ produto de gaussianas, log-verossimilhança $=$ soma.\n\n::: {.fragment}\n4. Único termo de $\\ell$ que depende de $\\beta$ é $-\\frac{1}{2\\sigma^2}\\text{RSS}(\\beta)$ $\\Rightarrow$ maximizar $\\equiv$ minimizar RSS. **Identidade algébrica**, confirmada a $10^{-8}$.\n:::\n\n::: {.fragment}\n**Próximas aulas:** Aula 7 (Bernoulli $\\to$ entropia cruzada), Aula 8 (penalidade $=$ priori, MAP), Aula 9 (decomposição viés-variância).\n:::\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n# <i class=\"bi bi-pencil-square\" style=\"color:#0085CA;\"></i> Exercícios\n\n## Questões discursivas\n\n1. A Fonte 4 (PRML, p. 143) e a Fonte 7 (ESL, p. 46) descrevem a mesma\n   ideia geométrica — a solução de mínimos quadrados como projeção\n   ortogonal — usando notações ligeiramente diferentes\n   ($\\mathcal S=\\text{span}(\\varphi_1,\\ldots,\\varphi_M)$ no PRML;\n   hiperplano gerado por $x_0,\\ldots,x_p$ no ESL). Usando o ajuste\n   `MedInc`$\\to$`MedHouseVal` desta aula como exemplo concreto, explique o\n   que os vetores $\\varphi_1,\\varphi_2$ representam nesse ajuste\n   específico, e por que $\\hat y$ precisa estar dentro do subespaço gerado\n   por eles.\n\n2. O Bloco 3 mostrou que $\\hat\\sigma^2_{\\text{MLE}}=\\text{RSS}/N$ é um\n   estimador viesado para baixo (o mesmo fenômeno já visto na Aula 3 para\n   a variância gaussiana). Usando os números computados nesta aula\n   ($N=16\\,640$, $\\text{RSS}\\approx11\\,710{,}64$), calcule\n   $\\hat\\sigma^2_{\\text{MLE}}$ e o estimador não-viesado\n   $\\text{RSS}/(N-2)$, compare os dois valores numericamente, e explique\n   por que a diferença relativa é tão pequena neste caso específico — e em\n   que situação (em termos de $N$ e do número de parâmetros) essa\n   diferença deixaria de ser desprezível.\n\n3. A Seção de Limitações mostrou que a variância dos resíduos cresce com\n   `MedInc` (de $0{,}486$ no 1º quartil a $0{,}849$ no 3º quartil de\n   renda) — uma violação real de homocedasticidade nos próprios dados\n   desta aula. Explique, retomando a construção da verossimilhança do\n   Bloco 2, exatamente qual passo da derivação deixaria de ser válido se\n   $\\sigma^2$ dependesse de $x$, e proponha (sem precisar resolver\n   completamente) como a log-verossimilhança mudaria de forma.\n\n## Questões de Verdadeiro/Falso\n\nCada bloco de 4 itens trata do mesmo tema. A questão só é considerada\ncorreta se todos os 4 itens forem julgados corretamente (deixar em branco\ntem penalidade de 20% da nota da questão).\n\n::: {.callout-note icon=false}\n## Geometria da Projeção e Resíduos\n\n- □ Se o vetor observado $y$ já estivesse exatamente dentro do subespaço gerado pelas colunas de $X$ (por exemplo, se os dados não tivessem ruído algum), a projeção $\\hat y$ coincidiria com o próprio $y$, e o resíduo seria o vetor nulo.\n- □ Se o número de colunas de $X$ (incluindo o intercepto) fosse igual ao número de observações $N$, e essas colunas fossem linearmente independentes, o subespaço $\\mathcal S$ ocuparia todo o espaço $\\mathbb R^N$, e o ajuste por mínimos quadrados reproduziria $y$ exatamente, com resíduo nulo em todos os pontos.\n- □ Num algoritmo de recomendação que aproxima as avaliações de um usuário como combinação linear de \"perfis latentes\" pré-definidos, a mesma lógica de projeção ortogonal sobre o subespaço gerado pelos perfis garante que a aproximação encontrada terá erro zero sempre que houver pelo menos dois perfis latentes disponíveis.\n- □ Como o resíduo $y-\\hat y$ é ortogonal a cada coluna de $X$ individualmente, ele é necessariamente ortogonal a qualquer vetor fora do subespaço $\\mathcal S$ também.\n:::\n\n::: {.callout-note icon=false}\n## RSS, Equações Normais e Posto de X\n\n- □ Se todas as colunas de atributos de $X$ (exceto o intercepto) fossem multiplicadas por uma mesma constante $c\\ne 0$ antes do ajuste, o vetor $\\hat\\beta$ mudaria (os coeficientes correspondentes seriam divididos por $c$), mas a previsão $\\hat y=X\\hat\\beta$ e o RSS mínimo permaneceriam exatamente os mesmos.\n- □ No limite em que $X$ tem uma única coluna (só o intercepto, sem nenhum atributo), a equação normal $X^T(y-X\\hat\\beta)=0$ se reduz a dizer que $\\hat\\beta_0$ é exatamente a média amostral $\\bar y$.\n- □ Num ajuste de calibração de instrumento em que se busca a relação linear entre a leitura bruta de um sensor e o valor real de referência, a mesma equação normal determinaria os coeficientes de calibração independentemente do sensor ser de temperatura, pressão ou qualquer outra grandeza física — e a extrapolação da reta ajustada para leituras muito fora do intervalo calibrado teria a mesma confiabilidade estatística que dentro do intervalo calibrado.\n- □ Como $\\text{RSS}(\\beta)$ é uma função quadrática (e portanto convexa) de $\\beta$, ela tem sempre um único mínimo global estritamente, mesmo quando as colunas de $X$ são linearmente dependentes ($X^TX$ singular).\n:::\n\n::: {.callout-note icon=false}\n## Premissas do Modelo Gaussiano Homocedástico\n\n- □ Se assumíssemos que os erros $\\epsilon_n$ são gaussianos mas NÃO independentes entre observações (por exemplo, erros correlacionados entre imóveis vizinhos geograficamente), a verossimilhança conjunta deixaria de ser simplesmente o produto das densidades marginais de cada observação.\n- □ Se a variância do ruído $\\sigma^2$ fosse igual para todas as observações mas extremamente grande (tendendo a infinito), o modelo linear perderia praticamente toda sua capacidade preditiva, mesmo que $\\beta$ estivesse corretamente especificado.\n- □ Num modelo que prevê o tempo de resposta de um servidor a partir da carga de requisições, supor ruído gaussiano homocedástico seria tão razoável quanto no caso de preços de imóveis, desde que a variabilidade do tempo de resposta realmente não dependa sistematicamente do nível de carga — e, uma vez feita essa suposição, ela nunca precisaria ser verificada empiricamente depois do ajuste, pois o próprio ajuste por mínimos quadrados a confirma automaticamente.\n- □ Como o modelo desta aula assume $Y\\mid X\\sim\\mathcal N(\\beta^TX,\\sigma^2)$, isso implica que a distribuição marginal (não condicional) de $Y$ também deve ser gaussiana, para o modelo fazer sentido.\n:::\n\n::: {.callout-note icon=false}\n## Construção da Verossimilhança Conjunta\n\n- □ Se, em vez de tomar o logaritmo da verossimilhança, trabalhássemos diretamente com o produto de densidades $\\prod_n\\mathcal N(y_n\\mid\\beta^Tx_n,\\sigma^2)$, maximizar esse produto em relação a $\\beta$ ainda levaria exatamente ao mesmo $\\hat\\beta$ obtido via log-verossimilhança, porque o logaritmo é uma função estritamente crescente.\n- □ No caso extremo de $N=1$ (uma única observação), a \"log-verossimilhança\" ainda pode ser escrita pela mesma fórmula geral, mas maximizá-la em relação a $\\beta$ (com mais de um parâmetro livre) não determina um único $\\hat\\beta$, porque há infinitas retas passando exatamente por um ponto.\n- □ Num modelo que assume que o tempo entre chegadas de clientes numa fila segue uma distribuição exponencial (não gaussiana), a mesma lógica de multiplicar densidades individuais (assumindo observações independentes) e tomar o logaritmo se aplicaria — ainda que a forma final da função a maximizar fosse diferente da desta aula, o valor numérico do máximo obtido seria sempre diretamente comparável ao valor máximo da log-verossimilhança gaussiana desta aula, permitindo escolher qual das duas descreve melhor seus respectivos dados só comparando os números brutos.\n- □ Como a log-verossimilhança desta aula é $\\ell(\\beta,\\sigma^2)=-\\frac N2\\ln(2\\pi)-N\\ln\\sigma-\\frac{\\text{RSS}(\\beta)}{2\\sigma^2}$, maximizar $\\ell$ em relação a $\\beta$ e maximizar $\\ell$ em relação a $\\sigma^2$ são operações que precisam ser feitas simultaneamente, nunca uma depois da outra, porque os dois parâmetros aparecem na mesma expressão.\n:::\n\n::: {.callout-note icon=false}\n## O Teorema Central: OLS = MLE\n\n- □ Se a variância $\\sigma^2$ fosse conhecida e fixa de antemão (não estimada), o valor de $\\hat\\beta$ que maximiza a log-verossimilhança ainda seria exatamente o mesmo $\\hat\\beta_{\\text{OLS}}$, porque $\\sigma^2$ entra na log-verossimilhança apenas como um fator multiplicativo positivo do termo que depende de $\\beta$.\n- □ Se, por hipótese, $\\text{RSS}(\\hat\\beta)=0$ para o $\\hat\\beta$ que minimiza a soma de quadrados (ajuste perfeito, sem nenhum resíduo), o estimador $\\hat\\sigma^2_{\\text{MLE}}=\\text{RSS}(\\hat\\beta)/N$ seria exatamente zero, e a log-verossimilhança avaliada nesse ponto tenderia a $+\\infty$ conforme $\\sigma\\to0$ nessa mesma expressão, revelando uma degenerescência do modelo gaussiano nesse caso extremo.\n- □ Se, em outro domínio qualquer, alguém provar que maximizar uma verossimilhança assumida é algebricamente idêntico a minimizar uma soma de quadrados, essa prova por si só já implica que o ruído daquele modelo específico foi assumido gaussiano, porque é a densidade gaussiana (e nenhuma outra densidade comum) que produz esse termo quadrático especificamente na log-verossimilhança.\n- □ Como $\\hat\\beta_{\\text{MLE}}=\\hat\\beta_{\\text{OLS}}$ sob o modelo gaussiano desta aula, conclui-se que máxima verossimilhança e mínimos quadrados são sempre a mesma coisa, para qualquer modelo estatístico, não apenas para regressão linear sob ruído gaussiano.\n:::\n\n::: {.callout-note icon=false}\n## Viés do MLE de $\\sigma^2$\n\n- □ Se, em vez de dividir por $N$, dividíssemos $\\text{RSS}(\\hat\\beta)$ por $N-2$ (número de observações menos o número de parâmetros de $\\beta$ nesta aula), o estimador resultante teria valor esperado exatamente igual a $\\sigma^2$ verdadeiro — mas deixaria de ser o estimador de máxima verossimilhança.\n- □ Conforme $N\\to\\infty$ (mantendo o número de parâmetros de $\\beta$ fixo), a diferença relativa entre $\\hat\\sigma^2_{\\text{MLE}}=\\text{RSS}/N$ e o estimador não-viesado $\\text{RSS}/(N-2)$ tende a zero, porque $N/(N-2)\\to1$.\n- □ O mesmo padrão de viés — dividir por $N$ em vez de $N$ menos o número de parâmetros estimados — reaparece em qualquer estimador de variância obtido por máxima verossimilhança que primeiro estime uma média (ou, aqui, um hiperplano) a partir dos mesmos dados usados para medir a dispersão em torno dela; e por isso, na prática, é sempre preferível reportar o estimador não-viesado em vez do MLE, em qualquer aplicação, sem exceção.\n- □ Como $\\hat\\sigma^2_{\\text{MLE}}$ é viesado para baixo, ele é necessariamente um estimador pior do que o estimador não-viesado $\\text{RSS}/(N-2)$ em qualquer critério razoável de qualidade, incluindo o erro quadrático médio do próprio estimador de $\\sigma^2$.\n:::\n\n::: {.callout-note icon=false}\n## Verificação Numérica e Otimização\n\n- □ Se a otimização numérica desta aula tivesse sido inicializada num ponto de partida muito distante de $\\hat\\beta_{\\text{OLS}}$ (por exemplo, $\\beta_0=100,\\beta_1=-50$), o algoritmo Nelder-Mead ainda convergiria ao mesmo ponto ótimo, porque a log-verossimilhança gaussiana em função de $\\beta$ é uma função côncava sem outros máximos locais.\n- □ Se a grade (grid search) usada para visualizar a superfície de log-verossimilhança tivesse uma resolução extremamente grosseira (poucos pontos, muito espaçados), o pico da grade poderia ficar visivelmente deslocado do verdadeiro $\\hat\\beta_{\\text{OLS}}$, mesmo que a forma fechada continuasse exata — e, por essa razão, sempre que uma forma fechada exata existir, o grid search se torna uma ferramenta cientificamente inútil, sem nenhum valor pedagógico ou de verificação.\n- □ Em problemas de otimização com muitos parâmetros (por exemplo, uma rede neural com milhões de pesos), a mesma ideia de verificar uma solução fechada contra uma busca numérica deixaria de ser prática simplesmente por causa do volume de contas — não porque o princípio de comparação deixe de fazer sentido.\n- □ Como a otimização numérica confirmou o resultado da forma fechada neste exemplo específico, isso prova matematicamente (não apenas ilustra empiricamente) que $\\hat\\beta_{\\text{MLE}}=\\hat\\beta_{\\text{OLS}}$ para qualquer conjunto de dados sob o modelo gaussiano.\n:::\n\n::: {.callout-note icon=false}\n## Limitações: Heterocedasticidade, Censura e Não-Linearidade\n\n- □ Se `MedHouseVal` não fosse artificialmente censurado em $5{,}00001$ (ou seja, se os $4{,}49\\%$ de observações no teto tivessem seus valores reais, possivelmente maiores), o $\\hat\\beta_1$ estimado para `MedInc` provavelmente mudaria, porque essas observações censuradas concentram-se desproporcionalmente entre os imóveis de renda mais alta.\n- □ No extremo em que a censura afetasse 100% das observações (todos os valores exibidos como exatamente $5{,}00001$), a variância amostral de `MedHouseVal` seria zero, e o ajuste de mínimos quadrados encontraria $\\hat\\beta_1=0$.\n- □ Num estudo que mede o tempo de sobrevivência de pacientes após um tratamento, mas o estudo termina antes de alguns pacientes falecerem (censura à direita, análoga à censura de `MedHouseVal` no teto), a mesma distorção de ajustar mínimos quadrados diretamente sobre os tempos observados (ignorando a censura) se aplicaria, subestimando o verdadeiro tempo médio de sobrevivência — mas esse problema desapareceria automaticamente com uma amostra suficientemente grande, já que o viés de censura, ao contrário do viés de estimadores de variância, diminui conforme $N$ aumenta.\n- □ Como a variância dos resíduos cresce com `MedInc` (heterocedasticidade real, confirmada nos dados desta aula), o modelo linear ajustado por mínimos quadrados se torna inútil para prever `MedHouseVal`, e nenhuma previsão feita a partir dele deveria ser usada.\n:::\n\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}