{
  "hash": "55171b1fd16b09ed0ad3e7bdfc9aba97",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Aula 5: Decomposição em Valores Singulares (SVD) e Aproximações de Baixo Posto\"\nsubtitle: \"Álgebra Linear e Otimização para Aprendizado de Máquina\"\nauthor: \"Prof. Marcos Medeiros Raimundo\"\ndate: \"2026-09-12\"\nlang: pt-BR\nformat:\n  html:\n    include-after-body: ../../lesson-toc-accordion.html\n    output-file: notas.html\n    theme: [flatly, ../../../custom.scss, ../../lesson-theme.scss]\n    code-fold: false\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    fig-width: 8\n    fig-height: 4.5\n  revealjs:\n    transition: slide\n    width: 1280\n    height: 800\n    margin: 0.02\n    fig-responsive: true\n    fig-format: \"svg\"\n    footer: \"UNICAMP — Instituto de Computação\"\n    chalkboard:\n      boardmarker-width: 3\n      chalk-width: 3\n    include-in-header: ../../bootstrap-icons-header.html\n    include-after-body: ../../logos-footer.html\n    title-slide-attributes:\n      data-background-image: \"../../UNICAMP.png, ../../IC.png\"\n      data-background-size: \"140px, 140px\"\n      data-background-position: \"5% 8%, 95% 8%\"\n    theme: [simple, ../../lesson-theme.scss]\n    output-file: slides.html\n    slide-number: true\n    smaller: true\n    scrollable: true\n    fig-width: 8\n    fig-height: 4.5\njupyter: homepage\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n[Slides](slides.html){.see-all aria-label=\"Ver slides\" title=\"Ver slides\"}\n[Lista de aulas](../index.qmd){.see-all .lesson-list-link aria-label=\"Lista de aulas\" title=\"Lista de aulas\"}\n:::\n\n\n\n# Revisão e Introdução\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Revisão Rápida: Onde a Aula 4 Parou\n\nA Aula 4 respondeu, para matrizes **quadradas simétricas**, tudo que\nprecisávamos saber sobre autovalores e autovetores. **Primeiro**, provou\nque $A^TA$ é sempre simétrica e semidefinida positiva, para **qualquer**\nmatriz $A$ — mesmo quando $A$ não é quadrada. **Segundo**, o Teorema\nEspectral Real garantiu que toda matriz simétrica $A\\in\\mathbb{R}^{n\\times\nn}$ tem $n$ autovalores reais e admite uma base ortonormal de\nautovetores, isto é, $A=Q\\Lambda Q^T$ com $Q$ ortogonal e $\\Lambda$\ndiagonal. **Terceiro**, o sinal dos autovalores caracterizou definitude\npositiva/semidefinida ($A\\succ 0\\iff\\lambda_{\\min}(A)>0$), e a razão\nentre o maior e o menor autovalor forneceu o número de condição exato,\n$\\text{cond}(A)=\\lambda_{\\max}(A)/\\lambda_{\\min}(A)$ — fechando, sem\nperturbar nada, o ciclo que a Aula 3 só tinha *medido* empiricamente\n(perturbando os dados e observando o efeito no peso estimado).\n\nVale relembrar os números concretos, porque esta aula vai reencontrá-los:\npara os 4 atributos completos do *California Housing* ($X\\in\n\\mathbb{R}^{16\\,640\\times 4}$), os autovalores de $X^TX$ eram\n$[747{,}25;\\ 52\\,666{,}03;\\ 273\\,990{,}28;\\ 1{,}753\\times10^7]$, com\n$\\text{cond}(X^TX)\\approx 23\\,460{,}5$; para o par quase-colinear\n`AveRooms`/`AveBedrms`, $\\text{cond}\\approx 419{,}8$; para o par\nbem-condicionado `MedInc`/`HouseAge`, $\\text{cond}\\approx 169{,}1$.\n\n## Organizador Prévio: De $X^TX$ Simétrica Para $X$ Retangular\n\nTudo isso foi construído em cima de $X^TX$ — uma matriz $4\\times 4$,\nquadrada e simétrica por construção. Mas o objeto de interesse original\nnunca foi $X^TX$; é o próprio $X$, a matriz de design\n$16\\,640\\times 4$, retangular. Vale ser preciso aqui, porque é fácil\nconfundir dois problemas diferentes: **autovalor e autovetor não são\n\"difíceis de garantir\" para uma matriz retangular — eles simplesmente\nnão estão definidos.** A equação $A\\mathbf{x}=\\lambda\\mathbf{x}$ exige\nque $A\\mathbf{x}$ viva no mesmo espaço que $\\mathbf{x}$ (para que a\nigualdade com $\\lambda\\mathbf{x}$ faça sentido); se $A\\in\n\\mathbb{R}^{m\\times n}$ com $m\\ne n$, então $A\\mathbf{x}\\in\\mathbb{R}^m$\nenquanto $\\mathbf{x}\\in\\mathbb{R}^n$ — a equação nem sequer tem tipo\ncorreto, muito menos solução. O polinômio característico\n$\\det(A-\\lambda I)$ tem o mesmo problema: $A-\\lambda I$ exige subtrair\n$A$ de uma matriz identidade multiplicada por escalar, e isso só é\ndefinido quando $A$ é quadrada.\n\nA ideia central desta aula: em vez de insistir em decompor $X$ da mesma\nforma que decompomos $X^TX$, vamos **reciclar exatamente o que a Aula 4\njá provou** — aplicando-o não a $X$, mas às duas matrizes quadradas\nsimétricas que $X$ produz naturalmente, $X^TX\\in\\mathbb{R}^{4\\times 4}$ e\n$XX^T\\in\\mathbb{R}^{16\\,640\\times 16\\,640}$ — e depois costurar os dois\nresultados de volta em uma decomposição de $X$ propriamente dita. Essa\ncostura tem nome: **Decomposição em Valores Singulares (SVD)**.\n\n## Roteiro da Aula\n\nA pergunta que fecha o Organizador Prévio — \"como reciclar o Teorema\nEspectral Real, aplicado a $X^TX$ e $XX^T$, para decompor o próprio $X$\nretangular?\" — se desdobra em quatro perguntas mais específicas:\n\n1. O que é a **Decomposição em Valores Singulares (SVD)** e por que ela\n   existe para **qualquer** matriz retangular, sem exceção?\n2. Como **construir** a SVD a partir do que já sabemos sobre $X^TX$ e\n   $XX^T$ — isto é, a partir do próprio Teorema Espectral da Aula 4?\n3. Como usar a SVD para **aproximar** uma matriz por outra de posto\n   menor, e por que essa aproximação é a **melhor possível** (Teorema de\n   Eckart-Young-Mirsky)?\n4. O que é a **Decomposição Polar**, e como ela nasce \"de graça\" a\n   partir dos mesmos três fatores da SVD?\n\n## Problema Motivador\n\nConsidere um cenário bem diferente do *California Housing*, mas que vai\nse revelar regido pela mesma matemática. Três espectadores — Ali,\nBeatrix e Chandra — avaliam quatro filmes (Guerra nas Estrelas, Blade\nRunner, Amélie Poulain, Delicatessen) numa escala de 0 (pior) a 5\n(melhor). As notas formam uma matriz $A\\in\\mathbb{R}^{4\\times 3}$, uma\nlinha por filme, uma coluna por espectador (tradução livre de um\nexemplo do MathML, §4.5.1):\n\n::: {#b541bd74 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Ali</th>\n      <th>Beatrix</th>\n      <th>Chandra</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Guerra nas Estrelas</th>\n      <td>5.0</td>\n      <td>4.0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>Blade Runner</th>\n      <td>5.0</td>\n      <td>5.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>Amélie Poulain</th>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>Delicatessen</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>4.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nOlhando só para esses $12$ números, seria razoável suspeitar de uma\nestrutura escondida: talvez Ali e Beatrix compartilhem um \"perfil de\ngosto\" (ficção científica), e Chandra tenha um perfil bem diferente\n(cinema de arte francês) — e talvez os próprios filmes se agrupem em\n\"temas\" correspondentes. Pense por um instante, sem fazer nenhuma conta\nainda: **existe alguma forma de extrair, direto da matriz de notas, esses\n\"perfis\" e \"temas\" escondidos — sem que ninguém tenha rotulado os filmes\npor gênero de antemão?**\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Revisão Rápida\n\n::: {.fragment}\nAula 4: para $A$ **quadrada simétrica**, $A^TA$ é sempre simétrica PSD\n(qualquer $A$); Teorema Espectral Real $\\Rightarrow A=Q\\Lambda Q^T$, $Q$\nortogonal, $\\Lambda$ diagonal real.\n:::\n\n::: {.fragment}\nSinal de $\\lambda$ $\\Rightarrow$ definitude; razão\n$\\lambda_{\\max}/\\lambda_{\\min}$ $\\Rightarrow$ número de condição exato —\n$\\text{cond}(X^TX)\\approx 23\\,460{,}5$ (4 atributos completos), $\\approx\n419{,}8$ (quase-colinear), $\\approx 169{,}1$ (bem-condicionado).\n:::\n\n::: {.fragment}\nTudo isso construído em cima de $X^TX$ ($4\\times 4$, simétrica) — nunca\ndiretamente sobre $X$ ($16\\,640\\times 4$, retangular).\n:::\n\n## De $X^TX$ Simétrica Para $X$ Retangular\n\n::: {.fragment}\n**Autovalor/autovetor não são \"difíceis\" para matriz retangular — são\nindefinidos.** $A\\mathbf{x}=\\lambda\\mathbf{x}$ exige $A\\mathbf{x}$ no\nmesmo espaço que $\\mathbf{x}$; se $A\\in\\mathbb{R}^{m\\times n}$, $m\\ne n$,\nos dois lados nem têm o mesmo tipo.\n:::\n\n::: {.fragment}\n$\\det(A-\\lambda I)$: mesmo problema — $A-\\lambda I$ só é definido para\n$A$ quadrada.\n:::\n\n::: {.fragment}\nIdeia central: reciclar o Teorema Espectral aplicado a $X^TX$ **e**\n$XX^T$ (ambas quadradas simétricas), e costurar os dois de volta numa\ndecomposição de $X$ — a **SVD**.\n:::\n\n## Roteiro da Aula\n\n::: {.fragment}\n**1.** O que é a SVD e por que existe para **qualquer** matriz\nretangular?\n:::\n\n::: {.fragment}\n**2.** Como construí-la a partir do Teorema Espectral (Aula 4)?\n:::\n\n::: {.fragment}\n**3.** Como aproximar uma matriz por outra de posto menor, de forma\n**ótima** (Eckart-Young-Mirsky)?\n:::\n\n::: {.fragment}\n**4.** O que é a Decomposição Polar, e como nasce da SVD?\n:::\n\n## Problema Motivador\n\n::: {.fragment}\nTrês espectadores (Ali, Beatrix, Chandra), quatro filmes — notas\n$0$–$5$ numa matriz $A\\in\\mathbb{R}^{4\\times 3}$ (tradução livre, MathML\n§4.5.1):\n:::\n\n::: {#82d11aae .cell execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Ali</th>\n      <th>Beatrix</th>\n      <th>Chandra</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Guerra nas Estrelas</th>\n      <td>5.0</td>\n      <td>4.0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>Blade Runner</th>\n      <td>5.0</td>\n      <td>5.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>Amélie Poulain</th>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>Delicatessen</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>4.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.fragment}\nSuspeita: Ali/Beatrix compartilham um perfil (ficção científica),\nChandra outro (cinema de arte). **Existe uma forma de extrair esses\n\"perfis\"/\"temas\" direto da matriz de notas, sem rótulo de gênero\nalgum?**\n:::\n:::\n\n::: {.fig-resize style=\"width: 78%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{shapes.geometric, arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[\n  block/.style={rectangle, draw=icblue, fill=icblue!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.1cm, minimum height=1.15cm},\n  decision/.style={diamond, draw=icorange, fill=icorange!10, align=center,\n                    font=\\small, inner sep=1pt, text width=2.7cm, aspect=2.1},\n  concl/.style={rectangle, draw=icred, fill=icred!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.4cm, minimum height=1.15cm}\n]\n  \\node (A) [block] at (0,0) {matriz $A$\\\\qualquer};\n  \\node (Q) [decision] at (5.1,0) {quadrada\\\\e simétrica?};\n  \\node (S) [concl] at (11.0,2.3) {Teorema Espectral\\\\(Aula 4):\\\\$A=Q\\Lambda Q^T$};\n  \\node (SVD) [concl] at (11.0,-2.3) {SVD (Aula 5):\\\\$A=U\\Sigma V^T$\\\\sempre existe,\\\\qualquer formato};\n\n  \\draw [-Stealth, thick, color=gray!70] (A) -- (Q);\n  \\draw [-Stealth, thick, color=gray!70] (Q) -- (S);\n  \\draw [-Stealth, thick, color=gray!70] (Q) -- node[above, sloped, font=\\scriptsize] {não} (SVD);\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## De volta a $X^TX$: o que muda (e o que não muda) para $X$\n\nDica: pense com cuidado sobre o que está definido para uma matriz\n$m\\times n$ com $m\\ne n$, e o que continua definido só porque a matriz é\nquadrada simétrica.\n\n- □ Se $X$ fosse quadrada mas **não** simétrica, o Teorema Espectral\n  Real garantiria, mesmo assim, autovalores reais para $X$.\n- □ Se todos os espectadores dessem exatamente a mesma nota a todos os\n  filmes (a matriz de notas $A$ tivesse posto $1$), haveria mais de um\n  \"perfil\" de espectador (mais de um par não-nulo de vetores singulares)\n  associado a essa matriz.\n- □ Uma camada totalmente conectada de uma rede neural, com matriz de\n  pesos $W\\in\\mathbb{R}^{m\\times n}$ e $m\\ne n$ (mais neurônios de saída\n  do que de entrada, por exemplo), não possui autovalores no sentido\n  usual, mas ainda assim admite uma decomposição em valores singulares.\n- □ Como o Teorema Espectral (Aula 4) garante que $X^TX$ sempre tem\n  autovalores reais, isso implica que o próprio $X$ também possui\n  autovalores reais, só que de importância secundária.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## De volta a $X^TX$: o que muda (e o que não muda) para $X$\n\nDica: o que está definido para $m\\times n$, $m\\ne n$, e o que só existe\nporque a matriz é quadrada simétrica?\n\n- □ $X$ quadrada mas não simétrica $\\Rightarrow$ Teorema Espectral\n  ainda garantiria autovalores reais.\n- □ Matriz de notas de posto $1$ (todos dão a mesma nota a tudo)\n  $\\Rightarrow$ mais de um \"perfil\" (par de vetores singulares) não-nulo.\n- □ Camada de rede neural com $W\\in\\mathbb{R}^{m\\times n}$, $m\\ne n$: sem\n  autovalores no sentido usual, mas com SVD.\n- □ $X^TX$ sempre tem autovalores reais (Aula 4) $\\Rightarrow$ $X$\n  também tem, só que secundários.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## De volta a $X^TX$ — Resposta\n\n- ✗ Simetria é a hipótese do teorema, não uma consequência de ser\n  quadrada — sem ela, autovalores podem ser complexos (Aula 4, Bloco 3).\n- ✗ Posto $1$ $\\Rightarrow$ só **um** valor singular não-nulo — um único\n  \"perfil\" explica toda a matriz.\n- ✔ Mesma mecânica ($W$ retangular, sem autovalores, com SVD), outro\n  modelo de ML (camada linear de rede neural).\n- ✗ Confunde a entidade: autovalor é propriedade de $X^TX$ (quadrada);\n  $X$ em si, se retangular, simplesmente não tem autovalores — não é\n  \"secundário\", é indefinido.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** o Teorema Espectral só fala de $X^TX$/$XX^T$\n(sempre quadradas simétricas). Decompor $X$ de verdade exige a SVD — os\nBlocos 2-3 constroem exatamente essa ponte.\n:::\n:::\n\n# Intuição Geométrica da SVD\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Uma Matriz Qualquer Agindo sobre um Círculo\n\nAntes de qualquer fórmula, uma imagem concreta — desta vez com uma\nmatriz que **não** é simétrica, de propósito, para deixar claro por que\no Bloco 2 da Aula 4 não se aplica aqui:\n$$\nA = \\begin{bmatrix} 1{,}4 & 0{,}6 \\\\ 0{,}3 & 0{,}9 \\end{bmatrix} ,\n\\qquad A \\ne A^T .\n$$\nPense em $A$ como transformação linear agindo sobre o círculo unitário de\n$\\mathbb{R}^2$. Como qualquer matriz $2\\times 2$ com autovalores reais e\ndistintos, $A$ tem duas direções especiais no sentido da Aula 4 —\nautovetores que só esticam, nunca giram, sob $A$. Mas, como $A$ não é\nsimétrica, o Teorema Espectral Real **não garante** que essas direções\nsejam ortogonais entre si — e de fato não são.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Uma Matriz Qualquer Agindo sobre um Círculo\n\n::: {.fragment}\n**Matriz não-simétrica, de propósito:**\n$A=\\begin{bmatrix}1{,}4&0{,}6\\\\0{,}3&0{,}9\\end{bmatrix}$, $A\\ne A^T$.\n:::\n\n::: {.fragment}\nAutovalores reais e distintos (como qualquer $2\\times 2$ com esse\nperfil) $\\Rightarrow$ duas direções que só esticam, nunca giram — mas\n**sem garantia de ortogonalidade** (Teorema Espectral não se aplica,\n$A$ não é simétrica).\n:::\n\n## O Que a SVD Propõe Fazer Diferente\n\n:::\n\n::: {.fig-resize style=\"width: 92%; margin: 0 auto;\"}\n\n::: {#5255f482 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-5-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nNo painel esquerdo, as setas cheias (azul e laranja) são os **vetores\nsingulares à direita**, $\\mathbf{v}_1$ e $\\mathbf{v}_2$ — colunas da\nmatriz $V$ que o Bloco 3 vai construir; as setas tracejadas cinzas são\nos **autovetores** de $A$ no sentido da Aula 4. Numericamente, o ângulo\nentre os autovetores é $\\approx 106{,}9°$ (nada perto de $90°$), enquanto\no ângulo entre $\\mathbf{v}_1$ e $\\mathbf{v}_2$ é exatamente $90°$ — os\nvetores singulares são, por construção, **sempre** ortogonais entre si,\nautovetores de uma matriz qualquer, em geral, não são. Esse é\nprecisamente o ponto: autovetor e vetor singular são conceitos\nrelacionados, mas **não são a mesma coisa** — coincidem apenas quando\n$A$ é simétrica (Bloco 3 mostra exatamente por quê).\n\nO painel direito mostra a imagem do círculo unitário sob $A$: uma elipse\ncujos eixos caem sobre $\\sigma_1\\mathbf{u}_1$ e $\\sigma_2\\mathbf{u}_2$ —\nos **valores singulares** ($\\sigma_1\\approx 1{,}675$,\n$\\sigma_2\\approx 0{,}645$, sempre não-negativos e ordenados por\nconvenção, $\\sigma_1\\ge\\sigma_2$) escalando os **vetores singulares à\nesquerda**, $\\mathbf{u}_1,\\mathbf{u}_2$ — que também são ortogonais\nentre si. A intuição geométrica central da SVD: $A$ pega uma base\nortonormal do domínio ($\\mathbf{v}_1,\\mathbf{v}_2$) e a transforma em\noutra base ortogonal do codomínio ($\\sigma_1\\mathbf{u}_1,\n\\sigma_2\\mathbf{u}_2$) — nada gira \"torto\" nem no domínio nem no\ncodomínio; só a costura entre os dois lados muda de base.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\nEsquerda: **vetores singulares** $\\mathbf{v}_1,\\mathbf{v}_2$ (cheio,\nsempre a $90°$) vs. **autovetores** de $A$ (tracejado, $\\approx 106{,}9°$\nentre si — não-ortogonais). Mesma matriz, dois conceitos diferentes:\ncoincidem só quando $A$ é simétrica (Bloco 3).\n:::\n\n::: {.fragment}\nDireita: círculo unitário $\\to$ elipse sob $A$. Eixos da elipse\n$=\\sigma_1\\mathbf{u}_1,\\sigma_2\\mathbf{u}_2$\n($\\sigma_1\\approx1{,}675\\ge\\sigma_2\\approx0{,}645$, sempre\nnão-negativos, sempre ortogonais).\n:::\n\n::: {.fragment}\n**Intuição central:** $A$ leva uma base ortonormal do domínio\n($\\mathbf{v}_i$) em outra base ortogonal do codomínio ($\\sigma_i\n\\mathbf{u}_i$) — nada \"gira torto\"; só a base muda.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Autovetor e vetor singular: a mesma seta, dois papéis diferentes?\n\nDica: pense no que muda (e no que não muda) quando $A$ é simétrica —\nvolte, se precisar, ao Teorema Espectral Real da Aula 4.\n\n- □ Se $A$ for simétrica, os vetores singulares de $A$ e os autovetores\n  de $A$ podem ser escolhidos exatamente iguais (a menos de sinal).\n- □ Se todos os autovalores de uma matriz $2\\times 2$ forem complexos\n  (não-reais), essa matriz ainda assim possui uma SVD real bem definida.\n- □ Numa camada linear $f(\\mathbf{x})=W\\mathbf{x}$ de uma rede neural com\n  $W$ quadrada mas não-simétrica, os vetores singulares de $W$ e os\n  autovetores de $W$ apontam, em geral, em direções diferentes.\n- □ Como os vetores singulares são sempre ortogonais entre si, isso\n  implica que a imagem do círculo unitário sob qualquer matriz $A$ é\n  sempre um círculo (nunca uma elipse \"achatada\").\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Autovetor e vetor singular: a mesma seta, dois papéis diferentes?\n\nDica: o que muda quando $A$ é simétrica? Volte ao Teorema Espectral\n(Aula 4) se precisar.\n\n- □ $A$ simétrica $\\Rightarrow$ vetores singulares e autovetores podem\n  coincidir (a menos de sinal).\n- □ Todos os autovalores complexos $\\Rightarrow$ ainda assim existe SVD\n  real bem definida.\n- □ Camada linear $W\\mathbf{x}$, $W$ quadrada não-simétrica: vetores\n  singulares e autovetores de $W$ apontam, em geral, em direções\n  diferentes.\n- □ Vetores singulares sempre ortogonais $\\Rightarrow$ imagem do círculo\n  unitário sob qualquer $A$ é sempre um círculo.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Autovetor vs. vetor singular — Resposta\n\n- ✔ Bloco 3 prova exatamente isso: se $A=A^T$, a SVD e a decomposição\n  espectral coincidem.\n- ✔ A SVD (Teorema 4.22, MathML) existe para **qualquer** matriz real,\n  autovalores complexos ou não — é o Bloco 3 que constrói isso.\n- ✔ Correto — o painel esquerdo mostrou exatamente esse fenômeno; a\n  mesma mecânica se generaliza para qualquer $W$ não-simétrica.\n- ✗ Confunde ortogonalidade **entre os vetores singulares** com a forma\n  da imagem: os fatores de escala $\\sigma_i$ associados a eles é que\n  determinam se a imagem é círculo ($\\sigma_1=\\sigma_2$) ou elipse\n  ($\\sigma_1\\ne\\sigma_2$, como no painel direito).\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** são conceitos diferentes que só colapsam num\ncaso especial (simetria). O Bloco 3 mostra exatamente essa costura,\nconstruindo a SVD a partir do Teorema Espectral.\n:::\n:::\n\n# Construção Formal da SVD a Partir do Teorema Espectral\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Premissas: O Que Já Temos Disponível\n\nA construção que segue (tradução livre e reorganização nossa de MathML,\n§4.5.2, pp. 122-125) usa só resultados já disponíveis desde a Aula 4 —\nnenhuma ferramenta nova de álgebra linear precisa ser importada. Sejam\n$A\\in\\mathbb{R}^{m\\times n}$ uma matriz qualquer (não necessariamente\nquadrada) e $r=\\text{posto}(A)$. As duas premissas:\n\n::: {.callout-note icon=false}\n## Premissas (ambas já provadas na Aula 4)\n\n1. $A^TA\\in\\mathbb{R}^{n\\times n}$ e $AA^T\\in\\mathbb{R}^{m\\times m}$ são\n   **sempre** simétricas e semidefinidas positivas, para **qualquer**\n   $A$ — mesmo retangular (Aula 4, teorema $A^TA$ simétrica e\n   semidefinida positiva).\n2. Pelo **Teorema Espectral Real** (Aula 4), toda matriz simétrica\n   admite uma base ortonormal completa de autovetores associados a\n   autovalores reais e não-negativos (semidefinitude positiva $\\iff$\n   $\\lambda_i\\ge 0$ para todo $i$).\n:::\n\nA ideia da construção: aplicar essas duas premissas a $A^TA$ (para\nconstruir metade da decomposição) e depois usar a própria ação de $A$\npara construir a outra metade, ligando as duas com um único conjunto de\nfatores de escala.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Premissas: O Que Já Temos Disponível\n\n::: {.fragment}\nConstrução (MathML §4.5.2, tradução/reorganização nossa) usa só\nresultados **já provados na Aula 4** — nenhuma ferramenta nova.\n:::\n\n::: {.callout-note icon=false}\n## Premissas (Aula 4)\n\n- $A^TA$, $AA^T$ **sempre** simétricas e semidefinidas positivas,\n  qualquer $A$ (mesmo retangular).\n- Teorema Espectral Real: matriz simétrica $\\Rightarrow$ base ortonormal\n  de autovetores, autovalores reais; semidefinitude positiva\n  $\\iff\\lambda_i\\ge 0$.\n:::\n\n::: {.fragment}\nPlano: aplicar as premissas a $A^TA$ para construir metade da\ndecomposição, usar a ação de $A$ para a outra metade, ligar as duas com\num único fator de escala.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo 1: Vetores Singulares à Direita, a Partir de $A^TA$\n\nPela Premissa 1, $A^TA$ é simétrica e semidefinida positiva. Pela\nPremissa 2 (Teorema Espectral Real), existe uma base ortonormal completa\nde autovetores $\\mathbf{v}_1,\\dots,\\mathbf{v}_n\\in\\mathbb{R}^n$ de\n$A^TA$, com autovalores reais e não-negativos\n$\\lambda_1\\ge\\dots\\ge\\lambda_n\\ge 0$:\n$$\nA^TA = V\\Lambda V^T, \\qquad V=[\\mathbf{v}_1\\ \\cdots\\ \\mathbf{v}_n]\n\\text{ ortogonal}, \\qquad \\Lambda=\\text{diag}(\\lambda_1,\\dots,\\lambda_n).\n$$\nComo cada $\\lambda_i\\ge 0$ (semidefinitude positiva), a raiz quadrada\n$\\sqrt{\\lambda_i}$ está sempre bem definida em $\\mathbb{R}$ — **é aqui\nque a Premissa 1 entra de forma essencial**: se $A^TA$ não fosse\ngarantidamente semidefinida positiva, não haveria garantia de poder\ntomar essa raiz sem cair em números complexos. Definimos os **valores\nsingulares** de $A$ como\n$$\n\\sigma_i := \\sqrt{\\lambda_i} \\ge 0, \\qquad i=1,\\dots,n,\n$$\ne chamamos os $\\mathbf{v}_i$ (autovetores de $A^TA$) de **vetores\nsingulares à direita** de $A$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo 1: Vetores Singulares à Direita\n\n::: {.fragment}\nPremissas 1+2 $\\Rightarrow$ $A^TA=V\\Lambda V^T$, $V$ ortogonal,\n$\\Lambda=\\text{diag}(\\lambda_1,\\dots,\\lambda_n)$,\n$\\lambda_1\\ge\\dots\\ge\\lambda_n\\ge 0$.\n:::\n\n::: {.fragment}\n$\\lambda_i\\ge 0$ (semidefinitude positiva) $\\Rightarrow$\n$\\sigma_i:=\\sqrt{\\lambda_i}$ sempre real. **Essencial:** sem a\nPremissa 1 (PSD garantida), essa raiz poderia cair em números\ncomplexos.\n:::\n\n::: {.fragment}\n$\\sigma_i$ = **valor singular**; $\\mathbf{v}_i$ (autovetor de $A^TA$) =\n**vetor singular à direita**.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo 2: Vetores Singulares à Esquerda, Como Imagem Normalizada\n\nPara os $\\sigma_i>0$ (isto é, $i\\le r$, já que $\\text{posto}(A^TA)=\n\\text{posto}(A)=r$), defina\n$$\n\\mathbf{u}_i := \\frac{1}{\\sigma_i}A\\mathbf{v}_i \\in \\mathbb{R}^m .\n$$\nPrecisamos verificar que os $\\mathbf{u}_i$ assim definidos são\nortonormais — só assim eles formam de fato uma base ortogonal do\ncodomínio. A prova usa exatamente a Premissa 2 aplicada a $A^TA$: como\n$\\mathbf{v}_i$ é autovetor de $A^TA$ com autovalor $\\lambda_i$,\n$A^TA\\mathbf{v}_j=\\lambda_j\\mathbf{v}_j$, e para $i\\ne j$,\n$$\n(A\\mathbf{v}_i)^T(A\\mathbf{v}_j) = \\mathbf{v}_i^T(A^TA)\\mathbf{v}_j =\n\\mathbf{v}_i^T(\\lambda_j\\mathbf{v}_j) = \\lambda_j(\\mathbf{v}_i^T\n\\mathbf{v}_j) = 0 ,\n$$\nonde o último passo usa a ortogonalidade de $\\mathbf{v}_i$ e\n$\\mathbf{v}_j$ ($i\\ne j$), já garantida pela base ortonormal do Passo 1.\nOu seja: **as imagens $A\\mathbf{v}_i$ já são ortogonais entre si antes\nmesmo de normalizar** — o Passo 2 só divide cada uma por seu próprio\ncomprimento ($\\|A\\mathbf{v}_i\\|=\\sigma_i$, uma verificação direta:\n$\\|A\\mathbf{v}_i\\|^2=\\mathbf{v}_i^T A^TA\\mathbf{v}_i=\\lambda_i\\|\n\\mathbf{v}_i\\|^2=\\lambda_i$) para obter um conjunto ortonormal\n$\\mathbf{u}_1,\\dots,\\mathbf{u}_r$. Chamamos os $\\mathbf{u}_i$ de\n**vetores singulares à esquerda** de $A$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo 2: Vetores Singulares à Esquerda\n\n::: {.fragment}\nPara $\\sigma_i>0$ ($i\\le r=\\text{posto}(A)$): $\\mathbf{u}_i:=\n\\dfrac{1}{\\sigma_i}A\\mathbf{v}_i$.\n:::\n\n::: {.fragment}\n**Ortogonalidade das imagens** (usa a Premissa 2 de novo): para\n$i\\ne j$,\n$$\n(A\\mathbf{v}_i)^T(A\\mathbf{v}_j)=\\mathbf{v}_i^T(A^TA)\\mathbf{v}_j=\n\\lambda_j\\mathbf{v}_i^T\\mathbf{v}_j=0\n$$\n(último passo: $\\mathbf{v}_i\\perp\\mathbf{v}_j$, Passo 1).\n:::\n\n::: {.fragment}\n$\\|A\\mathbf{v}_i\\|^2=\\mathbf{v}_i^TA^TA\\mathbf{v}_i=\\lambda_i=\n\\sigma_i^2\\Rightarrow\\|A\\mathbf{v}_i\\|=\\sigma_i$. Normalizar dá\n$\\mathbf{u}_1,\\dots,\\mathbf{u}_r$ ortonormais — **vetores singulares à\nesquerda**.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo 3: A Equação de Valor Singular e a Montagem Final\n\nRearranjando a definição do Passo 2, $\\mathbf{u}_i=\\dfrac{1}{\\sigma_i}\nA\\mathbf{v}_i$, obtemos a **equação de valor singular**\n$$\nA\\mathbf{v}_i = \\sigma_i\\mathbf{u}_i, \\qquad i=1,\\dots,r .\n$$\nNote a semelhança — e a diferença — com a equação de autovalor\n$A\\mathbf{x}=\\lambda\\mathbf{x}$ da Aula 4: aqui os vetores dos dois lados\n($\\mathbf{v}_i$ no domínio, $\\mathbf{u}_i$ no codomínio) **não precisam\nser o mesmo vetor**, porque $A$ pode mudar de espaço. Empilhando os\n$\\mathbf{v}_i$ como colunas de $V$ e os $\\mathbf{u}_i$ como colunas de\n$U$ (completando $U$ e $V$ com bases ortonormais arbitrárias dos\nespaços-nulos de $A^T$ e $A$, se $r<m$ ou $r<n$ — os $\\sigma_i=0$\ncorrespondentes preenchem $\\Sigma$ com zeros, sem violar nada), a\nequação de valor singular vira, em forma matricial,\n$$\nAV = U\\Sigma ,\n$$\nonde $\\Sigma\\in\\mathbb{R}^{m\\times n}$ tem $\\Sigma_{ii}=\\sigma_i$ e\n$\\Sigma_{ij}=0$ para $i\\ne j$. Como $V$ é ortogonal, $V^{-1}=V^T$;\nmultiplicando ambos os lados à direita por $V^T$:\n$$\nA = U\\Sigma V^T .\n$$\nIsso completa a construção. Podemos agora enunciar o resultado de forma\nautocontida:\n\n::: {.callout-note icon=false}\n## Teorema (SVD — MathML, tradução nossa, Teo. 4.22, p. 119)\n\nSeja $A\\in\\mathbb{R}^{m\\times n}$ uma matriz de posto\n$r\\in[0,\\min(m,n)]$. Então existe uma decomposição\n$$\nA = U\\Sigma V^T\n$$\ncom $U\\in\\mathbb{R}^{m\\times m}$ ortogonal (colunas\n$\\mathbf{u}_1,\\dots,\\mathbf{u}_m$), $V\\in\\mathbb{R}^{n\\times n}$\nortogonal (colunas $\\mathbf{v}_1,\\dots,\\mathbf{v}_n$), e\n$\\Sigma\\in\\mathbb{R}^{m\\times n}$ com $\\Sigma_{ii}=\\sigma_i\\ge 0$ e\n$\\Sigma_{ij}=0$ para $i\\ne j$. Os $\\sigma_i$, $i=1,\\dots,r$, são os\n**valores singulares** (por convenção, ordenados\n$\\sigma_1\\ge\\dots\\ge\\sigma_r>0$); $\\mathbf{u}_i$ são os **vetores\nsingulares à esquerda**; $\\mathbf{v}_i$ são os **vetores singulares à\ndireita**. Essa decomposição existe para **qualquer** $A\\in\n\\mathbb{R}^{m\\times n}$, sem exceção — em particular, sem exigir que $A$\nseja quadrada nem simétrica.\n:::\n\nVale registrar explicitamente a diferença em relação à decomposição\nespectral da Aula 4: lá, $A=Q\\Lambda Q^{-1}$ usa a **mesma** matriz de\nbase ($Q$) nos dois lados, porque o domínio e o codomínio de uma\ntransformação $A:\\mathbb{R}^n\\to\\mathbb{R}^n$ são o mesmo espaço. A SVD\nusa **duas** bases diferentes ($U$ e $V$) precisamente porque, em geral,\ndomínio ($\\mathbb{R}^n$) e codomínio ($\\mathbb{R}^m$) da transformação\nrepresentada por $A$ são espaços diferentes — e a SVD é o que resta de\n\"decomposição em direções especiais\" quando essa igualdade de espaços é\nremovida.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo 3: Equação de Valor Singular e Montagem\n\n::: {.fragment}\n$\\mathbf{u}_i=\\dfrac{1}{\\sigma_i}A\\mathbf{v}_i\\Rightarrow$ **equação de\nvalor singular** $A\\mathbf{v}_i=\\sigma_i\\mathbf{u}_i$. Diferença da\nequação de autovalor: $\\mathbf{v}_i$ (domínio) e $\\mathbf{u}_i$\n(codomínio) não precisam ser o mesmo vetor.\n:::\n\n::: {.fragment}\nEmpilhando: $AV=U\\Sigma$; $V$ ortogonal $\\Rightarrow V^{-1}=V^T$\n$\\Rightarrow A=U\\Sigma V^T$.\n:::\n\n::: {.callout-note icon=false}\n## Teorema (SVD — MathML Teo. 4.22, tradução nossa)\n\n$A\\in\\mathbb{R}^{m\\times n}$ posto $r$ $\\Rightarrow$ $A=U\\Sigma V^T$,\n$U\\in\\mathbb{R}^{m\\times m}$/$V\\in\\mathbb{R}^{n\\times n}$ ortogonais,\n$\\Sigma_{ii}=\\sigma_i\\ge 0$ ($\\sigma_1\\ge\\dots\\ge\\sigma_r>0$),\n$\\Sigma_{ij}=0$. **Existe para qualquer $A$**, quadrada ou não,\nsimétrica ou não.\n:::\n\n::: {.fragment}\nDiferença-chave da Aula 4: $A=Q\\Lambda Q^{-1}$ usa a **mesma** base nos\ndois lados (domínio = codomínio, $A$ quadrada); SVD usa **duas** bases\n($U,V$) porque domínio ($\\mathbb{R}^n$) e codomínio ($\\mathbb{R}^m$)\npodem ser espaços diferentes.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Exemplo Resolvido à Mão\n\nVamos aplicar a construção passo a passo à matriz (MathML, Exemplo 4.13,\ntradução livre)\n$$\nA = \\begin{bmatrix} 1 & 0 & 1 \\\\ -2 & 1 & 0 \\end{bmatrix} \\in\n\\mathbb{R}^{2\\times 3} .\n$$\n**Passo 1.** $A^TA=\\begin{bmatrix}5&-2&1\\\\-2&1&0\\\\1&0&1\\end{bmatrix}$\n(simétrica e semidefinida positiva, Premissa 1, verificável por\nsubstituição direta). Seus autovalores (via o polinômio característico\n$3\\times 3$, ou diretamente por `numpy`) são $\\lambda=(6,\\,1,\\,0)$ — só\ndois não-nulos, consistente com $\\text{posto}(A)=2$. Logo,\n$\\sigma_1=\\sqrt{6}\\approx 2{,}449$ e $\\sigma_2=\\sqrt{1}=1$.\n\n**Passo 2.** $\\mathbf{u}_1=A\\mathbf{v}_1/\\sigma_1$ e\n$\\mathbf{u}_2=A\\mathbf{v}_2/\\sigma_2$, calculados a partir dos\nautovetores $\\mathbf{v}_1,\\mathbf{v}_2$ de $A^TA$.\n\n**Passo 3.** Verificação numérica completa a seguir.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Exemplo Resolvido à Mão\n\n::: {.fragment}\n$A=\\begin{bmatrix}1&0&1\\\\-2&1&0\\end{bmatrix}\\in\\mathbb{R}^{2\\times 3}$\n(MathML Exemplo 4.13). $A^TA=\\begin{bmatrix}5&-2&1\\\\-2&1&0\\\\1&0&1\n\\end{bmatrix}$, autovalores $(6,1,0)$ $\\Rightarrow\\sigma_1=\\sqrt6\n\\approx2{,}449$, $\\sigma_2=1$ — só $2$ não-nulos, $\\text{posto}(A)=2$.\n:::\n\n::: {.fragment}\n$\\mathbf{u}_i=A\\mathbf{v}_i/\\sigma_i$; verificação numérica completa a\nseguir.\n:::\n:::\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#075eff96 .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\nA =\n [[ 1.  0.  1.]\n [-2.  1.  0.]]\n\nposto(A) = 2\n\nvalores singulares sigma = [2.4495 1.    ]\n\nU (vetores singulares à esquerda, colunas) =\n [[-0.4472  0.8944]\n [ 0.8944  0.4472]]\n\nV (vetores singulares à direita, colunas) =\n [[-0.9129 -0.     -0.4082]\n [ 0.3651  0.4472 -0.8165]\n [-0.1826  0.8944  0.4082]]\n\nreconstrução U @ Sigma @ V^T =\n [[ 1. -0.  1.]\n [-2.  1.  0.]]\n\nreconstrução bate com A?  True\n```\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nA reconstrução $U\\Sigma V^T$ recupera $A$ exatamente (diferença menor\nque $10^{-10}$, arredondamento de ponto flutuante), confirmando a\nconstrução passo a passo. Repare que a terceira coluna de $V$ (associada\na $\\sigma_3=0$) é uma base ortonormal do espaço-nulo de $A$ — outra\nconsequência direta da construção: a SVD não só decompõe $A$, como\ntambém produz de graça uma base ortonormal de $\\ker(A)$, generalizando\no que a Aula 2 chamava de núcleo (espaço-solução de $A\\mathbf{x}=\n\\mathbf{0}$) para o caso retangular.\n\n**Aviso de leitura:** por construção, cada vetor singular é único **a\nmenos de sinal** (assim como os autovetores da Aula 4) — trocar\n$(\\mathbf{u}_i,\\mathbf{v}_i)$ por $(-\\mathbf{u}_i,-\\mathbf{v}_i)$\nsimultaneamente não muda $\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$. Por isso\nos sinais que o `numpy` devolve podem diferir dos de uma referência\nimpressa em livro sem que a decomposição esteja errada — o que importa\né o produto $U\\Sigma V^T$, não os sinais individuais.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\nReconstrução $U\\Sigma V^T$ recupera $A$ exatamente (erro $<10^{-10}$).\nTerceira coluna de $V$ ($\\sigma_3=0$) = base do espaço-nulo de $A$ — a\nSVD generaliza o núcleo da Aula 2 para o caso retangular.\n:::\n\n::: {.fragment}\n**Aviso:** vetor singular único só **a menos de sinal** (como autovetor,\nAula 4) — sinais do `numpy` podem diferir de uma referência impressa\nsem estar errados; o que importa é o produto $U\\Sigma V^T$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se $A^TA$ tivesse um autovalor negativo, a construção quebraria em qual passo exatamente?\n\nDica: releia a Premissa 1 e aponte, com precisão, onde ela é usada.\n\n- □ A construção quebraria já no Passo 1, porque $\\sigma_i:=\n  \\sqrt{\\lambda_i}$ deixaria de estar bem definido em $\\mathbb{R}$ para\n  um $\\lambda_i<0$.\n- □ Se $A$ for quadrada e invertível, todos os seus valores singulares\n  são necessariamente iguais aos valores absolutos de seus autovalores.\n- □ Numa matriz de covariância empírica (Aula 4, Bloco 6) — sempre\n  simétrica semidefinida positiva por construção — a mesma garantia de\n  raiz quadrada real dos autovalores se aplica ao construir os\n  \"desvios-padrão principais\" via SVD/decomposição espectral.\n- □ Como $A^TA$ é sempre semidefinida positiva para qualquer $A$ real\n  (Aula 4), isso implica que $A$ em si também tem só autovalores\n  não-negativos, quando $A$ é quadrada.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Se $A^TA$ tivesse autovalor negativo, a construção quebraria onde?\n\nDica: releia a Premissa 1 e aponte o passo exato.\n\n- □ Quebraria no Passo 1: $\\sigma_i:=\\sqrt{\\lambda_i}$ deixa de ser real\n  para $\\lambda_i<0$.\n- □ $A$ quadrada invertível $\\Rightarrow$ valores singulares sempre\n  iguais aos módulos dos autovalores de $A$.\n- □ Matriz de covariância (sempre PSD): mesma garantia de raiz real dos\n  autovalores.\n- □ $A^TA$ sempre PSD (qualquer $A$ real) $\\Rightarrow$ $A$ quadrada\n  também só tem autovalores não-negativos.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Onde a construção quebraria — Resposta\n\n- ✔ Exatamente: sem a Premissa 1 (PSD garantida), $\\sqrt{\\lambda_i}$\n  cairia em números complexos — a construção não teria nem por onde\n  começar.\n- ✗ Falso em geral — só vale quando $A$ é **normal** (comuta com\n  $A^T$); uma matriz invertível qualquer, não-simétrica, tem valores\n  singulares diferentes dos módulos de seus autovalores (o painel\n  esquerdo do Bloco 2 já mostrou autovalor $\\approx1{,}642$ vs. valor\n  singular $\\approx1{,}675$ — próximos, mas não iguais).\n- ✔ Mesma mecânica (raiz de autovalor PSD), aplicação já vista (Aula 4,\n  Bloco 6 — covariância empírica).\n- ✗ Confunde a entidade: a garantia é sobre $A^TA$ (sempre PSD), não\n  sobre $A$ propriamente dita — uma matriz $A$ quadrada qualquer pode\n  ter autovalores negativos ou complexos mesmo com $A^TA$ PSD.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** a Premissa 1 (PSD de $A^TA$) é a peça que\nsustenta a raiz quadrada real logo no primeiro passo — sem ela, a SVD\nsimplesmente não existiria para matrizes reais. É por isso que o\nTeorema 4.22 pode afirmar, sem ressalva, que a SVD existe para\n**qualquer** matriz real.\n:::\n:::\n\n# A SVD do Dataset-Fio: $X$ do *California Housing*\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Voltando ao Problema Original\n\nChegou a hora de aplicar a construção do Bloco 3 ao objeto que motivou\ntoda a aula: a matriz de design $X\\in\\mathbb{R}^{16\\,640\\times 4}$ do\n*California Housing* (colunas `MedInc`, `HouseAge`, `AveRooms`,\n`AveBedrms`), a mesma usada desde a Aula 1. Como $X$ tem muito mais\nlinhas que colunas ($m=16\\,640 \\gg n=4$), calcular a SVD completa\n($U\\in\\mathbb{R}^{16\\,640\\times 16\\,640}$) seria um desperdício: as\núltimas $16\\,640-4$ colunas de $U$ só completam uma base ortonormal do\ncodomínio sem carregar nenhuma informação nova sobre $X$ (correspondem a\n$\\sigma_i=0$). Por isso, na prática, usa-se a **SVD reduzida** (MathML,\np. 128) — $U\\in\\mathbb{R}^{16\\,640\\times 4}$, $\\Sigma\\in\n\\mathbb{R}^{4\\times 4}$ diagonal, $V\\in\\mathbb{R}^{4\\times 4}$ —,\nmatematicamente equivalente à SVD completa, só descartando as colunas\nque multiplicariam por zero de qualquer forma.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Voltando ao Problema Original\n\n::: {.fragment}\n$X\\in\\mathbb{R}^{16\\,640\\times 4}$ (California Housing, mesmas 4\ncolunas desde a Aula 1). $m=16\\,640\\gg n=4$.\n:::\n\n::: {.fragment}\nSVD completa desperdiçaria: $16\\,640-4$ colunas de $U$ só completam a\nbase do codomínio, todas com $\\sigma_i=0$. Usa-se a **SVD reduzida**\n(MathML p. 128): $U\\in\\mathbb{R}^{16\\,640\\times4}$,\n$\\Sigma,V\\in\\mathbb{R}^{4\\times4}$ — equivalente, sem as colunas nulas.\n:::\n\n## Os Valores Singulares de $X$ e a Ponte com a Aula 4\n\n:::\n\n::: {.fig-resize style=\"width: 96%; margin: 0 auto;\"}\n\n::: {#be0494a6 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-7-output-1.svg){fig-align='center'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nsigma(X)      = [4186.9964  523.4408  229.4908   27.3359]\nsigma(X)^2    = [1.75309388e+07 2.73990283e+05 5.26660328e+04 7.47253300e+02]\nlambda(X^TX)  = [1.75309388e+07 2.73990283e+05 5.26660328e+04 7.47253300e+02]\ncond(X)       = sigma_max/sigma_min       = 153.1682\ncond(X^TX)    = lambda_max/lambda_min     = 23460.5031\ncond(X)^2     = 23460.5031\n```\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nOs quatro valores singulares de $X$ são $\\sigma=[4\\,186{,}996;\\\n523{,}441;\\ 229{,}491;\\ 27{,}336]$ (ordem decrescente). Elevando ao\nquadrado: $\\sigma^2=[1{,}753\\times10^7;\\ 273\\,990{,}28;\\ 52\\,666{,}03;\\\n747{,}25]$ — **exatamente** os autovalores de $X^TX$ que a Aula 4 já\ntinha calculado, na mesma ordem. Isso não é coincidência nem\naproximação numérica: é o Passo 1 da construção do Bloco 3, aplicado\ndiretamente a $A=X$ — $\\sigma_i(X)^2=\\lambda_i(X^TX)$ por definição. O\npainel direito da figura confirma isso visualmente: todos os pontos\ncaem exatamente sobre a reta $y=x$ (em escala log-log, para acomodar a\ndiferença de quatro ordens de grandeza entre o maior e o menor\nautovalor).\n\nEssa identidade fecha, de forma exata, o gancho que a Aula 4 deixou em\naberto: o Boyd (Apêndice A.5.2, já citado na Aula 4) define o número de\ncondição de uma matriz retangular qualquer usando **valores\nsingulares**, $\\text{cond}(X)=\\sigma_{\\max}/\\sigma_{\\min}$, não\nautovalores. Calculando: $\\text{cond}(X)\\approx 4\\,186{,}996/27{,}336\n\\approx 153{,}168$. Compare com $\\text{cond}(X^TX)\\approx 23\\,460{,}5$,\njá calculado na Aula 4 — a razão entre os dois não é arbitrária:\n\n::: {.callout-note icon=false}\n## Proposição: $\\text{cond}(X^TX)=\\text{cond}(X)^2$\n\nPara qualquer $X\\in\\mathbb{R}^{m\\times n}$ de posto completo (todos os\n$\\sigma_i>0$), $\\text{cond}(X^TX)=\\text{cond}(X)^2$.\n\n**Prova (nossa, direta da definição).** Por $\\sigma_i(X)^2=\n\\lambda_i(X^TX)$ (Passo 1, Bloco 3, aplicado a $A=X$), o maior e o menor\nautovalor de $X^TX$ são $\\lambda_{\\max}=\\sigma_{\\max}^2$ e\n$\\lambda_{\\min}=\\sigma_{\\min}^2$. Logo,\n$$\n\\text{cond}(X^TX) = \\frac{\\lambda_{\\max}}{\\lambda_{\\min}} =\n\\frac{\\sigma_{\\max}^2}{\\sigma_{\\min}^2} = \\left(\\frac{\\sigma_{\\max}}\n{\\sigma_{\\min}}\\right)^2 = \\text{cond}(X)^2 . \\qquad\\blacksquare\n$$\n:::\n\nNumericamente: $153{,}168^2\\approx 23\\,460{,}5$ — bate exatamente com o\nvalor já calculado na Aula 4 (nenhuma aproximação, a igualdade é exata a\nmenos de arredondamento de ponto flutuante). Essa proposição tem uma\nconsequência prática que vale registrar como aviso, mesmo sem\ndesenvolver agora (a Aula 8 retoma o tema, ao discutir estabilidade de\nalgoritmos iterativos): **resolver as Equações Normais\n$X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$ diretamente trabalha, por dentro,\ncom o número de condição elevado ao quadrado** — $23\\,460{,}5$, contra\napenas $153{,}168$ se um algoritmo numérico trabalhasse com $X$\ndiretamente (via SVD, por exemplo, em vez de formar $X^TX$\nexplicitamente). É por isso que bibliotecas numéricas de produção\n(como o `scipy.linalg.lstsq`) evitam formar $X^TX$ explicitamente sempre\nque possível.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\n$\\sigma(X)=[4\\,186{,}996;\\ 523{,}441;\\ 229{,}491;\\ 27{,}336]$;\n$\\sigma^2=[1{,}753\\times10^7;\\ 273\\,990{,}28;\\ 52\\,666{,}03;\\ 747{,}25]$\n— **exatamente** os autovalores de $X^TX$ da Aula 4, mesma ordem\n(não é coincidência: $\\sigma_i(X)^2=\\lambda_i(X^TX)$, Passo 1 do\nBloco 3).\n:::\n\n::: {.fragment}\nBoyd (Aula 4) define $\\text{cond}$ de matriz retangular via $\\sigma$:\n$\\text{cond}(X)=\\sigma_{\\max}/\\sigma_{\\min}\\approx153{,}168$. Compare\ncom $\\text{cond}(X^TX)\\approx23\\,460{,}5$ (Aula 4).\n:::\n\n::: {.callout-note icon=false}\n## Proposição: $\\text{cond}(X^TX)=\\text{cond}(X)^2$\n\n$\\sigma_i(X)^2=\\lambda_i(X^TX)\\Rightarrow\\lambda_{\\max}/\\lambda_{\\min}=\n(\\sigma_{\\max}/\\sigma_{\\min})^2\\Rightarrow\\text{cond}(X^TX)=\n\\text{cond}(X)^2$. Numericamente: $153{,}168^2\\approx23\\,460{,}5$ —\nexato.\n:::\n\n::: {.fragment}\n**Aviso prático** (Aula 8 retoma): resolver Equações Normais trabalha,\npor dentro, com o número de condição **ao quadrado** — motivo pelo qual\nbibliotecas de produção evitam formar $X^TX$ explicitamente, preferindo\na SVD de $X$ direto.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se o menor valor singular de $X$ fosse exatamente zero, o que isso significaria sobre `AveRooms`/`AveBedrms`/`MedInc`/`HouseAge`?\n\nDica: relacione posto, dependência linear (Aula 2) e $\\sigma_{\\min}=0$.\n\n- □ $\\sigma_{\\min}(X)=0$ significaria que as 4 colunas de $X$ são\n  linearmente dependentes, no mesmo sentido de dependência linear\n  definido na Aula 2.\n- □ Se todos os 4 valores singulares de $X$ fossem exatamente iguais\n  entre si, o número de condição de $X$ seria $1$, mas isso não diria\n  nada sobre o número de condição de $X^TX$.\n- □ Numa matriz de embeddings de palavras (uma linha por palavra, uma\n  coluna por dimensão latente), um valor singular próximo de zero\n  indicaria uma dimensão latente quase redundante com as demais.\n- □ Como $\\sigma_i(X)^2=\\lambda_i(X^TX)$ vale para qualquer $X$, isso\n  implica que basta calcular os autovalores de $X^TX$ (Aula 4, já\n  feito) para nunca mais ser necessário calcular a SVD de $X$\n  diretamente, em qualquer aplicação.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## $\\sigma_{\\min}(X)=0$: o que isso diria sobre as 4 colunas?\n\nDica: relacione posto, dependência linear (Aula 2) e $\\sigma_{\\min}=0$.\n\n- □ $\\sigma_{\\min}(X)=0\\Rightarrow$ as 4 colunas de $X$ são linearmente\n  dependentes (Aula 2).\n- □ Todos os $\\sigma_i$ iguais $\\Rightarrow\\text{cond}(X)=1$, mas isso\n  não diria nada sobre $\\text{cond}(X^TX)$.\n- □ Matriz de embeddings (palavra $\\times$ dimensão latente):\n  $\\sigma_i\\approx0\\Rightarrow$ dimensão quase redundante.\n- □ $\\sigma_i(X)^2=\\lambda_i(X^TX)$ sempre $\\Rightarrow$ nunca mais\n  precisa calcular SVD de $X$ diretamente, em qualquer aplicação.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## $\\sigma_{\\min}=0$ e dependência linear — Resposta\n\n- ✔ Exato: $\\sigma_{\\min}=0\\Rightarrow\\lambda_{\\min}(X^TX)=0\n  \\Rightarrow X^TX$ singular $\\Rightarrow$ posto incompleto de $X$\n  (Aula 2/3) $\\Rightarrow$ colunas dependentes.\n- ✗ A Proposição diz exatamente o contrário do que o item afirma: se\n  todos os $\\sigma_i$ forem iguais, $\\text{cond}(X)=\\sigma_{\\max}/\n  \\sigma_{\\min}=1$, e daí $\\text{cond}(X^TX)=\\text{cond}(X)^2=1$\n  também — longe de \"não dizer nada\", o valor de $\\text{cond}(X^TX)$\n  fica completamente determinado.\n- ✔ Mesma mecânica (valor singular pequeno $\\Rightarrow$ direção quase\n  redundante), outro cenário de ML (embeddings).\n- ✗ A identidade poupa *uma* conta ($\\sigma$ a partir de $\\lambda$ já\n  calculado), mas a SVD carrega informação que $X^TX$ sozinha não tem\n  — os vetores $\\mathbf{u}_i$ (codomínio, dimensão $16\\,640$), usados\n  nos Blocos 5-6 para aproximação de baixo posto e decomposição polar.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** sim — $\\sigma_{\\min}=0$ é exatamente a mesma\ncondição de posto incompleto já vista na Aula 2/3, só que vista pela\nlente dos valores singulares em vez do determinante ou da eliminação de\nGauss.\n:::\n:::\n\n# Aproximação de Baixo Posto e o Teorema de Eckart-Young-Mirsky\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Decompondo $A$ em Pedaços de Posto 1\n\nA SVD $A=U\\Sigma V^T$ pode ser reescrita numa forma que deixa mais\nexplícito o que cada valor singular \"carrega\". Defina, para\n$i=1,\\dots,r$ ($r=\\text{posto}(A)$), a matriz de posto $1$\n$$\nA_i := \\mathbf{u}_i\\mathbf{v}_i^T \\in \\mathbb{R}^{m\\times n}\n$$\n(o produto externo entre a $i$-ésima coluna de $U$ e a $i$-ésima coluna\nde $V$). Então (MathML, §4.6, tradução nossa)\n$$\nA = \\sum_{i=1}^r \\sigma_i A_i = \\sum_{i=1}^r \\sigma_i\n\\mathbf{u}_i\\mathbf{v}_i^T .\n$$\n**Por que essa igualdade vale:** escrevendo $A=U\\Sigma V^T$ em forma de\nsomatório, $A=\\sum_{i,j}\\Sigma_{ij}\\mathbf{u}_i\\mathbf{v}_j^T$; como\n$\\Sigma$ é diagonal ($\\Sigma_{ij}=0$ para $i\\ne j$), só os termos com\n$i=j$ sobrevivem, e cada um deles vale exatamente\n$\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$ — a soma acima.\n\nSe, em vez de somar todos os $r$ termos, pararmos numa posição\nintermediária $k<r$, obtemos a **aproximação de posto-$k$** (MathML,\nDef. informal, §4.6):\n$$\n\\hat{A}^{(k)} := \\sum_{i=1}^k \\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T ,\n\\qquad \\text{com } \\text{posto}(\\hat{A}^{(k)})=k .\n$$\nIsso é chamado de **SVD truncada** (MathML, p. 129). Intuitivamente:\ncomo os $\\sigma_i$ vêm ordenados de forma decrescente, cada termo\nadicional contribui cada vez menos para $A$ — descartar os últimos\n$r-k$ termos descarta as direções que menos importam, na medida exata\nde $\\sigma_i$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Decompondo $A$ em Pedaços de Posto 1\n\n::: {.fragment}\n$A_i:=\\mathbf{u}_i\\mathbf{v}_i^T$ (posto $1$). Escrevendo $A=U\\Sigma\nV^T=\\sum_{i,j}\\Sigma_{ij}\\mathbf{u}_i\\mathbf{v}_j^T$: $\\Sigma$ diagonal\n$\\Rightarrow$ só $i=j$ sobrevive $\\Rightarrow A=\\sum_{i=1}^r\n\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$.\n:::\n\n::: {.fragment}\n**Aproximação de posto-$k$** ($k<r$): $\\hat{A}^{(k)}:=\n\\sum_{i=1}^k\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$ — a **SVD truncada**.\n$\\sigma_i$ decrescente $\\Rightarrow$ termos descartados são os que\nmenos importam.\n:::\n\n## Medindo o Erro: Norma Espectral\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Medindo o Erro da Aproximação: Norma Espectral\n\nPara dizer, com precisão, \"o quanto $\\hat{A}^{(k)}$ erra em relação a\n$A$\", precisamos de uma noção de tamanho para matrizes — uma norma\nmatricial, análoga às normas vetoriais da Aula 1.\n\n::: {.callout-note icon=false}\n## Definição (Norma Espectral — MathML, tradução nossa, Def. 4.23, p. 131)\n\nPara $A\\in\\mathbb{R}^{m\\times n}$, a **norma espectral** de $A$ é\n$$\n\\|A\\|_2 := \\max_{\\mathbf{x}\\ne\\mathbf{0}} \\frac{\\|A\\mathbf{x}\\|_2}\n{\\|\\mathbf{x}\\|_2} .\n$$\n:::\n\nOu seja: $\\|A\\|_2$ mede o maior fator de esticamento que $A$ pode impor\nsobre **qualquer** vetor. Isso tem uma resposta exata em termos da SVD:\n\n::: {.callout-note icon=false}\n## Teorema (MathML, tradução nossa, Teo. 4.24, p. 131)\n\nA norma espectral de $A$ é seu maior valor singular: $\\|A\\|_2=\n\\sigma_1$. *(O MathML deixa a prova como exercício — a demonstração\nabaixo é nossa, reciclando o quociente de Rayleigh da Aula 4.)*\n:::\n\n**Prova.** Para $\\mathbf{x}\\ne\\mathbf{0}$, $\\|A\\mathbf{x}\\|_2^2=\n\\mathbf{x}^T(A^TA)\\mathbf{x}$. Como $A^TA$ é simétrica semidefinida\npositiva (Premissa 1, Bloco 3), o **quociente de Rayleigh** da Aula 4\ngarante\n$$\n\\frac{\\mathbf{x}^T(A^TA)\\mathbf{x}}{\\mathbf{x}^T\\mathbf{x}} \\le\n\\lambda_{\\max}(A^TA) = \\sigma_1^2 ,\n$$\ncom igualdade quando $\\mathbf{x}=\\mathbf{v}_1$ (autovetor de $A^TA$\nassociado a $\\lambda_{\\max}$, isto é, o primeiro vetor singular à\ndireita). Logo,\n$$\n\\frac{\\|A\\mathbf{x}\\|_2^2}{\\|\\mathbf{x}\\|_2^2} \\le \\sigma_1^2 \\quad\n\\text{para todo } \\mathbf{x}\\ne\\mathbf{0}, \\quad\\text{com igualdade em }\n\\mathbf{x}=\\mathbf{v}_1 ,\n$$\ne tomando a raiz quadrada de ambos os lados (ambos não-negativos),\n$\\|A\\mathbf{x}\\|_2/\\|\\mathbf{x}\\|_2\\le\\sigma_1$, com igualdade atingida.\nLogo $\\max_{\\mathbf{x}\\ne\\mathbf{0}}\\|A\\mathbf{x}\\|_2/\\|\\mathbf{x}\\|_2=\n\\sigma_1$. $\\blacksquare$\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Medindo o Erro: Norma Espectral\n\n::: {.callout-note icon=false}\n## Definição (Norma Espectral — MathML Def. 4.23)\n\n$\\|A\\|_2:=\\max_{\\mathbf{x}\\ne\\mathbf{0}}\\|A\\mathbf{x}\\|_2/\n\\|\\mathbf{x}\\|_2$ — maior fator de esticamento sobre qualquer vetor.\n:::\n\n::: {.callout-note icon=false}\n## Teorema (MathML Teo. 4.24)\n\n$\\|A\\|_2=\\sigma_1$. *(Prova deixada como exercício no MathML — abaixo,\nprova nossa via quociente de Rayleigh, Aula 4.)*\n:::\n\n::: {.fragment}\n**Prova.** $\\|A\\mathbf{x}\\|_2^2=\\mathbf{x}^T(A^TA)\\mathbf{x}$; $A^TA$\nsimétrica PSD $\\Rightarrow$ quociente de Rayleigh (Aula 4):\n$\\mathbf{x}^T(A^TA)\\mathbf{x}/\\mathbf{x}^T\\mathbf{x}\\le\n\\lambda_{\\max}(A^TA)=\\sigma_1^2$, igualdade em $\\mathbf{x}=\n\\mathbf{v}_1$.\n:::\n\n::: {.fragment}\nRaiz quadrada: $\\|A\\mathbf{x}\\|_2/\\|\\mathbf{x}\\|_2\\le\\sigma_1$,\nigualdade atingida $\\Rightarrow\\|A\\|_2=\\sigma_1$. $\\blacksquare$\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## O Teorema de Eckart-Young-Mirsky\n\nAgora podemos enunciar, com precisão, o que significa $\\hat{A}^{(k)}$\nser a \"melhor\" aproximação de posto $k$:\n\n::: {.callout-note icon=false}\n## Teorema (Eckart-Young-Mirsky — MathML, tradução nossa, Teo. 4.25, p. 131)\n\nConsidere $A\\in\\mathbb{R}^{m\\times n}$ de posto $r$, e seja\n$B\\in\\mathbb{R}^{m\\times n}$ uma matriz qualquer de posto $k$. Para\nqualquer $k\\le r$, com $\\hat{A}^{(k)}=\\sum_{i=1}^k\\sigma_i\n\\mathbf{u}_i\\mathbf{v}_i^T$, vale\n$$\n\\hat{A}^{(k)} = \\operatorname*{argmin}_{\\text{posto}(B)=k}\\|A-B\\|_2 ,\n\\qquad \\|A-\\hat{A}^{(k)}\\|_2 = \\sigma_{k+1} .\n$$\n:::\n\nOu seja: **entre todas** as matrizes de posto no máximo $k$ (não só\nentre as que vêm de truncar a SVD), a aproximação $\\hat{A}^{(k)}$\nconstruída pela SVD é a que fica mais próxima de $A$ — e o erro dessa\nmelhor aproximação possível é, exatamente, o primeiro valor singular\ndescartado, $\\sigma_{k+1}$. Isso responde, de forma completa, à\npergunta \"quanto se perde ao aproximar por um posto menor\": a resposta\nnão depende de qual método de aproximação foi usado, é uma propriedade\nintrínseca de $A$.\n\n**Prova (tradução e reorganização nossa da prova do MathML, mesma\nseção).** A parte $\\hat{A}^{(k)}=\\operatorname{argmin}$ tem duas\nmetades: (i) mostrar que $\\|A-\\hat{A}^{(k)}\\|_2=\\sigma_{k+1}$, e (ii)\nmostrar que nenhuma outra matriz de posto $k$ faz melhor.\n\n**(i)** Por construção, $A-\\hat{A}^{(k)}=\\sum_{i=k+1}^r\n\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$ — a soma dos termos restantes, que é\nela mesma a SVD (truncada) dessa matriz-diferença, com maior valor\nsingular $\\sigma_{k+1}$. Pelo Teorema 4.24 (norma espectral $=$ maior\nvalor singular), $\\|A-\\hat{A}^{(k)}\\|_2=\\sigma_{k+1}$.\n\n**(ii)** Suponha, por contradição, que existisse $B$ com\n$\\text{posto}(B)\\le k$ e $\\|A-B\\|_2<\\sigma_{k+1}$. Como\n$\\text{posto}(B)\\le k$, o núcleo de $B$ tem dimensão pelo menos $n-k$\n(pelo **Teorema do Núcleo e da Imagem**, citado aqui sem prova — resultado\npadrão de álgebra linear que relaciona $\\dim(\\ker B)+\\text{posto}(B)=n$\npara $B:\\mathbb{R}^n\\to\\mathbb{R}^m$). Seja $Z\\subseteq\\mathbb{R}^n$\nesse núcleo, com $\\dim(Z)\\ge n-k$. Para $\\mathbf{x}\\in Z$,\n$B\\mathbf{x}=\\mathbf{0}$, logo $A\\mathbf{x}=(A-B)\\mathbf{x}$, e pela\ndefinição de norma espectral,\n$$\n\\|A\\mathbf{x}\\|_2 = \\|(A-B)\\mathbf{x}\\|_2 \\le \\|A-B\\|_2\\,\n\\|\\mathbf{x}\\|_2 < \\sigma_{k+1}\\|\\mathbf{x}\\|_2 \\qquad\n\\text{para todo } \\mathbf{x}\\in Z .\n$$\nPor outro lado, existe um subespaço $W:=\\text{span}(\\mathbf{v}_1,\n\\dots,\\mathbf{v}_{k+1})$, de dimensão $k+1$, sobre o qual\n$\\|A\\mathbf{x}\\|_2\\ge\\sigma_{k+1}\\|\\mathbf{x}\\|_2$ para todo\n$\\mathbf{x}\\in W$ (uma verificação direta a partir da SVD de $A$\nrestrita às $k+1$ primeiras direções singulares). Como\n$\\dim(Z)+\\dim(W)\\ge(n-k)+(k+1)=n+1>n=\\dim(\\mathbb{R}^n)$, os dois\nsubespaços têm intersecção não-trivial — existe $\\mathbf{x}\\ne\n\\mathbf{0}$ em $Z\\cap W$ satisfazendo, ao mesmo tempo,\n$\\|A\\mathbf{x}\\|_2<\\sigma_{k+1}\\|\\mathbf{x}\\|_2$ (de $Z$) e\n$\\|A\\mathbf{x}\\|_2\\ge\\sigma_{k+1}\\|\\mathbf{x}\\|_2$ (de $W$) — uma\ncontradição direta. Logo nenhum $B$ de posto $k$ pode fazer melhor que\n$\\hat{A}^{(k)}$. $\\blacksquare$\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Teorema de Eckart-Young-Mirsky\n\n::: {.callout-note icon=false}\n## Teorema (Eckart-Young-Mirsky — MathML Teo. 4.25)\n\n$A$ posto $r$; $B$ posto $k\\le r$ qualquer. $\\hat{A}^{(k)}=\n\\sum_{i=1}^k\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T\\Rightarrow\\hat{A}^{(k)}=\n\\operatorname*{argmin}_{\\text{posto}(B)=k}\\|A-B\\|_2$, e\n$\\|A-\\hat{A}^{(k)}\\|_2=\\sigma_{k+1}$.\n:::\n\n::: {.fragment}\n**Entre todas** as matrizes de posto $\\le k$ (não só truncamentos da\nSVD), $\\hat{A}^{(k)}$ é a mais próxima de $A$ — e o erro é\n**exatamente** $\\sigma_{k+1}$: propriedade intrínseca de $A$, não do\nmétodo de aproximação.\n:::\n\n::: {.fragment}\n**Prova, parte (i):** $A-\\hat{A}^{(k)}=\\sum_{i=k+1}^r\\sigma_i\n\\mathbf{u}_i\\mathbf{v}_i^T$ (SVD truncada da diferença, maior valor\nsingular $\\sigma_{k+1}$) $\\Rightarrow$ Teo. 4.24 $\\Rightarrow\n\\|A-\\hat{A}^{(k)}\\|_2=\\sigma_{k+1}$.\n:::\n\n::: {.fragment}\n**Parte (ii), por contradição:** $B$ posto $\\le k$ com\n$\\|A-B\\|_2<\\sigma_{k+1}$. Núcleo de $B$: $\\dim\\ge n-k$ (Teorema do\nNúcleo e da Imagem). Subespaço $W=\\text{span}(\\mathbf{v}_1,\\dots,\n\\mathbf{v}_{k+1})$: $\\dim=k+1$, $\\|Ax\\|_2\\ge\\sigma_{k+1}\\|x\\|_2$ em\n$W$.\n:::\n\n::: {.fragment}\n$\\dim(\\ker B)+\\dim(W)\\ge(n-k)+(k+1)=n+1>n\\Rightarrow$ interseção\nnão-trivial $\\Rightarrow$ mesmo $\\mathbf{x}$ satisfaz\n$\\|A\\mathbf{x}\\|_2<\\sigma_{k+1}\\|\\mathbf{x}\\|_2$ **e**\n$\\|A\\mathbf{x}\\|_2\\ge\\sigma_{k+1}\\|\\mathbf{x}\\|_2$ — contradição.\n$\\blacksquare$\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Aplicando a $X$: Quanto Se Perde ao Truncar\n\nVamos verificar a garantia do Teorema de Eckart-Young-Mirsky\nnumericamente, aplicando a aproximação de posto-$k$ à matriz de design\n$X$ do *California Housing* para $k=1,2,3$ (lembrando: $\\text{posto}(X)\n=4$, então $k=4$ recupera $X$ exatamente).\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Aplicando a $X$: Quanto Se Perde ao Truncar\n\n::: {.fragment}\nVerificação numérica de Eckart-Young-Mirsky em $X$ (California Housing),\n$k=1,2,3$ (posto completo $=4$).\n:::\n:::\n\n::: {.fig-resize style=\"width: 90%; margin: 0 auto;\"}\n\n::: {#0a833b4f .cell execution_count=7}\n\n::: {.cell-output .cell-output-stdout}\n```\n  k    ||X - X_k||_2    sigma_{k+1}    erro relativo (Frobenius)\n  1       523.440811     523.440811                     13.5401%\n  2       229.490812     229.490812                      5.4690%\n  3        27.335935      27.335935                      0.6469%\n```\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nPara $k=1,2,3$, o erro $\\|X-\\hat{X}^{(k)}\\|_2$ bate, até a sexta casa\ndecimal, com $\\sigma_{k+1}$ — confirmação numérica direta do Teorema\n4.25. O erro relativo em norma de Frobenius (uma medida \"de energia\ntotal\", diferente da norma espectral, mas relacionada) cai de\n$\\approx 13{,}5\\%$ ($k=1$) para $\\approx 0{,}6\\%$ ($k=3$) — mesmo\ndescartando $3$ de $4$ direções na primeira aproximação, mais de $86\\%$\nda \"energia\" de $X$ já está capturada, porque o primeiro valor singular\n($\\approx 4\\,187$) domina amplamente os demais.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\nErro $\\|X-\\hat{X}^{(k)}\\|_2$ bate com $\\sigma_{k+1}$ até a $6^a$ casa\ndecimal — confirma Teorema 4.25 na prática. Erro relativo Frobenius:\n$\\approx13{,}5\\%$ ($k=1$) $\\to\\approx0{,}6\\%$ ($k=3$) — $1^o$ valor\nsingular ($\\approx4\\,187$) domina.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Retomando o Problema Motivador: Filtragem Colaborativa\n\nVoltando à matriz de notas de filmes do Problema Motivador — a\naplicação de baixo posto revela exatamente a estrutura que suspeitávamos\nexistir (tradução livre de MathML, Exemplo 4.15, retomando o Exemplo\n4.14). A interpretação (MathML, §4.5.1): os vetores singulares à\nesquerda $\\mathbf{u}_i$ podem ser lidos como **\"filmes\nestereotípicos\"** (perfis de tema), e os vetores singulares à direita\n$\\mathbf{v}_i$ como **\"espectadores estereotípicos\"** (perfis de gosto)\n— sob a suposição de que cada espectador avalia filmes como combinação\nlinear desses perfis, e cada filme pertence a uma combinação linear\ndesses temas.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Retomando o Problema: Filtragem Colaborativa\n\n::: {.fragment}\nMathML Exemplo 4.15 (retomando 4.14): $\\mathbf{u}_i=$ \"filme\nestereotípico\" (perfil de tema); $\\mathbf{v}_i=$ \"espectador\nestereotípico\" (perfil de gosto). Suposição: notas = combinação linear\ndesses perfis.\n:::\n:::\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#00a4a1bc .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-9-output-1.svg){fig-align='center'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nvalores singulares: sigma = [9.6438 6.3639 0.7056]\nerro espectral k=1: 6.3639 (sigma_2 = 6.3639)\nerro espectral k=2: 0.7056 (sigma_3 = 0.7056)\n```\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nA aproximação de posto $1$ (usando só $\\sigma_1\\mathbf{u}_1\n\\mathbf{v}_1^T$) captura bem as notas de Ali e Beatrix para os filmes\nde ficção científica (valores $>4$, próximos do original), mas erra\nfeio nas notas de Chandra para Amélie Poulain e Delicatessen\n(previstos $\\approx 0{,}16$–$0{,}26$, contra as notas reais $4$ e $5$) —\no primeiro perfil, sozinho, só \"entende\" espectadores de ficção\ncientífica. A aproximação de posto $2$ (somando o segundo termo,\n$\\sigma_2\\mathbf{u}_2\\mathbf{v}_2^T$) já recupera a matriz quase\ninteira, incluindo o perfil de Chandra. Isso é exatamente o que o\nTeorema de Eckart-Young-Mirsky quantifica: o erro em norma espectral\ncai de $\\sigma_2\\approx 6{,}364$ (posto 1) para $\\sigma_3\\approx\n0{,}706$ (posto 2) — e, como $\\text{posto}(A)=3$, a aproximação de\nposto $3$ recuperaria $A$ exatamente.\n\nEssa é, em essência, a matemática por trás de **sistemas de recomendação\npor filtragem colaborativa**: em vez de uma matriz completa de\n$3\\times 4$ notas (aqui, artificialmente pequena e sem valores\nfaltantes), sistemas reais lidam com matrizes de milhões de usuários por\nmilhões de itens, majoritariamente **vazias** (a maioria dos usuários\nnunca avaliou a maioria dos itens) — mas a mesma ideia de aproximação de\nbaixo posto (adaptada para lidar com entradas faltantes, o que foge do\nescopo desta aula) é a base de métodos clássicos de **completamento de\nmatrizes** para prever as notas que faltam a partir da estrutura de\nbaixo posto capturada pelos poucos perfis latentes mais importantes.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\nPosto $1$: acerta Ali/Beatrix (ficção científica, $>4$), erra feio\nChandra em Amélie/Delicatessen ($\\approx0{,}2$ vs. $4$/$5$ reais) — só\n\"entende\" um perfil.\n:::\n\n::: {.fragment}\nPosto $2$: recupera quase tudo, incluindo Chandra. Erro espectral:\n$\\sigma_2\\approx6{,}364\\to\\sigma_3\\approx0{,}706$ — exatamente o que\nEckart-Young-Mirsky prevê. $\\text{posto}(A)=3\\Rightarrow$ posto $3$\nrecupera $A$ exato.\n:::\n\n::: {.fragment}\n**Filtragem colaborativa real:** matrizes de milhões de usuários $\\times$\nitens, majoritariamente vazias — mesma ideia de baixo posto (adaptada\npara entradas faltantes, fora do escopo) sustenta o **completamento de\nmatrizes** em sistemas de recomendação.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se $A$ tivesse posto $3$ mas só déssemos ao sistema de recomendação os dois primeiros perfis latentes, o que aconteceria com um quarto espectador de um perfil totalmente novo?\n\nDica: pense no que $\\hat{A}^{(2)}$ pode e não pode representar, dada sua\nprópria definição.\n\n- □ Um quarto espectador com um perfil de gosto genuinamente novo (não\n  combinação linear dos dois perfis já capturados) teria suas notas mal\n  previstas por $\\hat{A}^{(2)}$, mesmo que o sistema tivesse dados\n  históricos abundantes desse espectador.\n- □ Aumentar $k$ de $2$ para $3$ (o posto completo de $A$) sempre reduz\n  o erro de aproximação em norma espectral, mas nunca pode aumentá-lo.\n- □ Numa matriz de embeddings de documentos de texto (linhas =\n  documentos, colunas = termos), a mesma lógica de perfis latentes se\n  aplicaria: um documento sobre um assunto totalmente não-representado\n  nos primeiros $k$ tópicos latentes teria sua representação de\n  baixo-posto empobrecida.\n- □ Como a aproximação de posto-$k$ é a **melhor possível** entre\n  todas as matrizes de posto $k$ (Eckart-Young-Mirsky), isso implica\n  que o erro de aproximação $\\sigma_{k+1}$ pode ser reduzido escolhendo\n  um método de aproximação diferente da SVD, para o mesmo $k$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Um perfil de gosto totalmente novo, fora dos $k$ perfis capturados\n\nDica: o que $\\hat{A}^{(2)}$ pode e não pode representar, pela própria\ndefinição?\n\n- □ Espectador com perfil genuinamente novo (fora do espaço gerado\n  pelos $2$ perfis) $\\Rightarrow$ notas mal previstas por\n  $\\hat{A}^{(2)}$, mesmo com dados históricos abundantes.\n- □ $k=2\\to k=3$ (posto completo) sempre reduz o erro espectral, nunca\n  aumenta.\n- □ Embeddings de documentos: mesma lógica — assunto fora dos $k$\n  tópicos latentes tem representação empobrecida.\n- □ Aproximação de posto-$k$ é a melhor possível (Eckart-Young)\n  $\\Rightarrow$ $\\sigma_{k+1}$ pode ser reduzido trocando de método,\n  para o mesmo $k$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Perfil novo fora do posto-$k$ — Resposta\n\n- ✔ Exatamente a limitação estrutural: $\\hat{A}^{(k)}$ só representa\n  combinações lineares dos $k$ perfis já presentes nos dados usados\n  para computá-la — um perfil ortogonal a todos eles fica fora do\n  alcance, dados históricos ou não.\n- ✔ $\\sigma_i\\ge 0$ sempre, e $\\hat{A}^{(k+1)}=\\hat{A}^{(k)}+\n  \\sigma_{k+1}\\mathbf{u}_{k+1}\\mathbf{v}_{k+1}^T$ só adiciona\n  informação — o erro é monótono não-crescente em $k$.\n- ✔ Mesma mecânica (perfis/tópicos latentes truncados), outro cenário\n  de ML (embeddings de texto/tópicos latentes).\n- ✗ O Teorema de Eckart-Young-Mirsky é exatamente a garantia contrária:\n  $\\hat{A}^{(k)}$ **já é** o mínimo global entre **todas** as matrizes\n  de posto $k$ — nenhum método alternativo pode fazer melhor para o\n  mesmo $k$.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** a aproximação de baixo posto é ótima **dentro**\ndo que os dados de treino permitem capturar — ela não inventa\ninformação sobre um perfil nunca visto. É a mesma cautela que qualquer\nmodelo estatístico exige em relação a dados fora da distribuição de\ntreino.\n:::\n:::\n\n# Decomposição Polar\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Rearranjando os Três Fatores da SVD\n\nNenhuma das três fontes desta disciplina traz uma seção dedicada à\nDecomposição Polar — o que segue é uma construção **nossa**, a partir\ndo Teorema 4.22 já demonstrado no Bloco 3 (não uma tradução de trecho\nalgum). Diferente da SVD, que existe para matriz retangular qualquer, a\nDecomposição Polar como construída aqui exige $A$ **quadrada**\n($A\\in\\mathbb{R}^{n\\times n}$) — é essa restrição de dimensão que\npermite multiplicar os dois fatores finais na ordem certa, como o\nargumento abaixo deixa explícito.\n\nSeja $A\\in\\mathbb{R}^{n\\times n}$ com SVD completa $A=U\\Sigma V^T$\n($U,V\\in\\mathbb{R}^{n\\times n}$ ambas ortogonais, $\\Sigma\\in\n\\mathbb{R}^{n\\times n}$ diagonal com entradas $\\ge 0$). Insira a matriz\nidentidade $I=V^TV$ entre $U$ e $\\Sigma$:\n$$\nA = U\\Sigma V^T = (UV^T)(V\\Sigma V^T) =: QS ,\n$$\ndefinindo\n$$\nQ := UV^T \\in\\mathbb{R}^{n\\times n}, \\qquad\nS := V\\Sigma V^T \\in\\mathbb{R}^{n\\times n} .\n$$\n\n::: {.callout-note icon=false}\n## Proposição (Decomposição Polar — construção nossa a partir do Teorema 4.22)\n\nPara $A\\in\\mathbb{R}^{n\\times n}$, com $Q:=UV^T$ e $S:=V\\Sigma V^T$\ndefinidos a partir da SVD $A=U\\Sigma V^T$: $Q$ é ortogonal, $S$ é\nsimétrica semidefinida positiva, e $A=QS$.\n:::\n\n**Prova de que $Q$ é ortogonal.** $Q^TQ=(UV^T)^T(UV^T)=VU^TUV^T$; como\n$U$ é ortogonal, $U^TU=I$, logo $Q^TQ=VIV^T=VV^T=I$ (usando, de novo,\nque $V$ é ortogonal). Como $Q^TQ=I$ com $Q$ quadrada, $Q$ é ortogonal.\n\n**Prova de que $S$ é simétrica semidefinida positiva.** $S^T=(V\\Sigma\nV^T)^T=V\\Sigma^TV^T=V\\Sigma V^T=S$ (usando que $\\Sigma$, sendo diagonal,\nsatisfaz $\\Sigma^T=\\Sigma$) — logo $S$ é simétrica. Para qualquer\n$\\mathbf{x}\\ne\\mathbf{0}$, definindo $\\mathbf{z}:=V^T\\mathbf{x}$ (não-nulo,\njá que $V$ é invertível),\n$$\n\\mathbf{x}^TS\\mathbf{x} = \\mathbf{x}^TV\\Sigma V^T\\mathbf{x} =\n\\mathbf{z}^T\\Sigma\\mathbf{z} = \\sum_{i=1}^n \\sigma_i z_i^2 \\ge 0 ,\n$$\njá que cada $\\sigma_i\\ge 0$. Logo $S$ é semidefinida positiva. $\\blacksquare$\n\nRepare que a prova identifica, de graça, os autovalores e autovetores de\n$S$: como $S=V\\Sigma V^T$ com $V$ ortogonal e $\\Sigma$ diagonal, essa\n**é** a decomposição espectral de $S$ (Aula 4) — os autovalores de $S$\nsão exatamente os valores singulares de $A$, e os autovetores de $S$ são\nexatamente os vetores singulares à direita de $A$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Rearranjando os Três Fatores da SVD\n\n::: {.fragment}\n**Construção nossa** (nenhuma das 3 fontes cobre Decomposição Polar),\na partir do Teorema 4.22 (Bloco 3). Exige $A$ **quadrada**.\n:::\n\n::: {.fragment}\n$A=U\\Sigma V^T=(UV^T)(V\\Sigma V^T)=:QS$, com $Q:=UV^T$,\n$S:=V\\Sigma V^T$.\n:::\n\n::: {.callout-note icon=false}\n## Proposição (Decomposição Polar)\n\n$Q$ ortogonal, $S$ simétrica semidefinida positiva, $A=QS$.\n:::\n\n::: {.fragment}\n**$Q$ ortogonal:** $Q^TQ=VU^TUV^T=VIV^T=VV^T=I$ (usa $U^TU=I$ e\n$VV^T=I$).\n:::\n\n::: {.fragment}\n**$S$ simétrica PSD:** $S^T=V\\Sigma^TV^T=V\\Sigma V^T=S$\n($\\Sigma$ diagonal); $\\mathbf{x}^TS\\mathbf{x}=\\sum_i\\sigma_iz_i^2\\ge0$\ncom $\\mathbf{z}=V^T\\mathbf{x}$. $\\blacksquare$\n:::\n\n::: {.fragment}\n$S=V\\Sigma V^T$ **é** a decomposição espectral de $S$ (Aula 4):\nautovalores de $S$ = valores singulares de $A$; autovetores de $S$ =\nvetores singulares à direita de $A$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## A Generalização do Módulo e da Fase\n\nA Decomposição Polar leva esse nome por uma analogia direta: assim como\ntodo número complexo $z\\ne 0$ se escreve como $z=re^{i\\theta}$ — um\nmódulo $r\\ge 0$ (quanto \"esticar\") vezes uma fase $e^{i\\theta}$ (quanto\n\"girar\", sem esticar nem encolher) —, toda matriz quadrada $A$ se\nescreve como $A=QS$: uma parte $S$ que só estica/encolhe ao longo de\ndireções ortogonais (nunca gira — $S$ é simétrica, autovetores\nortogonais, exatamente o Teorema Espectral da Aula 4), seguida de uma\nparte $Q$ que só gira/reflete, sem esticar nada ($Q$ ortogonal —\npreserva norma e ângulo, Aula 1).\n\nReaproveitando a matriz do Bloco 2, $A=\\begin{bmatrix}1{,}4&0{,}6\\\\\n0{,}3&0{,}9\\end{bmatrix}$, o cálculo numérico abaixo mostra os dois\nfatores explicitamente e a leitura geométrica: primeiro $S$ estica o\ncírculo unitário ao longo de suas próprias direções principais\n($\\mathbf{v}_1,\\mathbf{v}_2$ — as mesmas retas cheias do painel esquerdo\ndo Bloco 2), produzindo uma elipse ainda alinhada com essas direções;\ndepois $Q$ gira essa elipse inteira como corpo rígido, sem distorcer seu\nformato, até a posição final — que é exatamente a mesma elipse do painel\ndireito do Bloco 2, a imagem de $A$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Módulo e Fase, Generalizados\n\n::: {.fragment}\nAnalogia: $z=re^{i\\theta}$ (número complexo) $\\leftrightarrow A=QS$\n(matriz). $S$ = \"módulo\" (estica/encolhe ao longo de direções\nortogonais, nunca gira — simétrica, Teorema Espectral). $Q$ = \"fase\"\n(só gira/reflete, preserva norma — ortogonal, Aula 1).\n:::\n\n## Verificação Geométrica: Estica, Depois Gira\n\n:::\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#c3b78a54 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-10-output-1.svg){fig-align='center'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nQ =\n [[ 0.9916  0.1293]\n [-0.1293  0.9916]]\ndet(Q) = 1.0 (1 = rotação pura, -1 = reflexão)\nS =\n [[1.3494 0.4786]\n [0.4786 0.97  ]]\nautovalores de S (= valores singulares de A): [0.645  1.6745]\nQ @ S == A? True\n```\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nOs números confirmam a proposição: $\\det(Q)\\approx 1$ (rotação pura,\nsem reflexão) por um ângulo de $\\approx 7{,}4°$; os autovalores de $S$\nsão $[0{,}645;\\ 1{,}675]$ — exatamente os valores singulares de $A$ já\ncalculados no Bloco 2 ($\\sigma_1\\approx 1{,}675$, $\\sigma_2\\approx\n0{,}645$); e $QS=A$ até erro de ponto flutuante. O painel do meio mostra\n$S$ agindo sozinha — uma elipse já com o formato final, mas **ainda\nalinhada** com $\\mathbf{v}_1,\\mathbf{v}_2$ (não com os eixos do\ncodomínio); o painel da direita mostra $Q$ girando essa elipse, como um\ncorpo rígido, até a posição final — idêntica à elipse do Bloco 2.\n\n**Ponte, sem desenvolver:** a Decomposição Polar reaparece, mais adiante\nneste curso (Aula 14, Preconditioning Estruturado — Shampoo e Muon),\ncomo o objetivo de um algoritmo iterativo (a **iteração de\nNewton-Schulz**) usado para *ortogonalizar* matrizes de atualização de\npesos de redes neurais em tempo real, sem calcular a SVD completa (cara\ndemais para ser recalculada a cada passo de treino) — extraindo,\nefetivamente, só o fator $Q$ da Decomposição Polar de cada matriz de\natualização.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\n$\\det(Q)\\approx1$ (rotação pura, $\\approx7{,}4°$); autovalores de\n$S=[0{,}645;\\,1{,}675]=$ valores singulares de $A$ (Bloco 2); $QS=A$\n(erro de ponto flutuante).\n:::\n\n::: {.fragment}\nPainel do meio: $S$ sozinha — formato final, mas ainda alinhada a\n$\\mathbf{v}_1,\\mathbf{v}_2$. Painel direito: $Q$ gira como corpo rígido\naté a posição final (idêntica ao Bloco 2).\n:::\n\n::: {.fragment}\n**Ponte (sem desenvolver):** Aula 14 (Shampoo/Muon) usa a iteração de\nNewton-Schulz para extrair só o fator $Q$ de matrizes de atualização de\npesos, sem calcular a SVD completa a cada passo de treino.\n:::\n:::\n\n# Fechamento e Ponte para a Aula 6\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n### Retomando as perguntas de abertura {.unnumbered}\n\n1. **O que é a SVD e por que existe para qualquer matriz retangular?**\n   $A=U\\Sigma V^T$, com $U,V$ ortogonais e $\\Sigma$ diagonal com\n   entradas não-negativas; existe sempre porque $A^TA$ é sempre\n   simétrica semidefinida positiva (Aula 4), o que garante autovalores\n   reais não-negativos e, portanto, raízes quadradas reais bem\n   definidas para os valores singulares.\n2. **Como construir a SVD a partir do Teorema Espectral?** Os\n   autovetores de $A^TA$ são os vetores singulares à direita ($V$); suas\n   imagens sob $A$, normalizadas pelo próprio comprimento (que é a raiz\n   do autovalor correspondente), são os vetores singulares à esquerda\n   ($U$) — a ortogonalidade de ambos os conjuntos vem diretamente da\n   relação de autovalor de $A^TA$.\n3. **Como aproximar por posto menor de forma ótima?** Truncando a soma\n   $A=\\sum\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$ nos $k$ primeiros termos;\n   o Teorema de Eckart-Young-Mirsky garante que essa é a melhor\n   aproximação possível entre **todas** as matrizes de posto $k$, com\n   erro exato $\\sigma_{k+1}$.\n4. **O que é a Decomposição Polar?** Rearranjar os três fatores da SVD\n   ($A=U\\Sigma V^T=(UV^T)(V\\Sigma V^T)=QS$) separa $A$ (quadrada) em uma\n   parte que só gira/reflete ($Q$, ortogonal) e uma parte que só\n   estica/encolhe ao longo de direções ortogonais ($S$, simétrica\n   semidefinida positiva) — a generalização matricial do módulo e da\n   fase de um número complexo.\n\n### O Que Fica em Aberto {.unnumbered}\n\nA SVD decompõe uma matriz **estática** — ela não diz nada sobre como\nencontrar os parâmetros de um modelo de aprendizado de máquina que\nminimizam uma função de perda. E, de fato, olhando para trás: a própria\nderivação das Equações Normais na Aula 3\n($X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$) já usou implicitamente a ideia de\n\"encontrar o ponto onde a perda para de diminuir\" — mas em nenhum\nmomento este curso definiu formalmente o que significa \"a perda parar de\ndiminuir\" para uma função de várias variáveis. Esse é exatamente o\nobjeto que abre a Parte 2 do curso, \"Cálculo da Otimização\nDiferenciável\": a **derivada em várias variáveis** — o gradiente e o\nJacobiano —, tema da Aula 6.\n\n[Exercícios](exercicios.qmd){.see-all .exercicios-link} [Soluções](soluções.qmd){.see-all .solucoes-link}\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Retomando as Perguntas de Abertura\n\n::: {.fragment}\n**1.** SVD: $A=U\\Sigma V^T$ ($U,V$ ortogonais, $\\Sigma$ diagonal\n$\\ge0$); existe sempre porque $A^TA$ é sempre PSD (Aula 4)\n$\\Rightarrow$ raízes quadradas reais garantidas.\n:::\n\n::: {.fragment}\n**2.** Construção: autovetores de $A^TA$ = $V$; imagens normalizadas\nsob $A$ = $U$; ortogonalidade de ambos vem da relação de autovalor de\n$A^TA$.\n:::\n\n::: {.fragment}\n**3.** Aproximação ótima: truncar\n$A=\\sum\\sigma_i\\mathbf{u}_i\\mathbf{v}_i^T$ em $k$ termos —\nEckart-Young-Mirsky garante mínimo global, erro $=\\sigma_{k+1}$.\n:::\n\n::: {.fragment}\n**4.** Decomposição Polar: $A=QS$ ($Q$ ortogonal, $S$ simétrica PSD) —\ngeneralização matricial de módulo $\\times$ fase.\n:::\n\n## Ponte para a Aula 6\n\n::: {.fragment}\nSVD decompõe uma matriz **estática** — não diz como achar parâmetros\nque minimizam uma perda. E as Equações Normais (Aula 3) já usaram, sem\nnunca definir, a ideia de \"perda parar de diminuir\".\n:::\n\n::: {.fragment}\nFalta um objeto formal para isso: a **derivada em várias variáveis** —\ngradiente e Jacobiano. Abre a **Parte 2** do curso: Cálculo da\nOtimização Diferenciável, Aula 6.\n:::\n\n[Exercícios](exercicios.qmd){.see-all .exercicios-link} [Soluções](soluções.qmd){.see-all .solucoes-link}\n:::\n\n::: {.fig-resize style=\"width: 78%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{shapes.geometric, arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[\n  block/.style={rectangle, draw=icblue, fill=icblue!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.0cm, minimum height=1.15cm},\n  concl/.style={rectangle, draw=icred, fill=icred!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.6cm, minimum height=1.15cm}\n]\n  \\node (A) [block] at (0,0) {SVD:\\\\$A=U\\Sigma V^T$\\\\(Aula 5, estática)};\n  \\node (B) [block] at (4.6,0) {Eq. Normais (Aula 3):\\\\$X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$\\\\\"perda para de diminuir\"};\n  \\node (C) [concl] at (9.7,0) {o que é, formalmente,\\\\\"parar de diminuir\"?\\\\$\\to$ gradiente/Jacobiano\\\\(Aula 6)};\n\n  \\draw [-Stealth, thick, color=gray!70] (A) -- (B);\n  \\draw [-Stealth, thick, color=gray!70] (B) -- (C);\n\\end{tikzpicture}\n```\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}